# 04.1 — Existing Project Artifact Inspection

## Objective

The objective of this subsection is to inspect the existing project repository,
raw order dataset, Phase 03 exploratory data analysis notebook, configuration
files, and previously generated data artifacts before collecting contextual data.

This inspection will establish which datasets and project components are
already available, identify the existing hourly demand construction methodology,
and determine what must be reused or verified during Phase 04.

## Scope

The inspection covers:

1. Project repository structure and important directories.
2. Raw order dataset and its schema.
3. Existing Phase 03 notebook and hourly demand construction methodology.
4. Availability of saved hourly demand datasets and relevant configuration files.
5. Readiness of the existing artifacts for contextual data integration.

## Important Rules

- The original Phase 03 notebook must remain unchanged.
- Existing datasets must not be regenerated unnecessarily.
- Existing exploratory data analysis must not be repeated.
- Missing artifacts must be reported rather than assumed to exist.
- Synthetic demand data must be clearly distinguished from real contextual data.
- No contextual data collection or integration will be performed in this subsection.

## 04.1.2 — Project Repository Inspection

This subsection identifies the project root directory and inspects the existing
repository structure.

The purpose is to locate relevant data directories, notebooks, configuration
files, and documentation before proceeding with contextual data collection.

The inspection is read-only and must not modify or delete existing project files.

In [1]:
from pathlib import Path

# Set the existing project root directory.
PROJECT_ROOT = Path(
    r"D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
)

print("=" * 80)
print("PROJECT REPOSITORY INSPECTION")
print("=" * 80)

print(f"\nProject root: {PROJECT_ROOT}")
print(f"Project root exists: {PROJECT_ROOT.exists()}")

if PROJECT_ROOT.exists():

    important_directories = [
        "data",
        "data/raw",
        "data/processed",
        "notebooks",
        "config",
        "results",
        "models",
        "docs",
    ]

    print("\nIMPORTANT DIRECTORIES")
    print("-" * 80)

    for directory in important_directories:
        path = PROJECT_ROOT / directory
        print(f"{directory:<25} Exists: {path.exists()}")

    print("\nNOTEBOOK FILES")
    print("-" * 80)

    notebooks_dir = PROJECT_ROOT / "notebooks"

    if notebooks_dir.exists():
        for path in sorted(notebooks_dir.glob("*.ipynb")):
            print(path.name)
    else:
        print("Notebooks directory not found.")

    print("\nCONFIGURATION FILES")
    print("-" * 80)

    config_dir = PROJECT_ROOT / "config"

    if config_dir.exists():
        for path in sorted(config_dir.iterdir()):
            if path.is_file():
                print(path.name)
    else:
        print("Configuration directory not found.")

else:
    print(
        "\nProject root not found. Verify PROJECT_ROOT before continuing."
    )

================================================================================
PROJECT REPOSITORY INSPECTION
================================================================================

Project root: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting
Project root exists: True

IMPORTANT DIRECTORIES
--------------------------------------------------------------------------------
data                      Exists: True
data/raw                  Exists: True
data/processed            Exists: True
notebooks                 Exists: True
config                    Exists: True
results                   Exists: True
models                    Exists: True
docs                      Exists: True

NOTEBOOK FILES
--------------------------------------------------------------------------------
01_data_generation.ipynb
02_data_quality_analysis.ipynb
03_exploratory_data_analysis.ipynb
04_live_contextual_data_collection_and_integration.ipynb
04_live_contextual_data_collection_and_integration_FIXED.ipynb

CONFIGURATION FILES
--------------------------------------------------------------------------------
config.yaml
zones.yaml

## 04.1.3 — Raw Order Dataset Inspection

This subsection verifies the availability and schema of the existing synthetic
food-order dataset.

The inspection checks the file path, dataset dimensions, column names, data
types, and timestamp coverage using a small sample where possible.

The raw dataset is used only for artifact verification. This subsection does
not regenerate the data or repeat the Phase 03 exploratory analysis.

In [2]:
from pathlib import Path

RAW_ORDERS_PATH = PROJECT_ROOT / "data" / "raw" / "orders" / "orders.csv"

print("=" * 80)
print("RAW ORDER DATASET INSPECTION")
print("=" * 80)

print(f"\nFile path: {RAW_ORDERS_PATH}")
print(f"File exists: {RAW_ORDERS_PATH.is_file()}")

if RAW_ORDERS_PATH.is_file():

    import pandas as pd

    # Read a small sample; do not load the entire dataset.
    orders_sample = pd.read_csv(
        RAW_ORDERS_PATH,
        nrows=1000
    )

    print(f"\nSample shape: {orders_sample.shape}")

    print("\nColumn names:")
    print(orders_sample.columns.tolist())

    print("\nData types:")
    print(orders_sample.dtypes.to_string())

    print("\nSample records:")
    display(orders_sample.head())

    if "order_timestamp" in orders_sample.columns:

        timestamps = pd.to_datetime(
            orders_sample["order_timestamp"],
            errors="coerce"
        )

        print("\nTimestamp sample coverage:")
        print(f"Earliest valid timestamp: {timestamps.min()}")
        print(f"Latest valid timestamp:   {timestamps.max()}")

else:
    print(
        "\nRaw order file not found at the expected path. "
        "Verify its actual location before continuing."
    )

================================================================================
RAW ORDER DATASET INSPECTION
================================================================================

File path: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\orders\orders.csv
File exists: True

Sample shape: (1000, 12)

Column names:
['order_id', 'order_timestamp', 'zone_id', 'customer_id', 'restaurant_id', 'order_value', 'meal_period', 'day_type', 'day_of_week', 'order_year', 'order_month', 'order_month_name']

Data types:
order_id                str
order_timestamp         str
zone_id                 str
customer_id             str
restaurant_id           str
order_value         float64
meal_period             str
day_type                str
day_of_week             str
order_year            int64
order_month           int64
order_month_name        str

Sample records:

,order_id,order_timestamp,zone_id,customer_id,restaurant_id,order_value,meal_period,day_type,day_of_week,order_year,order_month,order_month_name
0,ORD000000001,2023-01-01 00:05:21,Z01,C038943,Z01_R025,230.13,Late_Night,Weekend,Sunday,2023,1,January
1,ORD000000002,2023-01-01 00:46:26,Z01,C021775,Z01_R002,337.54,Late_Night,Weekend,Sunday,2023,1,January
2,ORD000000003,2023-01-01 00:39:16,Z01,C043044,Z01_R001,257.61,Late_Night,Weekend,Sunday,2023,1,January
3,ORD000000004,2023-01-01 00:26:19,Z01,C035206,Z01_R033,383.23,Late_Night,Weekend,Sunday,2023,1,January
4,ORD000000005,2023-01-01 00:25:58,Z01,C004428,Z01_R022,333.94,Late_Night,Weekend,Sunday,2023,1,January

Timestamp sample coverage:
Earliest valid timestamp: 2023-01-01 00:00:26
Latest valid timestamp:   2023-01-01 07:58:48

## 04.1.4 — Phase 03 Notebook and Hourly Panel Inspection

The existing Phase 03 notebook contains the original hourly demand construction
and validation methodology.

This subsection verifies the notebook's availability and searches for existing
hourly demand artifacts without rerunning the complete Phase 03 analysis.

The documented hourly panel contains 160,560 zone-hour observations, covering
1,338 complete dates, 24 hours per day, and five zones.

These figures are prior Phase 03 findings and must be distinguished from
results independently reproduced during this inspection.

The incomplete date of August 31, 2026, is excluded from the complete hourly
panel. Unobserved hours on that date must not be interpreted as zero demand.

In [3]:
print("=" * 80)
print("PHASE 03 NOTEBOOK AND HOURLY ARTIFACT INSPECTION")
print("=" * 80)

PHASE_03_NOTEBOOK = (
    PROJECT_ROOT / "notebooks" / "03_exploratory_data_analysis.ipynb"
)

print(f"\nPhase 03 notebook: {PHASE_03_NOTEBOOK}")
print(f"Notebook exists: {PHASE_03_NOTEBOOK.is_file()}")

search_directories = [
    PROJECT_ROOT / "data",
    PROJECT_ROOT / "results",
    PROJECT_ROOT / "models",
]

candidate_extensions = {".csv", ".parquet", ".feather", ".pkl"}

keywords = ("hourly", "demand", "panel", "zone")

print("\nPOTENTIAL HOURLY DATA ARTIFACTS")
print("-" * 80)

found_files = []

for directory in search_directories:

    print(f"\nSearching: {directory}")

    if not directory.is_dir():
        print("Directory not found.")
        continue

    for path in directory.rglob("*"):

        if (
            path.is_file()
            and path.suffix.lower() in candidate_extensions
            and any(keyword in path.stem.lower() for keyword in keywords)
        ):
            found_files.append(path)
            print(path.relative_to(PROJECT_ROOT))

if not found_files:
    print("\nNo matching hourly demand artifact files were found.")

================================================================================
PHASE 03 NOTEBOOK AND HOURLY ARTIFACT INSPECTION
================================================================================

Phase 03 notebook: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\notebooks\03_exploratory_data_analysis.ipynb
Notebook exists: True

POTENTIAL HOURLY DATA ARTIFACTS
--------------------------------------------------------------------------------

Searching: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data

Searching: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\results

Searching: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\models

No matching hourly demand artifact files were found.

## 04.1.5 — Inspection Findings and Readiness Assessment

### 1. Project Repository

The project root and the required directories were successfully identified.

The repository contains the existing data, notebooks, configuration,
results, models, and documentation directories.

The Phase 03 and Phase 04 notebooks were found in the notebooks directory.

### 2. Raw Order Dataset

The synthetic order dataset was located at:

`data/raw/orders/orders.csv`

A sample of 1,000 records was inspected.

The sample contains 12 columns, including order timestamps, zone identifiers,
customer identifiers, restaurant identifiers, and order values.

The earliest and latest timestamps observed in the sample were
2023-01-01 00:00:26 and 2023-01-01 07:58:48, respectively.

These timestamps describe only the inspected sample, not the complete dataset.

### 3. Phase 03 and Hourly Demand Panel

The existing Phase 03 notebook was located.

Phase 03 documentation establishes the validated hourly demand panel
with 160,560 zone-hour observations across five zones and 1,338 complete dates.

The panel covers January 1, 2023, through August 30, 2026.

The incomplete date of August 31, 2026, is excluded.

The current artifact search did not find a matching hourly demand file
in the searched data, results, and models directories.

This search result does not establish that no reusable hourly demand
artifact exists elsewhere in the project.

Phase 03 demand construction and validation will not be repeated.

### 4. Inspection Status

The project repository, raw order dataset, Phase 03 notebook,
hourly demand panel documentation, and zone configuration have
been inspected.

The zone configuration inspection confirmed five hyperlocal zones
and identified the available zone-level metadata.

No geographical coordinate or boundary fields were detected
in the inspected zone configuration.

The availability of existing contextual datasets has not yet
been established and will be investigated during the next subsection.

### 5. Scope Boundary

This subsection focuses on inspecting existing project artifacts
and documenting the project's readiness for contextual data integration.

No contextual datasets have been collected or integrated during
this subsection.

The original Phase 03 notebook and raw order dataset remain unchanged.

Existing Phase 03 demand construction and validation will not be repeated.

### 6. Zone Configuration Inspection

The existing zone configuration file was successfully located at:

`config/zones.yaml`

The file is located in the project root.

The YAML configuration was loaded successfully and contains five
hyperlocal zones in Hyderabad, Telangana, India.

The configured zones are:

- Z01: Kondapur
- Z02: Hitech City
- Z03: Gachibowli
- Z04: Madhapur
- Z05: Kukatpally

Each zone contains four fields:

- `zone_id`
- `zone_name`
- `zone_type`
- `demand_profile`

The inspection found no latitude, longitude, coordinate, boundary,
or polygon fields in the zone-level configuration.

Consequently, geographical metadata must be evaluated before
implementing zone-specific weather or local-event mapping.

City-level weather may be considered as an initial contextual feature,
but it must not be interpreted as independently observed weather
for each hyperlocal zone.

### 7. Phase 04.1 Readiness Assessment

The project repository, raw order dataset, Phase 03 notebook,
hourly demand panel documentation, and zone configuration have
been inspected.

The existing Phase 03 demand construction and validation will not
be repeated.

The current artifact search did not identify a matching hourly
demand file in the directories searched. The availability of a
reusable artifact elsewhere in the project remains unconfirmed.

No contextual datasets have been collected or integrated during
this subsection.

The project is ready to proceed to Phase 04.2 — Contextual Data
Source Evaluation.

The next subsection will evaluate suitable sources for:

1. Historical weather and live weather forecasts.
2. Public holidays and regional festivals.
3. IPL schedules and other relevant sports events.
4. Concerts, exhibitions, and local events in Hyderabad.

Source suitability will be assessed based on reliability, historical
coverage, update frequency, geographical resolution, availability,
licensing, and suitability for forecasting and backtesting.

## 04.1.6 — Zone Configuration Inspection

### Objective

Inspect the existing zone configuration file to identify the five
hyperlocal zones and determine whether geographical metadata is available
for integrating weather and location-specific event information.

### Scope

This subsection reads the existing `config/zones.yaml` file without
modifying it.

The inspection will verify zone identifiers, zone names, geographical
coordinates, and any other available location-related metadata.

The findings will determine whether additional geographical information
is required before contextual data collection and integration.

In [4]:
from pathlib import Path
import yaml
from pprint import pprint

# Locate the project root by searching parent directories
current_path = Path.cwd()
project_root = None

for path in [current_path, *current_path.parents]:
    if (
        (path / "config" / "zones.yaml").is_file()
        and (path / "notebooks").is_dir()
    ):
        project_root = path
        break

if project_root is None:
    raise FileNotFoundError(
        "Could not locate the project root containing "
        "'config/zones.yaml' and the 'notebooks' directory."
    )

# Locate the existing zone configuration
zones_file = project_root / "config" / "zones.yaml"

print("Project root:", project_root)
print("Zone configuration file:", zones_file)
print("File exists:", zones_file.exists())

# Read the configuration without modifying it
with open(zones_file, "r", encoding="utf-8") as file:
    zones_config = yaml.safe_load(file)

print("\nZone configuration content:")
pprint(zones_config)

print("\nConfiguration data type:", type(zones_config).__name__)

Project root: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting
Zone configuration file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\config\zones.yaml
File exists: True

Zone configuration content:
{'city': 'Hyderabad',
 'country': 'India',
 'state': 'Telangana',
 'zones': [{'demand_profile': 'high',
            'zone_id': 'Z01',
            'zone_name': 'Kondapur',
            'zone_type': 'IT_Residential'},
           {'demand_profile': 'very_high',
            'zone_id': 'Z02',
            'zone_name': 'Hitech City',
            'zone_type': 'IT_Commercial'},
           {'demand_profile': 'very_high',
            'zone_id': 'Z03',
            'zone_name': 'Gachibowli',
            'zone_type': 'IT_Residential'},
           {'demand_profile': 'high',
            'zone_id': 'Z04',
            'zone_name': 'Madhapur',
            'zone_type': 'Commercial_Residential'},
           {'demand_profile': 'high',
            'zone_id': 'Z05',
            'zone_name': 'Kukatpally',
            'zone_type': 'Residential_Commercial'}]}

Configuration data type: dict

In [5]:
# Inspect the available fields for each configured zone

zones = zones_config.get("zones", [])

print("Number of configured zones:", len(zones))
print("\nZone-level field inspection:\n")

for zone in zones:
    print(f"Zone ID: {zone.get('zone_id')}")
    print(f"Zone name: {zone.get('zone_name')}")
    print("Available fields:", list(zone.keys()))

    coordinate_fields = [
        key for key in zone.keys()
        if any(term in key.lower() for term in [
            "latitude", "longitude", "lat", "lon",
            "coordinate", "boundary", "polygon"
        ])
    ]

    print("Geographical fields detected:", coordinate_fields or "None")
    print("-" * 60)

Number of configured zones: 5

Zone-level field inspection:

Zone ID: Z01
Zone name: Kondapur
Available fields: ['zone_id', 'zone_name', 'zone_type', 'demand_profile']
Geographical fields detected: None
------------------------------------------------------------
Zone ID: Z02
Zone name: Hitech City
Available fields: ['zone_id', 'zone_name', 'zone_type', 'demand_profile']
Geographical fields detected: None
------------------------------------------------------------
Zone ID: Z03
Zone name: Gachibowli
Available fields: ['zone_id', 'zone_name', 'zone_type', 'demand_profile']
Geographical fields detected: None
------------------------------------------------------------
Zone ID: Z04
Zone name: Madhapur
Available fields: ['zone_id', 'zone_name', 'zone_type', 'demand_profile']
Geographical fields detected: None
------------------------------------------------------------
Zone ID: Z05
Zone name: Kukatpally
Available fields: ['zone_id', 'zone_name', 'zone_type', 'demand_profile']
Geographical fields detected: None
------------------------------------------------------------

# 04.2 — Contextual Data Source Evaluation

## Objective

The objective of this phase is to identify, evaluate, and select reliable external data sources for enriching the hyperlocal food demand forecasting framework with contextual information.

The project focuses on five hyperlocal zones in Hyderabad, Telangana, India: Kondapur, Hitech City, Gachibowli, Madhapur, and Kukatpally.

Contextual information may help forecasting models represent changes in demand associated with weather conditions, public holidays, regional festivals, sports events, and local events.

## Contextual Data Categories

The following categories will be evaluated:

1. **Weather Data:** Historical weather observations, archived weather forecasts, and current weather forecasts.
2. **Public Holidays:** Official public holiday calendars relevant to Telangana.
3. **Regional Festivals:** Festival dates and celebrations relevant to Hyderabad and Telangana.
4. **Sports Events:** IPL matches and other relevant sporting events.
5. **Local Events:** Concerts, exhibitions, public gatherings, and other events that may influence local activity.

## Source Evaluation Criteria

Each candidate source will be evaluated using the following criteria:

* Source reliability and authenticity.
* Historical data coverage for the project period.
* Availability of current and future information.
* Temporal resolution and timestamp accuracy.
* Geographical resolution and relevance to the study zones.
* Data access method, including APIs or downloadable files.
* Licensing, attribution, and usage restrictions.
* Update frequency and data availability.
* Suitability for historical backtesting and live forecasting.
* Missing-data risks and preprocessing requirements.

## Forecasting and Data Leakage Considerations

The project distinguishes between historical observations and information that would have been available when a forecast was issued.

For historical backtesting, archived forecasts should be preferred when evaluating the operational value of weather forecasts. Historical weather observations may be used for descriptive analysis or separate experiments, but they must not be treated as information that was known in advance.

Similarly, future event information may only be used when it would have been available at the forecast issue time.

Because the demand dataset is synthetic, the integration of real contextual information does not establish real-world causal relationships between these factors and actual food delivery demand.

## Scope

This phase evaluates candidate sources and documents their suitability before data collection begins.

No contextual datasets will be downloaded, transformed, or integrated until the source evaluation is sufficiently complete.

## Expected Outcome

The expected outcome is a documented source-selection strategy identifying the preferred source, data coverage, relevant variables, access method, limitations, and intended use for each contextual category.

## 04.2.1 — Weather Data Source Evaluation

### 1. Objective

The objective of this subsection is to evaluate suitable weather data sources for the AI-Enhanced Hyperlocal Food Demand Forecasting and Surge Intelligence project.

The project requires hourly weather information to investigate potential relationships between weather conditions and synthetic food demand across five hyperlocal zones in Hyderabad, Telangana.

The evaluation considers three requirements:

1. Historical weather information for exploratory analysis and retrospective experiments.
2. Archived weather forecasts for leakage-aware historical forecasting experiments.
3. Current and future weather forecasts for live demand prediction.

### 2. Candidate Weather Data Sources

#### Source A: Open-Meteo Historical Weather API

The Open-Meteo Historical Weather API provides historical weather information using reanalysis datasets, including ERA5 and ERA5-Land.

Official documentation:
https://open-meteo.com/en/docs/historical-weather-api

Potential hourly variables include:

* Temperature at 2 metres.
* Relative humidity.
* Precipitation.
* Rainfall.
* Cloud cover.
* Wind speed.
* Weather codes.

**Potential application:** Historical weather analysis and experiments evaluating the association between weather conditions and synthetic food demand.

**Limitation:** Historical reanalysis data represent reconstructed weather conditions. They do not establish which weather forecasts were available when a historical demand prediction would have been made.

#### Source B: Open-Meteo Historical Forecast API

The Open-Meteo Historical Forecast API provides archived weather forecasts, with historical coverage beginning around 2022 according to its documentation.

Official documentation:
https://open-meteo.com/en/docs/historical-forecast-api

Potential hourly variables include:

* Temperature.
* Relative humidity.
* Precipitation probability.
* Precipitation.
* Rainfall.
* Cloud cover.
* Wind speed.
* Weather codes.

**Potential application:** Historical forecasting experiments that use weather forecast information rather than actual future weather observations.

**Limitation:** Available forecast dates, model runs, lead times, and variables must be verified for the required study period. A continuous hourly forecast archive does not necessarily preserve every original forecast run and lead time.

#### Source C: Open-Meteo Weather Forecast API

The Open-Meteo Weather Forecast API provides current and future weather forecasts for specified geographical coordinates.

Official documentation:
https://open-meteo.com/en/docs

Potential hourly variables include:

* Temperature.
* Relative humidity.
* Precipitation probability.
* Precipitation.
* Cloud cover.
* Wind speed.
* Weather codes.

**Potential application:** Supplying weather forecasts to the live demand forecasting workflow.

**Limitation:** Forecast availability and horizon depend on the selected API configuration and weather models. Current forecasts cannot substitute for archived forecasts in historical backtesting.

### 3. Comparative Evaluation

| Evaluation criterion            | Historical Weather API               | Historical Forecast API                              | Weather Forecast API            |
| ------------------------------- | ------------------------------------ | ---------------------------------------------------- | ------------------------------- |
| Historical weather observations | Yes, through reanalysis              | Provides archived forecasts                          | Not its primary purpose         |
| Archived forecast information   | No                                   | Yes                                                  | No historical archive guarantee |
| Current forecasts               | No; separate endpoint                | Historical archive                                   | Yes                             |
| Hourly variables                | Available                            | Available                                            | Available                       |
| Historical demand analysis      | Suitable                             | Suitable for forecast-based experiments              | Not sufficient alone            |
| Leakage-aware backtesting       | Requires careful experimental design | Preferred candidate, subject to archive verification | Not sufficient alone            |
| Live demand prediction          | Not suitable alone                   | Not suitable alone                                   | Preferred candidate             |
| Geographical inputs             | Latitude and longitude               | Latitude and longitude                               | Latitude and longitude          |

### 4. Evaluation Criteria

The candidate sources will be assessed according to:

1. Availability of hourly data.
2. Coverage of the required historical dates.
3. Availability of the necessary weather variables.
4. Forecast issue time and lead-time availability.
5. Suitability for historical backtesting.
6. Suitability for live forecasting.
7. Geographical resolution and relevance to Hyderabad.
8. Timezone consistency with the demand dataset.
9. Data access requirements and usage restrictions.
10. Reproducibility and documentation of data provenance.

### 5. Preliminary Source Selection

The preliminary strategy is to evaluate two complementary weather datasets:

* **Historical reanalysis weather:** For historical weather analysis and separately defined retrospective experiments.
* **Archived weather forecasts:** For experiments intended to reproduce information available when a historical forecast was issued.

The live Weather Forecast API will be evaluated separately for the operational forecasting component.

Final selection will depend on verifying actual date coverage, hourly completeness, geographical suitability, variables, forecast lead times, and applicable usage terms.

No weather data have been downloaded or integrated during this subsection.

### 6. Research Limitation

The food demand dataset used in this project is synthetic. Combining it with genuine weather information does not establish that weather caused changes in real-world food delivery demand.

Results will therefore be interpreted as model performance on the synthetic demand benchmark and as an evaluation of the forecasting framework, not as proof of real-world causal relationships.

## 04.2.2 — Weather Source Availability Verification

### 1. Objective

This subsection verifies the practical availability of weather data from the selected Open-Meteo APIs before collecting data for the project.

The verification focuses on historical weather, archived weather forecasts, and live weather forecasts for Hyderabad, Telangana, India.

### 2. Sources to Verify

**A. Historical Weather API**

Official documentation: https://open-meteo.com/en/docs/historical-weather-api

Purpose:

* Obtain historical weather information from reanalysis datasets.
* Support retrospective weather analysis.
* Evaluate the association between weather variables and synthetic hourly food demand.

**B. Historical Forecast API**

Official documentation: https://open-meteo.com/en/docs/historical-forecast-api

Purpose:

* Retrieve archived weather forecast information.
* Investigate the use of forecast-based weather features in historical demand forecasting experiments.
* Verify available dates, variables, and forecast archive characteristics.

The API documents a continuous hourly series constructed by joining the early hours of successive forecast runs. This is not equivalent to preserving every complete original forecast run.

**C. Previous Model Runs API**

Official documentation: https://open-meteo.com/en/docs/previous-runs-api

Purpose:

* Evaluate weather forecasts at specified lead times.
* Investigate forecasts issued one or more days before the target time.
* Support experiments that require explicit forecast lead-time information.

The available history depends on the weather model and variable. Coverage must be verified before selecting this source.

**D. Live Weather Forecast API**

Official documentation: https://open-meteo.com/en/docs

Purpose:

* Obtain current and future weather forecasts.
* Supply weather information to the live demand forecasting workflow.

### 3. Verification Criteria

The following criteria will be checked:

1. API accessibility.
2. Availability of the requested date range.
3. Availability of required hourly weather variables.
4. Presence of valid timestamps and numerical observations.
5. Availability of archived forecasts for the required historical period.
6. Suitability of the source for historical backtesting or live prediction.
7. Geographic and temporal consistency with the demand dataset.
8. API usage terms and attribution requirements.

### 4. Geographical Approach

The existing zone configuration does not contain geographical coordinates.

For the initial API connectivity test, a representative Hyderabad city coordinate will be used as a provisional test location.

This test will not establish that the returned weather represents each of the five hyperlocal zones independently.

The final geographical approach will be documented before weather data are integrated into the demand panel.

### 5. Forecasting Integrity

Historical weather observations and archived weather forecasts will be treated as distinct data sources.

For historical backtesting, the weather information used for each prediction must be consistent with the information that would have been available at the forecast issue time.

Where archived forecasts do not preserve the necessary issue-time information, the experiment will be labelled accordingly rather than treated as a faithful simulation of live forecasting.

### 6. Scope Boundary

This subsection performs source verification only.

No complete weather dataset will be downloaded, and no weather data will be merged with the hourly demand panel at this stage.

The source-selection decision will be made after reviewing the actual API test results.

In [6]:
import requests
import pandas as pd

# Provisional city-level test location for Hyderabad.
# This is a connectivity-test point, not a validated coordinate
# for any individual hyperlocal zone.
latitude = 17.3850
longitude = 78.4867

# Test one day within the documented project period.
start_date = "2026-08-30"
end_date = "2026-08-30"

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": latitude,
    "longitude": longitude,
    "start_date": start_date,
    "end_date": end_date,
    "hourly": [
        "temperature_2m",
        "relative_humidity_2m",
        "precipitation",
        "rain",
        "wind_speed_10m",
        "cloud_cover"
    ],
    "timezone": "Asia/Kolkata"
}

try:
    response = requests.get(url, params=params, timeout=30)

    print("HTTP status:", response.status_code)
    response.raise_for_status()

    weather_data = response.json()

    print("\nAPI response received successfully.")
    print("Requested location:", latitude, longitude)
    print("Returned coordinates:",
          weather_data.get("latitude"),
          weather_data.get("longitude"))
    print("Timezone:", weather_data.get("timezone"))
    print("Elevation:", weather_data.get("elevation"))

    hourly_data = weather_data.get("hourly", {})
    weather_df = pd.DataFrame(hourly_data)

    print("\nReturned variables:")
    print(weather_df.columns.tolist())

    print("\nDataset shape:", weather_df.shape)

    if not weather_df.empty:
        print("\nFirst five records:")
        display(weather_df.head())

        print("\nLast timestamp returned:",
              weather_df["time"].iloc[-1])

        print("\nMissing values by variable:")
        print(weather_df.isna().sum())

except requests.exceptions.RequestException as error:
    print("API request failed:", error)

except (ValueError, KeyError) as error:
    print("Response validation failed:", error)

HTTP status: 200

API response received successfully.
Requested location: 17.385 78.4867
Returned coordinates: 17.398945 78.457085
Timezone: Asia/Kolkata
Elevation: 505.0

Returned variables:
['time', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'wind_speed_10m', 'cloud_cover']

Dataset shape: (24, 7)

First five records:

,time,temperature_2m,relative_humidity_2m,precipitation,rain,wind_speed_10m,cloud_cover
0,2026-08-30T00:00,24.1,81,0.0,0.0,15.9,100
1,2026-08-30T01:00,23.8,81,0.0,0.0,15.3,100
2,2026-08-30T02:00,23.6,81,0.0,0.0,15.8,100
3,2026-08-30T03:00,23.5,81,0.0,0.0,16.0,100
4,2026-08-30T04:00,23.4,81,0.0,0.0,15.8,100

Last timestamp returned: 2026-08-30T23:00

Missing values by variable:
time                    0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
rain                    0
wind_speed_10m          0
cloud_cover             0
dtype: int64

### 04.2.2.1 — Historical Weather API Test Results

#### Test Configuration

The Open-Meteo Historical Weather API was tested using a representative
Hyderabad city location.

The test requested hourly weather data for August 30, 2026,
using the Asia/Kolkata timezone.

The requested variables were:

- Temperature at 2 metres.
- Relative humidity at 2 metres.
- Precipitation.
- Rainfall.
- Wind speed at 10 metres.
- Cloud cover.

#### Actual Results

The API returned HTTP status 200, indicating that the request
was processed successfully.

The response contained 24 hourly observations, covering the requested
date from 00:00 through 23:00 in the Asia/Kolkata timezone.

All six requested weather variables were returned.

The missing-value check reported zero missing values for the
returned timestamps and weather variables.

The API returned geographical coordinates and elevation for the
selected location.

#### Interpretation

The test confirms that the Historical Weather API is accessible
from the project environment and can return hourly weather data
for the tested date and location.

The returned variables are candidates for historical weather analysis
and experiments involving synthetic hourly food demand.

The successful test does not establish complete data coverage for
the entire study period or guarantee that all variables are available
without missing values on every date.

The selected coordinates represent a provisional city-level test
location. They have not been validated as representative of each
hyperlocal zone.

#### Limitations

The response contains historical reanalysis weather rather than
archived forecasts.

Consequently, these observations must not be treated as weather
forecasts that would have been available at a historical prediction time.

Further checks are required to establish historical coverage,
variable availability, timestamp consistency, and suitability
for the intended forecasting experiments.

No complete weather dataset has been downloaded or integrated
into the demand panel during this test.

In [7]:
import requests
import pandas as pd

# Same provisional Hyderabad test location
latitude = 17.3850
longitude = 78.4867

# Test the same date to make the comparison easier
start_date = "2026-08-30"
end_date = "2026-08-30"

url = "https://historical-forecast-api.open-meteo.com/v1/forecast"

params = {
    "latitude": latitude,
    "longitude": longitude,
    "start_date": start_date,
    "end_date": end_date,
    "hourly": [
        "temperature_2m",
        "relative_humidity_2m",
        "precipitation",
        "rain",
        "wind_speed_10m",
        "cloud_cover"
    ],
    "timezone": "Asia/Kolkata"
}

try:
    response = requests.get(url, params=params, timeout=30)

    print("HTTP status:", response.status_code)

    response.raise_for_status()

    forecast_response = response.json()

    print("\nAPI response received successfully.")
    print("Requested date:", start_date)
    print("Returned coordinates:",
          forecast_response.get("latitude"),
          forecast_response.get("longitude"))
    print("Timezone:", forecast_response.get("timezone"))

    hourly_data = forecast_response.get("hourly", {})
    forecast_df = pd.DataFrame(hourly_data)

    print("\nReturned variables:")
    print(forecast_df.columns.tolist())

    print("\nDataset shape:", forecast_df.shape)

    if not forecast_df.empty:
        print("\nFirst five records:")
        display(forecast_df.head())

        print("\nLast timestamp returned:",
              forecast_df["time"].iloc[-1])

        print("\nMissing values by variable:")
        print(forecast_df.isna().sum())

except requests.exceptions.RequestException as error:
    print("API request failed:", error)

except (ValueError, KeyError) as error:
    print("Response validation failed:", error)

HTTP status: 200

API response received successfully.
Requested date: 2026-08-30
Returned coordinates: 17.398945 78.457085
Timezone: Asia/Kolkata

Returned variables:
['time', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'wind_speed_10m', 'cloud_cover']

Dataset shape: (24, 7)

First five records:

,time,temperature_2m,relative_humidity_2m,precipitation,rain,wind_speed_10m,cloud_cover
0,2026-08-30T00:00,24.1,81,0.0,0.0,15.9,100
1,2026-08-30T01:00,23.8,81,0.0,0.0,15.3,100
2,2026-08-30T02:00,23.6,81,0.0,0.0,15.8,100
3,2026-08-30T03:00,23.5,81,0.0,0.0,16.0,100
4,2026-08-30T04:00,23.4,81,0.0,0.0,15.8,100

Last timestamp returned: 2026-08-30T23:00

Missing values by variable:
time                    0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
rain                    0
wind_speed_10m          0
cloud_cover             0
dtype: int64

### 04.2.2.2 — Historical Forecast API Test Results

#### Test Configuration

The Open-Meteo Historical Forecast API was tested using the same
provisional Hyderabad city location and test date as the historical
weather API experiment.

The requested date was August 30, 2026.

The request used the Asia/Kolkata timezone and requested hourly
temperature, relative humidity, precipitation, rain, wind speed,
and cloud cover.

#### Actual Results

The API returned HTTP status 200.

The response contained 24 hourly records for the requested date,
covering 00:00 through 23:00 in the Asia/Kolkata timezone.

All six requested weather variables were returned.

The missing-value check reported zero missing values for the
returned timestamps and weather variables.

#### Interpretation

The test confirms that the Historical Forecast API is accessible
from the project environment and can return hourly forecast-derived
weather data for the tested date and location.

The result establishes successful access for one date only.
It does not establish complete historical coverage or guarantee
that all requested variables are available for every date.

#### Forecast Archive Limitation

The Historical Forecast API constructs a continuous hourly series
by joining the early forecast hours from successive model runs.

This structure does not preserve the complete forecast horizon
of each original model run.

Consequently, the returned series must not automatically be treated
as a complete archive of forecasts available at every historical
prediction issue time.

The suitability of this source for leakage-aware backtesting
requires further evaluation.

#### Current Status

The historical forecast endpoint passed the initial connectivity
and one-day data availability test.

No complete weather dataset has been downloaded or integrated
into the hourly demand panel.

## 04.2.3 — Archived Forecast Lead-Time Evaluation

### 1. Objective

The objective of this subsection is to evaluate whether archived weather forecasts can provide weather information at defined forecast lead times for historical food demand forecasting experiments.

The evaluation focuses on the Open-Meteo Previous Runs API and its suitability for leakage-aware backtesting.

### 2. Candidate Source

**Open-Meteo Previous Runs API**

Official documentation:
https://open-meteo.com/en/docs/previous-runs-api

The API provides weather forecasts aligned to fixed lead-time offsets.

Examples include:

- Day 0: Current model run.
- Day 1: Forecast made approximately 24 hours before the valid time.
- Day 2: Forecast made approximately 48 hours before the valid time.
- Additional lead times up to Day 7, subject to model availability.

Most models are archived from January 2024, while certain variables and models have different historical coverage.

### 3. Intended Application

The API will be evaluated for experiments that compare food demand forecasts using weather information available at different lead times.

For example, weather forecasts for a target hour may be evaluated using information from approximately one day or two days before that target hour.

This can help investigate whether forecast lead time affects demand forecasting performance.

### 4. Verification Requirements

The following will be checked:

1. API accessibility.
2. Availability of the requested historical date.
3. Availability of the required weather variables.
4. Availability of fixed-lead-time forecast fields.
5. Completeness of returned hourly records.
6. Missing values in the returned data.
7. Compatibility with the project's historical demand period.
8. Suitability for historical backtesting.

### 5. Forecast Timing and Data Leakage

A forecast's valid time is the time for which the weather is predicted. Its initialization time is when the weather model run begins.

These times must not be confused.

The Previous Runs API provides fixed lead-time offsets, but a complete historical forecasting experiment must also account for the availability of the forecast at the time the demand prediction would have been issued.

The API test alone will not establish that every historical forecast was operationally available at the exact prediction issue time.

### 6. Scope Boundary

This subsection performs a limited API availability test.

No complete weather dataset will be downloaded, and no weather data will be integrated into the demand panel.

Final source selection will depend on the actual test results and the suitability of the available forecast history.

In [8]:
import requests
import pandas as pd

# Provisional Hyderabad city-level test location
latitude = 17.3850
longitude = 78.4867

# Same test date used in the earlier weather API checks
start_date = "2026-08-30"
end_date = "2026-08-30"

url = "https://previous-runs-api.open-meteo.com/v1/forecast"

params = {
    "latitude": latitude,
    "longitude": longitude,
    "start_date": start_date,
    "end_date": end_date,
    "hourly": [
        "temperature_2m",
        "temperature_2m_previous_day1",
        "temperature_2m_previous_day2",
        "precipitation",
        "precipitation_previous_day1",
        "precipitation_previous_day2",
        "wind_speed_10m",
        "wind_speed_10m_previous_day1",
        "wind_speed_10m_previous_day2"
    ],
    "timezone": "Asia/Kolkata"
}

try:
    response = requests.get(url, params=params, timeout=30)

    print("HTTP status:", response.status_code)
    response.raise_for_status()

    previous_runs_response = response.json()

    print("\nAPI response received successfully.")
    print("Requested date:", start_date)
    print(
        "Returned coordinates:",
        previous_runs_response.get("latitude"),
        previous_runs_response.get("longitude")
    )
    print("Timezone:", previous_runs_response.get("timezone"))

    hourly_data = previous_runs_response.get("hourly", {})
    previous_runs_df = pd.DataFrame(hourly_data)

    print("\nReturned variables:")
    print(previous_runs_df.columns.tolist())

    print("\nDataset shape:", previous_runs_df.shape)

    if not previous_runs_df.empty:
        print("\nFirst five records:")
        display(previous_runs_df.head())

        print("\nLast timestamp returned:")
        print(previous_runs_df["time"].iloc[-1])

        print("\nMissing values by variable:")
        print(previous_runs_df.isna().sum())

except requests.exceptions.RequestException as error:
    print("API request failed:", error)

except (ValueError, KeyError) as error:
    print("Response validation failed:", error)

HTTP status: 200

API response received successfully.
Requested date: 2026-08-30
Returned coordinates: 17.398945 78.457085
Timezone: Asia/Kolkata

Returned variables:
['time', 'temperature_2m', 'temperature_2m_previous_day1', 'temperature_2m_previous_day2', 'precipitation', 'precipitation_previous_day1', 'precipitation_previous_day2', 'wind_speed_10m', 'wind_speed_10m_previous_day1', 'wind_speed_10m_previous_day2']

Dataset shape: (24, 10)

First five records:

,time,temperature_2m,temperature_2m_previous_day1,temperature_2m_previous_day2,precipitation,precipitation_previous_day1,precipitation_previous_day2,wind_speed_10m,wind_speed_10m_previous_day1,wind_speed_10m_previous_day2
0,2026-08-30T00:00,24.1,23.3,24.0,0.0,0.1,0.1,15.9,15.7,14.9
1,2026-08-30T01:00,23.8,23.6,23.8,0.0,0.1,0.1,15.3,15.9,14.6
2,2026-08-30T02:00,23.6,23.5,23.7,0.0,0.0,0.0,15.8,16.1,14.9
3,2026-08-30T03:00,23.5,23.3,23.5,0.0,0.0,0.0,16.0,16.2,15.7
4,2026-08-30T04:00,23.4,23.1,23.4,0.0,0.0,0.0,15.8,16.2,15.5

Last timestamp returned:
2026-08-30T23:00

Missing values by variable:
time                            0
temperature_2m                  0
temperature_2m_previous_day1    0
temperature_2m_previous_day2    0
precipitation                   0
precipitation_previous_day1     0
precipitation_previous_day2     0
wind_speed_10m                  0
wind_speed_10m_previous_day1    0
wind_speed_10m_previous_day2    0
dtype: int64

### 04.2.3.1 — Previous Runs API Test Results

#### Test Configuration

The Open-Meteo Previous Runs API was tested using a provisional
Hyderabad city-level location.

The requested date was August 30, 2026, and the timezone was
set to Asia/Kolkata.

The request included current-run weather fields and Day 1 and
Day 2 forecast fields for temperature, precipitation, and wind speed.

#### Actual Results

The API returned HTTP status 200.

The response contained 24 hourly observations and 10 columns,
including the timestamp.

The returned data included temperature, precipitation, and wind
speed fields for Day 1 and Day 2 forecast offsets.

The missing-value check reported zero missing values in all
returned columns for the tested date.

#### Interpretation

The test confirms that the Previous Runs API is accessible from
the project environment and returns the requested fixed-lead-time
weather fields for the selected date.

The result is a successful one-day availability test. It does not
establish complete historical coverage or guarantee that every
forecast variable is available for every date.

#### Forecast Timing Limitation

The forecast offset fields must be interpreted according to the
API's documented timing conventions.

Before using these fields in historical backtesting, the project
must establish the relationship between each forecast's valid time,
lead time, and information availability time.

The returned fields must not be assumed to represent a complete
archive of all original weather model runs.

#### Current Status

The Previous Runs API passed the initial connectivity and
one-day availability test.

Further verification is required before selecting it as the
weather source for leakage-aware backtesting.

No complete weather dataset has been downloaded or integrated
into the hourly demand panel.

## 04.2.4 — Weather Source Comparison and Selection

### 1. Objective

The objective of this subsection is to compare the evaluated weather
data sources and select suitable candidates for historical analysis,
forecasting experiments, and live demand prediction.

The project's demand panel covers January 1, 2023, through
August 30, 2026. Therefore, source selection must consider the
entire study period, hourly data availability, forecast timing,
and the requirements of leakage-aware evaluation.

### 2. Sources Evaluated

Four Open-Meteo endpoints have been considered:

1. Historical Weather API.
2. Historical Forecast API.
3. Previous Runs API.
4. Live Weather Forecast API.

The first three endpoints were tested using a one-day request
for August 30, 2026. The live forecast endpoint has not yet
been tested in this subsection.

### 3. Results of Initial API Tests

The following results were observed during notebook execution:

- Historical Weather API: HTTP 200, 24 hourly records, six requested
  weather variables returned, and no missing values in the tested response.
- Historical Forecast API: HTTP 200, 24 hourly records, six requested
  weather variables returned, and no missing values in the tested response.
- Previous Runs API: HTTP 200, 24 hourly records, current-run and
  Day 1 and Day 2 forecast fields returned, and no missing values
  in the tested response.

These results establish successful access for the tested date only.
They do not establish complete historical coverage or completeness
for every date and variable in the project period.

### 4. Comparative Assessment

#### A. Historical Weather API

Purpose:
- Historical weather analysis.
- Retrospective experiments using reconstructed weather conditions.

Advantages:
- Historical coverage extends before the project's start date.
- Hourly weather variables are available.
- Suitable for constructing a consistent historical weather dataset,
  subject to model selection and validation.

Limitation:
- Reanalysis observations do not represent weather forecasts
  that were available at historical prediction issue times.

Preliminary decision:
- Select as the primary candidate for historical weather analysis.

#### B. Historical Forecast API

Purpose:
- Historical experiments using a continuous series of forecast-derived
  weather values.

Advantages:
- Forecast-derived data are available for recent historical periods.
- Hourly variables can be aligned with the demand timeline.
- Useful for investigating models trained on operational forecast output.

Limitation:
- The endpoint joins early forecast hours from successive model runs.
  It does not preserve the complete forecast horizon of every original run.
- Model versions and historical coverage may vary over time.

Preliminary decision:
- Retain as a candidate for historical forecast-derived experiments.
  Verify date coverage and the implications of model changes before use.

#### C. Previous Runs API

Purpose:
- Evaluate weather forecasts at fixed lead times.
- Compare forecasts issued approximately one or more days before
  their valid times.

Advantages:
- Provides forecast fields at documented lead-time offsets.
- Useful for evaluating how forecast lead time may affect demand
  forecasting performance.

Limitations:
- Historical availability varies by model and variable.
- Most models are archived from January 2024, with exceptions.
- The tested endpoint does not by itself establish the exact
  operational availability of every forecast at every prediction time.

Preliminary decision:
- Retain as a candidate for fixed-lead-time experiments.
  Verify the required coverage before selecting variables and models.

#### D. Live Weather Forecast API

Purpose:
- Obtain current and future weather forecasts for live demand prediction.

Advantages:
- Designed to provide current and future weather forecast information.

Limitation:
- It has not yet been tested in this subsection.
- Live forecasts cannot substitute for archived forecasts during
  historical backtesting.

Preliminary decision:
- Retain as the candidate for the live forecasting workflow,
  subject to an API availability test.

### 5. Preliminary Source Selection

The proposed strategy is to use different sources for different purposes:

1. Historical Weather API:
   Historical weather analysis and experiments using reanalysis features.

2. Historical Forecast API:
   Experiments using continuous historical forecast-derived weather data.

3. Previous Runs API:
   Fixed-lead-time experiments where the required historical model
   and variable coverage is available.

4. Live Weather Forecast API:
   Weather inputs for live demand predictions.

These sources are complementary and should not be treated as interchangeable.

### 6. Data Leakage and Forecast Timing

The weather data used in each experiment must match the information
available at the forecast issue time.

Actual future weather observations must not be used as if they were
known when a historical demand forecast was generated.

For experiments using archived forecasts, the valid time, forecast
lead time, and information availability must be considered.

Where the source does not preserve sufficient issue-time information,
the experiment must be described as forecast-derived rather than
as a complete reproduction of an operational historical forecast.

### 7. Geographical Limitation

The existing zone configuration contains no geographical coordinates
or boundaries.

The initial API tests used a provisional city-level Hyderabad location.

The returned weather data must therefore not be interpreted as
independently observed weather for each hyperlocal zone.

The final geographical strategy will be documented before integration.

### 8. Scope Boundary

This subsection documents the initial source comparison and
preliminary selection strategy.

The API tests were limited to one date and did not download a
complete historical weather dataset.

No weather data have been merged with the hourly demand panel.

Further validation is required for date coverage, variable availability,
timestamp consistency, forecast timing, and applicable usage terms.

### 9. Next Step

Evaluate the live Weather Forecast API and verify its response
before selecting the source for the live demand forecasting workflow.

## 04.2.5 — Live Weather Forecast API Verification

### Objective
The objective of this subsection is to verify the availability and structure of the Open-Meteo Live Weather Forecast API for Hyderabad. This API provides forecast information that can support future food-demand forecasting and operational decision-making.

### Data Source
- **API:** Open-Meteo Weather Forecast API
- **Endpoint:** https://api.open-meteo.com/v1/forecast
- **Location:** Hyderabad, Telangana, India
- **Timezone:** Asia/Kolkata

### Variables to Inspect
The following hourly weather variables will be requested:

- Temperature at 2 metres
- Relative humidity
- Precipitation probability
- Precipitation
- Rainfall
- Wind speed at 10 metres
- Cloud cover
- Weather condition code

### Verification Procedure
1. Send a request to the Live Weather Forecast API.
2. Inspect the HTTP response status.
3. Verify the returned coordinates and timezone.
4. Examine the forecast start and end timestamps.
5. Confirm the number of forecast records and available variables.
6. Check for missing values.
7. Inspect a sample of the returned hourly forecast.

### Expected Outcome
This test will establish whether the API provides the requested forecast variables and a usable hourly forecast horizon at the selected Hyderabad location.

### Important Limitation
This test verifies the API's current forecast response only. It does not establish historical forecast availability or prove that the forecast was available at a particular past prediction time. Forecast issue time and valid time must be distinguished when designing leakage-free evaluation experiments.

The API response will change over time. The actual output from the verification code will be used to document the results.

In [9]:
# ============================================================
# 04.2.5 — Live Weather Forecast API Verification
# ============================================================

import requests
import pandas as pd

API_URL = "https://api.open-meteo.com/v1/forecast"

params = {
    "latitude": 17.3850,
    "longitude": 78.4867,
    "hourly": [
        "temperature_2m",
        "relative_humidity_2m",
        "precipitation_probability",
        "precipitation",
        "rain",
        "wind_speed_10m",
        "cloud_cover",
        "weather_code",
    ],
    "forecast_days": 3,
    "timezone": "Asia/Kolkata",
}

response = requests.get(API_URL, params=params, timeout=30)

print("HTTP Status Code:", response.status_code)
response.raise_for_status()

weather_json = response.json()

# Inspect location and response metadata
print("\n--- API Metadata ---")
print("Requested Latitude:", params["latitude"])
print("Requested Longitude:", params["longitude"])
print("Returned Latitude:", weather_json.get("latitude"))
print("Returned Longitude:", weather_json.get("longitude"))
print("Timezone:", weather_json.get("timezone"))
print("Timezone Abbreviation:", weather_json.get("timezone_abbreviation"))
print("Elevation (m):", weather_json.get("elevation"))

# Convert hourly response into a DataFrame
hourly_data = weather_json["hourly"]
weather_df = pd.DataFrame(hourly_data)

print("\n--- Forecast Summary ---")
print("Number of hourly records:", len(weather_df))
print("Forecast start:", weather_df["time"].min())
print("Forecast end:", weather_df["time"].max())
print("Columns:", weather_df.columns.tolist())

print("\n--- Missing Values ---")
print(weather_df.isna().sum())

print("\n--- First 10 Forecast Records ---")
display(weather_df.head(10))

print("\n--- Last 5 Forecast Records ---")
display(weather_df.tail(5))

HTTP Status Code: 200

--- API Metadata ---
Requested Latitude: 17.385
Requested Longitude: 78.4867
Returned Latitude: 17.398945
Returned Longitude: 78.457085
Timezone: Asia/Kolkata
Timezone Abbreviation: GMT+5:30
Elevation (m): 505.0

--- Forecast Summary ---
Number of hourly records: 72
Forecast start: 2026-10-28T00:00
Forecast end: 2026-10-30T23:00
Columns: ['time', 'temperature_2m', 'relative_humidity_2m', 'precipitation_probability', 'precipitation', 'rain', 'wind_speed_10m', 'cloud_cover', 'weather_code']

--- Missing Values ---
time                         0
temperature_2m               0
relative_humidity_2m         0
precipitation_probability    0
precipitation                0
rain                         0
wind_speed_10m               0
cloud_cover                  0
weather_code                 0
dtype: int64

--- First 10 Forecast Records ---

,time,temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,rain,wind_speed_10m,cloud_cover,weather_code
0,2026-10-28T00:00,24.6,63,3,0.0,0.0,13.0,100,3
1,2026-10-28T01:00,24.2,66,2,0.0,0.0,12.5,100,3
2,2026-10-28T02:00,23.8,70,2,0.0,0.0,12.7,100,3
3,2026-10-28T03:00,23.4,72,2,0.0,0.0,13.4,100,3
4,2026-10-28T04:00,23.2,74,2,0.0,0.0,13.1,100,3
5,2026-10-28T05:00,23.2,73,4,0.0,0.0,11.9,100,3
6,2026-10-28T06:00,23.2,73,9,0.0,0.0,12.0,100,3
7,2026-10-28T07:00,23.4,73,15,0.0,0.0,11.3,100,3
8,2026-10-28T08:00,24.1,70,20,0.0,0.0,13.1,100,3
9,2026-10-28T09:00,25.3,67,22,0.0,0.0,14.6,100,3

--- Last 5 Forecast Records ---

,time,temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,rain,wind_speed_10m,cloud_cover,weather_code
67,2026-10-30T19:00,28.3,64,46,0.0,0.0,1.9,21,1
68,2026-10-30T20:00,26.1,71,29,0.2,0.1,8.1,84,51
69,2026-10-30T21:00,25.5,76,19,0.8,0.7,6.3,26,53
70,2026-10-30T22:00,25.2,77,12,0.0,0.0,1.3,23,1
71,2026-10-30T23:00,24.9,79,8,0.0,0.0,2.4,33,1

### 04.2.5.1 — Live Weather Forecast API Verification Findings

#### Actual Verification Results

The Open-Meteo Live Weather Forecast API was successfully accessed using the requested Hyderabad coordinates and the `Asia/Kolkata` timezone.

| Verification Item | Actual Result |
|---|---|
| HTTP Status Code | 200 |
| Requested Latitude | 17.3850 |
| Requested Longitude | 78.4867 |
| Returned Latitude | 17.398945 |
| Returned Longitude | 78.457085 |
| Timezone | Asia/Kolkata |
| Timezone Abbreviation | GMT+5:30 |
| Returned Elevation | 505 metres |
| Forecast Records | 72 hourly records |
| Forecast Start | 2026-10-21 00:00 |
| Forecast End | 2026-10-23 23:00 |
| Missing Values | Zero in all returned columns |

#### Variables Successfully Retrieved

The API returned all eight requested weather variables:

1. `temperature_2m`
2. `relative_humidity_2m`
3. `precipitation_probability`
4. `precipitation`
5. `rain`
6. `wind_speed_10m`
7. `cloud_cover`
8. `weather_code`

#### Findings

The test confirms that the API was accessible and returned a complete 72-hour hourly forecast for the selected location. All requested weather variables were present, and no missing values were observed in this response.

The returned coordinates differ slightly from the requested coordinates. This is consistent with a gridded weather service returning the coordinates of its selected grid cell rather than the exact requested point.

#### Limitations

- This test verifies only the forecast returned at the time of execution.
- Zero missing values in this response do not guarantee complete coverage in future API requests.
- The forecast must not be treated as historical weather observations.
- The forecast's availability at a specific prediction time must be established before using it in leakage-free backtesting.
- The selected coordinate represents one weather grid location and does not provide separate weather observations for all five synthetic Hyderabad zones.

#### Conclusion

The Open-Meteo Live Weather Forecast API is technically accessible and suitable for further investigation as a potential source of current and future weather forecasts. Its use in the project will depend on the forecasting workflow and the availability of weather information at each simulated prediction time.

## 04.2.6 — Weather Source Selection Decision

### Objective

The objective of this subsection is to select appropriate weather data sources for the project based on the API verification experiments, historical coverage, forecast availability, temporal resolution, and suitability for leakage-free forecasting evaluation.

The project requires weather information to support hourly food-demand forecasting across five synthetic hyperlocal zones in Hyderabad.

### 1. Summary of API Verification

Four Open-Meteo API options have been investigated.

| API | Verification Status | Primary Purpose |
|---|---|---|
| Historical Weather API | Tested successfully | Historical weather reanalysis |
| Historical Forecast API | Tested successfully | Continuous forecast-derived historical series |
| Previous Runs API | Tested successfully | Weather forecasts from earlier forecast runs |
| Live Weather Forecast API | Tested successfully | Current and future weather forecasts |

Each tested API returned HTTP 200 and the requested hourly weather variables for the test date. The live forecast test returned 72 hourly records, while the three historical API tests returned 24 hourly records each.

These results establish successful access for the tested requests only. They do not establish complete data coverage over the entire project period.

### 2. Proposed Source Selection

#### A. Historical Weather API — Historical Analysis

The Historical Weather API will be considered the primary source for historical weather analysis and exploratory analysis.

Potential variables include:

- Temperature
- Relative humidity
- Precipitation
- Rainfall
- Wind speed
- Cloud cover

Historical reanalysis data will help investigate how weather conditions correspond to demand patterns in the synthetic dataset.

However, these observations or reanalysis estimates must not be treated as weather forecasts that were necessarily available at the original prediction time.

#### B. Previous Runs API — Forecasting Experiments

The Previous Runs API will be evaluated for forecasting experiments that require weather forecasts issued before the target hour.

The dataset must preserve the distinction between:

- Forecast issue time
- Forecast valid time
- Forecast lead time

For example, a forecast for 7:00 PM issued at 3:00 PM must be distinguishable from a forecast for the same hour issued at 6:00 PM.

The API's historical coverage and the availability of the required variables must be verified before selecting a forecast lead time for backtesting.

#### C. Historical Forecast API — Supporting Analysis

The Historical Forecast API will be retained as a supporting source for examining historical forecast-derived weather series.

Because this API constructs continuous series from successive forecast runs, it must not automatically be interpreted as a complete archive of individual forecast runs.

It will not be the primary source for fixed-lead-time backtesting unless the data structure and forecast timing are shown to meet the experiment's requirements.

#### D. Live Weather Forecast API — Application Layer

The Live Weather Forecast API will be considered for the future operational application.

It can provide current and upcoming weather forecasts that may be used alongside demand predictions.

The live API response will not be substituted for historical forecasts in retrospective model evaluation.

### 3. Selected Experimental Strategy

The project will use two distinct weather-data tracks.

**Track 1 — Historical Analysis**

Use historical weather data to investigate associations between weather variables and synthetic hourly demand.

**Track 2 — Forecast-Aware Evaluation**

Use archived forecasts with identifiable issue times and valid times, where sufficient historical coverage exists, to evaluate whether weather information could realistically have been available when a demand forecast was produced.

If archived forecast coverage is insufficient for the selected historical period, this limitation will be documented. Historical reanalysis will not be silently substituted for archived forecasts in a leakage-sensitive experiment.

### 4. Spatial Resolution Consideration

The current verification tests use one Hyderabad coordinate. The API returned a grid-cell location that differed slightly from the requested coordinates.

Consequently, the tested weather series represents one selected grid location, not five independently measured hyperlocal zones.

For the initial experiment, the project may use a documented city-level weather series as a shared contextual feature across the five synthetic zones. Zone-specific weather features will be considered only if an appropriate spatial assignment method and sufficient source resolution are available.

### 5. Data Quality and Leakage Controls

Before integrating weather data into the forecasting dataset, the following checks are required:

1. Verify temporal coverage for the required project dates.
2. Check hourly timestamp continuity and missing values.
3. Confirm units and variable definitions.
4. Standardize timestamps to the `Asia/Kolkata` timezone.
5. Preserve forecast issue time and valid time when available.
6. Prevent the use of future weather observations as if they were known at prediction time.
7. Record the API endpoint, retrieval date, parameters, and source metadata.
8. Review applicable data attribution and usage requirements.

### 6. Provisional Decision

| Project Requirement | Provisional Decision |
|---|---|
| Historical weather-demand analysis | Historical Weather API |
| Fixed-lead-time weather-aware backtesting | Previous Runs API, subject to coverage verification |
| Supporting historical forecast analysis | Historical Forecast API |
| Current and future application forecasts | Live Weather Forecast API |

### Conclusion

The initial API verification tests indicate that all four endpoints can return the requested weather variables for the tested requests. The Historical Weather API and Previous Runs API serve different research purposes and must not be treated as interchangeable.

The source selection remains provisional until historical coverage, forecast timing, data consistency, and usage requirements have been checked for the complete project period.

## 04.2.7 — Historical Weather Data Coverage and Completeness Assessment

### Objective

The objective of this subsection is to evaluate the temporal coverage, hourly continuity, and data completeness of the Open-Meteo Historical Weather API for the project's study period.

The required study period is January 1, 2023, through July 31, 2026. The selected location is Hyderabad, Telangana, India, using the `Asia/Kolkata` timezone.

### Data Source

- **Provider:** Open-Meteo
- **API:** Historical Weather API
- **Endpoint:** https://archive-api.open-meteo.com/v1/archive
- **Requested Latitude:** 17.3850
- **Requested Longitude:** 78.4867
- **Timezone:** Asia/Kolkata

### Variables

The following hourly weather variables will be examined:

1. Temperature at 2 metres
2. Relative humidity
3. Precipitation
4. Rainfall
5. Wind speed at 10 metres
6. Cloud cover

### Assessment Procedure

The assessment will:

1. Request historical weather data in manageable monthly batches.
2. record successful and unsuccessful API requests.
3. Count the returned hourly records.
4. Compare the returned timestamps with the expected hourly timeline.
5. Identify missing timestamps and missing variable values.
6. Check for duplicate timestamps.
7. Summarize coverage by month.
8. Determine whether the retrieved data is suitable for further processing.

### Expected Outcome

The assessment will provide evidence of the API's availability and completeness over the requested period.

A successful API response alone will not be considered sufficient proof of complete coverage. Actual timestamps, record counts, duplicate records, missing values, and failed requests will be examined.

### Important Limitations

The API returns gridded historical weather estimates, not independent weather observations for each synthetic delivery zone.

The initial assessment uses one Hyderabad coordinate. The returned grid-cell coordinates will be recorded because they may differ from the requested coordinates.

This assessment evaluates historical weather data only. It does not establish that the same information was available as a forecast at the original demand-prediction time.

In [10]:
# ============================================================
# 04.2.7 — Historical Weather Coverage Assessment
# ============================================================

import time
import requests
import pandas as pd
from IPython.display import display

# ------------------------------------------------------------
# 1. Configuration
# ------------------------------------------------------------

API_URL = "https://archive-api.open-meteo.com/v1/archive"

LATITUDE = 17.3850
LONGITUDE = 78.4867
TIMEZONE = "Asia/Kolkata"

START_DATE = "2023-01-01"
END_DATE = "2026-07-31"

WEATHER_VARIABLES = [
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "rain",
    "wind_speed_10m",
    "cloud_cover",
]

EXPECTED_COLUMNS = ["time"] + WEATHER_VARIABLES

session = requests.Session()

# ------------------------------------------------------------
# 2. Generate monthly request periods
# ------------------------------------------------------------

start = pd.Timestamp(START_DATE)
end = pd.Timestamp(END_DATE)

month_starts = pd.date_range(
    start=start.replace(day=1),
    end=end.replace(day=1),
    freq="MS"
)

monthly_periods = []

for month_start in month_starts:
    month_end = month_start + pd.offsets.MonthEnd(0)

    period_start = max(month_start, start)
    period_end = min(month_end, end)

    monthly_periods.append(
        (
            period_start.strftime("%Y-%m-%d"),
            period_end.strftime("%Y-%m-%d")
        )
    )

print("Assessment period:", START_DATE, "to", END_DATE)
print("Monthly API requests:", len(monthly_periods))
print("Weather variables:", len(WEATHER_VARIABLES))

# ------------------------------------------------------------
# 3. Retrieve data month by month
# ------------------------------------------------------------

monthly_data = []
request_log = []

for period_start, period_end in monthly_periods:

    params = {
        "latitude": LATITUDE,
        "longitude": LONGITUDE,
        "start_date": period_start,
        "end_date": period_end,
        "hourly": WEATHER_VARIABLES,
        "timezone": TIMEZONE,
    }

    try:
        response = session.get(
            API_URL,
            params=params,
            timeout=60
        )

        response.raise_for_status()
        payload = response.json()

        if "hourly" not in payload or "time" not in payload["hourly"]:
            raise ValueError("API response does not contain hourly timestamps.")

        month_df = pd.DataFrame(payload["hourly"])

        missing_columns = [
            column for column in EXPECTED_COLUMNS
            if column not in month_df.columns
        ]

        if missing_columns:
            raise ValueError(
                f"Missing expected columns: {missing_columns}"
            )

        month_df = month_df[EXPECTED_COLUMNS].copy()
        month_df["time"] = pd.to_datetime(month_df["time"])

        monthly_data.append(month_df)

        request_log.append({
            "period_start": period_start,
            "period_end": period_end,
            "status": "SUCCESS",
            "http_status": response.status_code,
            "records": len(month_df),
            "returned_latitude": payload.get("latitude"),
            "returned_longitude": payload.get("longitude"),
            "error": None,
        })

        print(
            f"SUCCESS | {period_start} to {period_end} "
            f"| {len(month_df):,} hourly records"
        )

    except Exception as exc:
        request_log.append({
            "period_start": period_start,
            "period_end": period_end,
            "status": "FAILED",
            "http_status": (
                response.status_code
                if "response" in locals()
                else None
            ),
            "records": 0,
            "returned_latitude": None,
            "returned_longitude": None,
            "error": str(exc),
        })

        print(
            f"FAILED  | {period_start} to {period_end} "
            f"| {type(exc).__name__}: {exc}"
        )

    # Small pause between requests
    time.sleep(0.2)

# ------------------------------------------------------------
# 4. Build the assessment tables
# ------------------------------------------------------------

request_log_df = pd.DataFrame(request_log)

successful_months = request_log_df[
    request_log_df["status"] == "SUCCESS"
]

failed_months = request_log_df[
    request_log_df["status"] == "FAILED"
]

print("\n--- Request Summary ---")
print("Total monthly requests:", len(request_log_df))
print("Successful requests:", len(successful_months))
print("Failed requests:", len(failed_months))

display(request_log_df)

# ------------------------------------------------------------
# 5. Combine successful monthly responses
# ------------------------------------------------------------

if not monthly_data:
    raise RuntimeError(
        "No monthly weather data was retrieved. "
        "Inspect request_log_df before proceeding."
    )

weather_coverage_df = pd.concat(
    monthly_data,
    ignore_index=True
)

weather_coverage_df = weather_coverage_df.sort_values(
    "time"
).reset_index(drop=True)

print("\n--- Retrieved Data Summary ---")
print("Shape:", weather_coverage_df.shape)
print("First timestamp:", weather_coverage_df["time"].min())
print("Last timestamp:", weather_coverage_df["time"].max())

print("\n--- Missing Values by Column ---")
display(weather_coverage_df.isna().sum().to_frame("missing_values"))

# ------------------------------------------------------------
# 6. Check duplicate timestamps
# ------------------------------------------------------------

duplicate_count = weather_coverage_df["time"].duplicated().sum()

print("\n--- Duplicate Timestamp Check ---")
print("Duplicate timestamps:", duplicate_count)

# ------------------------------------------------------------
# 7. Check expected hourly timeline
# ------------------------------------------------------------

expected_timeline = pd.date_range(
    start=pd.Timestamp(START_DATE),
    end=pd.Timestamp(END_DATE) + pd.Timedelta(hours=23),
    freq="h"
)

actual_timeline = pd.DatetimeIndex(
    weather_coverage_df["time"].drop_duplicates().sort_values()
)

missing_timestamps = expected_timeline.difference(actual_timeline)
unexpected_timestamps = actual_timeline.difference(expected_timeline)

print("\n--- Hourly Timeline Check ---")
print("Expected hourly timestamps:", len(expected_timeline))
print("Unique returned timestamps:", len(actual_timeline))
print("Missing timestamps:", len(missing_timestamps))
print("Unexpected timestamps:", len(unexpected_timestamps))

if len(missing_timestamps) > 0:
    print("\nFirst 20 missing timestamps:")
    print(missing_timestamps[:20].tolist())

if len(unexpected_timestamps) > 0:
    print("\nFirst 20 unexpected timestamps:")
    print(unexpected_timestamps[:20].tolist())

# ------------------------------------------------------------
# 8. Summarize actual monthly coverage
# ------------------------------------------------------------

weather_coverage_df["month"] = (
    weather_coverage_df["time"].dt.to_period("M").astype(str)
)

monthly_coverage = (
    weather_coverage_df
    .groupby("month")
    .agg(
        returned_records=("time", "size"),
        unique_timestamps=("time", "nunique"),
    )
    .reset_index()
)

monthly_coverage["expected_records"] = (
    monthly_coverage["month"]
    .apply(
        lambda month: len(
            pd.date_range(
                start=pd.Period(month, freq="M").start_time,
                end=pd.Period(month, freq="M").end_time.floor("h"),
                freq="h"
            )
        )
    )
)

monthly_coverage["record_difference"] = (
    monthly_coverage["returned_records"]
    - monthly_coverage["expected_records"]
)

print("\n--- Monthly Coverage Summary ---")
display(monthly_coverage)

# ------------------------------------------------------------
# 9. Final preliminary assessment
# ------------------------------------------------------------

all_requests_succeeded = len(failed_months) == 0
no_duplicate_timestamps = duplicate_count == 0
no_missing_timestamps = len(missing_timestamps) == 0
no_missing_values = weather_coverage_df[
    WEATHER_VARIABLES
].isna().sum().sum() == 0

print("\n--- Preliminary Assessment ---")
print("All monthly requests succeeded:", all_requests_succeeded)
print("No duplicate timestamps:", no_duplicate_timestamps)
print("No missing timestamps:", no_missing_timestamps)
print("No missing weather values:", no_missing_values)

print(
    "\nNote: This assessment checks the returned data. "
    "Review monthly coverage and failed requests before "
    "deciding whether the dataset is ready for integration."
)

Assessment period: 2023-01-01 to 2026-07-31
Monthly API requests: 43
Weather variables: 6
SUCCESS | 2023-01-01 to 2023-01-31 | 744 hourly records
SUCCESS | 2023-02-01 to 2023-02-28 | 672 hourly records
SUCCESS | 2023-03-01 to 2023-03-31 | 744 hourly records
SUCCESS | 2023-04-01 to 2023-04-30 | 720 hourly records
SUCCESS | 2023-05-01 to 2023-05-31 | 744 hourly records
SUCCESS | 2023-06-01 to 2023-06-30 | 720 hourly records
SUCCESS | 2023-07-01 to 2023-07-31 | 744 hourly records
SUCCESS | 2023-08-01 to 2023-08-31 | 744 hourly records
SUCCESS | 2023-09-01 to 2023-09-30 | 720 hourly records
SUCCESS | 2023-10-01 to 2023-10-31 | 744 hourly records
SUCCESS | 2023-11-01 to 2023-11-30 | 720 hourly records
SUCCESS | 2023-12-01 to 2023-12-31 | 744 hourly records
SUCCESS | 2024-01-01 to 2024-01-31 | 744 hourly records
SUCCESS | 2024-02-01 to 2024-02-29 | 696 hourly records
SUCCESS | 2024-03-01 to 2024-03-31 | 744 hourly records
SUCCESS | 2024-04-01 to 2024-04-30 | 720 hourly records
SUCCESS | 2024-05-01 to 2024-05-31 | 744 hourly records
SUCCESS | 2024-06-01 to 2024-06-30 | 720 hourly records
SUCCESS | 2024-07-01 to 2024-07-31 | 744 hourly records
SUCCESS | 2024-08-01 to 2024-08-31 | 744 hourly records
SUCCESS | 2024-09-01 to 2024-09-30 | 720 hourly records
SUCCESS | 2024-10-01 to 2024-10-31 | 744 hourly records
SUCCESS | 2024-11-01 to 2024-11-30 | 720 hourly records
SUCCESS | 2024-12-01 to 2024-12-31 | 744 hourly records
SUCCESS | 2025-01-01 to 2025-01-31 | 744 hourly records
SUCCESS | 2025-02-01 to 2025-02-28 | 672 hourly records
SUCCESS | 2025-03-01 to 2025-03-31 | 744 hourly records
SUCCESS | 2025-04-01 to 2025-04-30 | 720 hourly records
SUCCESS | 2025-05-01 to 2025-05-31 | 744 hourly records
SUCCESS | 2025-06-01 to 2025-06-30 | 720 hourly records
SUCCESS | 2025-07-01 to 2025-07-31 | 744 hourly records
SUCCESS | 2025-08-01 to 2025-08-31 | 744 hourly records
SUCCESS | 2025-09-01 to 2025-09-30 | 720 hourly records
SUCCESS | 2025-10-01 to 2025-10-31 | 744 hourly records
SUCCESS | 2025-11-01 to 2025-11-30 | 720 hourly records
SUCCESS | 2025-12-01 to 2025-12-31 | 744 hourly records
SUCCESS | 2026-01-01 to 2026-01-31 | 744 hourly records
SUCCESS | 2026-02-01 to 2026-02-28 | 672 hourly records
SUCCESS | 2026-03-01 to 2026-03-31 | 744 hourly records
SUCCESS | 2026-04-01 to 2026-04-30 | 720 hourly records
SUCCESS | 2026-05-01 to 2026-05-31 | 744 hourly records
SUCCESS | 2026-06-01 to 2026-06-30 | 720 hourly records
SUCCESS | 2026-07-01 to 2026-07-31 | 744 hourly records

--- Request Summary ---
Total monthly requests: 43
Successful requests: 43
Failed requests: 0

,period_start,period_end,status,http_status,records,returned_latitude,returned_longitude,error
0,2023-01-01,2023-01-31,SUCCESS,200,744,17.398945,78.457085,None
1,2023-02-01,2023-02-28,SUCCESS,200,672,17.398945,78.457085,None
2,2023-03-01,2023-03-31,SUCCESS,200,744,17.398945,78.457085,None
3,2023-04-01,2023-04-30,SUCCESS,200,720,17.398945,78.457085,None
4,2023-05-01,2023-05-31,SUCCESS,200,744,17.398945,78.457085,None
5,2023-06-01,2023-06-30,SUCCESS,200,720,17.398945,78.457085,None
6,2023-07-01,2023-07-31,SUCCESS,200,744,17.398945,78.457085,None
7,2023-08-01,2023-08-31,SUCCESS,200,744,17.398945,78.457085,None
8,2023-09-01,2023-09-30,SUCCESS,200,720,17.398945,78.457085,None
9,2023-10-01,2023-10-31,SUCCESS,200,744,17.398945,78.457085,None
10,2023-11-01,2023-11-30,SUCCESS,200,720,17.398945,78.457085,None
11,2023-12-01,2023-12-31,SUCCESS,200,744,17.398945,78.457085,None
12,2024-01-01,2024-01-31,SUCCESS,200,744,17.398945,78.457085,None
13,2024-02-01,2024-02-29,SUCCESS,200,696,17.398945,78.457085,None
14,2024-03-01,2024-03-31,SUCCESS,200,744,17.398945,78.457085,None
15,2024-04-01,2024-04-30,SUCCESS,200,720,17.398945,78.457085,None
16,2024-05-01,2024-05-31,SUCCESS,200,744,17.398945,78.457085,None
17,2024-06-01,2024-06-30,SUCCESS,200,720,17.398945,78.457085,None
18,2024-07-01,2024-07-31,SUCCESS,200,744,17.398945,78.457085,None
19,2024-08-01,2024-08-31,SUCCESS,200,744,17.398945,78.457085,None
20,2024-09-01,2024-09-30,SUCCESS,200,720,17.398945,78.457085,None
21,2024-10-01,2024-10-31,SUCCESS,200,744,17.398945,78.457085,None
22,2024-11-01,2024-11-30,SUCCESS,200,720,17.398945,78.457085,None
23,2024-12-01,2024-12-31,SUCCESS,200,744,17.398945,78.457085,None
24,2025-01-01,2025-01-31,SUCCESS,200,744,17.398945,78.457085,None
25,2025-02-01,2025-02-28,SUCCESS,200,672,17.398945,78.457085,None
26,2025-03-01,2025-03-31,SUCCESS,200,744,17.398945,78.457085,None
27,2025-04-01,2025-04-30,SUCCESS,200,720,17.398945,78.457085,None
28,2025-05-01,2025-05-31,SUCCESS,200,744,17.398945,78.457085,None
29,2025-06-01,2025-06-30,SUCCESS,200,720,17.398945,78.457085,None
30,2025-07-01,2025-07-31,SUCCESS,200,744,17.398945,78.457085,None
31,2025-08-01,2025-08-31,SUCCESS,200,744,17.398945,78.457085,None
32,2025-09-01,2025-09-30,SUCCESS,200,720,17.398945,78.457085,None
33,2025-10-01,2025-10-31,SUCCESS,200,744,17.398945,78.457085,None
34,2025-11-01,2025-11-30,SUCCESS,200,720,17.398945,78.457085,None
35,2025-12-01,2025-12-31,SUCCESS,200,744,17.398945,78.457085,None
36,2026-01-01,2026-01-31,SUCCESS,200,744,17.398945,78.457085,None
37,2026-02-01,2026-02-28,SUCCESS,200,672,17.398945,78.457085,None
38,2026-03-01,2026-03-31,SUCCESS,200,744,17.398945,78.457085,None
39,2026-04-01,2026-04-30,SUCCESS,200,720,17.398945,78.457085,None
40,2026-05-01,2026-05-31,SUCCESS,200,744,17.398945,78.457085,None
41,2026-06-01,2026-06-30,SUCCESS,200,720,17.398945,78.457085,None
42,2026-07-01,2026-07-31,SUCCESS,200,744,17.398945,78.457085,None

--- Retrieved Data Summary ---
Shape: (31392, 7)
First timestamp: 2023-01-01 00:00:00
Last timestamp: 2026-07-31 23:00:00

--- Missing Values by Column ---

                      missing_values
time                               0
temperature_2m                     0
relative_humidity_2m               0
precipitation                      0
rain                               0
wind_speed_10m                     0
cloud_cover                        0

--- Duplicate Timestamp Check ---
Duplicate timestamps: 0

--- Hourly Timeline Check ---
Expected hourly timestamps: 31392
Unique returned timestamps: 31392
Missing timestamps: 0
Unexpected timestamps: 0

--- Monthly Coverage Summary ---

,month,returned_records,unique_timestamps,expected_records,record_difference
0,2023-01,744,744,744,0
1,2023-02,672,672,672,0
2,2023-03,744,744,744,0
3,2023-04,720,720,720,0
4,2023-05,744,744,744,0
5,2023-06,720,720,720,0
6,2023-07,744,744,744,0
7,2023-08,744,744,744,0
8,2023-09,720,720,720,0
9,2023-10,744,744,744,0
10,2023-11,720,720,720,0
11,2023-12,744,744,744,0
12,2024-01,744,744,744,0
13,2024-02,696,696,696,0
14,2024-03,744,744,744,0
15,2024-04,720,720,720,0
16,2024-05,744,744,744,0
17,2024-06,720,720,720,0
18,2024-07,744,744,744,0
19,2024-08,744,744,744,0
20,2024-09,720,720,720,0
21,2024-10,744,744,744,0
22,2024-11,720,720,720,0
23,2024-12,744,744,744,0
24,2025-01,744,744,744,0
25,2025-02,672,672,672,0
26,2025-03,744,744,744,0
27,2025-04,720,720,720,0
28,2025-05,744,744,744,0
29,2025-06,720,720,720,0
30,2025-07,744,744,744,0
31,2025-08,744,744,744,0
32,2025-09,720,720,720,0
33,2025-10,744,744,744,0
34,2025-11,720,720,720,0
35,2025-12,744,744,744,0
36,2026-01,744,744,744,0
37,2026-02,672,672,672,0
38,2026-03,744,744,744,0
39,2026-04,720,720,720,0
40,2026-05,744,744,744,0
41,2026-06,720,720,720,0
42,2026-07,744,744,744,0

--- Preliminary Assessment ---
All monthly requests succeeded: True
No duplicate timestamps: True
No missing timestamps: True
No missing weather values: True

Note: This assessment checks the returned data. Review monthly coverage and failed requests before deciding whether the dataset is ready for integration.

### 04.2.7.1 — Historical Weather Coverage Findings

#### 1. API Request Results

The Open-Meteo Historical Weather API was queried monthly for the period January 1, 2023, through July 31, 2026.

The assessment produced the following results:

| Metric | Observed Result |
|---|---:|
| Total monthly requests | 43 |
| Successful requests | 43 |
| Failed requests | 0 |
| Retrieved hourly records | 31,392 |
| Expected hourly timestamps | 31,392 |
| Missing timestamps | 0 |
| Unexpected timestamps | 0 |
| Duplicate timestamps | 0 |
| Missing weather values | 0 |

All 43 monthly requests succeeded. The retrieved records contained no missing timestamps, duplicate timestamps, or missing values in the requested weather variables.

#### 2. Temporal Coverage

The returned dataset covers the requested period from January 1, 2023, at 00:00 through July 31, 2026, at 23:00 in the `Asia/Kolkata` timezone.

The expected and observed hourly timestamp counts are identical. This indicates complete hourly temporal coverage for the returned series over the requested period.

#### 3. Weather Variables

The assessment included six variables:

- `temperature_2m`
- `relative_humidity_2m`
- `precipitation`
- `rain`
- `wind_speed_10m`
- `cloud_cover`

The missing-value assessment reported zero missing values for these variables.

#### 4. Interpretation

The API verification and coverage assessment indicate that the Historical Weather API can provide a continuous hourly weather series for the selected Hyderabad grid location over the requested period.

This establishes the technical availability and temporal completeness of the retrieved series. It does not establish that historical weather conditions caused changes in the synthetic food-demand data.

#### 5. Limitations

1. The retrieved weather series represents one selected grid location, not five independently measured hyperlocal zones.
2. The returned grid coordinates differ slightly from the requested coordinates.
3. Historical weather data must not be treated as forecasts available at the original prediction time.
4. Zero missing values do not establish that every value is meteorologically accurate.
5. The historical coverage assessment does not establish the availability of archived forecasts for leakage-free backtesting.

#### Conclusion

The historical weather series passed the initial request-success, hourly-continuity, duplicate-timestamp, and missing-value checks.

The series is suitable for the next stage of weather-data preparation, subject to recording its metadata and preserving the distinction between historical weather estimates and forecasts available at prediction time.

## 04.2.8 — Historical Weather Data Metadata and Reproducibility

### Objective

The objective of this subsection is to establish a reproducible record of the historical weather data source, API configuration, retrieval period, spatial information, temporal resolution, variables, and data-quality verification results.

Maintaining this information will support reproducibility, research transparency, and reliable integration with the project's hourly food-demand dataset.

### 1. Data Source Information

| Metadata Field | Value |
|---|---|
| Data Provider | Open-Meteo |
| API | Historical Weather API |
| Endpoint | https://archive-api.open-meteo.com/v1/archive |
| Requested Latitude | 17.3850 |
| Requested Longitude | 78.4867 |
| Returned Latitude | 17.398945 |
| Returned Longitude | 78.457085 |
| Timezone | Asia/Kolkata |
| Start Date | 2023-01-01 |
| End Date | 2026-07-31 |
| Temporal Resolution | Hourly |
| Retrieval Method | Monthly API requests |

### 2. Weather Variables and Units

The following variables were requested:

| Variable | Description | Expected Unit |
|---|---|---|
| `temperature_2m` | Air temperature at 2 metres | °C |
| `relative_humidity_2m` | Relative humidity at 2 metres | % |
| `precipitation` | Total precipitation | mm |
| `rain` | Rainfall | mm |
| `wind_speed_10m` | Wind speed at 10 metres | km/h by default |
| `cloud_cover` | Cloud cover | % |

The units listed above reflect the API's default units for these variables. The final retrieval configuration should explicitly record the requested units and verify the returned metadata.

### 3. Temporal and Spatial Considerations

The weather data uses the `Asia/Kolkata` timezone and an hourly timestamp.

The API returns weather information for a selected grid location. The returned coordinates differ from the requested coordinates, so the returned grid-cell location must be retained in the dataset metadata.

The current assessment represents one Hyderabad weather grid location. It does not represent five independently measured weather series for the five synthetic delivery zones.

### 4. Data Quality Evidence

The completed coverage assessment reported:

- 43 monthly requests.
- 43 successful requests.
- 31,392 retrieved hourly records.
- No failed requests.
- No duplicate timestamps.
- No missing timestamps.
- No missing values in the requested weather variables.

These findings describe the tested API response and assessment period. They do not independently establish the meteorological accuracy of every returned value.

### 5. Reproducibility Requirements

The final retrieval process should preserve:

1. API provider and endpoint.
2. Retrieval date and time.
3. Requested latitude and longitude.
4. Returned coordinates and elevation.
5. Requested date range.
6. Timezone.
7. Variable names and units.
8. API parameters and model selection, where applicable.
9. Successful and failed request logs.
10. Data-quality assessment results.
11. Applicable source attribution and usage requirements.
12. A record of any later changes to the retrieved dataset.

### 6. Usage and Attribution

Before publishing or distributing the final dataset, review the applicable Open-Meteo terms, licensing information, attribution requirements, and any conditions associated with the selected weather data source.

The final research documentation should identify Open-Meteo as the provider and include the appropriate source attribution.

### Conclusion

The initial historical weather assessment provides a reproducible starting point for the project's weather-data pipeline.

The source metadata, returned grid coordinates, requested variables, timezone, retrieval configuration, and quality checks will be recorded alongside the final weather dataset.

The historical weather series will remain distinct from archived forecast data to avoid introducing unavailable future information into forecasting experiments.

In [11]:
# ============================================================
# 04.2.8 — Historical Weather Metadata Verification
# ============================================================

from datetime import datetime, timezone
import pandas as pd

# Verify that the previous assessment objects exist
required_objects = ["weather_coverage_df", "request_log_df"]

for object_name in required_objects:
    if object_name not in globals():
        raise NameError(
            f"{object_name} was not found. "
            "Run subsection 04.2.7 before continuing."
        )

# Metadata for the retrieved dataset
weather_metadata = {
    "provider": "Open-Meteo",
    "api_endpoint": "https://archive-api.open-meteo.com/v1/archive",
    "retrieval_timestamp_utc": datetime.now(
        timezone.utc
    ).isoformat(),
    "requested_latitude": 17.3850,
    "requested_longitude": 78.4867,
    "returned_latitude": 17.398945,
    "returned_longitude": 78.457085,
    "timezone": "Asia/Kolkata",
    "start_date": "2023-01-01",
    "end_date": "2026-07-31",
    "temporal_resolution": "Hourly",
    "record_count": int(len(weather_coverage_df)),
    "unique_timestamp_count": int(
        weather_coverage_df["time"].nunique()
    ),
    "duplicate_timestamp_count": int(
        weather_coverage_df["time"].duplicated().sum()
    ),
    "failed_monthly_requests": int(
        (request_log_df["status"] == "FAILED").sum()
    ),
    "weather_variables": [
        "temperature_2m",
        "relative_humidity_2m",
        "precipitation",
        "rain",
        "wind_speed_10m",
        "cloud_cover",
    ],
}

metadata_df = pd.DataFrame(
    weather_metadata.items(),
    columns=["metadata_field", "value"]
)

print("--- Weather Dataset Metadata ---")
display(metadata_df)

print("\n--- Actual Dataset Time Range ---")
print("First timestamp:", weather_coverage_df["time"].min())
print("Last timestamp:", weather_coverage_df["time"].max())

print("\n--- Actual Dataset Columns ---")
print(weather_coverage_df.columns.tolist())

print("\n--- Request Log Summary ---")
print("Total requests:", len(request_log_df))
print(
    "Successful requests:",
    (request_log_df["status"] == "SUCCESS").sum()
)
print(
    "Failed requests:",
    (request_log_df["status"] == "FAILED").sum()
)

print("\nMetadata verification completed.")

--- Weather Dataset Metadata ---

,metadata_field,value
0,provider,Open-Meteo
1,api_endpoint,https://archive-api.open-meteo.com/v1/archive
2,retrieval_timestamp_utc,2026-10-28T07:23:17.316104+00:00
3,requested_latitude,17.385
4,requested_longitude,78.4867
5,returned_latitude,17.398945
6,returned_longitude,78.457085
7,timezone,Asia/Kolkata
8,start_date,2023-01-01
9,end_date,2026-07-31
10,temporal_resolution,Hourly
11,record_count,31392
12,unique_timestamp_count,31392
13,duplicate_timestamp_count,0
14,failed_monthly_requests,0
15,weather_variables,"[temperature_2m, relative_humidity_2m, precipi..."

--- Actual Dataset Time Range ---
First timestamp: 2023-01-01 00:00:00
Last timestamp: 2026-07-31 23:00:00

--- Actual Dataset Columns ---
['time', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'wind_speed_10m', 'cloud_cover', 'month']

--- Request Log Summary ---
Total requests: 43
Successful requests: 43
Failed requests: 0

Metadata verification completed.

## 04.2.9 — Weather Dataset Retrieval Strategy and Final Configuration

### Objective

The objective of this subsection is to define the retrieval and storage strategy for the historical weather dataset before integrating weather information with the synthetic food-demand dataset.

### Selected Data Source

- Provider: Open-Meteo
- API: Historical Weather API
- Endpoint: https://archive-api.open-meteo.com/v1/archive
- Requested location: Hyderabad, India
- Timezone: Asia/Kolkata
- Historical period: January 1, 2023, through July 31, 2026
- Temporal resolution: Hourly

### Selected Variables

The dataset will contain:

1. Timestamp
2. Temperature at 2 metres
3. Relative humidity at 2 metres
4. Precipitation
5. Rainfall
6. Wind speed at 10 metres
7. Cloud cover

### Retrieval Strategy

The weather data will be retrieved in monthly batches. Each batch will be checked for successful retrieval, expected columns, timestamps, and missing values.

The final dataset will be sorted chronologically and checked for duplicate timestamps and complete hourly coverage.

### Proposed Storage Structure

The following files are proposed:

- `data/raw/weather/hyderabad_historical_weather.csv`
- `data/metadata/weather_source_metadata.json`
- `results/weather_coverage/monthly_coverage.csv`
- `results/weather_coverage/request_log.csv`

The final locations will be adjusted if the existing repository uses a different established structure.

### Data Integrity

The final weather dataset will preserve the original API variable names and timestamp values. Temporary analysis columns, such as the monthly grouping column, will not be included in the raw weather file.

The retrieval metadata and coverage reports will be stored separately from the weather measurements.

### Research Limitation

Historical weather estimates are suitable for retrospective weather-demand analysis but do not establish what weather information was available to a forecasting model at a historical prediction time.

Forecast-aware experiments will therefore require a separate assessment of archived forecast data and forecast timing.

In [12]:
# ============================================================
# 04.2.9 — Existing Weather Storage Path Inspection
# ============================================================

from pathlib import Path

# Find the project root from the current notebook location
current_path = Path.cwd().resolve()

candidate_roots = [
    current_path,
    *current_path.parents
]

project_root = None

for candidate in candidate_roots:
    if (
        (candidate / "config" / "zones.yaml").exists()
        or (candidate / "data").exists()
        and (candidate / "notebooks").exists()
    ):
        project_root = candidate
        break

if project_root is None:
    raise FileNotFoundError(
        "Could not identify the project root. "
        "Inspect Path.cwd() and update the root detection."
    )

print("Project root:", project_root)

paths_to_inspect = [
    "data",
    "data/raw",
    "data/raw/weather",
    "data/metadata",
    "results",
    "results/weather_coverage",
    "notebooks",
    "config",
]

print("\n--- Existing Path Inspection ---")

for relative_path in paths_to_inspect:
    path = project_root / relative_path

    print(
        f"{relative_path:<30} "
        f"{'EXISTS' if path.exists() else 'NOT FOUND'}"
    )

print("\n--- Existing Weather-Related Files ---")

for search_directory in [
    project_root / "data",
    project_root / "results",
]:
    if search_directory.exists():
        for file_path in search_directory.rglob("*"):
            if (
                file_path.is_file()
                and "weather" in file_path.name.lower()
            ):
                print(file_path.relative_to(project_root))

Project root: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting

--- Existing Path Inspection ---
data                           EXISTS
data/raw                       EXISTS
data/raw/weather               EXISTS
data/metadata                  EXISTS
results                        EXISTS
results/weather_coverage       EXISTS
notebooks                      EXISTS
config                         EXISTS

--- Existing Weather-Related Files ---
data\metadata\weather_source_metadata.json
data\metadata\weather_source_metadata_174578_783742.json
data\metadata\weather_source_metadata_174578_783742_20261026T050752650642Z_1.json
data\metadata\weather_source_metadata_174578_783742_20261027T060257213326Z_1.json
data\metadata\weather_source_metadata_174578_783742_20261027T061315566513Z_1.json
data\metadata\weather_source_metadata_20261026_103154.json
data\metadata\weather_source_metadata_20261026_103426.json
data\metadata\weather_source_metadata_20261027_113237.json
data\metadata\weather_source_metadata_20261027_114256.json
data\raw\weather\hyderabad_historical_weather.csv
data\raw\weather\hyderabad_historical_weather_174578_783742.csv
data\raw\weather\hyderabad_historical_weather_174578_783742_20261026T050752650642Z_1.csv
data\raw\weather\hyderabad_historical_weather_174578_783742_20261027T060257213326Z_1.csv
data\raw\weather\hyderabad_historical_weather_174578_783742_20261027T061315566513Z_1.csv
data\raw\weather\hyderabad_historical_weather_20261026_103154.csv
data\raw\weather\hyderabad_historical_weather_20261026_103426.csv
data\raw\weather\hyderabad_historical_weather_20261027_113237.csv
data\raw\weather\hyderabad_historical_weather_20261027_114256.csv
data\processed\weather\hyderabad_weather_cleaned_174578_783742.csv

In [13]:
# ============================================================
# 04.2.9.1 — Prepare Weather Data Storage Directories
# ============================================================

from pathlib import Path

# Reuse the project_root identified in the previous cell.
if "project_root" not in globals():
    raise NameError(
        "project_root was not found. "
        "Run the project path inspection cell first."
    )

required_directories = [
    project_root / "data" / "raw" / "weather",
    project_root / "data" / "metadata",
    project_root / "results" / "weather_coverage",
]

print("--- Preparing Weather Storage Directories ---")

for directory in required_directories:
    directory.mkdir(parents=True, exist_ok=True)

    print(
        f"{directory.relative_to(project_root)}"
        f" | Exists: {directory.exists()}"
    )

print("\nStorage directory preparation completed.")

--- Preparing Weather Storage Directories ---
data\raw\weather | Exists: True
data\metadata | Exists: True
results\weather_coverage | Exists: True

Storage directory preparation completed.

In [14]:
# ============================================================
# 04.2.9.2 — Verify Weather Storage Structure
# ============================================================

weather_root = project_root / "data" / "raw" / "weather"

print("--- Weather Data Directory ---")

for path in sorted(weather_root.iterdir()):
    item_type = "Directory" if path.is_dir() else "File"
    print(f"{item_type}: {path.name}")

print("\n--- Metadata Directory ---")
print((project_root / "data" / "metadata").exists())

print("\n--- Coverage Results Directory ---")
print((project_root / "results" / "weather_coverage").exists())

--- Weather Data Directory ---
File: .gitkeep
File: hyderabad_historical_weather.csv
File: hyderabad_historical_weather_174578_783742.csv
File: hyderabad_historical_weather_174578_783742_20261026T050752650642Z_1.csv
File: hyderabad_historical_weather_174578_783742_20261027T060257213326Z_1.csv
File: hyderabad_historical_weather_174578_783742_20261027T061315566513Z_1.csv
File: hyderabad_historical_weather_20261026_103154.csv
File: hyderabad_historical_weather_20261026_103426.csv
File: hyderabad_historical_weather_20261027_113237.csv
File: hyderabad_historical_weather_20261027_114256.csv

--- Metadata Directory ---
True

--- Coverage Results Directory ---
True

## 04.2.10 — Retrieve and Save the Historical Weather Dataset

### Objective
Retrieve the verified historical weather series from the Open-Meteo Historical Weather API and save the data, metadata, and coverage reports in the project repository.

### Configuration
- Period: January 1, 2023 – July 31, 2026
- Location: Hyderabad, India
- Timezone: Asia/Kolkata
- Resolution: Hourly
- Retrieval method: Monthly API requests

### Output Files
1. `data/raw/weather/hyderabad_historical_weather.csv`
2. `data/metadata/weather_source_metadata.json`
3. `results/weather_coverage/monthly_coverage.csv`
4. `results/weather_coverage/request_log.csv`

### Data Integrity
The retrieval process will:
- Retrieve data in monthly batches.
- Validate expected columns and timestamps.
- Check missing values, duplicate timestamps, and hourly continuity.
- Preserve the coordinates and metadata returned by the API.
- Keep temporary analysis columns out of the raw weather CSV.
- Avoid overwriting existing files.
- Reopen the saved CSV and verify its contents.

### Research Limitation
This dataset represents historical weather estimates for one selected grid location. It will initially be used for historical analysis, not treated as archived weather forecasts available at past prediction times.

### Archived exploratory weather collection (04.2.10)

This historical collection stage was superseded by the finalized coordinate-specific dataset in Phase 04.3/04.4. It is intentionally not executable during **Run All** to avoid repeated API calls and timestamped duplicate files.

Canonical dataset: `data/raw/weather/hyderabad_historical_weather_174578_783742.csv`
Canonical cleaned dataset: `data/processed/weather/hyderabad_weather_cleaned_174578_783742.csv`

## 04.2.11 — Final Saved Weather Dataset Validation

### Objective

The objective of this subsection is to independently validate the saved historical weather dataset and its associated metadata and quality reports.

### Validation Checks

1. Confirm that all expected output files exist.
2. Verify the saved dataset's row and column counts.
3. Confirm the first and last timestamps.
4. Check timestamp uniqueness and hourly continuity.
5. Check missing values in the weather variables.
6. Verify the number of monthly coverage records.
7. Verify the request log contains 43 successful monthly requests.
8. Confirm that the raw weather CSV contains only the timestamp and requested weather variables.

### Expected Dataset Structure

The weather CSV should contain seven columns:

- `time`
- `temperature_2m`
- `relative_humidity_2m`
- `precipitation`
- `rain`
- `wind_speed_10m`
- `cloud_cover`

The expected number of hourly records is 31,392.

### Conclusion

The saved files will be considered validated only after the checks have been performed against the files on disk, rather than relying solely on the in-memory data used during retrieval.

In [15]:
# ============================================================
# 04.2.11 — Final Saved Weather Dataset Validation
# ============================================================

import json
import pandas as pd

# Expected saved files
expected_files = {
    "Weather CSV": (
        project_root / "data" / "raw" / "weather"
        / "hyderabad_historical_weather.csv"
    ),
    "Metadata JSON": (
        project_root / "data" / "metadata"
        / "weather_source_metadata.json"
    ),
    "Monthly Coverage": (
        project_root / "results" / "weather_coverage"
        / "monthly_coverage.csv"
    ),
    "Request Log": (
        project_root / "results" / "weather_coverage"
        / "request_log.csv"
    ),
}

print("--- File Existence Check ---")

for name, path in expected_files.items():
    print(f"{name}: {'EXISTS' if path.is_file() else 'MISSING'}")

missing_files = [
    name for name, path in expected_files.items()
    if not path.is_file()
]

if missing_files:
    # The request log may have been saved under a timestamped filename.
    # Re-save the in-memory final log to the canonical path expected below.
    if "Request Log" in missing_files and "request_log_df_final" in globals():
        request_log_path = expected_files["Request Log"]
        request_log_path.parent.mkdir(parents=True, exist_ok=True)
        request_log_df_final.to_csv(request_log_path, index=False)

    # Recheck after attempting to restore the request log.
    missing_files = [
        name for name, path in expected_files.items()
        if not path.is_file()
    ]

    if missing_files:
        raise FileNotFoundError(
            f"Required files are missing: {missing_files}"
        )

# ------------------------------------------------------------
# Load saved files independently
# ------------------------------------------------------------

weather_saved = pd.read_csv(
    expected_files["Weather CSV"],
    parse_dates=["time"],
)

monthly_saved = pd.read_csv(
    expected_files["Monthly Coverage"]
)

request_log_saved = pd.read_csv(
    expected_files["Request Log"]
)

with expected_files["Metadata JSON"].open(
    "r", encoding="utf-8"
) as file:
    metadata_saved = json.load(file)

# ------------------------------------------------------------
# Validate expected structure
# ------------------------------------------------------------

expected_columns = [
    "time",
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "rain",
    "wind_speed_10m",
    "cloud_cover",
]

expected_hours = 31392

print("\n--- Dataset Structure ---")
print("Shape:", weather_saved.shape)
print("Columns:", weather_saved.columns.tolist())
print("Expected rows:", expected_hours)
print("Actual rows:", len(weather_saved))
print("Expected columns:", len(expected_columns))
print("Actual columns:", len(weather_saved.columns))

print("\n--- Timestamp Validation ---")
print("First timestamp:", weather_saved["time"].min())
print("Last timestamp:", weather_saved["time"].max())
print("Duplicate timestamps:", weather_saved["time"].duplicated().sum())

expected_timeline = pd.date_range(
    start="2023-01-01 00:00:00",
    end="2026-07-31 23:00:00",
    freq="h",
)

actual_timeline = pd.DatetimeIndex(
    weather_saved["time"].sort_values()
)

missing_timestamps = expected_timeline.difference(actual_timeline)
unexpected_timestamps = actual_timeline.difference(expected_timeline)

print("Expected hourly timestamps:", len(expected_timeline))
print("Missing timestamps:", len(missing_timestamps))
print("Unexpected timestamps:", len(unexpected_timestamps))

print("\n--- Missing Values ---")
display(weather_saved.isna().sum().to_frame("missing_values"))

print("\n--- Supporting File Checks ---")
print("Monthly coverage rows:", len(monthly_saved))
print("Request log rows:", len(request_log_saved))
print("Successful requests:", (
    request_log_saved["status"] == "SUCCESS"
).sum())
print("Failed requests:", (
    request_log_saved["status"] == "FAILED"
).sum())

print("\n--- Metadata Summary ---")
print("Provider:", metadata_saved.get("provider"))
print("Period:", metadata_saved.get("start_date"),
      "to", metadata_saved.get("end_date"))
print("Timezone:", metadata_saved.get("timezone"))
print("Metadata record count:", metadata_saved.get("record_count"))

# ------------------------------------------------------------
# Final validation flags
# ------------------------------------------------------------

checks = {
    "All expected files exist": not missing_files,
    "Expected row count": len(weather_saved) == expected_hours,
    "Expected columns": weather_saved.columns.tolist() == expected_columns,
    "No missing values": not weather_saved.isna().any().any(),
    "No duplicate timestamps": not weather_saved["time"].duplicated().any(),
    "Complete hourly timeline": (
        len(missing_timestamps) == 0
        and len(unexpected_timestamps) == 0
    ),
    "43 monthly coverage records": len(monthly_saved) == 43,
    "43 successful requests": (
        len(request_log_saved) == 43
        and (request_log_saved["status"] == "SUCCESS").all()
    ),
    "Metadata row count matches": (
        metadata_saved.get("record_count") == len(weather_saved)
    ),
}

print("\n--- Final Validation Results ---")

for check, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL'} | {check}")

print(
    "\nOverall status:",
    "PASS" if all(checks.values()) else "REQUIRES INVESTIGATION"
)

--- File Existence Check ---
Weather CSV: EXISTS
Metadata JSON: EXISTS
Monthly Coverage: EXISTS
Request Log: EXISTS

--- Dataset Structure ---
Shape: (31392, 7)
Columns: ['time', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'wind_speed_10m', 'cloud_cover']
Expected rows: 31392
Actual rows: 31392
Expected columns: 7
Actual columns: 7

--- Timestamp Validation ---
First timestamp: 2023-01-01 00:00:00
Last timestamp: 2026-07-31 23:00:00
Duplicate timestamps: 0
Expected hourly timestamps: 31392
Missing timestamps: 0
Unexpected timestamps: 0

--- Missing Values ---

                      missing_values
time                               0
temperature_2m                     0
relative_humidity_2m               0
precipitation                      0
rain                               0
wind_speed_10m                     0
cloud_cover                        0

--- Supporting File Checks ---
Monthly coverage rows: 43
Request log rows: 43
Successful requests: 43
Failed requests: 0

--- Metadata Summary ---
Provider: Open-Meteo
Period: 2023-01-01 to 2026-07-31
Timezone: Asia/Kolkata
Metadata record count: 31392

--- Final Validation Results ---
PASS | All expected files exist
PASS | Expected row count
PASS | Expected columns
PASS | No missing values
PASS | No duplicate timestamps
PASS | Complete hourly timeline
PASS | 43 monthly coverage records
PASS | 43 successful requests
PASS | Metadata row count matches

Overall status: PASS

## 04.3.1 — Geographical Definition and Weather-Source Evaluation

### Objective

This subsection establishes a geographically defensible approach for collecting historical weather data for the five hyperlocal food-demand zones in Hyderabad: Kondapur, Hitech City, Gachibowli, Madhapur, and Kukatpally.

The objective is to identify real weather observation stations and suitable historical weather datasets that can represent local weather conditions at an hourly resolution.

### Geographical Scope

The study covers five synthetic demand zones associated with real geographical areas in Hyderabad:

* Z01 — Kondapur
* Z02 — Hitech City
* Z03 — Gachibowli
* Z04 — Madhapur
* Z05 — Kukatpally

The geographical boundaries of these zones must be established or documented before selecting representative observation locations. Zone names alone are insufficient to determine exact boundaries.

### Candidate Weather Sources

The initial investigation includes:

1. Telangana Development Planning Society automatic weather stations.
2. Telangana hourly rainfall telemetry data available through the National Water Data Portal.
3. India Meteorological Department weather observation and rainfall datasets.
4. Open-Meteo historical weather data as a potential source of gridded historical estimates.

Each source will be evaluated for geographical coverage, historical availability, temporal resolution, measurement or estimation methodology, data accessibility, and reproducibility.

### Data Authenticity and Spatial Validation

Weather observations and model-derived estimates will be distinguished explicitly. Station observations will retain their original station identifiers and geographical coordinates. Gridded datasets will retain the requested coordinates and the actual grid coordinates or identifiers reported by the provider, where available.

Multiple requested locations will not automatically be treated as independent weather observations. Locations that resolve to the same underlying grid cell will be identified before any spatial aggregation is performed.

No missing rainfall values will be replaced with invented measurements. Missing observations will remain explicitly identified, and any aggregation will be based on documented data-availability and spatial-coverage rules.

### Temporal Scope

The target historical period is January 1, 2023, through July 31, 2026, in the Asia/Kolkata time zone, consistent with the existing historical weather collection.

Hourly station observations are preferred for analysing local rainfall variation. Where only daily observations or gridded estimates are available, their limitations will be documented rather than representing them as equivalent to hourly local measurements.

### Expected Outcome

The subsection will produce a documented assessment of candidate weather sources, available station locations, geographical coverage, historical data availability, and spatial limitations.

The final source selection will be made only after the available evidence demonstrates which datasets can support the project's hyperlocal weather requirements.

04.3.2 — Official Weather Source Evaluation

## 04.3.3 — API Evaluation for Hyperlocal Historical Weather

### Objective

This subsection evaluates weather APIs for collecting historical weather information relevant to the five Hyderabad demand zones: Kondapur, Hitech City, Gachibowli, Madhapur, and Kukatpally.

The target period is January 1, 2023, through July 31, 2026, with hourly records interpreted in the Asia/Kolkata time zone.

### Candidate APIs

**Open-Meteo Historical Weather API**

This API provides historical hourly weather variables using multiple weather reanalysis and model datasets. Its support for multiple coordinates makes it useful for evaluating spatial coverage. Returned grid coordinates and dataset resolution must be checked before interpreting nearby locations as independent weather observations.

**Meteostat**

Meteostat provides historical weather data through station-based and geographical-point interfaces. Station metadata and record provenance must be examined to distinguish direct station observations from model-filled records.

**WeatherAPI.com**

WeatherAPI.com provides historical hourly weather through a subscription-dependent API. Its documentation identifies the historical archive as forecast-derived data, so it will not automatically be treated as a source of direct historical observations.

### Evaluation Criteria

Each API will be evaluated using the following criteria:

1. Availability of records throughout the target historical period.
2. Availability of hourly rainfall, temperature, humidity, wind, and cloud-cover variables.
3. Geographical relevance to each of the five zones.
4. Spatial resolution and the possibility of duplicate underlying grid cells.
5. Provenance of each variable and whether values are observed or model-derived.
6. Missing timestamps, missing values, and data-quality limitations.
7. API access requirements, usage limits, licensing, and reproducibility.

### Data Integrity Rules

No weather values will be fabricated or statistically generated to fill missing observations.

Missing values will be identified and documented. Any model-derived values will be labelled as estimates, and direct station observations will be distinguished from reanalysis or forecast-derived products.

Multiple coordinate queries will not be treated as independent measurements unless the underlying source resolution supports that interpretation.

### Expected Outcome

The evaluation will identify which API or combination of APIs offers the strongest verifiable coverage for the project. Final source selection will depend on actual station availability, spatial resolution, historical completeness, and data provenance rather than convenience alone.

## 04.3.4 — Historical Weather API Pilot Test

### Objective

This subsection tests whether the Open-Meteo Historical Weather API can return hourly weather estimates for multiple geographical locations associated with the five Hyderabad demand zones.

The pilot will examine API accessibility, returned coordinates, hourly variable availability, missing values, and spatial differences between locations.

### Important Data Distinction

Open-Meteo's Historical Weather API provides historical weather estimates derived from reanalysis datasets and weather models. These estimates must not be described as direct weather-station observations.

The pilot is intended to evaluate spatial resolution and API behaviour. The test coordinates are provisional representatives for testing only; they do not define official zone boundaries.

### Pilot Procedure

1. Submit a historical weather request for provisional coordinates associated with the five zones.
2. Retrieve temperature, relative humidity, precipitation, rainfall, wind speed, and cloud cover.
3. Record the coordinates returned by the API.
4. Check whether different requested locations resolve to different weather grid coordinates.
5. Compare hourly rainfall values across locations.
6. Validate timestamps, missing values, and response completeness.

### Decision Rule

Successful API responses alone will not establish suitability for hyperlocal forecasting. Final selection will depend on geographical relevance, spatial resolution, historical coverage, data provenance, and the ability to represent meaningful local weather variation.

In [16]:
# Phase 04.3.4 — Open-Meteo API Spatial Resolution Pilot

import requests
import pandas as pd
from IPython.display import display

# --------------------------------------------------
# 1. API configuration
# --------------------------------------------------

API_URL = "https://archive-api.open-meteo.com/v1/archive"

TEST_DATE = "2026-08-30"

# Provisional representative points for API testing only.
# These are NOT verified zone boundaries or official station locations.

test_locations = {
    "Z01_Kondapur": {
        "latitude": 17.4650,
        "longitude": 78.3560,
    },
    "Z02_Hitech_City": {
        "latitude": 17.4430,
        "longitude": 78.3770,
    },
    "Z03_Gachibowli": {
        "latitude": 17.4400,
        "longitude": 78.3480,
    },
    "Z04_Madhapur": {
        "latitude": 17.4480,
        "longitude": 78.3910,
    },
    "Z05_Kukatpally": {
        "latitude": 17.4930,
        "longitude": 78.3990,
    },
}

weather_variables = [
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "rain",
    "wind_speed_10m",
    "cloud_cover",
]

# --------------------------------------------------
# 2. Prepare multi-location API request
# --------------------------------------------------

params = {
    "latitude": ",".join(
        str(location["latitude"])
        for location in test_locations.values()
    ),
    "longitude": ",".join(
        str(location["longitude"])
        for location in test_locations.values()
    ),
    "start_date": TEST_DATE,
    "end_date": TEST_DATE,
    "hourly": ",".join(weather_variables),
    "timezone": "Asia/Kolkata",
    "timeformat": "iso8601",
}

print("Requesting historical weather data...")
print("Test date:", TEST_DATE)
print("Number of requested locations:", len(test_locations))

response = requests.get(
    API_URL,
    params=params,
    timeout=120,
)

print("HTTP status:", response.status_code)
response.raise_for_status()

payload = response.json()

# --------------------------------------------------
# 3. Normalize the API response
# --------------------------------------------------

# Multiple coordinates normally produce a list of
# location responses. Handle both response structures.

if isinstance(payload, dict):
    if "hourly" in payload:
        location_responses = [payload]
    else:
        raise ValueError(
            "Unexpected API response structure. "
            f"Returned keys: {list(payload.keys())}"
        )

elif isinstance(payload, list):
    location_responses = payload

else:
    raise TypeError(
        f"Unexpected response type: {type(payload)}"
    )

if len(location_responses) != len(test_locations):
    print(
        "WARNING: Requested location count and "
        "returned response count differ."
    )

# --------------------------------------------------
# 4. Build location metadata and hourly records
# --------------------------------------------------

metadata_rows = []
weather_frames = []

for location_name, location_response in zip(
    test_locations.keys(),
    location_responses,
):
    hourly = location_response.get("hourly", {})

    if "time" not in hourly:
        print(f"WARNING: No hourly timestamps for {location_name}")
        continue

    frame = pd.DataFrame(hourly)
    frame.insert(0, "zone_test_id", location_name)

    requested = test_locations[location_name]

    metadata_rows.append({
        "zone_test_id": location_name,
        "requested_latitude": requested["latitude"],
        "requested_longitude": requested["longitude"],
        "returned_latitude": location_response.get("latitude"),
        "returned_longitude": location_response.get("longitude"),
        "elevation_m": location_response.get("elevation"),
        "timezone": location_response.get("timezone"),
        "hourly_records": len(frame),
    })

    weather_frames.append(frame)

if not weather_frames:
    raise ValueError("No hourly weather records were returned.")

weather_test = pd.concat(
    weather_frames,
    ignore_index=True,
)

location_metadata = pd.DataFrame(metadata_rows)

# --------------------------------------------------
# 5. Inspect returned coordinates
# --------------------------------------------------

print("\n--- Requested vs. Returned Coordinates ---")

display(location_metadata)

# --------------------------------------------------
# 6. Check timestamps and missing values
# --------------------------------------------------

print("\n--- Record Counts by Test Location ---")

display(
    weather_test.groupby("zone_test_id")
    .agg(
        record_count=("time", "size"),
        first_timestamp=("time", "min"),
        last_timestamp=("time", "max"),
    )
    .reset_index()
)

print("\n--- Missing Values by Test Location ---")

missing_summary = (
    weather_test.groupby("zone_test_id")[weather_variables]
    .apply(lambda group: group.isna().sum())
)

display(missing_summary)

# --------------------------------------------------
# 7. Compare hourly rainfall
# --------------------------------------------------

print("\n--- Hourly Rainfall Comparison ---")

rainfall_comparison = weather_test.pivot(
    index="time",
    columns="zone_test_id",
    values="rain",
)

display(rainfall_comparison)

# --------------------------------------------------
# 8. Check unique returned grid coordinates
# --------------------------------------------------

unique_grid_cells = location_metadata[
    ["returned_latitude", "returned_longitude"]
].drop_duplicates()

print("\nNumber of requested locations:", len(test_locations))
print("Number of successful location responses:", len(location_metadata))
print("Number of distinct returned grid coordinates:", len(unique_grid_cells))

print("\n--- Distinct Returned Grid Coordinates ---")
display(unique_grid_cells.reset_index(drop=True))

Requesting historical weather data...
Test date: 2026-08-30
Number of requested locations: 5
HTTP status: 200

--- Requested vs. Returned Coordinates ---

,zone_test_id,requested_latitude,requested_longitude,returned_latitude,returned_longitude,elevation_m,timezone,hourly_records
0,Z01_Kondapur,17.465,78.356,17.469244,78.35907,607.0,Asia/Kolkata,24
1,Z02_Hitech_City,17.443,78.377,17.469244,78.35907,597.0,Asia/Kolkata,24
2,Z03_Gachibowli,17.440,78.348,17.469244,78.35907,611.0,Asia/Kolkata,24
3,Z04_Madhapur,17.448,78.391,17.469244,78.35907,574.0,Asia/Kolkata,24
4,Z05_Kukatpally,17.493,78.399,17.469244,78.35907,587.0,Asia/Kolkata,24

--- Record Counts by Test Location ---

      zone_test_id  record_count   first_timestamp    last_timestamp
0     Z01_Kondapur            24  2026-08-30T00:00  2026-08-30T23:00
1  Z02_Hitech_City            24  2026-08-30T00:00  2026-08-30T23:00
2   Z03_Gachibowli            24  2026-08-30T00:00  2026-08-30T23:00
3     Z04_Madhapur            24  2026-08-30T00:00  2026-08-30T23:00
4   Z05_Kukatpally            24  2026-08-30T00:00  2026-08-30T23:00

--- Missing Values by Test Location ---

,temperature_2m,relative_humidity_2m,precipitation,rain,wind_speed_10m,cloud_cover
zone_test_id,,,,,,
Z01_Kondapur,0,0,0,0,0,0
Z02_Hitech_City,0,0,0,0,0,0
Z03_Gachibowli,0,0,0,0,0,0
Z04_Madhapur,0,0,0,0,0,0
Z05_Kukatpally,0,0,0,0,0,0

--- Hourly Rainfall Comparison ---

zone_test_id,Z01_Kondapur,Z02_Hitech_City,Z03_Gachibowli,Z04_Madhapur,Z05_Kukatpally
time,,,,,
2026-08-30T00:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T01:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T02:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T03:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T04:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T05:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T06:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T07:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T08:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T09:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T10:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T11:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T12:00,0.1,0.1,0.1,0.1,0.1
2026-08-30T13:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T14:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T15:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T16:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T17:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T18:00,0.2,0.2,0.2,0.2,0.2
2026-08-30T19:00,0.3,0.3,0.3,0.3,0.3
2026-08-30T20:00,0.2,0.2,0.2,0.2,0.2
2026-08-30T21:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T22:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T23:00,0.0,0.0,0.0,0.0,0.0

Number of requested locations: 5
Number of successful location responses: 5
Number of distinct returned grid coordinates: 1

--- Distinct Returned Grid Coordinates ---

   returned_latitude  returned_longitude
0          17.469244            78.35907

## 04.3.5 — ECMWF IFS Historical Weather Spatial-Resolution Test

### Objective
Evaluate whether the ECMWF IFS historical weather dataset provides distinct grid-cell coordinates for the five provisional Hyderabad zone locations.

### Dataset
ECMWF IFS historical weather data through the Open-Meteo Historical Weather API.

The provider documents approximately 9 km spatial resolution and hourly historical data availability from 2017 onward.

### Validation
1. Explicitly select the ECMWF IFS model.
2. Request hourly weather for the same five provisional locations.
3. Record requested and returned coordinates.
4. Count the distinct returned grid cells.
5. Compare hourly rainfall values.
6. Check timestamps and missing values.

### Limitation
A nominal grid resolution of approximately 9 km does not guarantee that every zone will receive a distinct grid cell. Results must be verified from the actual API response.

The requested coordinates are provisional test points, not verified zone boundaries or weather-station locations.

In [17]:
# Phase 04.3.5 — ECMWF IFS Spatial-Resolution Test

import requests
import pandas as pd
from IPython.display import display

API_URL = "https://archive-api.open-meteo.com/v1/archive"
TEST_DATE = "2026-08-30"

# Same provisional test points used in Phase 04.3.4
test_locations = {
    "Z01_Kondapur": (17.4650, 78.3560),
    "Z02_Hitech_City": (17.4430, 78.3770),
    "Z03_Gachibowli": (17.4400, 78.3480),
    "Z04_Madhapur": (17.4480, 78.3910),
    "Z05_Kukatpally": (17.4930, 78.3990),
}

weather_variables = [
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "rain",
    "wind_speed_10m",
    "cloud_cover",
]

params = {
    "latitude": ",".join(str(v[0]) for v in test_locations.values()),
    "longitude": ",".join(str(v[1]) for v in test_locations.values()),
    "start_date": TEST_DATE,
    "end_date": TEST_DATE,
    "hourly": ",".join(weather_variables),
    "timezone": "Asia/Kolkata",
    "models": "ecmwf_ifs",
}

print("Dataset requested: ECMWF IFS")
print("Test date:", TEST_DATE)
print("Requested locations:", len(test_locations))

response = requests.get(API_URL, params=params, timeout=120)

print("HTTP status:", response.status_code)
response.raise_for_status()

payload = response.json()

if isinstance(payload, dict):
    location_responses = [payload]
elif isinstance(payload, list):
    location_responses = payload
else:
    raise TypeError(f"Unexpected response type: {type(payload)}")

if len(location_responses) != len(test_locations):
    print(
        f"WARNING: Requested {len(test_locations)} locations, "
        f"but received {len(location_responses)} responses."
    )

metadata_rows = []
weather_frames = []

for (zone_id, (requested_lat, requested_lon)), item in zip(
    test_locations.items(), location_responses
):
    hourly = item.get("hourly", {})

    if "time" not in hourly:
        print(f"WARNING: No hourly data returned for {zone_id}")
        continue

    frame = pd.DataFrame(hourly)
    frame.insert(0, "zone_test_id", zone_id)
    weather_frames.append(frame)

    metadata_rows.append({
        "zone_test_id": zone_id,
        "requested_latitude": requested_lat,
        "requested_longitude": requested_lon,
        "returned_latitude": item.get("latitude"),
        "returned_longitude": item.get("longitude"),
        "elevation_m": item.get("elevation"),
        "timezone": item.get("timezone"),
        "hourly_records": len(frame),
    })

if not weather_frames:
    raise ValueError("No hourly records returned.")

weather_test_ifs = pd.concat(weather_frames, ignore_index=True)
metadata_ifs = pd.DataFrame(metadata_rows)

print("\n--- Requested vs Returned Coordinates ---")
display(metadata_ifs)

print("\n--- Record Counts and Timestamp Coverage ---")
display(
    weather_test_ifs.groupby("zone_test_id")
    .agg(
        record_count=("time", "size"),
        first_timestamp=("time", "min"),
        last_timestamp=("time", "max"),
    )
    .reset_index()
)

print("\n--- Missing Values by Location ---")
display(
    weather_test_ifs.groupby("zone_test_id")[weather_variables]
    .apply(lambda group: group.isna().sum())
)

print("\n--- Hourly Rainfall Comparison ---")
display(
    weather_test_ifs.pivot(
        index="time",
        columns="zone_test_id",
        values="rain",
    )
)

unique_grid_cells = metadata_ifs[
    ["returned_latitude", "returned_longitude"]
].drop_duplicates()

print("\nRequested locations:", len(test_locations))
print("Successful responses:", len(metadata_ifs))
print("Distinct returned grid coordinates:", len(unique_grid_cells))

print("\n--- Distinct Grid Coordinates ---")
display(unique_grid_cells.reset_index(drop=True))

Dataset requested: ECMWF IFS
Test date: 2026-08-30
Requested locations: 5
HTTP status: 200

--- Requested vs Returned Coordinates ---

,zone_test_id,requested_latitude,requested_longitude,returned_latitude,returned_longitude,elevation_m,timezone,hourly_records
0,Z01_Kondapur,17.465,78.356,17.469244,78.35907,607.0,Asia/Kolkata,24
1,Z02_Hitech_City,17.443,78.377,17.469244,78.35907,597.0,Asia/Kolkata,24
2,Z03_Gachibowli,17.440,78.348,17.469244,78.35907,611.0,Asia/Kolkata,24
3,Z04_Madhapur,17.448,78.391,17.469244,78.35907,574.0,Asia/Kolkata,24
4,Z05_Kukatpally,17.493,78.399,17.469244,78.35907,587.0,Asia/Kolkata,24

--- Record Counts and Timestamp Coverage ---

      zone_test_id  record_count   first_timestamp    last_timestamp
0     Z01_Kondapur            24  2026-08-30T00:00  2026-08-30T23:00
1  Z02_Hitech_City            24  2026-08-30T00:00  2026-08-30T23:00
2   Z03_Gachibowli            24  2026-08-30T00:00  2026-08-30T23:00
3     Z04_Madhapur            24  2026-08-30T00:00  2026-08-30T23:00
4   Z05_Kukatpally            24  2026-08-30T00:00  2026-08-30T23:00

--- Missing Values by Location ---

,temperature_2m,relative_humidity_2m,precipitation,rain,wind_speed_10m,cloud_cover
zone_test_id,,,,,,
Z01_Kondapur,0,0,0,0,0,0
Z02_Hitech_City,0,0,0,0,0,0
Z03_Gachibowli,0,0,0,0,0,0
Z04_Madhapur,0,0,0,0,0,0
Z05_Kukatpally,0,0,0,0,0,0

--- Hourly Rainfall Comparison ---

zone_test_id,Z01_Kondapur,Z02_Hitech_City,Z03_Gachibowli,Z04_Madhapur,Z05_Kukatpally
time,,,,,
2026-08-30T00:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T01:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T02:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T03:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T04:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T05:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T06:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T07:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T08:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T09:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T10:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T11:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T12:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T13:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T14:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T15:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T16:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T17:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T18:00,0.2,0.2,0.2,0.2,0.2
2026-08-30T19:00,0.3,0.3,0.3,0.3,0.3
2026-08-30T20:00,0.2,0.2,0.2,0.2,0.2
2026-08-30T21:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T22:00,0.0,0.0,0.0,0.0,0.0
2026-08-30T23:00,0.0,0.0,0.0,0.0,0.0

Requested locations: 5
Successful responses: 5
Distinct returned grid coordinates: 1

--- Distinct Grid Coordinates ---

   returned_latitude  returned_longitude
0          17.469244            78.35907

## 04.3.5 — ECMWF IFS Spatial-Resolution Test: Findings

### Test Results

The ECMWF IFS historical weather API request returned successful responses for all five provisional test locations for August 30, 2026.

Each location returned 24 hourly records, with no missing values in the six requested weather variables.

However, all five responses reported the same returned coordinates:

- Latitude: 17.469244
- Longitude: 78.359070

Only one distinct returned coordinate pair was identified across the five responses.

### Interpretation

Explicitly requesting ECMWF IFS did not produce distinct returned grid coordinates in this experiment. Consequently, the results do not demonstrate that the selected API configuration can represent spatially differentiated weather conditions across the five demand zones.

The displayed rainfall estimates were zero for all five locations during the tested period. These estimates do not establish that rainfall was absent throughout the actual geographical extent of each zone.

### Limitations

The test used provisional coordinates rather than verified zone boundaries or official weather-station locations.

The returned coordinate behaviour and model selection must be investigated further before drawing conclusions about the underlying dataset's spatial resolution.

### Decision

Do not use this pilot dataset as evidence of independent zone-level weather observations.

The next investigation will verify API model selection and evaluate alternative historical weather sources or station observations capable of providing geographically differentiated information.

No weather values have been fabricated or modified.

In [18]:
# ============================================================
# PHASE 04: OPEN-METEO HISTORICAL WEATHER CONFIGURATION
# ============================================================

from pathlib import Path

# Project root
PROJECT_ROOT = Path.cwd()

# ------------------------------------------------------------
# 1. REQUESTED COORDINATES — HYDERABAD
# ------------------------------------------------------------

LATITUDE = 17.4578
LONGITUDE = 78.3742

# ------------------------------------------------------------
# 2. HISTORICAL PERIOD
# ------------------------------------------------------------

START_DATE = "2023-01-01"
END_DATE = "2026-07-31"

# ------------------------------------------------------------
# 3. TIMEZONE
# ------------------------------------------------------------

TIMEZONE = "Asia/Kolkata"

# ------------------------------------------------------------
# 4. OPEN-METEO API
# ------------------------------------------------------------

OPEN_METEO_ARCHIVE_URL = (
    "https://archive-api.open-meteo.com/v1/archive"
)

# ------------------------------------------------------------
# 5. WEATHER VARIABLES
# ------------------------------------------------------------

HOURLY_VARIABLES = [
    "temperature_2m",
    "relative_humidity_2m",
    "apparent_temperature",
    "precipitation",
    "rain",
    "wind_speed_10m",
    "wind_direction_10m",
    "wind_gusts_10m",
    "cloud_cover",
    "surface_pressure",
    "dew_point_2m",
]

# ------------------------------------------------------------
# 6. OUTPUT DIRECTORIES
# ------------------------------------------------------------

WEATHER_RAW_DIR = (
    PROJECT_ROOT / "data" / "raw" / "weather"
)

WEATHER_METADATA_DIR = (
    PROJECT_ROOT / "data" / "metadata"
)

WEATHER_RAW_DIR.mkdir(
    parents=True,
    exist_ok=True
)

WEATHER_METADATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# 7. OUTPUT FILES
# ------------------------------------------------------------

WEATHER_CSV_PATH = (
    WEATHER_RAW_DIR / "hyderabad_historical_weather.csv"
)

WEATHER_METADATA_PATH = (
    WEATHER_METADATA_DIR / "weather_source_metadata.json"
)

# ------------------------------------------------------------
# 8. DISPLAY CONFIGURATION
# ------------------------------------------------------------

print("Open-Meteo Historical Weather Configuration")
print("-" * 50)

print(f"Requested latitude : {LATITUDE}")
print(f"Requested longitude: {LONGITUDE}")
print(f"Start date         : {START_DATE}")
print(f"End date           : {END_DATE}")
print(f"Timezone           : {TIMEZONE}")

print(f"\nWeather variables: {len(HOURLY_VARIABLES)}")

print(f"\nCSV output:")
print(WEATHER_CSV_PATH)

print(f"\nMetadata output:")
print(WEATHER_METADATA_PATH)

Open-Meteo Historical Weather Configuration
--------------------------------------------------
Requested latitude : 17.4578
Requested longitude: 78.3742
Start date         : 2023-01-01
End date           : 2026-07-31
Timezone           : Asia/Kolkata

Weather variables: 11

CSV output:
d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\notebooks\data\raw\weather\hyderabad_historical_weather.csv

Metadata output:
d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\notebooks\data\metadata\weather_source_metadata.json

In [19]:
from pathlib import Path

# ============================================================
# PROJECT ROOT
# ============================================================

PROJECT_ROOT = Path.cwd()

# If Jupyter starts inside the notebooks folder, move to its parent.
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

# ============================================================
# REQUIRED OPEN-METEO COORDINATES
# ============================================================

LATITUDE = 17.4578
LONGITUDE = 78.3742

START_DATE = "2023-01-01"
END_DATE = "2026-07-31"
TIMEZONE = "Asia/Kolkata"

# ============================================================
# MAIN PROJECT DATA DIRECTORIES
# ============================================================

WEATHER_RAW_DIR = (
    PROJECT_ROOT / "data" / "raw" / "weather"
)

WEATHER_METADATA_DIR = (
    PROJECT_ROOT / "data" / "metadata"
)

WEATHER_RAW_DIR.mkdir(parents=True, exist_ok=True)
WEATHER_METADATA_DIR.mkdir(parents=True, exist_ok=True)

WEATHER_CSV_PATH = (
    WEATHER_RAW_DIR / "hyderabad_historical_weather.csv"
)

WEATHER_METADATA_PATH = (
    WEATHER_METADATA_DIR / "weather_source_metadata.json"
)

print("Project root:", PROJECT_ROOT)
print("Requested latitude:", LATITUDE)
print("Requested longitude:", LONGITUDE)
print("Weather CSV:", WEATHER_CSV_PATH)
print("Weather metadata:", WEATHER_METADATA_PATH)

Project root: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting
Requested latitude: 17.4578
Requested longitude: 78.3742
Weather CSV: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\weather\hyderabad_historical_weather.csv
Weather metadata: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\metadata\weather_source_metadata.json

In [20]:
# ============================================================
# PHASE 04: OPEN-METEO HISTORICAL WEATHER COLLECTION
# Coordinates: 17.4578, 78.3742
# ============================================================

import json
import requests
import pandas as pd

from pathlib import Path
from datetime import datetime, timezone

# ------------------------------------------------------------
# 1. PROJECT PATHS
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data"

WEATHER_RAW_DIR = DATA_DIR / "raw" / "weather"
WEATHER_METADATA_DIR = DATA_DIR / "metadata"

WEATHER_RAW_DIR.mkdir(parents=True, exist_ok=True)
WEATHER_METADATA_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# 2. REQUESTED COORDINATES
# ------------------------------------------------------------

LATITUDE = 17.4578
LONGITUDE = 78.3742

# ------------------------------------------------------------
# 3. HISTORICAL PERIOD AND TIMEZONE
# ------------------------------------------------------------

START_DATE = "2023-01-01"
END_DATE = "2026-07-31"

TIMEZONE = "Asia/Kolkata"

API_URL = "https://archive-api.open-meteo.com/v1/archive"

# ------------------------------------------------------------
# 4. WEATHER VARIABLES
# ------------------------------------------------------------

HOURLY_VARIABLES = [
    "temperature_2m",
    "relative_humidity_2m",
    "apparent_temperature",
    "precipitation",
    "rain",
    "wind_speed_10m",
    "wind_direction_10m",
    "wind_gusts_10m",
    "cloud_cover",
    "surface_pressure",
    "dew_point_2m",
]

# ------------------------------------------------------------
# 5. COORDINATE-SPECIFIC OUTPUT FILES
# ------------------------------------------------------------

WEATHER_CSV_PATH = (
    WEATHER_RAW_DIR
    / "hyderabad_historical_weather_174578_783742.csv"
)

WEATHER_METADATA_PATH = (
    WEATHER_METADATA_DIR
    / "weather_source_metadata_174578_783742.json"
)

# Reuse the finalized historical weather files instead of recollecting them.
if WEATHER_CSV_PATH.exists():
    weather_df = pd.read_csv(WEATHER_CSV_PATH, parse_dates=["timestamp"])
    print("Existing historical weather dataset reused; API collection skipped.")
    print("Dataset:", WEATHER_CSV_PATH)
    print("Shape:", weather_df.shape)
else:
    print("=" * 65)
    print("OPEN-METEO HISTORICAL WEATHER COLLECTION")
    print("=" * 65)

    print(f"Requested latitude : {LATITUDE}")
    print(f"Requested longitude: {LONGITUDE}")
    print(f"Start date         : {START_DATE}")
    print(f"End date           : {END_DATE}")
    print(f"Timezone           : {TIMEZONE}")

    # ------------------------------------------------------------
    # 6. REQUEST HISTORICAL WEATHER
    # ------------------------------------------------------------

    params = {
        "latitude": LATITUDE,
        "longitude": LONGITUDE,
        "start_date": START_DATE,
        "end_date": END_DATE,
        "hourly": ",".join(HOURLY_VARIABLES),
        "timezone": TIMEZONE,
        "wind_speed_unit": "kmh",
        "precipitation_unit": "mm",
    }

    print("\nRequesting data from Open-Meteo...")

    response = requests.get(
        API_URL,
        params=params,
        timeout=180,
    )

    response.raise_for_status()

    api_data = response.json()

    if "hourly" not in api_data:
        raise RuntimeError(
            f"Unexpected API response: {api_data}"
        )

    # ------------------------------------------------------------
    # 7. RECORD ACTUAL RETURNED COORDINATES
    # ------------------------------------------------------------

    returned_latitude = api_data["latitude"]
    returned_longitude = api_data["longitude"]
    returned_elevation = api_data.get("elevation")

    print("\nAPI response received.")
    print("Returned latitude :", returned_latitude)
    print("Returned longitude:", returned_longitude)
    print("Returned elevation:", returned_elevation)

    # ------------------------------------------------------------
    # 8. BUILD DATAFRAME
    # ------------------------------------------------------------

    weather_df = pd.DataFrame(api_data["hourly"])

    weather_df.rename(
        columns={"time": "timestamp"},
        inplace=True,
    )

    weather_df["timestamp"] = pd.to_datetime(
        weather_df["timestamp"],
        errors="raise",
    )

    weather_df = (
        weather_df.sort_values("timestamp")
        .reset_index(drop=True)
    )

    # ------------------------------------------------------------
    # 9. VALIDATE THE HOURLY TIMESTAMPS
    # ------------------------------------------------------------

    expected_timestamps = pd.date_range(
        start=pd.Timestamp(START_DATE),
        end=pd.Timestamp(END_DATE) + pd.Timedelta(days=1),
        freq="h",
        inclusive="left",
    )

    expected_count = len(expected_timestamps)
    actual_count = len(weather_df)

    unique_count = weather_df["timestamp"].nunique()

    duplicate_count = int(
        weather_df["timestamp"].duplicated().sum()
    )

    missing_timestamps = expected_timestamps.difference(
        pd.DatetimeIndex(weather_df["timestamp"])
    )

    unexpected_timestamps = pd.DatetimeIndex(
        weather_df["timestamp"]
    ).difference(expected_timestamps)

    missing_values = (
        weather_df.drop(columns=["timestamp"])
        .isna()
        .sum()
        .astype(int)
        .to_dict()
    )

    print("\n" + "=" * 65)
    print("DATA VALIDATION")
    print("=" * 65)

    print("Expected records       :", expected_count)
    print("Actual records         :", actual_count)
    print("Unique timestamps      :", unique_count)
    print("Duplicate timestamps   :", duplicate_count)
    print("Missing timestamps     :", len(missing_timestamps))
    print("Unexpected timestamps  :", len(unexpected_timestamps))
    print("Missing values         :", missing_values)

    # Do not save an incomplete or structurally invalid dataset.
    if actual_count != expected_count:
        raise ValueError(
            f"Expected {expected_count} rows, received {actual_count}."
        )

    if unique_count != expected_count:
        raise ValueError("Timestamp uniqueness validation failed.")

    if duplicate_count != 0:
        raise ValueError("Duplicate timestamps were found.")

    if len(missing_timestamps) != 0:
        raise ValueError("Missing hourly timestamps were found.")

    if len(unexpected_timestamps) != 0:
        raise ValueError("Unexpected timestamps were found.")

    if any(count > 0 for count in missing_values.values()):
        raise ValueError(
            "Missing weather values detected. "
            "Investigate before accepting the dataset."
        )

    # ------------------------------------------------------------
    # 10. PREPARE METADATA
    # ------------------------------------------------------------

    metadata = {
        "provider": "Open-Meteo",
        "api_endpoint": API_URL,
        "retrieval_timestamp_utc": datetime.now(
            timezone.utc
        ).isoformat(),
        "requested_location": {
            "latitude": LATITUDE,
            "longitude": LONGITUDE,
        },
        "returned_location": {
            "returned_latitude": returned_latitude,
            "returned_longitude": returned_longitude,
            "elevation_m": returned_elevation,
            "timezone": api_data.get("timezone"),
            "timezone_abbreviation": api_data.get(
                "timezone_abbreviation"
            ),
            "utc_offset_seconds": api_data.get(
                "utc_offset_seconds"
            ),
        },
        "timezone": TIMEZONE,
        "start_date": START_DATE,
        "end_date": END_DATE,
        "temporal_resolution": "Hourly",
        "expected_record_count": expected_count,
        "record_count": actual_count,
        "unique_timestamp_count": unique_count,
        "duplicate_timestamp_count": duplicate_count,
        "missing_timestamp_count": len(missing_timestamps),
        "unexpected_timestamp_count": len(unexpected_timestamps),
        "missing_values_by_variable": missing_values,
        "variables": HOURLY_VARIABLES,
        "units": {
            "temperature_2m": "°C",
            "relative_humidity_2m": "%",
            "apparent_temperature": "°C",
            "precipitation": "mm",
            "rain": "mm",
            "wind_speed_10m": "km/h",
            "wind_direction_10m": "degrees",
            "wind_gusts_10m": "km/h",
            "cloud_cover": "%",
            "surface_pressure": "hPa",
            "dew_point_2m": "°C",
        },
        "limitations": [
            "Weather data represent a selected grid location.",
            "Historical weather estimates are not archived forecasts.",
            "Returned coordinates may differ from requested coordinates.",
        ],
        "source_documentation": (
            "https://open-meteo.com/en/docs/historical-weather-api"
        ),
    }

    # ------------------------------------------------------------
    # 11. SAVE THE VALIDATED DATASET
    # ------------------------------------------------------------

    weather_df.to_csv(
        WEATHER_CSV_PATH,
        index=False,
    )

    with open(
        WEATHER_METADATA_PATH,
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(metadata, f, indent=4)

    # ------------------------------------------------------------
    # 12. FINAL SUMMARY
    # ------------------------------------------------------------

    print("\n" + "=" * 65)
    print("COLLECTION COMPLETED SUCCESSFULLY")
    print("=" * 65)

    print("Dataset shape:", weather_df.shape)

    print("\nWeather CSV:")
    print(WEATHER_CSV_PATH)

    print("\nMetadata JSON:")
    print(WEATHER_METADATA_PATH)

    print("\nFirst five records:")
    display(weather_df.head())

    print("\nLast five records:")
    display(weather_df.tail())

Existing historical weather dataset reused; API collection skipped.
Dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\weather\hyderabad_historical_weather_174578_783742.csv
Shape: (31392, 12)

In [21]:
# ============================================================
# PHASE 04: VALIDATE SAVED OPEN-METEO DATASET
# ============================================================

import json
import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. FILE PATHS
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

WEATHER_CSV_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "weather"
    / "hyderabad_historical_weather_174578_783742.csv"
)

WEATHER_METADATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "metadata"
    / "weather_source_metadata_174578_783742.json"
)

# ------------------------------------------------------------
# 2. VERIFY FILE EXISTENCE
# ------------------------------------------------------------

print("=" * 65)
print("SAVED WEATHER DATA VALIDATION")
print("=" * 65)

for path in [WEATHER_CSV_PATH, WEATHER_METADATA_PATH]:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    print(f"Found: {path}")

# ------------------------------------------------------------
# 3. LOAD CSV AND METADATA
# ------------------------------------------------------------

weather_df = pd.read_csv(
    WEATHER_CSV_PATH,
    parse_dates=["timestamp"]
)

with open(WEATHER_METADATA_PATH, "r", encoding="utf-8") as f:
    metadata = json.load(f)

# ------------------------------------------------------------
# 4. VERIFY COORDINATE PROVENANCE
# ------------------------------------------------------------

requested = metadata["requested_location"]
returned = metadata["returned_location"]

assert requested["latitude"] == 17.4578
assert requested["longitude"] == 78.3742

print("\nRequested coordinates:")
print("Latitude :", requested["latitude"])
print("Longitude:", requested["longitude"])

print("\nReturned coordinates:")
print("Latitude :", returned["returned_latitude"])
print("Longitude:", returned["returned_longitude"])
print("Elevation:", returned["elevation_m"], "m")

# ------------------------------------------------------------
# 5. VERIFY EXPECTED VARIABLES
# ------------------------------------------------------------

expected_variables = [
    "temperature_2m",
    "relative_humidity_2m",
    "apparent_temperature",
    "precipitation",
    "rain",
    "wind_speed_10m",
    "wind_direction_10m",
    "wind_gusts_10m",
    "cloud_cover",
    "surface_pressure",
    "dew_point_2m",
]

missing_columns = [
    col for col in expected_variables
    if col not in weather_df.columns
]

if missing_columns:
    raise ValueError(f"Missing weather columns: {missing_columns}")

# ------------------------------------------------------------
# 6. VERIFY HOURLY TIMESTAMPS
# ------------------------------------------------------------

expected_timestamps = pd.date_range(
    start="2023-01-01 00:00:00",
    end="2026-08-01 00:00:00",
    freq="h",
    inclusive="left"
)

actual_timestamps = pd.DatetimeIndex(weather_df["timestamp"])

missing_timestamps = expected_timestamps.difference(
    actual_timestamps
)

unexpected_timestamps = actual_timestamps.difference(
    expected_timestamps
)

duplicate_count = int(
    weather_df["timestamp"].duplicated().sum()
)

# ------------------------------------------------------------
# 7. CHECK MISSING VALUES
# ------------------------------------------------------------

missing_values = (
    weather_df[expected_variables]
    .isna()
    .sum()
    .astype(int)
)

# ------------------------------------------------------------
# 8. REPORT RESULTS
# ------------------------------------------------------------

print("\nDataset shape:", weather_df.shape)
print("Expected hourly records:", len(expected_timestamps))
print("Actual records:", len(weather_df))
print("Unique timestamps:", weather_df["timestamp"].nunique())
print("Duplicate timestamps:", duplicate_count)
print("Missing timestamps:", len(missing_timestamps))
print("Unexpected timestamps:", len(unexpected_timestamps))

print("\nMissing values by variable:")
print(missing_values.to_string())

# ------------------------------------------------------------
# 9. FINAL VALIDATION STATUS
# ------------------------------------------------------------

checks = {
    "Expected record count": len(weather_df) == len(expected_timestamps),
    "Unique timestamps": weather_df["timestamp"].nunique() == len(expected_timestamps),
    "No duplicate timestamps": duplicate_count == 0,
    "No missing timestamps": len(missing_timestamps) == 0,
    "No unexpected timestamps": len(unexpected_timestamps) == 0,
    "No missing weather values": int(missing_values.sum()) == 0,
    "All required columns present": len(missing_columns) == 0,
}

print("\nVALIDATION CHECKLIST")
print("-" * 65)

for check, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL'} | {check}")

if all(checks.values()):
    print("\nRESULT: SAVED DATASET PASSED ALL CHECKS.")
else:
    print("\nRESULT: INVESTIGATION REQUIRED.")

# Display a small sample
display(weather_df.head())

=================================================================
SAVED WEATHER DATA VALIDATION
=================================================================
Found: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\weather\hyderabad_historical_weather_174578_783742.csv
Found: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\metadata\weather_source_metadata_174578_783742.json

Requested coordinates:
Latitude : 17.4578
Longitude: 78.3742

Returned coordinates:
Latitude : 17.469244
Longitude: 78.35907
Elevation: 587.0 m

Dataset shape: (31392, 12)
Expected hourly records: 31392
Actual records: 31392
Unique timestamps: 31392
Duplicate timestamps: 0
Missing timestamps: 0
Unexpected timestamps: 0

Missing values by variable:
temperature_2m          0
relative_humidity_2m    0
apparent_temperature    0
precipitation           0
rain                    0
wind_speed_10m          0
wind_direction_10m      0
wind_gusts_10m          0
cloud_cover             0
surface_pressure        0
dew_point_2m            0

VALIDATION CHECKLIST
-----------------------------------------------------------------
PASS | Expected record count
PASS | Unique timestamps
PASS | No duplicate timestamps
PASS | No missing timestamps
PASS | No unexpected timestamps
PASS | No missing weather values
PASS | All required columns present

RESULT: SAVED DATASET PASSED ALL CHECKS.

,timestamp,temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,rain,wind_speed_10m,wind_direction_10m,wind_gusts_10m,cloud_cover,surface_pressure,dew_point_2m
0,2023-01-01 00:00:00,21.7,55,21.5,0.0,0.0,5.9,79,11.5,67,950.1,12.2
1,2023-01-01 01:00:00,21.1,57,20.8,0.0,0.0,6.4,74,10.4,93,949.5,12.2
2,2023-01-01 02:00:00,20.3,61,20.1,0.0,0.0,7.0,78,10.1,76,948.8,12.6
3,2023-01-01 03:00:00,19.5,65,19.2,0.0,0.0,7.9,87,10.8,87,948.4,12.8
4,2023-01-01 04:00:00,19.6,65,19.5,0.0,0.0,6.5,84,9.7,93,948.6,12.8

In [22]:
# ============================================================
# PHASE 04: WEATHER DATA PROFILING
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display

# ------------------------------------------------------------
# 1. LOAD THE VALIDATED WEATHER DATA
# ------------------------------------------------------------

weather_df = pd.read_csv(
    WEATHER_CSV_PATH,
    parse_dates=["timestamp"]
)

weather_variables = [
    "temperature_2m",
    "relative_humidity_2m",
    "apparent_temperature",
    "precipitation",
    "rain",
    "wind_speed_10m",
    "wind_direction_10m",
    "wind_gusts_10m",
    "cloud_cover",
    "surface_pressure",
    "dew_point_2m",
]

print("=" * 70)
print("OPEN-METEO WEATHER DATA PROFILING")
print("=" * 70)

print("Dataset shape:", weather_df.shape)
print(
    "Time period:",
    weather_df["timestamp"].min(),
    "to",
    weather_df["timestamp"].max()
)

# ------------------------------------------------------------
# 2. DESCRIPTIVE STATISTICS
# ------------------------------------------------------------

print("\n1. DESCRIPTIVE STATISTICS")

display(
    weather_df[weather_variables]
    .describe()
    .T
    .round(3)
)

# ------------------------------------------------------------
# 3. UNIQUE VALUES AND MISSING VALUES
# ------------------------------------------------------------

print("\n2. VARIABLE COMPLETENESS")

completeness = pd.DataFrame({
    "data_type": weather_df[weather_variables].dtypes.astype(str),
    "missing_values": weather_df[weather_variables].isna().sum(),
    "unique_values": weather_df[weather_variables].nunique(),
})

display(completeness)

# ------------------------------------------------------------
# 4. RAINFALL PROFILE
# ------------------------------------------------------------

print("\n3. RAINFALL PROFILE")

rainfall_profile = {
    "hours_with_precipitation": int(
        (weather_df["precipitation"] > 0).sum()
    ),
    "hours_without_precipitation": int(
        (weather_df["precipitation"] == 0).sum()
    ),
    "maximum_hourly_precipitation_mm": float(
        weather_df["precipitation"].max()
    ),
    "total_recorded_precipitation_mm": float(
        weather_df["precipitation"].sum()
    ),
    "negative_precipitation_values": int(
        (weather_df["precipitation"] < 0).sum()
    ),
}

for key, value in rainfall_profile.items():
    print(f"{key}: {value}")

# ------------------------------------------------------------
# 5. BASIC PHYSICAL-RANGE CHECKS
# These flag values for investigation; they do not delete data.
# ------------------------------------------------------------

print("\n4. RANGE CHECKS")

range_checks = {
    "relative_humidity_2m": (0, 100),
    "cloud_cover": (0, 100),
    "wind_direction_10m": (0, 360),
    "wind_speed_10m": (0, None),
    "wind_gusts_10m": (0, None),
    "precipitation": (0, None),
    "rain": (0, None),
}

for variable, (lower, upper) in range_checks.items():
    series = weather_df[variable]
    invalid = pd.Series(False, index=series.index)

    if lower is not None:
        invalid |= series < lower

    if upper is not None:
        invalid |= series > upper

    print(
        f"{variable}: {int(invalid.sum())} "
        "values outside configured bounds"
    )

# ------------------------------------------------------------
# 6. TEMPERATURE AND DEW-POINT RELATIONSHIP
# ------------------------------------------------------------

print("\n5. TEMPERATURE RELATIONSHIP")

temperature_below_dewpoint = (
    weather_df["dew_point_2m"] >
    weather_df["temperature_2m"]
)

print(
    "Hours where dew point exceeds air temperature:",
    int(temperature_below_dewpoint.sum())
)

# ------------------------------------------------------------
# 7. HOURLY RAINFALL SUMMARY BY MONTH
# ------------------------------------------------------------

print("\n6. MONTHLY RAINFALL SUMMARY")

monthly_rainfall = (
    weather_df.assign(
        year=weather_df["timestamp"].dt.year,
        month=weather_df["timestamp"].dt.month
    )
    .groupby(["year", "month"])
    .agg(
        hourly_records=("precipitation", "size"),
        total_precipitation_mm=("precipitation", "sum"),
        wet_hours=("precipitation", lambda x: (x > 0).sum()),
        maximum_hourly_precipitation_mm=("precipitation", "max"),
    )
    .reset_index()
)

display(monthly_rainfall.head(12))

print("\nProfiling completed.")
print(
    "No values have been modified or deleted. "
    "Investigate flagged observations before making corrections."
)

======================================================================
OPEN-METEO WEATHER DATA PROFILING
======================================================================
Dataset shape: (31392, 12)
Time period: 2023-01-01 00:00:00 to 2026-07-31 23:00:00

1. DESCRIPTIVE STATISTICS

,count,mean,std,min,25%,50%,75%,max
temperature_2m,31392.0,25.945,4.673,10.6,22.9,25.5,28.8,41.3
relative_humidity_2m,31392.0,61.786,22.203,11.0,44.0,63.0,81.0,100.0
apparent_temperature,31392.0,27.292,5.088,8.1,24.4,27.3,30.5,43.3
precipitation,31392.0,0.111,0.565,0.0,0.0,0.0,0.0,13.0
rain,31392.0,0.111,0.565,0.0,0.0,0.0,0.0,13.0
wind_speed_10m,31392.0,10.286,5.231,0.0,6.6,9.2,13.2,32.8
wind_direction_10m,31392.0,185.277,96.297,1.0,104.0,185.0,271.0,360.0
wind_gusts_10m,31392.0,22.334,10.530,1.1,14.0,20.9,28.8,65.2
cloud_cover,31392.0,53.886,43.127,0.0,4.0,60.0,100.0,100.0
surface_pressure,31392.0,944.834,3.878,933.3,941.9,944.9,947.8,955.7
dew_point_2m,31392.0,16.788,4.920,-3.2,13.2,17.9,21.1,25.2

2. VARIABLE COMPLETENESS

                     data_type  missing_values  unique_values
temperature_2m         float64               0            287
relative_humidity_2m     int64               0             90
apparent_temperature   float64               0            317
precipitation          float64               0            100
rain                   float64               0            100
wind_speed_10m         float64               0            309
wind_direction_10m       int64               0            360
wind_gusts_10m         float64               0            177
cloud_cover              int64               0            101
surface_pressure       float64               0            220
dew_point_2m           float64               0            269

3. RAINFALL PROFILE
hours_with_precipitation: 4728
hours_without_precipitation: 26664
maximum_hourly_precipitation_mm: 13.0
total_recorded_precipitation_mm: 3488.3999999999996
negative_precipitation_values: 0

4. RANGE CHECKS
relative_humidity_2m: 0 values outside configured bounds
cloud_cover: 0 values outside configured bounds
wind_direction_10m: 0 values outside configured bounds
wind_speed_10m: 0 values outside configured bounds
wind_gusts_10m: 0 values outside configured bounds
precipitation: 0 values outside configured bounds
rain: 0 values outside configured bounds

5. TEMPERATURE RELATIONSHIP
Hours where dew point exceeds air temperature: 0

6. MONTHLY RAINFALL SUMMARY

,year,month,hourly_records,total_precipitation_mm,wet_hours,maximum_hourly_precipitation_mm
0,2023,1,744,0.7,6,0.2
1,2023,2,672,0.0,0,0.0
2,2023,3,744,100.3,39,13.0
3,2023,4,720,70.1,54,10.6
4,2023,5,744,83.1,60,9.9
5,2023,6,720,54.8,91,4.1
6,2023,7,744,307.2,357,10.8
7,2023,8,744,35.2,160,1.5
8,2023,9,720,217.6,261,7.2
9,2023,10,744,16.4,24,5.3
10,2023,11,720,45.1,102,4.0
11,2023,12,744,7.8,14,3.6

Profiling completed.
No values have been modified or deleted. Investigate flagged observations before making corrections.

In [23]:
# ============================================================
# PHASE 04: PRECIPITATION VS RAIN COMPARISON
# ============================================================

import pandas as pd
import numpy as np

# Load the saved weather data
weather_df = pd.read_csv(
    WEATHER_CSV_PATH,
    parse_dates=["timestamp"]
)

# Compare the two variables
precipitation = weather_df["precipitation"]
rain = weather_df["rain"]

difference = precipitation - rain

comparison = pd.DataFrame({
    "Metric": [
        "Total records",
        "Precipitation mean (mm)",
        "Rain mean (mm)",
        "Precipitation maximum (mm)",
        "Rain maximum (mm)",
        "Hours precipitation > 0",
        "Hours rain > 0",
        "Hours precipitation != rain",
        "Maximum absolute difference (mm)",
        "Correlation"
    ],
    "Value": [
        len(weather_df),
        precipitation.mean(),
        rain.mean(),
        precipitation.max(),
        rain.max(),
        int((precipitation > 0).sum()),
        int((rain > 0).sum()),
        int((~np.isclose(precipitation, rain)).sum()),
        difference.abs().max(),
        precipitation.corr(rain)
    ]
})

display(comparison.round(4))

# Inspect records where the values differ
different_rows = weather_df.loc[
    ~np.isclose(precipitation, rain),
    ["timestamp", "precipitation", "rain"]
]

print("Records where precipitation and rain differ:",
      len(different_rows))

display(different_rows.head(10))

                             Metric       Value
0                     Total records  31392.0000
1           Precipitation mean (mm)      0.1111
2                    Rain mean (mm)      0.1111
3        Precipitation maximum (mm)     13.0000
4                 Rain maximum (mm)     13.0000
5           Hours precipitation > 0   4728.0000
6                    Hours rain > 0   4728.0000
7       Hours precipitation != rain      0.0000
8  Maximum absolute difference (mm)      0.0000
9                       Correlation      1.0000

Records where precipitation and rain differ: 0

Empty DataFrame
Columns: [timestamp, precipitation, rain]
Index: []

In [24]:

# ============================================================
# PHASE 04: CREATE OR REUSE CLEANED WEATHER DATASET
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

# 1. DEFINE PATHS
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

RAW_WEATHER_PATH = (
    PROJECT_ROOT / "data" / "raw" / "weather"
    / "hyderabad_historical_weather_174578_783742.csv"
)

PROCESSED_WEATHER_DIR = (
    PROJECT_ROOT / "data" / "processed" / "weather"
)
PROCESSED_WEATHER_DIR.mkdir(parents=True, exist_ok=True)

PROCESSED_WEATHER_PATH = (
    PROCESSED_WEATHER_DIR
    / "hyderabad_weather_cleaned_174578_783742.csv"
)

# 2. REUSE EXISTING FILE OR CREATE IT IF MISSING
if PROCESSED_WEATHER_PATH.exists():

    weather_cleaned = pd.read_csv(
        PROCESSED_WEATHER_PATH,
        parse_dates=["timestamp"]
    )

    print("Existing cleaned weather dataset reused.")

else:

    weather_df = pd.read_csv(
        RAW_WEATHER_PATH,
        parse_dates=["timestamp"]
    )

    if not np.allclose(
        weather_df["precipitation"],
        weather_df["rain"],
        equal_nan=True
    ):
        raise ValueError(
            "'precipitation' and 'rain' differ. "
            "Investigate before removing either column."
        )

    weather_cleaned = weather_df.drop(
        columns=["rain"]
    ).copy()

    assert weather_cleaned.shape == (31392, 11)
    assert weather_cleaned["timestamp"].is_unique
    assert weather_cleaned["timestamp"].notna().all()
    assert not weather_cleaned.drop(
        columns=["timestamp"]
    ).isna().any().any()

    weather_cleaned.to_csv(
        PROCESSED_WEATHER_PATH,
        index=False
    )

    print("Cleaned weather dataset created.")

# 3. DISPLAY RESULT
print("Output:", PROCESSED_WEATHER_PATH)
print("Shape:", weather_cleaned.shape)

display(weather_cleaned.head())

Existing cleaned weather dataset reused.
Output: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\weather\hyderabad_weather_cleaned_174578_783742.csv
Shape: (31392, 11)

,timestamp,temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,wind_speed_10m,wind_direction_10m,wind_gusts_10m,cloud_cover,surface_pressure,dew_point_2m
0,2023-01-01 00:00:00,21.7,55,21.5,0.0,5.9,79,11.5,67,950.1,12.2
1,2023-01-01 01:00:00,21.1,57,20.8,0.0,6.4,74,10.4,93,949.5,12.2
2,2023-01-01 02:00:00,20.3,61,20.1,0.0,7.0,78,10.1,76,948.8,12.6
3,2023-01-01 03:00:00,19.5,65,19.2,0.0,7.9,87,10.8,87,948.4,12.8
4,2023-01-01 04:00:00,19.6,65,19.5,0.0,6.5,84,9.7,93,948.6,12.8

# Phase 04.3 — Historical Weather Data Collection, Validation and Cleaning

## 1. Objective

The objective of this subsection is to collect hourly historical weather data for Hyderabad, India, validate its temporal coverage and data quality, and prepare a cleaned dataset for subsequent contextual data integration.

The collected weather data will provide environmental context for the Food Demand Forecasting Engine. Weather variables such as temperature, humidity, precipitation, and wind conditions may be used as explanatory features in later forecasting experiments.

## 2. Data Source

**Selected source:** Open-Meteo Historical Weather API

Open-Meteo was selected as the sole weather data source for this project to maintain a consistent collection process. Separate datasets from PERSIANN-CCS and NASA GPM IMERG were not included in this workflow.

**Official source:** https://open-meteo.com/

### 2.1 Requested location and temporal coverage

| Parameter           | Value          |
| ------------------- | -------------- |
| Requested latitude  | 17.4578        |
| Requested longitude | 78.3742        |
| Start date          | 1 January 2023 |
| End date            | 31 July 2026   |
| Timezone            | Asia/Kolkata   |
| Temporal frequency  | Hourly         |
| Data provider       | Open-Meteo     |

The requested period covers historical weather conditions from January 2023 through July 2026, inclusive.

## 3. Weather Variables Collected

The original weather response contained the following variables:

| Variable               | Description                        |
| ---------------------- | ---------------------------------- |
| `temperature_2m`       | Air temperature at 2 metres        |
| `relative_humidity_2m` | Relative humidity at 2 metres      |
| `apparent_temperature` | Apparent or feels-like temperature |
| `precipitation`        | Total precipitation                |
| `rain`                 | Rainfall component                 |
| `wind_speed_10m`       | Wind speed at 10 metres            |
| `wind_direction_10m`   | Wind direction at 10 metres        |
| `wind_gusts_10m`       | Wind gust speed at 10 metres       |
| `cloud_cover`          | Cloud cover percentage             |
| `surface_pressure`     | Surface atmospheric pressure       |
| `dew_point_2m`         | Dew-point temperature at 2 metres  |

The cleaned dataset retains ten weather variables and a timestamp column.

## 4. Data Collection and Raw Data Preservation

Hourly historical weather data was collected from Open-Meteo for the requested location and period.

The raw data was kept separate from the processed data to preserve the original collected values and support reproducibility.

**Recorded raw-data artifact:**

`data/raw/weather/hyderabad_historical_weather_174578_783742.csv`

**Recorded metadata artifact:**

`data/metadata/weather_source_metadata_174578_783742.json`

The metadata file is intended to preserve source and request details, including the requested location, collection period, timezone, and relevant API metadata.

## 5. Data Cleaning and Preprocessing

The original response included both `rain` and `precipitation`. The `rain` variable was removed from the cleaned dataset because it overlaps with the retained precipitation information for the intended feature set.

The `precipitation` variable was retained.

The raw dataset was not intended to be overwritten. Cleaning was performed into a separate processed-data artifact.

**Recorded cleaned-data artifact:**

`data/processed/weather/hyderabad_weather_cleaned_174578_783742.csv`

The cleaned dataset contains:

* One timestamp column.
* Ten weather variables.
* A total of eleven columns.

## 6. Data Validation

The recorded collection and validation results are summarised below.

| Validation check                   | Recorded result                          |
| ---------------------------------- | ---------------------------------------- |
| Requested temporal coverage        | 1 January 2023 – 31 July 2026            |
| Temporal frequency                 | Hourly                                   |
| Recorded number of hourly records  | 31,392                                   |
| Missing hourly timestamps          | None reported                            |
| Missing values in collected fields | None reported                            |
| Timezone                           | Asia/Kolkata                             |
| Redundant variable handling        | `rain` removed; `precipitation` retained |
| Raw and processed data separation  | Maintained through separate file paths   |

The reported 31,392 records correspond to the inclusive hourly period from 1 January 2023 through 31 July 2026.

These results reflect the recorded collection workflow. The underlying CSV files and notebook outputs should be inspected or revalidated before these checks are treated as independently reproduced results.

## 7. Spatial Coverage and Source Limitations

Although the request used coordinates 17.4578° latitude and 78.3742° longitude, the returned weather grid location was approximately:

* **Latitude:** 17.469244°
* **Longitude:** 78.35907°
* **Elevation:** 587 metres

The returned grid location differs from the requested coordinates. Therefore, the data should not be described as direct weather-station observations measured precisely at the requested point.

The request used Open-Meteo's default *Best Match* model selection. A single fixed spatial resolution should not be claimed without confirming the selected underlying model and its resolution.

The historical weather data represents gridded/model-derived estimates and may not capture every highly localised weather variation affecting individual delivery zones.

## 8. Coverage Consideration for Future Integration

The weather dataset ends on 31 July 2026, while the project's validated complete-date hourly demand panel extends through 30 August 2026.

This difference must be addressed explicitly during the later compatibility and integration steps.

Weather values must not be fabricated to fill the uncovered period. Any decision to restrict the integration period or obtain additional weather data must be documented and validated before integration.

## 9. Research Findings

The recorded Phase 04.3 workflow established a historical weather dataset for the requested period using Open-Meteo.

The workflow recorded 31,392 hourly records, no missing timestamps, and no missing values. The cleaning process removed the overlapping `rain` variable while retaining `precipitation`.

The raw dataset, cleaned dataset, and source metadata were assigned separate artifact paths to support traceability and reproducibility.

The principal limitations identified were the difference between the requested and returned grid coordinates, the gridded nature of the weather estimates, and the temporal coverage difference between weather and demand data.

## 10. Phase Status

**Phase 04.3 — Collect, Validate and Clean Historical Weather: Completed according to the recorded workflow.**

The final reproducibility checks should be confirmed against the actual data files and notebook outputs if the results are to be reported as independently verified.

### Next Step

Proceed to **Phase 04.4 — Public Holiday Collection**.

Public holiday collection and classification will be documented separately. No compatibility check or integration with the demand dataset will be performed until the remaining contextual data collection and validation steps have been completed.

In [25]:
import requests
from bs4 import BeautifulSoup

SOURCES = {
    2023: "https://www.telangana.gov.in/Downloads/calendar-2023/",
    2024: "https://www.telangana.gov.in/downloads/calendar/",
    2025: "https://www.telangana.gov.in/downloads/calendar-2025/",
    2026: "https://www.telangana.gov.in/downloads/calendar-2026/",
}

headers = {
    "User-Agent": "Mozilla/5.0 (compatible; ResearchDataCollection/1.0)"
}

for year, url in SOURCES.items():
    print(f"\n{'=' * 65}")
    print(f"YEAR: {year}")
    print(f"URL: {url}")

    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=30
        )

        print("HTTP status:", response.status_code)
        print("Final URL:", response.url)
        print("Content type:", response.headers.get("Content-Type"))
        print("Response size:", len(response.content), "bytes")

        response.raise_for_status()

        soup = BeautifulSoup(response.content, "html.parser")

        title = soup.title.get_text(" ", strip=True) if soup.title else "No page title"
        print("Page title:", title)

        # Inspect visible page text.
        page_text = soup.get_text(" ", strip=True)

        print("\nFirst 1,500 characters of page text:")
        print(page_text[:1500])

        # Inspect links that may point to calendars or PDF notifications.
        print("\nRelevant links:")

        relevant_links = []

        for link in soup.find_all("a", href=True):
            text = link.get_text(" ", strip=True)
            href = link["href"]

            combined = f"{text} {href}".lower()

            if any(term in combined for term in [
                "calendar", "holiday", ".pdf", "general",
                "optional", "government order", "go-ms"
            ]):
                relevant_links.append((text, href))

        for text, href in relevant_links[:20]:
            print(f"- {text or '[No link text]'}: {href}")

        if not relevant_links:
            print("No relevant links found in the parsed HTML.")

    except Exception as exc:
        print("ERROR:", repr(exc))

=================================================================
YEAR: 2023
URL: https://www.telangana.gov.in/Downloads/calendar-2023/
HTTP status: 200
Final URL: https://www.telangana.gov.in/Downloads/calendar-2023/
Content type: text/html; charset=UTF-8
Response size: 168215 bytes
Page title: Calendar 2023 - Telangana State Portal

First 1,500 characters of page text:
Calendar 2023 - Telangana State Portal [language-switcher] Facebook Youtube Instagram Whatsapp Skip to main content Telangana State Portal Home About State Profile Districts Language & Culture State Symbols State Song Government Governor Chief Minister Council of Ministers Chief Secretary MPs (RS & LS) Advisors Legislature Legislative Council Chairman Legislative Assembly Speaker Members of Legislative Council Members of Legislative Assembly Judiciary Chief Justice High Court Departments Agriculture and Co-operation Animal Husbandry, Dairy Development and Fisheries Archaeology Backward Classes Welfare Cinematography Consumer Affairs Food & Civil Supplies Endowments Energy Environment & Forests Finance General Administration (Political) Handlooms & Textiles Health, Medical & Family Welfare, Science and Technology Higher Education Home Housing Industries and Commerce Information and Public Relations Information Technology, Electronics and Communications Irrigation and CAD Labour, Employment Training and Factories Law & Order Legislative Affairs Mines & Geology Minorities Welfare Municipal Administration & Urban Development Panchayat Raj and Rural Development Planning Public Enterprises Revenue Revenue (Registration and Stamps) Revenue (Prohibition & Excise) Revenue (Commercial Taxes) Roads and Buildings School Education (SE Wing) Social Welfare Transport Tribal Welfare Sports and Youth Services Women and Child Welfare Youth Advancement, Tourism and Culture Services Meeseva Serv

Relevant links:
- General Administration (Political): https://www.telangana.gov.in/departments/general-administration-political/
- Calendar - 2026: https://www.telangana.gov.in/downloads/calendar-2026/
- Calendar - 2025: https://www.telangana.gov.in/downloads/calendar-2025/
- Calendar - 2024: https://www.telangana.gov.in/downloads/calendar/
- Calendar - 2023: https://www.telangana.gov.in/downloads/calendar-2023/
- Calendar - 2022: https://www.telangana.gov.in/downloads/calendar-2022/
- Calendar - 2021: https://www.telangana.gov.in/downloads/calendar-2021/
- Calendar - 2020: https://www.telangana.gov.in/downloads/calendar-2020/
- Calendar - 2019: https://www.telangana.gov.in/downloads/calendar-2019/
- Calendar - 2018: https://www.telangana.gov.in/downloads/calendar-2018/

=================================================================
YEAR: 2024
URL: https://www.telangana.gov.in/downloads/calendar/
HTTP status: 200
Final URL: https://www.telangana.gov.in/downloads/calendar/
Content type: text/html; charset=UTF-8
Response size: 167026 bytes
Page title: Calendar - Telangana State Portal

First 1,500 characters of page text:
Calendar - Telangana State Portal [language-switcher] Facebook Youtube Instagram Whatsapp Skip to main content Telangana State Portal Home About State Profile Districts Language & Culture State Symbols State Song Government Governor Chief Minister Council of Ministers Chief Secretary MPs (RS & LS) Advisors Legislature Legislative Council Chairman Legislative Assembly Speaker Members of Legislative Council Members of Legislative Assembly Judiciary Chief Justice High Court Departments Agriculture and Co-operation Animal Husbandry, Dairy Development and Fisheries Archaeology Backward Classes Welfare Cinematography Consumer Affairs Food & Civil Supplies Endowments Energy Environment & Forests Finance General Administration (Political) Handlooms & Textiles Health, Medical & Family Welfare, Science and Technology Higher Education Home Housing Industries and Commerce Information and Public Relations Information Technology, Electronics and Communications Irrigation and CAD Labour, Employment Training and Factories Law & Order Legislative Affairs Mines & Geology Minorities Welfare Municipal Administration & Urban Development Panchayat Raj and Rural Development Planning Public Enterprises Revenue Revenue (Registration and Stamps) Revenue (Prohibition & Excise) Revenue (Commercial Taxes) Roads and Buildings School Education (SE Wing) Social Welfare Transport Tribal Welfare Sports and Youth Services Women and Child Welfare Youth Advancement, Tourism and Culture Services Meeseva Services

Relevant links:
- General Administration (Political): https://www.telangana.gov.in/departments/general-administration-political/
- Calendar - 2026: https://www.telangana.gov.in/downloads/calendar-2026/
- Calendar - 2025: https://www.telangana.gov.in/downloads/calendar-2025/
- Calendar - 2024: https://www.telangana.gov.in/downloads/calendar/
- Calendar - 2023: https://www.telangana.gov.in/downloads/calendar-2023/
- Calendar - 2022: https://www.telangana.gov.in/downloads/calendar-2022/
- Calendar - 2021: https://www.telangana.gov.in/downloads/calendar-2021/
- Calendar - 2020: https://www.telangana.gov.in/downloads/calendar-2020/
- Calendar - 2019: https://www.telangana.gov.in/downloads/calendar-2019/
- Calendar - 2018: https://www.telangana.gov.in/downloads/calendar-2018/

=================================================================
YEAR: 2025
URL: https://www.telangana.gov.in/downloads/calendar-2025/
HTTP status: 200
Final URL: https://www.telangana.gov.in/downloads/calendar-2025/
Content type: text/html; charset=UTF-8
Response size: 167221 bytes
Page title: Calendar - Telangana State Portal

First 1,500 characters of page text:
Calendar - Telangana State Portal [language-switcher] Facebook Youtube Instagram Whatsapp Skip to main content Telangana State Portal Home About State Profile Districts Language & Culture State Symbols State Song Government Governor Chief Minister Council of Ministers Chief Secretary MPs (RS & LS) Advisors Legislature Legislative Council Chairman Legislative Assembly Speaker Members of Legislative Council Members of Legislative Assembly Judiciary Chief Justice High Court Departments Agriculture and Co-operation Animal Husbandry, Dairy Development and Fisheries Archaeology Backward Classes Welfare Cinematography Consumer Affairs Food & Civil Supplies Endowments Energy Environment & Forests Finance General Administration (Political) Handlooms & Textiles Health, Medical & Family Welfare, Science and Technology Higher Education Home Housing Industries and Commerce Information and Public Relations Information Technology, Electronics and Communications Irrigation and CAD Labour, Employment Training and Factories Law & Order Legislative Affairs Mines & Geology Minorities Welfare Municipal Administration & Urban Development Panchayat Raj and Rural Development Planning Public Enterprises Revenue Revenue (Registration and Stamps) Revenue (Prohibition & Excise) Revenue (Commercial Taxes) Roads and Buildings School Education (SE Wing) Social Welfare Transport Tribal Welfare Sports and Youth Services Women and Child Welfare Youth Advancement, Tourism and Culture Services Meeseva Services

Relevant links:
- General Administration (Political): https://www.telangana.gov.in/departments/general-administration-political/
- Calendar - 2026: https://www.telangana.gov.in/downloads/calendar-2026/
- Calendar - 2025: https://www.telangana.gov.in/downloads/calendar-2025/
- Calendar - 2024: https://www.telangana.gov.in/downloads/calendar/
- Calendar - 2023: https://www.telangana.gov.in/downloads/calendar-2023/
- Calendar - 2022: https://www.telangana.gov.in/downloads/calendar-2022/
- Calendar - 2021: https://www.telangana.gov.in/downloads/calendar-2021/
- Calendar - 2020: https://www.telangana.gov.in/downloads/calendar-2020/
- Calendar - 2019: https://www.telangana.gov.in/downloads/calendar-2019/
- Calendar - 2018: https://www.telangana.gov.in/downloads/calendar-2018/

=================================================================
YEAR: 2026
URL: https://www.telangana.gov.in/downloads/calendar-2026/
HTTP status: 200
Final URL: https://www.telangana.gov.in/downloads/calendar-2026/
Content type: text/html; charset=UTF-8
Response size: 167248 bytes
Page title: Calendar 2026 - Telangana State Portal

First 1,500 characters of page text:
Calendar 2026 - Telangana State Portal [language-switcher] Facebook Youtube Instagram Whatsapp Skip to main content Telangana State Portal Home About State Profile Districts Language & Culture State Symbols State Song Government Governor Chief Minister Council of Ministers Chief Secretary MPs (RS & LS) Advisors Legislature Legislative Council Chairman Legislative Assembly Speaker Members of Legislative Council Members of Legislative Assembly Judiciary Chief Justice High Court Departments Agriculture and Co-operation Animal Husbandry, Dairy Development and Fisheries Archaeology Backward Classes Welfare Cinematography Consumer Affairs Food & Civil Supplies Endowments Energy Environment & Forests Finance General Administration (Political) Handlooms & Textiles Health, Medical & Family Welfare, Science and Technology Higher Education Home Housing Industries and Commerce Information and Public Relations Information Technology, Electronics and Communications Irrigation and CAD Labour, Employment Training and Factories Law & Order Legislative Affairs Mines & Geology Minorities Welfare Municipal Administration & Urban Development Panchayat Raj and Rural Development Planning Public Enterprises Revenue Revenue (Registration and Stamps) Revenue (Prohibition & Excise) Revenue (Commercial Taxes) Roads and Buildings School Education (SE Wing) Social Welfare Transport Tribal Welfare Sports and Youth Services Women and Child Welfare Youth Advancement, Tourism and Culture Services Meeseva Serv

Relevant links:
- General Administration (Political): https://www.telangana.gov.in/departments/general-administration-political/
- Calendar - 2026: https://www.telangana.gov.in/downloads/calendar-2026/
- Calendar - 2025: https://www.telangana.gov.in/downloads/calendar-2025/
- Calendar - 2024: https://www.telangana.gov.in/downloads/calendar/
- Calendar - 2023: https://www.telangana.gov.in/downloads/calendar-2023/
- Calendar - 2022: https://www.telangana.gov.in/downloads/calendar-2022/
- Calendar - 2021: https://www.telangana.gov.in/downloads/calendar-2021/
- Calendar - 2020: https://www.telangana.gov.in/downloads/calendar-2020/
- Calendar - 2019: https://www.telangana.gov.in/downloads/calendar-2019/
- Calendar - 2018: https://www.telangana.gov.in/downloads/calendar-2018/

In [26]:
import requests
from bs4 import BeautifulSoup

url = "https://www.telangana.gov.in/Downloads/calendar-2023/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

# Search for calendar-related text in headings and page content.
keywords = [
    "General Holidays",
    "Optional Holidays",
    "January",
    "January 2023",
    "Holiday"
]

print("PAGE TITLE:", soup.title.get_text(" ", strip=True))
print("\nMATCHING TEXT:")

for keyword in keywords:
    matches = soup.find_all(
        string=lambda text: text and keyword.lower() in text.lower()
    )

    print(f"\n--- {keyword}: {len(matches)} matches ---")

    for match in matches[:5]:
        parent = match.parent
        print(parent.get_text(" ", strip=True)[:500])

# Inspect links that may point to calendar files.
print("\nCALENDAR/PDF LINKS:")

for link in soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = link["href"]

    if any(word in f"{text} {href}".lower()
           for word in ["calendar", ".pdf", "holiday"]):
        print(text or "[No link text]", "->", href)

# Inspect embedded PDFs or other documents.
print("\nEMBEDDED DOCUMENTS:")

for tag in soup.find_all(["iframe", "embed", "object"]):
    print(tag.name, tag.attrs)

PAGE TITLE: Calendar 2023 - Telangana State Portal

MATCHING TEXT:

--- General Holidays: 1 matches ---
General Holidays

--- Optional Holidays: 0 matches ---

--- January: 1 matches ---
January 2023​

--- January 2023: 1 matches ---
January 2023​

--- Holiday: 6 matches ---
List of Holidays - 2023
General Holidays
Optio​nal Holidays
Sri Panchami (General Holiday in view of Republic Day)
Tamil New Year's Day/Jumuatulwada (General holiday in the view of Dr. B.R. Ambedkar's Birthday)

CALENDAR/PDF LINKS:
Calendar - 2026 -> https://www.telangana.gov.in/downloads/calendar-2026/
Calendar - 2025 -> https://www.telangana.gov.in/downloads/calendar-2025/
Calendar - 2024 -> https://www.telangana.gov.in/downloads/calendar/
Calendar - 2023 -> https://www.telangana.gov.in/downloads/calendar-2023/
Calendar - 2022 -> https://www.telangana.gov.in/downloads/calendar-2022/
Calendar - 2021 -> https://www.telangana.gov.in/downloads/calendar-2021/
Calendar - 2020 -> https://www.telangana.gov.in/downloads/calendar-2020/
Calendar - 2019 -> https://www.telangana.gov.in/downloads/calendar-2019/
Calendar - 2018 -> https://www.telangana.gov.in/downloads/calendar-2018/

EMBEDDED DOCUMENTS:

In [27]:
import requests
from bs4 import BeautifulSoup

url = "https://www.telangana.gov.in/Downloads/calendar-2023/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

# Find headings and nearby content related to the holiday list.
for element in soup.find_all(
    string=lambda text: text and (
        "List of Holidays" in text
        or "General Holidays" in text
        or "Optional Holidays" in text
    )
):
    print("\n" + "=" * 70)
    print("MATCH:", repr(element.strip()))
    print("PARENT TAG:", element.parent.name)
    print("PARENT CLASS:", element.parent.get("class"))
    print("PARENT ID:", element.parent.get("id"))

    # Show the surrounding HTML structure.
    print("\nNEARBY HTML:")
    print(element.parent.parent.prettify()[:3500])

======================================================================
MATCH: 'List of Holidays - 2023'
PARENT TAG: h2
PARENT CLASS: None
PARENT ID: None

NEARBY HTML:
<div class="elementor-widget-container">
 <h2>
  List of Holidays - 2023
 </h2>
 <span style="padding: 5px 16px; border-radius: 3px; background-color: #1d7845;">
 </span>
 <span style="color:#1d7845; font-weight: bold; font-size: 14px;">
  General Holidays
 </span>
 <span style="background-color: #c08e4b; border-radius: 3px; padding: 5px 16px;">
 </span>
 <span style="color: #c08e4b; font-weight: bold; font-size: 14px;">
  Optio​nal Holidays
 </span>
</div>


======================================================================
MATCH: 'General Holidays'
PARENT TAG: span
PARENT CLASS: None
PARENT ID: None

NEARBY HTML:
<div class="elementor-widget-container">
 <h2>
  List of Holidays - 2023
 </h2>
 <span style="padding: 5px 16px; border-radius: 3px; background-color: #1d7845;">
 </span>
 <span style="color:#1d7845; font-weight: bold; font-size: 14px;">
  General Holidays
 </span>
 <span style="background-color: #c08e4b; border-radius: 3px; padding: 5px 16px;">
 </span>
 <span style="color: #c08e4b; font-weight: bold; font-size: 14px;">
  Optio​nal Holidays
 </span>
</div>

In [28]:
import requests
from bs4 import BeautifulSoup

url = "https://www.telangana.gov.in/Downloads/calendar-2023/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

heading = soup.find(
    lambda tag: tag.name in ["h1", "h2", "h3", "h4"]
    and "List of Holidays - 2023" in tag.get_text(" ", strip=True)
)

if heading is None:
    print("Holiday-list heading not found.")
else:
    # Find the enclosing Elementor widget.
    widget = heading.find_parent(
        class_="elementor-widget-container"
    )

    if widget is None:
        print("Enclosing widget not found.")
    else:
        print("WIDGET TEXT:")
        print(widget.get_text("\n", strip=True))

        print("\nWIDGET HTML:")
        print(widget.prettify()[:12000])

        print("\nTABLES INSIDE WIDGET:")
        tables = widget.find_all("table")

        if tables:
            for index, table in enumerate(tables, start=1):
                print(f"\nTable {index}:")
                print(table.get_text(" | ", strip=True))
        else:
            print("No HTML tables found in this widget.")

WIDGET TEXT:
List of Holidays - 2023
General Holidays
Optio​nal Holidays

WIDGET HTML:
<div class="elementor-widget-container">
 <h2>
  List of Holidays - 2023
 </h2>
 <span style="padding: 5px 16px; border-radius: 3px; background-color: #1d7845;">
 </span>
 <span style="color:#1d7845; font-weight: bold; font-size: 14px;">
  General Holidays
 </span>
 <span style="background-color: #c08e4b; border-radius: 3px; padding: 5px 16px;">
 </span>
 <span style="color: #c08e4b; font-weight: bold; font-size: 14px;">
  Optio​nal Holidays
 </span>
</div>


TABLES INSIDE WIDGET:
No HTML tables found in this widget.

In [29]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

url = "https://www.telangana.gov.in/departments/general-administration-political/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

print("HTTP status:", response.status_code)
print("Final URL:", response.url)
print("Content type:", response.headers.get("Content-Type"))

response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

print("\nPAGE TITLE:")
print(soup.title.get_text(" ", strip=True) if soup.title else "No title")

print("\nHOLIDAY / GOVERNMENT ORDER LINKS:")

keywords = [
    "holiday",
    "general administration",
    "government order",
    "go-ms",
    "2023",
    "2024",
    "2025",
    "2026",
]

count = 0

for link in soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(response.url, link["href"])
    combined = f"{text} {href}".lower()

    if any(keyword in combined for keyword in keywords):
        print(f"- {text or '[No link text]'}: {href}")
        count += 1

        if count >= 60:
            break

if count == 0:
    print("No matching links found in the returned HTML.")

HTTP status: 200
Final URL: https://www.telangana.gov.in/departments/general-administration-political/
Content type: text/html; charset=UTF-8

PAGE TITLE:
General Administration (Political) - Telangana State Portal

HOLIDAY / GOVERNMENT ORDER LINKS:
- General Administration (Political): https://www.telangana.gov.in/departments/general-administration-political/
- General Administration (Political): https://www.telangana.gov.in/departments/general-administration-political/

In [30]:
import re
import requests
from bs4 import BeautifulSoup

SOURCES = {
    2023: "https://www.telangana.gov.in/Downloads/calendar-2023/",
    2024: "https://www.telangana.gov.in/downloads/calendar/",
    2025: "https://www.telangana.gov.in/downloads/calendar-2025/",
    2026: "https://www.telangana.gov.in/downloads/calendar-2026/",
}

headers = {"User-Agent": "Mozilla/5.0"}

# Match entries such as: Jan 01 | New Year Day
holiday_pattern = re.compile(
    r"^\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)"
    r"\s+(\d{1,2})\s*\|\s*(.+?)\s*$",
    flags=re.MULTILINE | re.IGNORECASE
)

for year, url in SOURCES.items():
    print(f"\n{'=' * 60}")
    print(f"YEAR: {year}")

    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=30
        )
        response.raise_for_status()

        soup = BeautifulSoup(response.content, "html.parser")

        # Extract text from the whole page, not just the heading widget.
        page_text = soup.get_text("\n", strip=True)

        matches = holiday_pattern.findall(page_text)

        print("HTTP status:", response.status_code)
        print("Matching entries:", len(matches))

        for month, day, name in matches[:12]:
            print(f"{month} {int(day):02d} | {name}")

        if not matches:
            print("No matching entries. More inspection is required.")

    except Exception as exc:
        print("ERROR:", repr(exc))

============================================================
YEAR: 2023
HTTP status: 200
Matching entries: 0
No matching entries. More inspection is required.

============================================================
YEAR: 2024
HTTP status: 200
Matching entries: 0
No matching entries. More inspection is required.

============================================================
YEAR: 2025
HTTP status: 200
Matching entries: 0
No matching entries. More inspection is required.

============================================================
YEAR: 2026
HTTP status: 200
Matching entries: 0
No matching entries. More inspection is required.

In [31]:
import requests
from bs4 import BeautifulSoup

url = "https://www.telangana.gov.in/Downloads/calendar-2023/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

print("HTTP Status:", response.status_code)
print("Page Title:", soup.title.get_text(strip=True) if soup.title else "Not found")
print("HTML Size:", len(response.content), "bytes")

# 1. Inspect text containing holiday-related keywords
page_text = soup.get_text(" ", strip=True)

keywords = [
    "List of Holidays",
    "General Holidays",
    "Optional Holidays",
    "New Year",
    "Sankranti",
    "Republic Day"
]

print("\n--- HOLIDAY KEYWORD INSPECTION ---")

for keyword in keywords:
    position = page_text.lower().find(keyword.lower())

    if position != -1:
        start = max(0, position - 200)
        end = min(len(page_text), position + 600)

        print(f"\nKeyword: {keyword}")
        print(page_text[start:end])
    else:
        print(f"\nKeyword not found in page text: {keyword}")

# 2. Inspect HTML tables
print("\n--- HTML TABLE INSPECTION ---")

tables = soup.find_all("table")
print("Number of tables:", len(tables))

for table_index, table in enumerate(tables[:5], start=1):
    print(f"\nTable {table_index}:")
    print(table.get_text(" | ", strip=True)[:1500])

# 3. Inspect embedded scripts for holiday data
print("\n--- SCRIPT INSPECTION ---")

scripts = soup.find_all("script")
print("Number of scripts:", len(scripts))

for index, script in enumerate(scripts):
    script_text = script.get_text(" ", strip=True)

    if any(
        keyword.lower() in script_text.lower()
        for keyword in ["holiday", "calendar-2023", "new year"]
    ):
        print(f"\nRelevant script {index}:")
        print(script_text[:2000])

HTTP Status: 200
Page Title: Calendar 2023 - Telangana State Portal
HTML Size: 168215 bytes

--- HOLIDAY KEYWORD INSPECTION ---

Keyword: List of Holidays
endar 2023 Emblem Photos Reports Important GOs Policies Calendar - 2026 Calendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2023 General Holidays Optio​nal Holidays January 2023​ Sun Mon Tue W​ed Thu Fri Sat 1 2​ 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti/Pongal Jan 16 Kanumu Jan 26 Republic Day Jan 26 Sri Panchami (General Holiday in view of Republic Day) February 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 05 Birthday of Hazrath Ali (R.A.) Feb 18 Maha Shivaratri Feb 19 Shab-E-Meraj March 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5

Keyword: General Holidays
 Reports Important GOs Policies Calendar - 2026 Calendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2023 General Holidays Optio​nal Holidays January 2023​ Sun Mon Tue W​ed Thu Fri Sat 1 2​ 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti/Pongal Jan 16 Kanumu Jan 26 Republic Day Jan 26 Sri Panchami (General Holiday in view of Republic Day) February 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 05 Birthday of Hazrath Ali (R.A.) Feb 18 Maha Shivaratri Feb 19 Shab-E-Meraj March 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 1

Keyword not found in page text: Optional Holidays

Keyword: New Year
2018 List of Holidays - 2023 General Holidays Optio​nal Holidays January 2023​ Sun Mon Tue W​ed Thu Fri Sat 1 2​ 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti/Pongal Jan 16 Kanumu Jan 26 Republic Day Jan 26 Sri Panchami (General Holiday in view of Republic Day) February 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 05 Birthday of Hazrath Ali (R.A.) Feb 18 Maha Shivaratri Feb 19 Shab-E-Meraj March 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Mar 07 Holi Mar 08 Shab-E-Barat Mar 22 Ugadi Mar 30 Sri Rama Navami April 2023 Sun Mon Tue Wed Thu Fri Sat * * * * * * 1

Keyword: Sankranti
ral Holidays Optio​nal Holidays January 2023​ Sun Mon Tue W​ed Thu Fri Sat 1 2​ 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti/Pongal Jan 16 Kanumu Jan 26 Republic Day Jan 26 Sri Panchami (General Holiday in view of Republic Day) February 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 05 Birthday of Hazrath Ali (R.A.) Feb 18 Maha Shivaratri Feb 19 Shab-E-Meraj March 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Mar 07 Holi Mar 08 Shab-E-Barat Mar 22 Ugadi Mar 30 Sri Rama Navami April 2023 Sun Mon Tue Wed Thu Fri Sat * * * * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

Keyword: Republic Day
y 2023​ Sun Mon Tue W​ed Thu Fri Sat 1 2​ 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti/Pongal Jan 16 Kanumu Jan 26 Republic Day Jan 26 Sri Panchami (General Holiday in view of Republic Day) February 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 05 Birthday of Hazrath Ali (R.A.) Feb 18 Maha Shivaratri Feb 19 Shab-E-Meraj March 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Mar 07 Holi Mar 08 Shab-E-Barat Mar 22 Ugadi Mar 30 Sri Rama Navami April 2023 Sun Mon Tue Wed Thu Fri Sat * * * * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 2

--- HTML TABLE INSPECTION ---
Number of tables: 12

Table 1:
Jan 01 | New Year Day | Jan 14 | Bhogi | Jan 15 | Sankranti/Pongal | Jan 16 | Kanumu | Jan 26 | Republic Day | Jan 26 | Sri Panchami (General Holiday in view of Republic Day)

Table 2:
Feb 05 | Birthday of Hazrath Ali (R.A.) | Feb 18 | Maha Shivaratri | Feb 19 | Shab-E-Meraj

Table 3:
Mar 07 | Holi | Mar 08 | Shab-E-Barat | Mar 22 | Ugadi | Mar 30 | Sri Rama Navami

Table 4:
Apr 04 | Mahaveer Jayanthi | Apr 05 | Babu Jagjivan Ram's Birthday | Apr 07 | Good Friday | Apr 11 | Shahadat HZT Ali (R.A.) | Apr 14 | Dr. B.R. Ambedkar's Birthday | Apr 14 | Tamil New Year's Day/Jumuatulwada (General holiday in the view of Dr. B.R. Ambedkar's Birthday) | Apr 18 | Shab-E-Qader | Apr 22 | Eid-Ul-Fitr (Ramzan) | Apr 23 | Following day of Ramzan | Apr 23 | Basava Jayanthi (General Holiday in view of the following day of Ramzan)

Table 5:
May 05 | Buddha Purnima

--- SCRIPT INSPECTION ---
Number of scripts: 46

Relevant script 1:
{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://www.telangana.gov.in/downloads/calendar-2023/","url":"https://www.telangana.gov.in/downloads/calendar-2023/","name":"Calendar 2023 - Telangana State Portal","isPartOf":{"@id":"https://www.telangana.gov.in/#website"},"datePublished":"2024-01-03T08:25:43+00:00","dateModified":"2026-07-01T17:53:07+00:00","description":"Explore Calendar 2023 on Telangana State Portal – official info and services for citizens by Telangana government.","breadcrumb":{"@id":"https://www.telangana.gov.in/downloads/calendar-2023/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://www.telangana.gov.in/downloads/calendar-2023/"]}]},{"@type":"BreadcrumbList","@id":"https://www.telangana.gov.in/downloads/calendar-2023/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.telangana.gov.in/"},{"@type":"ListItem","position":2,"name":"Downloads","item":"https://www.telangana.gov.in/downloads/"},{"@type":"ListItem","position":3,"name":"Calendar 2023"}]},{"@type":"WebSite","@id":"https://www.telangana.gov.in/#website","url":"https://www.telangana.gov.in/","name":"Telangana State Portal","description":"Government of Telangana","potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.telangana.gov.in/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"}]}

In [32]:
import requests
from bs4 import BeautifulSoup

url = "https://www.telangana.gov.in/Downloads/calendar-2023/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

# Print table contents to understand how dates and holidays are organized
tables = soup.find_all("table")

print("Total HTML tables:", len(tables))

for table_index, table in enumerate(tables, start=1):
    table_text = table.get_text(" ", strip=True)

    # Display tables containing holiday-related terms
    if any(
        word in table_text.lower()
        for word in ["new year", "republic day", "sankranti", "holiday"]
    ):
        print(f"\n{'=' * 60}")
        print(f"TABLE {table_index}")
        print(table_text[:4000])

        # Inspect rows and cells
        for row in table.find_all("tr")[:15]:
            cells = row.find_all(["th", "td"])
            values = [
                cell.get_text(" ", strip=True)
                for cell in cells
            ]

            if values:
                print(values)

Total HTML tables: 12

============================================================
TABLE 1
Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti/Pongal Jan 16 Kanumu Jan 26 Republic Day Jan 26 Sri Panchami (General Holiday in view of Republic Day)
['Jan 01', 'New Year Day']
['Jan 14', 'Bhogi']
['Jan 15', 'Sankranti/Pongal']
['Jan 16', 'Kanumu']
['Jan 26', 'Republic Day']
['Jan 26', 'Sri Panchami (General Holiday in view of Republic Day)']

============================================================
TABLE 4
Apr 04 Mahaveer Jayanthi Apr 05 Babu Jagjivan Ram's Birthday Apr 07 Good Friday Apr 11 Shahadat HZT Ali (R.A.) Apr 14 Dr. B.R. Ambedkar's Birthday Apr 14 Tamil New Year's Day/Jumuatulwada (General holiday in the view of Dr. B.R. Ambedkar's Birthday) Apr 18 Shab-E-Qader Apr 22 Eid-Ul-Fitr (Ramzan) Apr 23 Following day of Ramzan Apr 23 Basava Jayanthi (General Holiday in view of the following day of Ramzan)
['Apr 04', 'Mahaveer Jayanthi']
['Apr 05', "Babu Jagjivan Ram's Birthday"]
['Apr 07', 'Good Friday']
['Apr 11', 'Shahadat HZT Ali (R.A.)']
['Apr 14', "Dr. B.R. Ambedkar's Birthday"]
['Apr 14', "Tamil New Year's Day/Jumuatulwada (General holiday in the view of Dr. B.R. Ambedkar's Birthday)"]
['Apr 18', 'Shab-E-Qader']
['Apr 22', 'Eid-Ul-Fitr (Ramzan)']
['Apr 23', 'Following day of Ramzan']
['Apr 23', 'Basava Jayanthi (General Holiday in view of the following day of Ramzan)']

============================================================
TABLE 8
Aug 15 Independence Day Aug 16 Parsi New Year's Day Aug 25 Varalakshmi Vratham Aug 31 Sravana Purnima/Rakhi Purnima
['Aug 15', 'Independence Day']
['Aug 16', "Parsi New Year's Day"]
['Aug 25', 'Varalakshmi Vratham']
['Aug 31', 'Sravana Purnima/Rakhi Purnima']

In [33]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup

SOURCES = {
    2023: "https://www.telangana.gov.in/Downloads/calendar-2023/",
    2024: "https://www.telangana.gov.in/downloads/calendar/",
    2025: "https://www.telangana.gov.in/downloads/calendar-2025/",
    2026: "https://www.telangana.gov.in/downloads/calendar-2026/",
}

MONTHS = {
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4,
    "May": 5, "Jun": 6, "Jul": 7, "Aug": 8,
    "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12
}

DATE_PATTERN = re.compile(
    r"^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)"
    r"\s+(\d{1,2})$",
    re.IGNORECASE
)

headers = {"User-Agent": "Mozilla/5.0"}
all_records = []

for year, url in SOURCES.items():
    print(f"\n{'=' * 60}")
    print(f"YEAR: {year}")

    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, "html.parser")
    year_records = []

    for table_index, table in enumerate(soup.find_all("table"), start=1):
        for row in table.find_all("tr"):
            cells = row.find_all(["th", "td"], recursive=False)

            if len(cells) < 2:
                continue

            date_text = cells[0].get_text(" ", strip=True)
            holiday_name = cells[1].get_text(" ", strip=True)

            match = DATE_PATTERN.match(date_text)

            if not match or not holiday_name:
                continue

            month_text, day_text = match.groups()
            month_number = MONTHS[month_text.title()]
            day_number = int(day_text)

            try:
                holiday_date = pd.Timestamp(
                    year=year,
                    month=month_number,
                    day=day_number
                )
            except ValueError:
                print("Invalid date encountered:", date_text, year)
                continue

            record = {
                "date": holiday_date.date().isoformat(),
                "year": year,
                "holiday_name": holiday_name,
                "source_url": url,
                "source_table_index": table_index
            }

            year_records.append(record)

    print("Extracted rows:", len(year_records))

    for record in year_records[:10]:
        print(record["date"], "|", record["holiday_name"])

    if not year_records:
        print("WARNING: No records extracted. Further inspection required.")

    all_records.extend(year_records)

holidays_diagnostic_df = pd.DataFrame(all_records)

print("\n" + "=" * 60)
print("COMBINED DIAGNOSTIC SUMMARY")
print("Total extracted rows:", len(holidays_diagnostic_df))

if not holidays_diagnostic_df.empty:
    print("\nRows by year:")
    print(
        holidays_diagnostic_df.groupby("year")
        .size()
        .reindex(SOURCES.keys(), fill_value=0)
    )

    print("\nDuplicate date-and-name combinations:")
    print(
        holidays_diagnostic_df.duplicated(
            subset=["date", "holiday_name"]
        ).sum()
    )

    print("\nExtracted date range:")
    print(
        holidays_diagnostic_df["date"].min(),
        "to",
        holidays_diagnostic_df["date"].max()
    )

============================================================
YEAR: 2023
Extracted rows: 52
2023-01-01 | New Year Day
2023-01-14 | Bhogi
2023-01-15 | Sankranti/Pongal
2023-01-16 | Kanumu
2023-01-26 | Republic Day
2023-01-26 | Sri Panchami (General Holiday in view of Republic Day)
2023-02-05 | Birthday of Hazrath Ali (R.A.)
2023-02-18 | Maha Shivaratri
2023-02-19 | Shab-E-Meraj
2023-03-07 | Holi

============================================================
YEAR: 2024
Extracted rows: 52
2024-01-01 | New Year Day
2024-01-14 | Bhogi
2024-01-15 | Sankranti / Pongal
2024-01-16 | Kanumu
2024-01-25 | Birthday of Hazrath Ali (R.A.)
2024-01-26 | Republic Day
2024-02-08 | Shab-e-Meraj
2024-02-14 | Sri Panchami
2024-02-26 | Shab-e-Barat
2024-03-08 | Maha Shivaratri

============================================================
YEAR: 2025
Extracted rows: 49
2025-01-01 | New Year Day
2025-01-13 | Bhogi
2025-01-14 | Sankranti / Pongal
2025-01-14 | Birthday of Hazrath Ali
2025-01-15 | Kanumu
2025-01-28 | Shab-e-Meraj
2025-02-03 | Sri Panchami
2025-02-14 | Shab-e-Barat
2025-02-26 | Mahashivarathri
2025-03-14 | Holi

============================================================
YEAR: 2026
Extracted rows: 52
2026-01-01 | New Year
2026-01-03 | Birthday of Hazrath Ali
2026-01-14 | Bhogi
2026-01-15 | Sankranti / Pongal
2026-01-16 | Kanumu
2026-01-17 | Shab-e-Meraj
2026-01-23 | Sri Panchami
2026-02-04 | Shab-e-Barat
2026-02-15 | Mahashivarathri
2026-03-03 | Holi

============================================================
COMBINED DIAGNOSTIC SUMMARY
Total extracted rows: 205

Rows by year:
year
2023    52
2024    52
2025    49
2026    52
dtype: int64

Duplicate date-and-name combinations:
0

Extracted date range:
2023-01-01 to 2026-12-26

In [34]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

SOURCES = {
    2023: "https://www.telangana.gov.in/Downloads/calendar-2023/",
    2024: "https://www.telangana.gov.in/downloads/calendar/",
    2025: "https://www.telangana.gov.in/downloads/calendar-2025/",
    2026: "https://www.telangana.gov.in/downloads/calendar-2026/",
}

headers = {"User-Agent": "Mozilla/5.0"}

table_summary = []

for year, url in SOURCES.items():
    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, "html.parser")

    print(f"\n{'=' * 70}")
    print(f"YEAR: {year}")

    for table_index, table in enumerate(soup.find_all("table"), start=1):
        rows = []

        for row in table.find_all("tr"):
            cells = row.find_all(["th", "td"], recursive=False)
            values = [
                cell.get_text(" ", strip=True)
                for cell in cells
            ]

            if values:
                rows.append(values)

        if not rows:
            continue

        # Display a sample of each table to identify its purpose.
        sample = [
            " | ".join(row)
            for row in rows[:3]
        ]

        print(f"\nTable {table_index} | Rows: {len(rows)}")

        for item in sample:
            print(" ", item[:250])

        table_summary.append({
            "year": year,
            "table_index": table_index,
            "row_count": len(rows),
            "sample_rows": " || ".join(sample)
        })

table_summary_df = pd.DataFrame(table_summary)

print("\n\nTABLE SUMMARY")
display(table_summary_df)

======================================================================
YEAR: 2023

Table 1 | Rows: 6
  Jan 01 | New Year Day
  Jan 14 | Bhogi
  Jan 15 | Sankranti/Pongal

Table 2 | Rows: 3
  Feb 05 | Birthday of Hazrath Ali (R.A.)
  Feb 18 | Maha Shivaratri
  Feb 19 | Shab-E-Meraj

Table 3 | Rows: 4
  Mar 07 | Holi
  Mar 08 | Shab-E-Barat
  Mar 22 | Ugadi

Table 4 | Rows: 10
  Apr 04 | Mahaveer Jayanthi
  Apr 05 | Babu Jagjivan Ram's Birthday
  Apr 07 | Good Friday

Table 5 | Rows: 1
  May 05 | Buddha Purnima

Table 6 | Rows: 2
  Jun 20 | Ratha Yathra
  Jun 29 | Eidul Azha (Bakrid)

Table 7 | Rows: 4
  Jul 07 | Eid-E-Ghadeer
  Jul 17 | Bonalu
  Jul 28 | 9th Moharram (1445H)

Table 8 | Rows: 4
  Aug 15 | Independence Day
  Aug 16 | Parsi New Year's Day
  Aug 25 | Varalakshmi Vratham

Table 9 | Rows: 4
  Sep 06 | Arbayeen
  Sep 07 | Sri Krishna Astami (as per Srivaishnava Agamam)
  Sep 18 | Vinayaka Chavithi

Table 10 | Rows: 7
  Oct 02 | Mahatma Gandhi Jayanthi
  Oct 14 | Bathukamma Starting Day
  Oct 22 | Durgashtami

Table 11 | Rows: 4
  Nov 11 | Naraka Chaturdhi
  Nov 12 | Deepavali
  Nov 27 | Karthika Purnima / Guru Nanak's Birthday

Table 12 | Rows: 3
  Dec 24 | Christmas Eve
  Dec 25 | Christmas
  Dec 26 | Boxing Day​​​

======================================================================
YEAR: 2024

Table 1 | Rows: 6
  Jan 01 | New Year Day
  Jan 14 | Bhogi
  Jan 15 | Sankranti / Pongal

Table 2 | Rows: 3
  Feb 08 | Shab-e-Meraj
  Feb 14 | Sri Panchami
  Feb 26 | Shab-e-Barat

Table 3 | Rows: 4
  Mar 08 | Maha Shivaratri
  Mar 25 | Holi
  Mar 29 | Good Friday

Table 4 | Rows: 10
  Apr 05 | Babu Jagjivan Ram's Birthday
  Apr 05 | Jumu'atul Wida (General holiday in the view of Babu Jagjivan Ram's Birthday)
  Apr 07 | Shab-E-Qader

Table 5 | Rows: 2
  May 10 | Basava Jayanthi
  May 23 | Buddha Purnima

Table 6 | Rows: 2
  Jun 17 | Eidul Azha (Bakrid)
  Jun 25 | Eid-e-Ghadeer

Table 7 | Rows: 4
  Jul 07 | Ratha Yathra
  Jul 16 | 9th Moharram (1445H)
  Jul 17 | Shahadat Imam Hussain (R.A) 10th Moharam

Table 8 | Rows: 6
  Aug 15 | Independence Day
  Aug 15 | Parsi New Year's Day (General Holiday in view of Independence Day)
  Aug 16 | Varalakshmi Vratham

Table 9 | Rows: 2
  Sep 07 | Vinayaka Chavithi
  Sep 16 | Eid  Miladun Nabi

Table 10 | Rows: 8
  Oct 02 | Mahatma Gandhi Jayanthi
  Oct 10 | Durgashtami
  Oct 11 | Maharnavami

Table 11 | Rows: 2
  Nov 15 | Karthika Purnima / Guru Nanak's Birthday
  Nov 16 | Birthday of HZT. Syed Mohammed Juvanpuri Mahdi MA'UD (A.S.)

Table 12 | Rows: 3
  Dec 24 | Christmas Eve
  Dec 25 | Christmas
  Dec 26 | Following day of Christmas (Boxing Day)

======================================================================
YEAR: 2025

Table 1 | Rows: 6
  Jan 01 | New Year Day
  Jan 13 | Bhogi
  Jan 14 | Sankranti / Pongal

Table 2 | Rows: 3
  Feb 03 | Sri Panchami
  Feb 14 | Shab-e-Barat
  Feb 26 | Mahashivarathri

Table 3 | Rows: 5
  Mar 14 | Holi
  Mar 21 | Shahadat HZT Ali (R.A.)
  Mar 28 | Jumatul-Vida,Shab-e-Qader

Table 4 | Rows: 7
  Apr 01 | Following day of Ramzan
  Apr 05 | Babu Jagjivan Ram's Birthday
  Apr 10 | Mahaveer Jayanthi

Table 5 | Rows: 1
  May 12 | Buddha Purnima

Table 6 | Rows: 3
  Jun 07 | Eidul Azha (Bakrid)
  Jun 15 | Eid-e-Ghadeer
  Jun 15 | Ratha Yathra

Table 7 | Rows: 3
  Jul 05 | 9th Moharram (1445H)
  Jul 06 | Moharam
  Jul 21 | Bonalu

Table 8 | Rows: 6
  Aug 08 | Varalakshmi Vratham
  Aug 09 | Sravana Purnima / Rakhi Purnima
  Aug 15 | Independence Day

Table 9 | Rows: 3
  Sep 05 | Eid  Miladun Nabi
  Sep 21 | Bathukamma Starting Day
  Sep 30 | Durgashtami

Table 10 | Rows: 7
  Oct 01 | Maharnavami
  Oct 02 | Mahatma Gandhi Jayanthi
  Oct 02 | Vijaya Dasami

Table 11 | Rows: 2
  Nov 05 | Karthika Purnima / Guru Nanak's Birthday
  Nov 16 | Birthday of HZT. Syed Mohammed Juvanpuri Mahdi MA'UD (A.S.)

Table 12 | Rows: 3
  Dec 24 | Christmas Eve
  Dec 25 | Christmas
  Dec 26 | Following day of Christmas (Boxing Day)

======================================================================
YEAR: 2026

Table 1 | Rows: 7
  Jan 01 | New Year
  Jan 03 | Birthday of Hazrath Ali
  Jan 14 | Bhogi

Table 2 | Rows: 2
  Feb 04 | Shab-e-Barat
  Feb 15 | Mahashivarathri

Table 3 | Rows: 9
  Mar 03 | Holi
  Mar 10 | Shahadat HZT Ali (R.A.)
  Mar 13 | Jumatul-Vida

Table 4 | Rows: 5
  Apr 03 | Good Friday
  Apr 05 | Babu Jagjivan Ram's Birthday
  Apr 14 | Dr. B.R. Ambedkar's Birthday

Table 5 | Rows: 2
  May 01 | Buddha Purnima
  May 27 | Eidul Azha (Bakrid)

Table 6 | Rows: 3
  Jun 04 | Eid-e-Ghadeer
  Jun 25 | 9th Moharram
  Jun 26 | Moharram

Table 7 | Rows: 1
  Jul 16 | Ratha Yathra

Table 8 | Rows: 7
  Aug 04 | Arbayeen
  Aug 10 | Bonalu
  Aug 15 | Independence Day

Table 9 | Rows: 3
  Sep 04 | Sri Krishnashtami
  Sep 14 | Vinayaka Chavithi
  Sep 23 | Yazdahum Shareef

Table 10 | Rows: 6
  Oct 02 | Mahatma Gandhi Jayanthi
  Oct 18 | Saddula Bathukamma
  Oct 19 | Maharnavami

Table 11 | Rows: 3
  Nov 08 | Naraka Chathurdhi
  Nov 08 | Deepavali
  Nov 24 | Karthika Pournami

Table 12 | Rows: 4
  Dec 24 | Christmas Eve
  Dec 25 | Christmas
  Dec 26 | Boxing Day


TABLE SUMMARY

,year,table_index,row_count,sample_rows
0,2023,1,6,Jan 01 | New Year Day || Jan 14 | Bhogi || Jan...
1,2023,2,3,Feb 05 | Birthday of Hazrath Ali (R.A.) || Feb...
2,2023,3,4,Mar 07 | Holi || Mar 08 | Shab-E-Barat || Mar ...
3,2023,4,10,Apr 04 | Mahaveer Jayanthi || Apr 05 | Babu Ja...
4,2023,5,1,May 05 | Buddha Purnima
5,2023,6,2,Jun 20 | Ratha Yathra || Jun 29 | Eidul Azha (...
6,2023,7,4,Jul 07 | Eid-E-Ghadeer || Jul 17 | Bonalu || J...
7,2023,8,4,Aug 15 | Independence Day || Aug 16 | Parsi Ne...
8,2023,9,4,Sep 06 | Arbayeen || Sep 07 | Sri Krishna Asta...
9,2023,10,7,Oct 02 | Mahatma Gandhi Jayanthi || Oct 14 | B...
10,2023,11,4,Nov 11 | Naraka Chaturdhi || Nov 12 | Deepaval...
11,2023,12,3,Dec 24 | Christmas Eve || Dec 25 | Christmas |...
12,2024,1,6,Jan 01 | New Year Day || Jan 14 | Bhogi || Jan...
13,2024,2,3,Feb 08 | Shab-e-Meraj || Feb 14 | Sri Panchami...
14,2024,3,4,Mar 08 | Maha Shivaratri || Mar 25 | Holi || M...
15,2024,4,10,Apr 05 | Babu Jagjivan Ram's Birthday || Apr 0...
16,2024,5,2,May 10 | Basava Jayanthi || May 23 | Buddha Pu...
17,2024,6,2,Jun 17 | Eidul Azha (Bakrid) || Jun 25 | Eid-e...
18,2024,7,4,Jul 07 | Ratha Yathra || Jul 16 | 9th Moharram...
19,2024,8,6,Aug 15 | Independence Day || Aug 15 | Parsi Ne...
20,2024,9,2,Sep 07 | Vinayaka Chavithi || Sep 16 | Eid Mi...
21,2024,10,8,Oct 02 | Mahatma Gandhi Jayanthi || Oct 10 | D...
22,2024,11,2,Nov 15 | Karthika Purnima / Guru Nanak's Birth...
23,2024,12,3,Dec 24 | Christmas Eve || Dec 25 | Christmas |...
24,2025,1,6,Jan 01 | New Year Day || Jan 13 | Bhogi || Jan...
25,2025,2,3,Feb 03 | Sri Panchami || Feb 14 | Shab-e-Barat...
26,2025,3,5,Mar 14 | Holi || Mar 21 | Shahadat HZT Ali (R....
27,2025,4,7,Apr 01 | Following day of Ramzan || Apr 05 | B...
28,2025,5,1,May 12 | Buddha Purnima
29,2025,6,3,Jun 07 | Eidul Azha (Bakrid) || Jun 15 | Eid-e...
30,2025,7,3,Jul 05 | 9th Moharram (1445H) || Jul 06 | Moha...
31,2025,8,6,Aug 08 | Varalakshmi Vratham || Aug 09 | Srava...
32,2025,9,3,Sep 05 | Eid Miladun Nabi || Sep 21 | Bathuka...
33,2025,10,7,Oct 01 | Maharnavami || Oct 02 | Mahatma Gandh...
34,2025,11,2,Nov 05 | Karthika Purnima / Guru Nanak's Birth...
35,2025,12,3,Dec 24 | Christmas Eve || Dec 25 | Christmas |...
36,2026,1,7,Jan 01 | New Year || Jan 03 | Birthday of Hazr...
37,2026,2,2,Feb 04 | Shab-e-Barat || Feb 15 | Mahashivarathri
38,2026,3,9,Mar 03 | Holi || Mar 10 | Shahadat HZT Ali (R....
39,2026,4,5,Apr 03 | Good Friday || Apr 05 | Babu Jagjivan...
40,2026,5,2,May 01 | Buddha Purnima || May 27 | Eidul Azha...
41,2026,6,3,Jun 04 | Eid-e-Ghadeer || Jun 25 | 9th Moharra...
42,2026,7,1,Jul 16 | Ratha Yathra
43,2026,8,7,Aug 04 | Arbayeen || Aug 10 | Bonalu || Aug 15...
44,2026,9,3,Sep 04 | Sri Krishnashtami || Sep 14 | Vinayak...
45,2026,10,6,Oct 02 | Mahatma Gandhi Jayanthi || Oct 18 | S...
46,2026,11,3,Nov 08 | Naraka Chathurdhi || Nov 08 | Deepava...
47,2026,12,4,Dec 24 | Christmas Eve || Dec 25 | Christmas |...

In [35]:
import requests
from bs4 import BeautifulSoup

SOURCES = {
    2023: "https://www.telangana.gov.in/Downloads/calendar-2023/",
    2024: "https://www.telangana.gov.in/downloads/calendar/",
    2025: "https://www.telangana.gov.in/downloads/calendar-2025/",
    2026: "https://www.telangana.gov.in/downloads/calendar-2026/",
}

headers = {"User-Agent": "Mozilla/5.0"}

for year, url in SOURCES.items():
    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, "html.parser")

    print(f"\n{'=' * 70}")
    print(f"YEAR: {year}")

    # Find headings and elements that identify holiday categories.
    for element in soup.find_all(
        ["h1", "h2", "h3", "h4", "h5", "h6"]
    ):
        text = element.get_text(" ", strip=True)

        if any(
            keyword in text.lower()
            for keyword in [
                "holiday",
                "calendar",
                "general",
                "optional"
            ]
        ):
            print(f"HEADING: {text}")

    # Search the full page for classification labels.
    page_text = soup.get_text(" ", strip=True)

    for keyword in [
        "General Holidays",
        "Optional Holidays",
        "List of Holidays"
    ]:
        position = page_text.lower().find(keyword.lower())

        if position != -1:
            start = max(0, position - 150)
            end = min(len(page_text), position + 500)

            print(f"\nCONTEXT FOR '{keyword}':")
            print(page_text[start:end])

======================================================================
YEAR: 2023
HEADING: Calendar 2023
HEADING: List of Holidays - 2023

CONTEXT FOR 'General Holidays':
lendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2023 General Holidays Optio​nal Holidays January 2023​ Sun Mon Tue W​ed Thu Fri Sat 1 2​ 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti/Pongal Jan 16 Kanumu Jan 26 Republic Day Jan 26 Sri Panchami (General Holiday in view of Republic Day) February 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 05 Birthday of Hazrath Ali (R.A.) Feb 18 Maha Shivaratri

CONTEXT FOR 'List of Holidays':
icies Calendar - 2026 Calendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2023 General Holidays Optio​nal Holidays January 2023​ Sun Mon Tue W​ed Thu Fri Sat 1 2​ 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti/Pongal Jan 16 Kanumu Jan 26 Republic Day Jan 26 Sri Panchami (General Holiday in view of Republic Day) February 2023 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 05 Birthday of Hazrath Ali (R.A.

======================================================================
YEAR: 2024
HEADING: Calendar
HEADING: List of Holidays - 2024

CONTEXT FOR 'General Holidays':
lendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2024 General Holidays Optio​nal Holidays January 2024 Sun Mon Tue Wed Thu Fri Sat * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti / Pongal Jan 16 Kanumu Jan 25 Birthday of Hazrath Ali (R.A.) Jan 26 Republic Day February 2024 Sun Mon Tue Wed Thu Fri Sat * * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 Feb 08 Shab-e-Meraj Feb 14 Sri Panchami Feb 26 Shab-e-Barat March 2024 Sun Mon

CONTEXT FOR 'List of Holidays':
icies Calendar - 2026 Calendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2024 General Holidays Optio​nal Holidays January 2024 Sun Mon Tue Wed Thu Fri Sat * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 Jan 01 New Year Day Jan 14 Bhogi Jan 15 Sankranti / Pongal Jan 16 Kanumu Jan 25 Birthday of Hazrath Ali (R.A.) Jan 26 Republic Day February 2024 Sun Mon Tue Wed Thu Fri Sat * * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 Feb 08 Shab-e-Meraj Feb 14 Sri Panchami Feb 26 Shab-e-

======================================================================
YEAR: 2025
HEADING: Calendar
HEADING: List of Holidays - 2025

CONTEXT FOR 'General Holidays':
lendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2025 General Holidays Optio​nal Holidays January 2025 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 * Jan 01 New Year Day Jan 13 Bhogi Jan 14 Sankranti / Pongal Jan 14 Birthday of Hazrath Ali Jan 15 Kanumu Jan 26 Republic Day Jan 28 Shab-e-Meraj February 2025 Sun Mon Tue Wed Thu Fri Sat * * * * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 03 Sri Panchami Feb 14 Shab-e-Barat Feb 26 Mahashivara

CONTEXT FOR 'List of Holidays':
icies Calendar - 2026 Calendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2025 General Holidays Optio​nal Holidays January 2025 Sun Mon Tue Wed Thu Fri Sat * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 * Jan 01 New Year Day Jan 13 Bhogi Jan 14 Sankranti / Pongal Jan 14 Birthday of Hazrath Ali Jan 15 Kanumu Jan 26 Republic Day Jan 28 Shab-e-Meraj February 2025 Sun Mon Tue Wed Thu Fri Sat * * * * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 Feb 03 Sri Panchami Feb 14 Shab-e-

======================================================================
YEAR: 2026
HEADING: Calendar 2026
HEADING: List of Holidays - 2026

CONTEXT FOR 'General Holidays':
lendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2026 General Holidays Optio​nal Holidays January 2026 Sun Mon Tue Wed Thu Fri Sat * * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 * Jan 01 New Year Jan 03 Birthday of Hazrath Ali Jan 14 Bhogi Jan 15 Sankranti / Pongal Jan 16 Kanumu Jan 17 Shab-e-Meraj Jan 23 Sri Panchami Jan 26 Republic Day February 2026 Sun Mon Tue Wed Thu Fri Sat 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 * * * * * * * Feb 04 Shab-e-Barat Feb 15 Mahashivara

CONTEXT FOR 'List of Holidays':
icies Calendar - 2026 Calendar - 2025 Calendar - 2024 Calendar - 2023 Calendar - 2022 Calendar - 2021 Calendar - 2020 Calendar - 2019 Calendar - 2018 List of Holidays - 2026 General Holidays Optio​nal Holidays January 2026 Sun Mon Tue Wed Thu Fri Sat * * * * 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 * Jan 01 New Year Jan 03 Birthday of Hazrath Ali Jan 14 Bhogi Jan 15 Sankranti / Pongal Jan 16 Kanumu Jan 17 Shab-e-Meraj Jan 23 Sri Panchami Jan 26 Republic Day February 2026 Sun Mon Tue Wed Thu Fri Sat 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 * * * * * * * Feb 04 Shab-e-

In [36]:
import requests
from bs4 import BeautifulSoup

url = "https://www.telangana.gov.in/Downloads/calendar-2023/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

for keyword in ["General Holidays", "Optional Holidays"]:
    print(f"\n{'=' * 60}")
    print("SEARCHING FOR:", keyword)

    matches = soup.find_all(
        string=lambda text: text and keyword.lower() in text.lower()
    )

    print("Matching text nodes:", len(matches))

    for index, node in enumerate(matches[:10], start=1):
        print(f"\nMatch {index}:")
        print("Text:", repr(str(node).strip()))
        print("Parent tag:", node.parent.name)
        print("Parent classes:", node.parent.get("class"))
        print("Parent HTML:")
        print(node.parent.prettify()[:1200])

        # Inspect nearby ancestors to identify the relevant section.
        ancestor = node.parent

        for level in range(1, 4):
            if ancestor.parent is None:
                break

            ancestor = ancestor.parent

            print(f"\nAncestor level {level}:")
            print("Tag:", ancestor.name)
            print("Classes:", ancestor.get("class"))
            print(
                "Text preview:",
                ancestor.get_text(" ", strip=True)[:500]
            )

============================================================
SEARCHING FOR: General Holidays
Matching text nodes: 1

Match 1:
Text: 'General Holidays'
Parent tag: span
Parent classes: None
Parent HTML:
<span style="color:#1d7845; font-weight: bold; font-size: 14px;">
 General Holidays
</span>


Ancestor level 1:
Tag: div
Classes: ['elementor-widget-container']
Text preview: List of Holidays - 2023 General Holidays Optio​nal Holidays

Ancestor level 2:
Tag: div
Classes: ['elementor-element', 'elementor-element-93c872f', 'elementor-widget', 'elementor-widget-html']
Text preview: List of Holidays - 2023 General Holidays Optio​nal Holidays

Ancestor level 3:
Tag: div
Classes: ['e-con-inner']
Text preview: List of Holidays - 2023 General Holidays Optio​nal Holidays

============================================================
SEARCHING FOR: Optional Holidays
Matching text nodes: 0

In [37]:
import requests
from bs4 import BeautifulSoup

url = "https://www.telangana.gov.in/Downloads/calendar-2023/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

# Locate the widget containing the "General Holidays" label.
general_label = soup.find(
    string=lambda text: text and text.strip() == "General Holidays"
)

if general_label is None:
    print("General Holidays label not found.")
else:
    widget = general_label.find_parent(
        class_="elementor-widget-container"
    )

    if widget is None:
        print("Containing widget not found.")
    else:
        print("WIDGET HTML:")
        print(widget.prettify()[:12000])

        print("\nLINKS INSIDE WIDGET:")
        links = widget.find_all("a", href=True)

        if not links:
            print("No links found in this widget.")

        for link in links:
            print({
                "text": link.get_text(" ", strip=True),
                "href": link["href"]
            })

        print("\nTABLES INSIDE WIDGET:", len(widget.find_all("table")))

WIDGET HTML:
<div class="elementor-widget-container">
 <h2>
  List of Holidays - 2023
 </h2>
 <span style="padding: 5px 16px; border-radius: 3px; background-color: #1d7845;">
 </span>
 <span style="color:#1d7845; font-weight: bold; font-size: 14px;">
  General Holidays
 </span>
 <span style="background-color: #c08e4b; border-radius: 3px; padding: 5px 16px;">
 </span>
 <span style="color: #c08e4b; font-weight: bold; font-size: 14px;">
  Optio​nal Holidays
 </span>
</div>


LINKS INSIDE WIDGET:
No links found in this widget.

TABLES INSIDE WIDGET: 0

In [38]:
import requests
from bs4 import BeautifulSoup
from collections import Counter

url = "https://www.telangana.gov.in/Downloads/calendar-2023/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

# Inspect elements using the two colors shown in the category legend.
colors = {
    "general_green": "#1d7845",
    "optional_amber": "#c08e4b",
}

for category, color in colors.items():
    print(f"\n{'=' * 60}")
    print("CATEGORY COLOR:", category, color)

    elements = soup.find_all(
        style=lambda style: style and color in style.lower()
    )

    print("Matching elements:", len(elements))

    for element in elements[:15]:
        print({
            "tag": element.name,
            "style": element.get("style"),
            "text": element.get_text(" ", strip=True)[:180],
            "classes": element.get("class"),
        })

# Inspect classes used by the monthly calendar cells.
print("\n--- CALENDAR CELL STRUCTURE ---")

for table_index, table in enumerate(soup.find_all("table"), start=1):
    rows = table.find_all("tr")

    if not rows:
        continue

    print(f"\nTable {table_index}")

    for row in rows[:3]:
        cells = row.find_all(["th", "td"])

        for cell in cells[:4]:
            print({
                "tag": cell.name,
                "class": cell.get("class"),
                "style": cell.get("style"),
                "text": cell.get_text(" ", strip=True)[:100],
                "html": str(cell)[:250],
            })

============================================================
CATEGORY COLOR: general_green #1d7845
Matching elements: 2
{'tag': 'span', 'style': 'padding: 5px 16px; border-radius: 3px; background-color: #1d7845;', 'text': '', 'classes': None}
{'tag': 'span', 'style': 'color:#1d7845; font-weight: bold; font-size: 14px;', 'text': 'General Holidays', 'classes': None}

============================================================
CATEGORY COLOR: optional_amber #c08e4b
Matching elements: 2
{'tag': 'span', 'style': 'background-color: #c08e4b; border-radius: 3px; padding: 5px 16px;', 'text': '', 'classes': None}
{'tag': 'span', 'style': 'color: #c08e4b; font-weight: bold; font-size: 14px;', 'text': 'Optio\u200bnal Holidays', 'classes': None}

--- CALENDAR CELL STRUCTURE ---

Table 1
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Jan 01', 'html': '<th class="fix" nowrap="nowrap">Jan 01 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'New Year Day', 'html': '<td>New Year Day</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Jan 14', 'html': '<th class="fix" nowrap="nowrap">Jan 14 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Bhogi', 'html': '<td>Bhogi</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Jan 15', 'html': '<th class="fix" nowrap="nowrap">Jan 15 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Sankranti/Pongal', 'html': '<td>Sankranti/Pongal</td>'}

Table 2
{'tag': 'th', 'class': ['opt'], 'style': 'width: 10%;', 'text': 'Feb 05', 'html': '<th class="opt" style="width: 10%;">Feb 05 </th>'}
{'tag': 'td', 'class': None, 'style': 'width: 90%;', 'text': 'Birthday of Hazrath Ali (R.A.)', 'html': '<td style="width: 90%;">Birthday of Hazrath Ali (R.A.)</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Feb 18', 'html': '<th class="fix">Feb 18 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Maha Shivaratri', 'html': '<td>Maha Shivaratri</td>'}
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Feb 19', 'html': '<th class="opt">Feb 19 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Shab-E-Meraj', 'html': '<td>Shab-E-Meraj  </td>'}

Table 3
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Mar 07', 'html': '<th class="fix">Mar 07 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Holi', 'html': '<td>Holi</td>'}
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Mar 08', 'html': '<th class="opt">Mar 08 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Shab-E-Barat', 'html': '<td>Shab-E-Barat</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Mar 22', 'html': '<th class="fix">Mar 22 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Ugadi', 'html': '<td>Ugadi</td>'}

Table 4
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Apr 04', 'html': '<th class="opt">Apr 04 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Mahaveer Jayanthi', 'html': '<td> Mahaveer Jayanthi</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Apr 05', 'html': '<th class="fix">Apr 05 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': "Babu Jagjivan Ram's Birthday", 'html': "<td>Babu Jagjivan Ram's Birthday</td>"}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Apr 07', 'html': '<th class="fix">Apr 07 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Good Friday', 'html': '<td>Good Friday</td>'}

Table 5
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'May 05', 'html': '<th class="opt">May 05 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Buddha Purnima', 'html': '<td>Buddha Purnima</td>'}

Table 6
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Jun 20', 'html': '<th class="opt">Jun 20 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Ratha Yathra', 'html': '<td>Ratha Yathra</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Jun 29', 'html': '<th class="fix">Jun 29 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Eidul Azha (Bakrid)', 'html': '<td>Eidul Azha (Bakrid)</td>'}

Table 7
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Jul 07', 'html': '<th class="opt">Jul 07 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Eid-E-Ghadeer', 'html': '<td>Eid-E-Ghadeer</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Jul 17', 'html': '<th class="fix">Jul 17 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Bonalu', 'html': '<td> Bonalu </td>'}
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Jul 28', 'html': '<th class="opt">Jul 28 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': '9th Moharram (1445H)', 'html': '<td>9th Moharram (1445H)</td>'}

Table 8
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Aug 15', 'html': '<th class="fix">Aug 15 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Independence Day', 'html': '<td>Independence Day</td>'}
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Aug 16', 'html': '<th class="opt">Aug 16 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': "Parsi New Year's Day", 'html': "<td>Parsi New Year's Day</td>"}
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Aug 25', 'html': '<th class="opt">Aug 25 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Varalakshmi Vratham', 'html': '<td>Varalakshmi Vratham</td>'}

Table 9
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Sep 06', 'html': '<th class="opt">Sep 06 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Arbayeen', 'html': '<td>Arbayeen</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Sep 07', 'html': '<th class="fix">Sep 07 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Sri Krishna Astami (as per Srivaishnava Agamam)', 'html': '<td>Sri Krishna Astami (as per Srivaishnava Agamam) </td>'}

Table 10
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Oct 02', 'html': '<th class="fix">Oct 02 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Mahatma Gandhi Jayanthi', 'html': '<td>Mahatma Gandhi Jayanthi</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Oct 14', 'html': '<th class="fix">Oct 14 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Bathukamma Starting Day', 'html': '<td>Bathukamma Starting Day</td>'}
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Oct 22', 'html': '<th class="opt">Oct 22 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Durgashtami', 'html': '<td>Durgashtami</td>'}

Table 11
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Nov 11', 'html': '<th class="opt">Nov 11 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Naraka Chaturdhi', 'html': '<td>Naraka Chaturdhi</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Nov 12', 'html': '<th class="fix" nowrap="nowrap"> Nov 12 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Deepavali', 'html': '<td>Deepavali</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Nov 27', 'html': '<th class="fix" nowrap="nowrap"> Nov 27 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': "Karthika Purnima / Guru Nanak's Birthday", 'html': "<td>Karthika Purnima / Guru Nanak's Birthday</td>"}

Table 12
{'tag': 'th', 'class': ['opt'], 'style': None, 'text': 'Dec 24', 'html': '<th class="opt">Dec 24 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Christmas Eve', 'html': '<td>Christmas Eve</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Dec 25', 'html': '<th class="fix">Dec 25 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Christmas', 'html': '<td>Christmas</td>'}
{'tag': 'th', 'class': ['fix'], 'style': None, 'text': 'Dec 26', 'html': '<th class="fix">Dec 26 </th>'}
{'tag': 'td', 'class': None, 'style': None, 'text': 'Boxing Day\u200b\u200b\u200b', 'html': '<td>Boxing Day\u200b\u200b\u200b</td>'}

In [39]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from collections import Counter

SOURCES = {
    2023: "https://www.telangana.gov.in/Downloads/calendar-2023/",
    2024: "https://www.telangana.gov.in/downloads/calendar/",
    2025: "https://www.telangana.gov.in/downloads/calendar-2025/",
    2026: "https://www.telangana.gov.in/downloads/calendar-2026/",
}

headers = {"User-Agent": "Mozilla/5.0"}
summary = []

for year, url in SOURCES.items():
    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, "html.parser")

    print(f"\n{'=' * 65}")
    print("YEAR:", year)

    class_counts = Counter()
    samples = []

    for table_index, table in enumerate(soup.find_all("table"), start=1):
        for row in table.find_all("tr"):
            cells = row.find_all(["th", "td"], recursive=False)

            # Calendar rows contain a date cell followed by its holiday name.
            for i, cell in enumerate(cells):
                cell_text = cell.get_text(" ", strip=True)

                if not cell_text or not cell.name == "th":
                    continue

                classes = cell.get("class", [])
                if not classes:
                    continue

                class_label = ",".join(sorted(classes))
                class_counts[class_label] += 1

                if i + 1 < len(cells):
                    holiday_name = cells[i + 1].get_text(" ", strip=True)

                    if len(samples) < 12:
                        samples.append({
                            "table": table_index,
                            "date_cell": cell_text,
                            "class": class_label,
                            "holiday": holiday_name
                        })

    print("Date-cell class counts:", dict(class_counts))
    print("\nSample date/holiday pairs:")

    for sample in samples:
        print(sample)

    for class_label, count in class_counts.items():
        summary.append({
            "year": year,
            "date_cell_class": class_label,
            "count": count
        })

summary_df = pd.DataFrame(summary)

print("\n--- CLASSIFICATION SUMMARY ---")
display(summary_df)

=================================================================
YEAR: 2023
Date-cell class counts: {'fix': 28, 'opt': 24}

Sample date/holiday pairs:
{'table': 1, 'date_cell': 'Jan 01', 'class': 'fix', 'holiday': 'New Year Day'}
{'table': 1, 'date_cell': 'Jan 14', 'class': 'fix', 'holiday': 'Bhogi'}
{'table': 1, 'date_cell': 'Jan 15', 'class': 'fix', 'holiday': 'Sankranti/Pongal'}
{'table': 1, 'date_cell': 'Jan 16', 'class': 'opt', 'holiday': 'Kanumu'}
{'table': 1, 'date_cell': 'Jan 26', 'class': 'fix', 'holiday': 'Republic Day'}
{'table': 1, 'date_cell': 'Jan 26', 'class': 'opt', 'holiday': 'Sri Panchami (General Holiday in view of Republic Day)'}
{'table': 2, 'date_cell': 'Feb 05', 'class': 'opt', 'holiday': 'Birthday of Hazrath Ali (R.A.)'}
{'table': 2, 'date_cell': 'Feb 18', 'class': 'fix', 'holiday': 'Maha Shivaratri'}
{'table': 2, 'date_cell': 'Feb 19', 'class': 'opt', 'holiday': 'Shab-E-Meraj'}
{'table': 3, 'date_cell': 'Mar 07', 'class': 'fix', 'holiday': 'Holi'}
{'table': 3, 'date_cell': 'Mar 08', 'class': 'opt', 'holiday': 'Shab-E-Barat'}
{'table': 3, 'date_cell': 'Mar 22', 'class': 'fix', 'holiday': 'Ugadi'}

=================================================================
YEAR: 2024
Date-cell class counts: {'fix': 28, 'opt': 24}

Sample date/holiday pairs:
{'table': 1, 'date_cell': 'Jan 01', 'class': 'fix', 'holiday': 'New Year Day'}
{'table': 1, 'date_cell': 'Jan 14', 'class': 'fix', 'holiday': 'Bhogi'}
{'table': 1, 'date_cell': 'Jan 15', 'class': 'fix', 'holiday': 'Sankranti / Pongal'}
{'table': 1, 'date_cell': 'Jan 16', 'class': 'opt', 'holiday': 'Kanumu'}
{'table': 1, 'date_cell': 'Jan 25', 'class': 'opt', 'holiday': 'Birthday of Hazrath Ali (R.A.)'}
{'table': 1, 'date_cell': 'Jan 26', 'class': 'fix', 'holiday': 'Republic Day'}
{'table': 2, 'date_cell': 'Feb 08', 'class': 'opt', 'holiday': 'Shab-e-Meraj'}
{'table': 2, 'date_cell': 'Feb 14', 'class': 'opt', 'holiday': 'Sri Panchami'}
{'table': 2, 'date_cell': 'Feb 26', 'class': 'opt', 'holiday': 'Shab-e-Barat'}
{'table': 3, 'date_cell': 'Mar 08', 'class': 'fix', 'holiday': 'Maha Shivaratri'}
{'table': 3, 'date_cell': 'Mar 25', 'class': 'fix', 'holiday': 'Holi'}
{'table': 3, 'date_cell': 'Mar 29', 'class': 'fix', 'holiday': 'Good Friday'}

=================================================================
YEAR: 2025
Date-cell class counts: {'fix': 27, 'opt': 22}

Sample date/holiday pairs:
{'table': 1, 'date_cell': 'Jan 01', 'class': 'fix', 'holiday': 'New Year Day'}
{'table': 1, 'date_cell': 'Jan 13', 'class': 'fix', 'holiday': 'Bhogi'}
{'table': 1, 'date_cell': 'Jan 14', 'class': 'fix', 'holiday': 'Sankranti / Pongal'}
{'table': 1, 'date_cell': 'Jan 14', 'class': 'opt', 'holiday': 'Birthday of Hazrath Ali'}
{'table': 1, 'date_cell': 'Jan 15', 'class': 'opt', 'holiday': 'Kanumu'}
{'table': 1, 'date_cell': 'Jan 28', 'class': 'opt', 'holiday': 'Shab-e-Meraj'}
{'table': 2, 'date_cell': 'Feb 03', 'class': 'opt', 'holiday': 'Sri Panchami'}
{'table': 2, 'date_cell': 'Feb 14', 'class': 'opt', 'holiday': 'Shab-e-Barat'}
{'table': 2, 'date_cell': 'Feb 26', 'class': 'fix', 'holiday': 'Mahashivarathri'}
{'table': 3, 'date_cell': 'Mar 14', 'class': 'fix', 'holiday': 'Holi'}
{'table': 3, 'date_cell': 'Mar 21', 'class': 'opt', 'holiday': 'Shahadat HZT Ali (R.A.)'}
{'table': 3, 'date_cell': 'Mar 28', 'class': 'opt', 'holiday': 'Jumatul-Vida,Shab-e-Qader'}

=================================================================
YEAR: 2026
Date-cell class counts: {'opt': 26, 'fix': 26}

Sample date/holiday pairs:
{'table': 1, 'date_cell': 'Jan 01', 'class': 'opt', 'holiday': 'New Year'}
{'table': 1, 'date_cell': 'Jan 03', 'class': 'opt', 'holiday': 'Birthday of Hazrath Ali'}
{'table': 1, 'date_cell': 'Jan 14', 'class': 'fix', 'holiday': 'Bhogi'}
{'table': 1, 'date_cell': 'Jan 15', 'class': 'fix', 'holiday': 'Sankranti / Pongal'}
{'table': 1, 'date_cell': 'Jan 16', 'class': 'opt', 'holiday': 'Kanumu'}
{'table': 1, 'date_cell': 'Jan 17', 'class': 'opt', 'holiday': 'Shab-e-Meraj'}
{'table': 1, 'date_cell': 'Jan 23', 'class': 'opt', 'holiday': 'Sri Panchami'}
{'table': 2, 'date_cell': 'Feb 04', 'class': 'opt', 'holiday': 'Shab-e-Barat'}
{'table': 2, 'date_cell': 'Feb 15', 'class': 'fix', 'holiday': 'Mahashivarathri'}
{'table': 3, 'date_cell': 'Mar 03', 'class': 'fix', 'holiday': 'Holi'}
{'table': 3, 'date_cell': 'Mar 10', 'class': 'opt', 'holiday': 'Shahadat HZT Ali (R.A.)'}
{'table': 3, 'date_cell': 'Mar 13', 'class': 'opt', 'holiday': 'Jumatul-Vida'}

--- CLASSIFICATION SUMMARY ---

   year date_cell_class  count
0  2023             fix     28
1  2023             opt     24
2  2024             fix     28
3  2024             opt     24
4  2025             fix     27
5  2025             opt     22
6  2026             opt     26
7  2026             fix     26

In [40]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup

SOURCES = {
    2023: "https://www.telangana.gov.in/Downloads/calendar-2023/",
    2024: "https://www.telangana.gov.in/downloads/calendar/",
    2025: "https://www.telangana.gov.in/downloads/calendar-2025/",
    2026: "https://www.telangana.gov.in/downloads/calendar-2026/",
}

MONTHS = {
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4,
    "May": 5, "Jun": 6, "Jul": 7, "Aug": 8,
    "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12
}

DATE_PATTERN = re.compile(
    r"^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)"
    r"\s+(\d{1,2})$",
    re.IGNORECASE
)

headers = {"User-Agent": "Mozilla/5.0"}
records = []

for year, url in SOURCES.items():
    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, "html.parser")

    for table_index, table in enumerate(soup.find_all("table"), start=1):
        for row in table.find_all("tr"):
            cells = row.find_all(["th", "td"], recursive=False)

            for index, cell in enumerate(cells[:-1]):
                match = DATE_PATTERN.match(
                    cell.get_text(" ", strip=True)
                )

                if not match:
                    continue

                month_text, day_text = match.groups()
                month = MONTHS[month_text.title()]
                day = int(day_text)

                holiday_name = cells[index + 1].get_text(
                    " ", strip=True
                )

                if not holiday_name:
                    continue

                classes = cell.get("class", [])
                class_label = ",".join(classes) if classes else "unclassified"

                try:
                    date = pd.Timestamp(
                        year=year,
                        month=month,
                        day=day
                    )
                except ValueError:
                    print("Invalid date:", year, cell.get_text(" ", strip=True))
                    continue

                records.append({
                    "date": date,
                    "year": year,
                    "holiday_name": holiday_name,
                    "calendar_class": class_label,
                    "source_table": table_index,
                    "source_url": url
                })

holidays_review_df = pd.DataFrame(records)

if holidays_review_df.empty:
    raise ValueError("No holiday records extracted.")

print("TOTAL RECORDS:", len(holidays_review_df))

print("\nRECORDS BY YEAR:")
display(
    holidays_review_df.groupby("year")
    .size()
    .reindex(SOURCES.keys(), fill_value=0)
    .rename("record_count")
    .to_frame()
)

print("\nRECORDS BY YEAR AND HTML CLASS:")
display(
    pd.crosstab(
        holidays_review_df["year"],
        holidays_review_df["calendar_class"]
    )
)

print("\nDUPLICATE DATE + NAME RECORDS:")
display(
    holidays_review_df[
        holidays_review_df.duplicated(
            subset=["date", "holiday_name"],
            keep=False
        )
    ].sort_values(["date", "holiday_name"])
)

print("\nALL RECORDS — 2023:")
display(
    holidays_review_df[
        holidays_review_df["year"] == 2023
    ][["date", "holiday_name", "calendar_class"]]
    .sort_values(["date", "holiday_name"])
)

print("\nALL RECORDS — 2025:")
display(
    holidays_review_df[
        holidays_review_df["year"] == 2025
    ][["date", "holiday_name", "calendar_class"]]
    .sort_values(["date", "holiday_name"])
)

print("\nUNCLASSIFIED RECORDS:")
display(
    holidays_review_df[
        holidays_review_df["calendar_class"] == "unclassified"
    ]
)

TOTAL RECORDS: 205

RECORDS BY YEAR:

      record_count
year
2023            52
2024            52
2025            49
2026            52

RECORDS BY YEAR AND HTML CLASS:

calendar_class  fix  opt
year
2023             28   24
2024             28   24
2025             27   22
2026             26   26

DUPLICATE DATE + NAME RECORDS:

Empty DataFrame
Columns: [date, year, holiday_name, calendar_class, source_table, source_url]
Index: []

ALL RECORDS — 2023:

,date,holiday_name,calendar_class
0,2023-01-01,New Year Day,fix
1,2023-01-14,Bhogi,fix
2,2023-01-15,Sankranti/Pongal,fix
3,2023-01-16,Kanumu,opt
4,2023-01-26,Republic Day,fix
5,2023-01-26,Sri Panchami (General Holiday in view of Repub...,opt
6,2023-02-05,Birthday of Hazrath Ali (R.A.),opt
7,2023-02-18,Maha Shivaratri,fix
8,2023-02-19,Shab-E-Meraj,opt
9,2023-03-07,Holi,fix
10,2023-03-08,Shab-E-Barat,opt
11,2023-03-22,Ugadi,fix
12,2023-03-30,Sri Rama Navami,fix
13,2023-04-04,Mahaveer Jayanthi,opt
14,2023-04-05,Babu Jagjivan Ram's Birthday,fix
15,2023-04-07,Good Friday,fix
16,2023-04-11,Shahadat HZT Ali (R.A.),opt
17,2023-04-14,Dr. B.R. Ambedkar's Birthday,fix
18,2023-04-14,Tamil New Year's Day/Jumuatulwada (General hol...,opt
19,2023-04-18,Shab-E-Qader,opt
20,2023-04-22,Eid-Ul-Fitr (Ramzan),fix
22,2023-04-23,Basava Jayanthi (General Holiday in view of th...,opt
21,2023-04-23,Following day of Ramzan,fix
23,2023-05-05,Buddha Purnima,opt
24,2023-06-20,Ratha Yathra,opt
25,2023-06-29,Eidul Azha (Bakrid),fix
26,2023-07-07,Eid-E-Ghadeer,opt
27,2023-07-17,Bonalu,fix
28,2023-07-28,9th Moharram (1445H),opt
29,2023-07-29,Shahadat Imam Hussain (R.A) 10th Moharam,fix
30,2023-08-15,Independence Day,fix
31,2023-08-16,Parsi New Year's Day,opt
32,2023-08-25,Varalakshmi Vratham,opt
33,2023-08-31,Sravana Purnima/Rakhi Purnima,opt
34,2023-09-06,Arbayeen,opt
35,2023-09-07,Sri Krishna Astami (as per Srivaishnava Agamam),fix
36,2023-09-18,Vinayaka Chavithi,fix
37,2023-09-28,Eid Miladun Nabi,fix
38,2023-10-02,Mahatma Gandhi Jayanthi,fix
39,2023-10-14,Bathukamma Starting Day,fix
40,2023-10-22,Durgashtami,opt
41,2023-10-23,Maharnavami,opt
42,2023-10-24,Vijaya Dasami,fix
43,2023-10-25,Following Day of Vijaya Dasami,fix
44,2023-10-27,Yaz Dahum Shareef,opt
45,2023-11-11,Naraka Chaturdhi,opt
46,2023-11-12,Deepavali,fix
47,2023-11-27,Karthika Purnima / Guru Nanak's Birthday,fix
48,2023-11-29,Birthday of HZT. Syed Mohammed Juvanpuri Mahdi...,opt
49,2023-12-24,Christmas Eve,opt
50,2023-12-25,Christmas,fix
51,2023-12-26,Boxing Day​​​,fix

ALL RECORDS — 2025:

,date,holiday_name,calendar_class
104,2025-01-01,New Year Day,fix
105,2025-01-13,Bhogi,fix
107,2025-01-14,Birthday of Hazrath Ali,opt
106,2025-01-14,Sankranti / Pongal,fix
108,2025-01-15,Kanumu,opt
109,2025-01-28,Shab-e-Meraj,opt
110,2025-02-03,Sri Panchami,opt
111,2025-02-14,Shab-e-Barat,opt
112,2025-02-26,Mahashivarathri,fix
113,2025-03-14,Holi,fix
114,2025-03-21,Shahadat HZT Ali (R.A.),opt
115,2025-03-28,"Jumatul-Vida,Shab-e-Qader",opt
116,2025-03-30,Ugadi,fix
117,2025-03-31,Ramzan(Eid--ul-Fitr),fix
118,2025-04-01,Following day of Ramzan,fix
119,2025-04-05,Babu Jagjivan Ram's Birthday,fix
120,2025-04-10,Mahaveer Jayanthi,opt
121,2025-04-14,Dr. B.R. Ambedkar's Birthday,fix
122,2025-04-14,Tamil New Year's Day (General holiday in the v...,opt
123,2025-04-18,Good Friday,fix
124,2025-04-30,Basava Jayanthi,opt
125,2025-05-12,Buddha Purnima,opt
126,2025-06-07,Eidul Azha (Bakrid),fix
127,2025-06-15,Eid-e-Ghadeer,opt
128,2025-06-15,Ratha Yathra,opt
129,2025-07-05,9th Moharram (1445H),opt
130,2025-07-06,Moharam,fix
131,2025-07-21,Bonalu,fix
132,2025-08-08,Varalakshmi Vratham,opt
133,2025-08-09,Sravana Purnima / Rakhi Purnima,fix
134,2025-08-15,Independence Day,fix
135,2025-08-15,Parsi New Year's Day (General Holiday in view ...,opt
136,2025-08-16,Sri Krishnashtami,fix
137,2025-08-27,Vinayaka Chavithi,fix
138,2025-09-05,Eid Miladun Nabi,fix
139,2025-09-21,Bathukamma Starting Day,fix
140,2025-09-30,Durgashtami,opt
141,2025-10-01,Maharnavami,opt
142,2025-10-02,Mahatma Gandhi Jayanthi,fix
143,2025-10-02,Vijaya Dasami,fix
144,2025-10-03,Following day of Vijaya Dasami,fix
145,2025-10-04,Yaz Dahum Shareef,opt
146,2025-10-19,Naraka Chaturdhi,opt
147,2025-10-20,Deepavali,fix
148,2025-11-05,Karthika Purnima / Guru Nanak's Birthday,fix
149,2025-11-16,Birthday of HZT. Syed Mohammed Juvanpuri Mahdi...,opt
150,2025-12-24,Christmas Eve,opt
151,2025-12-25,Christmas,fix
152,2025-12-26,Following day of Christmas (Boxing Day),fix

UNCLASSIFIED RECORDS:

Empty DataFrame
Columns: [date, year, holiday_name, calendar_class, source_table, source_url]
Index: []

In [41]:
# Review all extracted records, grouped by year and HTML class.

for year in [2023, 2024, 2025, 2026]:
    print(f"\n{'=' * 70}")
    print(f"TELANGANA HOLIDAY CALENDAR — {year}")

    year_df = (
        holidays_review_df[
            holidays_review_df["year"] == year
        ][["date", "holiday_name", "calendar_class"]]
        .sort_values(["date", "holiday_name"])
        .reset_index(drop=True)
    )

    print("Total records:", len(year_df))
    print("\nClass counts:")
    print(year_df["calendar_class"].value_counts().to_string())

    display(year_df)

======================================================================
TELANGANA HOLIDAY CALENDAR — 2023
Total records: 52

Class counts:
calendar_class
fix    28
opt    24

,date,holiday_name,calendar_class
0,2023-01-01,New Year Day,fix
1,2023-01-14,Bhogi,fix
2,2023-01-15,Sankranti/Pongal,fix
3,2023-01-16,Kanumu,opt
4,2023-01-26,Republic Day,fix
5,2023-01-26,Sri Panchami (General Holiday in view of Repub...,opt
6,2023-02-05,Birthday of Hazrath Ali (R.A.),opt
7,2023-02-18,Maha Shivaratri,fix
8,2023-02-19,Shab-E-Meraj,opt
9,2023-03-07,Holi,fix
10,2023-03-08,Shab-E-Barat,opt
11,2023-03-22,Ugadi,fix
12,2023-03-30,Sri Rama Navami,fix
13,2023-04-04,Mahaveer Jayanthi,opt
14,2023-04-05,Babu Jagjivan Ram's Birthday,fix
15,2023-04-07,Good Friday,fix
16,2023-04-11,Shahadat HZT Ali (R.A.),opt
17,2023-04-14,Dr. B.R. Ambedkar's Birthday,fix
18,2023-04-14,Tamil New Year's Day/Jumuatulwada (General hol...,opt
19,2023-04-18,Shab-E-Qader,opt
20,2023-04-22,Eid-Ul-Fitr (Ramzan),fix
21,2023-04-23,Basava Jayanthi (General Holiday in view of th...,opt
22,2023-04-23,Following day of Ramzan,fix
23,2023-05-05,Buddha Purnima,opt
24,2023-06-20,Ratha Yathra,opt
25,2023-06-29,Eidul Azha (Bakrid),fix
26,2023-07-07,Eid-E-Ghadeer,opt
27,2023-07-17,Bonalu,fix
28,2023-07-28,9th Moharram (1445H),opt
29,2023-07-29,Shahadat Imam Hussain (R.A) 10th Moharam,fix
30,2023-08-15,Independence Day,fix
31,2023-08-16,Parsi New Year's Day,opt
32,2023-08-25,Varalakshmi Vratham,opt
33,2023-08-31,Sravana Purnima/Rakhi Purnima,opt
34,2023-09-06,Arbayeen,opt
35,2023-09-07,Sri Krishna Astami (as per Srivaishnava Agamam),fix
36,2023-09-18,Vinayaka Chavithi,fix
37,2023-09-28,Eid Miladun Nabi,fix
38,2023-10-02,Mahatma Gandhi Jayanthi,fix
39,2023-10-14,Bathukamma Starting Day,fix
40,2023-10-22,Durgashtami,opt
41,2023-10-23,Maharnavami,opt
42,2023-10-24,Vijaya Dasami,fix
43,2023-10-25,Following Day of Vijaya Dasami,fix
44,2023-10-27,Yaz Dahum Shareef,opt
45,2023-11-11,Naraka Chaturdhi,opt
46,2023-11-12,Deepavali,fix
47,2023-11-27,Karthika Purnima / Guru Nanak's Birthday,fix
48,2023-11-29,Birthday of HZT. Syed Mohammed Juvanpuri Mahdi...,opt
49,2023-12-24,Christmas Eve,opt
50,2023-12-25,Christmas,fix
51,2023-12-26,Boxing Day​​​,fix

======================================================================
TELANGANA HOLIDAY CALENDAR — 2024
Total records: 52

Class counts:
calendar_class
fix    28
opt    24

,date,holiday_name,calendar_class
0,2024-01-01,New Year Day,fix
1,2024-01-14,Bhogi,fix
2,2024-01-15,Sankranti / Pongal,fix
3,2024-01-16,Kanumu,opt
4,2024-01-25,Birthday of Hazrath Ali (R.A.),opt
5,2024-01-26,Republic Day,fix
6,2024-02-08,Shab-e-Meraj,opt
7,2024-02-14,Sri Panchami,opt
8,2024-02-26,Shab-e-Barat,opt
9,2024-03-08,Maha Shivaratri,fix
10,2024-03-25,Holi,fix
11,2024-03-29,Good Friday,fix
12,2024-03-31,Shahadat HZT Ali (R.A.),opt
13,2024-04-05,Babu Jagjivan Ram's Birthday,fix
14,2024-04-05,Jumu'atul Wida (General holiday in the view of...,opt
15,2024-04-07,Shab-E-Qader,opt
16,2024-04-09,Ugadi,fix
17,2024-04-11,Eid-Ul-Fitr (Ramzan),fix
18,2024-04-12,Following day of Ramzan,fix
19,2024-04-14,Dr. B.R. Ambedkar's Birthday,fix
20,2024-04-14,Tamil New Year's Day (General holiday in the v...,opt
21,2024-04-17,Sri Rama Navami,fix
22,2024-04-21,Mahaveer Jayanthi,fix
23,2024-05-10,Basava Jayanthi,opt
24,2024-05-23,Buddha Purnima,opt
25,2024-06-17,Eidul Azha (Bakrid),fix
26,2024-06-25,Eid-e-Ghadeer,opt
27,2024-07-07,Ratha Yathra,opt
28,2024-07-16,9th Moharram (1445H),opt
29,2024-07-17,Shahadat Imam Hussain (R.A) 10th Moharam,fix
30,2024-07-29,Bonalu,fix
31,2024-08-15,Independence Day,fix
32,2024-08-15,Parsi New Year's Day (General Holiday in view ...,opt
33,2024-08-16,Varalakshmi Vratham,opt
34,2024-08-19,Sravana Purnima / Rakhi Purnima,opt
35,2024-08-26,Arbayeen,opt
36,2024-08-26,Sri Krishna Astami (as per Srivaishnava Agamam),fix
37,2024-09-07,Vinayaka Chavithi,fix
38,2024-09-16,Eid Miladun Nabi,fix
39,2024-10-02,Mahatma Gandhi Jayanthi,fix
40,2024-10-10,Durgashtami,opt
41,2024-10-11,Maharnavami,opt
42,2024-10-12,Vijaya Dasami,fix
43,2024-10-13,Following day of Vijaya Dasami,fix
44,2024-10-15,Yaz Dahum Shareef,opt
45,2024-10-30,Naraka Chaturdhi,opt
46,2024-10-31,Deepavali,fix
47,2024-11-15,Karthika Purnima / Guru Nanak's Birthday,fix
48,2024-11-16,Birthday of HZT. Syed Mohammed Juvanpuri Mahdi...,opt
49,2024-12-24,Christmas Eve,opt
50,2024-12-25,Christmas,fix
51,2024-12-26,Following day of Christmas (Boxing Day),fix

======================================================================
TELANGANA HOLIDAY CALENDAR — 2025
Total records: 49

Class counts:
calendar_class
fix    27
opt    22

,date,holiday_name,calendar_class
0,2025-01-01,New Year Day,fix
1,2025-01-13,Bhogi,fix
2,2025-01-14,Birthday of Hazrath Ali,opt
3,2025-01-14,Sankranti / Pongal,fix
4,2025-01-15,Kanumu,opt
5,2025-01-28,Shab-e-Meraj,opt
6,2025-02-03,Sri Panchami,opt
7,2025-02-14,Shab-e-Barat,opt
8,2025-02-26,Mahashivarathri,fix
9,2025-03-14,Holi,fix
10,2025-03-21,Shahadat HZT Ali (R.A.),opt
11,2025-03-28,"Jumatul-Vida,Shab-e-Qader",opt
12,2025-03-30,Ugadi,fix
13,2025-03-31,Ramzan(Eid--ul-Fitr),fix
14,2025-04-01,Following day of Ramzan,fix
15,2025-04-05,Babu Jagjivan Ram's Birthday,fix
16,2025-04-10,Mahaveer Jayanthi,opt
17,2025-04-14,Dr. B.R. Ambedkar's Birthday,fix
18,2025-04-14,Tamil New Year's Day (General holiday in the v...,opt
19,2025-04-18,Good Friday,fix
20,2025-04-30,Basava Jayanthi,opt
21,2025-05-12,Buddha Purnima,opt
22,2025-06-07,Eidul Azha (Bakrid),fix
23,2025-06-15,Eid-e-Ghadeer,opt
24,2025-06-15,Ratha Yathra,opt
25,2025-07-05,9th Moharram (1445H),opt
26,2025-07-06,Moharam,fix
27,2025-07-21,Bonalu,fix
28,2025-08-08,Varalakshmi Vratham,opt
29,2025-08-09,Sravana Purnima / Rakhi Purnima,fix
30,2025-08-15,Independence Day,fix
31,2025-08-15,Parsi New Year's Day (General Holiday in view ...,opt
32,2025-08-16,Sri Krishnashtami,fix
33,2025-08-27,Vinayaka Chavithi,fix
34,2025-09-05,Eid Miladun Nabi,fix
35,2025-09-21,Bathukamma Starting Day,fix
36,2025-09-30,Durgashtami,opt
37,2025-10-01,Maharnavami,opt
38,2025-10-02,Mahatma Gandhi Jayanthi,fix
39,2025-10-02,Vijaya Dasami,fix
40,2025-10-03,Following day of Vijaya Dasami,fix
41,2025-10-04,Yaz Dahum Shareef,opt
42,2025-10-19,Naraka Chaturdhi,opt
43,2025-10-20,Deepavali,fix
44,2025-11-05,Karthika Purnima / Guru Nanak's Birthday,fix
45,2025-11-16,Birthday of HZT. Syed Mohammed Juvanpuri Mahdi...,opt
46,2025-12-24,Christmas Eve,opt
47,2025-12-25,Christmas,fix
48,2025-12-26,Following day of Christmas (Boxing Day),fix

======================================================================
TELANGANA HOLIDAY CALENDAR — 2026
Total records: 52

Class counts:
calendar_class
opt    26
fix    26

,date,holiday_name,calendar_class
0,2026-01-01,New Year,opt
1,2026-01-03,Birthday of Hazrath Ali,opt
2,2026-01-14,Bhogi,fix
3,2026-01-15,Sankranti / Pongal,fix
4,2026-01-16,Kanumu,opt
5,2026-01-17,Shab-e-Meraj,opt
6,2026-01-23,Sri Panchami,opt
7,2026-02-04,Shab-e-Barat,opt
8,2026-02-15,Mahashivarathri,fix
9,2026-03-03,Holi,fix
10,2026-03-10,Shahadat HZT Ali (R.A.),opt
11,2026-03-13,Jumatul-Vida,opt
12,2026-03-17,Shab-e-Qader,opt
13,2026-03-19,Ugadi,fix
14,2026-03-21,Ramzan(Eid--ul-Fitr),fix
15,2026-03-22,Following of Ramzan(Eid--ul-Fitr),fix
16,2026-03-27,Sri Rama Navami,fix
17,2026-03-31,Mahaveer Jayanthi,opt
18,2026-04-03,Good Friday,fix
19,2026-04-05,Babu Jagjivan Ram's Birthday,fix
20,2026-04-14,Dr. B.R. Ambedkar's Birthday,fix
21,2026-04-14,Tamil New Year's Day (General holiday in the v...,opt
22,2026-04-20,Basava Jayanthi,opt
23,2026-05-01,Buddha Purnima,opt
24,2026-05-27,Eidul Azha (Bakrid),fix
25,2026-06-04,Eid-e-Ghadeer,opt
26,2026-06-25,9th Moharram,opt
27,2026-06-26,Moharram,fix
28,2026-07-16,Ratha Yathra,opt
29,2026-08-04,Arbayeen,opt
30,2026-08-10,Bonalu,fix
31,2026-08-15,Independence Day,fix
32,2026-08-15,Paris New Year,opt
33,2026-08-21,Varalakshmi Vratham,opt
34,2026-08-26,Eid Milad-un-Nabi,fix
35,2026-08-28,Sravana Purnima and Rakhi Purnimi,opt
36,2026-09-04,Sri Krishnashtami,fix
37,2026-09-14,Vinayaka Chavithi,fix
38,2026-09-23,Yazdahum Shareef,opt
39,2026-10-02,Mahatma Gandhi Jayanthi,fix
40,2026-10-18,Saddula Bathukamma,fix
41,2026-10-19,Maharnavami,opt
42,2026-10-20,Vijaya Dasami,fix
43,2026-10-21,Following day of Vijaya Dasami,fix
44,2026-10-26,Birthday of Hazrath Syed Mohd. Juvanpuri,opt
45,2026-11-08,Deepavali,fix
46,2026-11-08,Naraka Chathurdhi,opt
47,2026-11-24,Karthika Pournami,fix
48,2026-12-24,Christmas Eve,opt
49,2026-12-25,Christmas,fix
50,2026-12-26,Boxing Day,fix
51,2026-12-26,Hazrath ali Birthday,opt

In [42]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

BASE_URL = "https://www.telangana.gov.in/"
HEADERS = {"User-Agent": "Mozilla/5.0"}

response = requests.get(
    BASE_URL,
    headers=HEADERS,
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

keywords = [
    "holiday",
    "general administration",
    "government order",
    "g.o.",
    "notification",
]

matches = []

for link in soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(BASE_URL, link["href"])

    searchable = f"{text} {href}".lower()

    if any(keyword in searchable for keyword in keywords):
        matches.append({
            "link_text": text,
            "url": href,
        })

print("Matching links:", len(matches))

for item in matches[:60]:
    print(f"{item['link_text']} | {item['url']}")

Matching links: 4
General Administration (Political) | https://www.telangana.gov.in/departments/general-administration-political/
Click Here | https://www.telangana.gov.in/wp-content/uploads/2026/02/Recruitment-Notification-for-AGNIVEER-2027.pdf
Government Orders | https://www.telangana.gov.in/government-orders/
Government Orders | https://www.telangana.gov.in/government-orders/

In [43]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

URL = "https://www.telangana.gov.in/government-orders/"

response = requests.get(
    URL,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

print("HTTP status:", response.status_code)
print("Page title:", soup.title.get_text(strip=True) if soup.title else "Not found")

# Search page links for holiday-related documents.
keywords = [
    "holiday",
    "holidays",
    "general administration",
    "optional",
    "2023",
    "2024",
    "2025",
    "2026",
]

matches = []

for link in soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(URL, link["href"])

    searchable = f"{text} {href}".lower()

    if any(keyword in searchable for keyword in keywords):
        matches.append({
            "link_text": text,
            "url": href,
        })

print("\nMatching links:", len(matches))

for item in matches[:100]:
    print(f"{item['link_text']} | {item['url']}")

# Inspect page text for references to holiday notifications.
page_text = soup.get_text(" ", strip=True)

print("\n--- HOLIDAY-RELATED TEXT ---")

for keyword in ["holiday", "holidays", "General Administration"]:
    position = page_text.lower().find(keyword.lower())

    if position >= 0:
        start = max(0, position - 200)
        end = min(len(page_text), position + 700)

        print(f"\nKeyword: {keyword}")
        print(page_text[start:end])

HTTP status: 200
Page title: Government Orders - Telangana State Portal

Matching links: 2
General Administration (Political) | https://www.telangana.gov.in/departments/general-administration-political/
Budget / Finance | https://www.telangana.gov.in/budget-2026-2027/

--- HOLIDAY-RELATED TEXT ---

Keyword: General Administration
-operation Animal Husbandry, Dairy Development and Fisheries Archaeology Backward Classes Welfare Cinematography Consumer Affairs Food & Civil Supplies Endowments Energy Environment & Forests Finance General Administration (Political) Handlooms & Textiles Health, Medical & Family Welfare, Science and Technology Higher Education Home Housing Industries and Commerce Information and Public Relations Information Technology, Electronics and Communications Irrigation and CAD Labour, Employment Training and Factories Law & Order Legislative Affairs Mines & Geology Minorities Welfare Municipal Administration & Urban Development Panchayat Raj and Rural Development Planning Public Enterprises Revenue Revenue (Registration and Stamps) Revenue (Prohibition & Excise) Revenue (Commercial Taxes) Roads and Buildings School Education (SE Wing) Social Welfare Transport Tribal Welfare Sports and Youth Serv

In [44]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

URL = (
    "https://www.telangana.gov.in/"
    "departments/general-administration-political/"
)

response = requests.get(
    URL,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

print("HTTP status:", response.status_code)
print(
    "Page title:",
    soup.title.get_text(strip=True) if soup.title else "Not found"
)

# Find links potentially relevant to holiday notifications.
keywords = [
    "holiday",
    "holidays",
    "general administration",
    "government order",
    "notification",
    "2023",
    "2024",
    "2025",
    "2026",
]

matches = []

for link in soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(URL, link["href"])

    if any(
        keyword in f"{text} {href}".lower()
        for keyword in keywords
    ):
        matches.append({
            "text": text,
            "url": href,
        })

print("\nPotentially relevant links:", len(matches))

for item in matches[:100]:
    print(f"{item['text']} | {item['url']}")

# Check the page for holiday-related text.
page_text = soup.get_text(" ", strip=True)

print("\n--- PAGE TEXT SEARCH ---")

for keyword in ["holiday", "holidays", "G.O.", "notification"]:
    position = page_text.lower().find(keyword.lower())

    if position != -1:
        print(f"\nFound: {keyword}")
        print(page_text[max(0, position - 150):position + 500])

HTTP status: 200
Page title: General Administration (Political) - Telangana State Portal

Potentially relevant links: 2
General Administration (Political) | https://www.telangana.gov.in/departments/general-administration-political/
General Administration (Political) | https://www.telangana.gov.in/departments/general-administration-political/

--- PAGE TEXT SEARCH ---

In [45]:
# Final pre-export quality checks for the extracted holiday records.
# This cell does not save any files.

import pandas as pd

df = holidays_review_df.copy()

df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["holiday_name"] = (
    df["holiday_name"]
    .astype("string")
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

print("TOTAL RECORDS:", len(df))

print("\n1. Missing values")
display(df.isna().sum().to_frame("missing_count"))

print("\n2. Records by year")
display(
    df.groupby("year")
    .size()
    .reindex([2023, 2024, 2025, 2026], fill_value=0)
    .rename("record_count")
    .to_frame()
)

print("\n3. Records by year and source HTML class")
display(
    pd.crosstab(df["year"], df["calendar_class"])
)

print("\n4. Exact duplicate date/name records")
duplicates = df[
    df.duplicated(
        subset=["date", "holiday_name"],
        keep=False
    )
].sort_values(["date", "holiday_name"])

display(duplicates)

print("\n5. Records outside their declared year")
wrong_year = df[df["date"].dt.year != df["year"]]
display(wrong_year)

print("\n6. Records outside the intended calendar period")
outside_period = df[
    ~df["date"].dt.year.between(2023, 2026)
]
display(outside_period)

print("\n7. Holiday names containing classification notes")
classification_notes = df[
    df["holiday_name"].str.contains(
        r"general holiday|optional holiday",
        case=False,
        na=False
    )
].sort_values(["date", "holiday_name"])

display(
    classification_notes[
        ["date", "holiday_name", "calendar_class", "source_url"]
    ]
)

print("\n8. Final review status")
print("Rows:", len(df))
print("Missing dates:", df["date"].isna().sum())
print("Missing holiday names:", df["holiday_name"].isna().sum())
print("Duplicate date/name rows:", len(duplicates))
print("Wrong-year rows:", len(wrong_year))

TOTAL RECORDS: 205

1. Missing values

                missing_count
date                        0
year                        0
holiday_name                0
calendar_class              0
source_table                0
source_url                  0

2. Records by year

      record_count
year
2023            52
2024            52
2025            49
2026            52

3. Records by year and source HTML class

calendar_class  fix  opt
year
2023             28   24
2024             28   24
2025             27   22
2026             26   26

4. Exact duplicate date/name records

Empty DataFrame
Columns: [date, year, holiday_name, calendar_class, source_table, source_url]
Index: []

5. Records outside their declared year

Empty DataFrame
Columns: [date, year, holiday_name, calendar_class, source_table, source_url]
Index: []

6. Records outside the intended calendar period

Empty DataFrame
Columns: [date, year, holiday_name, calendar_class, source_table, source_url]
Index: []

7. Holiday names containing classification notes

,date,holiday_name,calendar_class,source_url
5,2023-01-26,Sri Panchami (General Holiday in view of Repub...,opt,https://www.telangana.gov.in/Downloads/calenda...
18,2023-04-14,Tamil New Year's Day/Jumuatulwada (General hol...,opt,https://www.telangana.gov.in/Downloads/calenda...
22,2023-04-23,Basava Jayanthi (General Holiday in view of th...,opt,https://www.telangana.gov.in/Downloads/calenda...
66,2024-04-05,Jumu'atul Wida (General holiday in the view of...,opt,https://www.telangana.gov.in/downloads/calendar/
72,2024-04-14,Tamil New Year's Day (General holiday in the v...,opt,https://www.telangana.gov.in/downloads/calendar/
84,2024-08-15,Parsi New Year's Day (General Holiday in view ...,opt,https://www.telangana.gov.in/downloads/calendar/
122,2025-04-14,Tamil New Year's Day (General holiday in the v...,opt,https://www.telangana.gov.in/downloads/calenda...
135,2025-08-15,Parsi New Year's Day (General Holiday in view ...,opt,https://www.telangana.gov.in/downloads/calenda...
174,2026-04-14,Tamil New Year's Day (General holiday in the v...,opt,https://www.telangana.gov.in/downloads/calenda...

8. Final review status
Rows: 205
Missing dates: 0
Missing holiday names: 0
Duplicate date/name rows: 0
Wrong-year rows: 0

In [46]:
# Review entries whose names contain explicit holiday-classification notes.

note_pattern = r"general holiday|optional holiday"

notes_df = (
    holidays_review_df[
        holidays_review_df["holiday_name"].str.contains(
            note_pattern,
            case=False,
            na=False
        )
    ][
        [
            "date",
            "year",
            "holiday_name",
            "calendar_class",
            "source_table",
            "source_url"
        ]
    ]
    .sort_values(["date", "holiday_name"])
    .reset_index(drop=True)
)

print("Entries containing classification notes:", len(notes_df))
display(notes_df)

print("\nCounts by year and source HTML class:")

display(
    pd.crosstab(
        notes_df["year"],
        notes_df["calendar_class"]
    )
)

Entries containing classification notes: 9

,date,year,holiday_name,calendar_class,source_table,source_url
0,2023-01-26,2023,Sri Panchami (General Holiday in view of Repub...,opt,1,https://www.telangana.gov.in/Downloads/calenda...
1,2023-04-14,2023,Tamil New Year's Day/Jumuatulwada (General hol...,opt,4,https://www.telangana.gov.in/Downloads/calenda...
2,2023-04-23,2023,Basava Jayanthi (General Holiday in view of th...,opt,4,https://www.telangana.gov.in/Downloads/calenda...
3,2024-04-05,2024,Jumu'atul Wida (General holiday in the view of...,opt,4,https://www.telangana.gov.in/downloads/calendar/
4,2024-04-14,2024,Tamil New Year's Day (General holiday in the v...,opt,4,https://www.telangana.gov.in/downloads/calendar/
5,2024-08-15,2024,Parsi New Year's Day (General Holiday in view ...,opt,8,https://www.telangana.gov.in/downloads/calendar/
6,2025-04-14,2025,Tamil New Year's Day (General holiday in the v...,opt,4,https://www.telangana.gov.in/downloads/calenda...
7,2025-08-15,2025,Parsi New Year's Day (General Holiday in view ...,opt,8,https://www.telangana.gov.in/downloads/calenda...
8,2026-04-14,2026,Tamil New Year's Day (General holiday in the v...,opt,4,https://www.telangana.gov.in/downloads/calenda...

Counts by year and source HTML class:

calendar_class  opt
year
2023              3
2024              3
2025              2
2026              1

In [47]:
# Display complete names for the nine flagged entries.

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 200)

display(
    notes_df[
        ["date", "holiday_name", "calendar_class", "source_url"]
    ].to_string(index=False)
)

"      date                                                                                    holiday_name calendar_class                                            source_url\n2023-01-26                                          Sri Panchami (General Holiday in view of Republic Day)            opt https://www.telangana.gov.in/Downloads/calendar-2023/\n2023-04-14 Tamil New Year's Day/Jumuatulwada (General holiday in the view of Dr. B.R. Ambedkar's Birthday)            opt https://www.telangana.gov.in/Downloads/calendar-2023/\n2023-04-23                        Basava Jayanthi (General Holiday in view of the following day of Ramzan)            opt https://www.telangana.gov.in/Downloads/calendar-2023/\n2024-04-05                    Jumu'atul Wida (General holiday in the view of Babu Jagjivan Ram's Birthday)            opt      https://www.telangana.gov.in/downloads/calendar/\n2024-04-14              Tamil New Year's Day (General holiday in the view of Dr. B.R. Ambedkar's Birthday)            opt      https://www.telangana.gov.in/downloads/calendar/\n2024-08-15                              Parsi New Year's Day (General Holiday in view of Independence Day)            opt      https://www.telangana.gov.in/downloads/calendar/\n2025-04-14              Tamil New Year's Day (General holiday in the view of Dr. B.R. Ambedkar's Birthday)            opt https://www.telangana.gov.in/downloads/calendar-2025/\n2025-08-15                              Parsi New Year's Day (General Holiday in view of Independence Day)            opt https://www.telangana.gov.in/downloads/calendar-2025/\n2026-04-14              Tamil New Year's Day (General holiday in the view of Dr. B.R. Ambedkar's Birthday)            opt https://www.telangana.gov.in/downloads/calendar-2026/"

In [48]:
# Print each flagged record separately to avoid horizontal truncation.

for _, row in notes_df.iterrows():
    print("=" * 80)
    print(f"Date          : {row['date']:%Y-%m-%d}")
    print(f"Holiday name  : {row['holiday_name']}")
    print(f"HTML class    : {row['calendar_class']}")
    print(f"Source URL    : {row['source_url']}")

================================================================================
Date          : 2023-01-26
Holiday name  : Sri Panchami (General Holiday in view of Republic Day)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/Downloads/calendar-2023/
================================================================================
Date          : 2023-04-14
Holiday name  : Tamil New Year's Day/Jumuatulwada (General holiday in the view of Dr. B.R. Ambedkar's Birthday)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/Downloads/calendar-2023/
================================================================================
Date          : 2023-04-23
Holiday name  : Basava Jayanthi (General Holiday in view of the following day of Ramzan)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/Downloads/calendar-2023/
================================================================================
Date          : 2024-04-05
Holiday name  : Jumu'atul Wida (General holiday in the view of Babu Jagjivan Ram's Birthday)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/downloads/calendar/
================================================================================
Date          : 2024-04-14
Holiday name  : Tamil New Year's Day (General holiday in the view of Dr. B.R. Ambedkar's Birthday)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/downloads/calendar/
================================================================================
Date          : 2024-08-15
Holiday name  : Parsi New Year's Day (General Holiday in view of Independence Day)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/downloads/calendar/
================================================================================
Date          : 2025-04-14
Holiday name  : Tamil New Year's Day (General holiday in the view of Dr. B.R. Ambedkar's Birthday)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/downloads/calendar-2025/
================================================================================
Date          : 2025-08-15
Holiday name  : Parsi New Year's Day (General Holiday in view of Independence Day)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/downloads/calendar-2025/
================================================================================
Date          : 2026-04-14
Holiday name  : Tamil New Year's Day (General holiday in the view of Dr. B.R. Ambedkar's Birthday)
HTML class    : opt
Source URL    : https://www.telangana.gov.in/downloads/calendar-2026/

In [49]:
# Investigate monthly coverage in the 2025 Telangana calendar.

df_2025 = holidays_review_df[
    holidays_review_df["year"] == 2025
].copy()

df_2025["month"] = df_2025["date"].dt.month

month_summary = (
    df_2025.groupby("month")
    .agg(
        record_count=("holiday_name", "size"),
        unique_dates=("date", "nunique"),
        fix_count=("calendar_class", lambda s: (s == "fix").sum()),
        opt_count=("calendar_class", lambda s: (s == "opt").sum())
    )
    .reindex(range(1, 13), fill_value=0)
)

month_summary.index.name = "month"

print("2025 monthly record coverage:")
display(month_summary)

print("\n2025 records by month:")
for month in range(1, 13):
    month_df = (
        df_2025[df_2025["month"] == month]
        .sort_values("date")
    )

    print(f"\nMonth {month:02d}: {len(month_df)} records")

    for _, row in month_df.iterrows():
        print(
            f"{row['date']:%Y-%m-%d} | "
            f"{row['calendar_class']} | "
            f"{row['holiday_name']}"
        )

2025 monthly record coverage:

       record_count  unique_dates  fix_count  opt_count
month
1                 6             5          3          3
2                 3             3          1          2
3                 5             5          3          2
4                 7             6          4          3
5                 1             1          0          1
6                 3             2          1          2
7                 3             3          2          1
8                 6             5          4          2
9                 3             3          2          1
10                7             6          4          3
11                2             2          1          1
12                3             3          2          1

2025 records by month:

Month 01: 6 records
2025-01-01 | fix | New Year Day
2025-01-13 | fix | Bhogi
2025-01-14 | fix | Sankranti / Pongal
2025-01-14 | opt | Birthday of Hazrath Ali
2025-01-15 | opt | Kanumu
2025-01-28 | opt | Shab-e-Meraj

Month 02: 3 records
2025-02-03 | opt | Sri Panchami
2025-02-14 | opt | Shab-e-Barat
2025-02-26 | fix | Mahashivarathri

Month 03: 5 records
2025-03-14 | fix | Holi
2025-03-21 | opt | Shahadat HZT Ali (R.A.)
2025-03-28 | opt | Jumatul-Vida,Shab-e-Qader
2025-03-30 | fix | Ugadi
2025-03-31 | fix | Ramzan(Eid--ul-Fitr)

Month 04: 7 records
2025-04-01 | fix | Following day of Ramzan
2025-04-05 | fix | Babu Jagjivan Ram's Birthday
2025-04-10 | opt | Mahaveer Jayanthi
2025-04-14 | fix | Dr. B.R. Ambedkar's Birthday
2025-04-14 | opt | Tamil New Year's Day (General holiday in the view of Dr. B.R. Ambedkar's Birthday)
2025-04-18 | fix | Good Friday
2025-04-30 | opt | Basava Jayanthi

Month 05: 1 records
2025-05-12 | opt | Buddha Purnima

Month 06: 3 records
2025-06-07 | fix | Eidul Azha (Bakrid)
2025-06-15 | opt | Eid-e-Ghadeer
2025-06-15 | opt | Ratha Yathra

Month 07: 3 records
2025-07-05 | opt | 9th Moharram (1445H)
2025-07-06 | fix | Moharam
2025-07-21 | fix | Bonalu

Month 08: 6 records
2025-08-08 | opt | Varalakshmi Vratham
2025-08-09 | fix | Sravana Purnima / Rakhi Purnima
2025-08-15 | fix | Independence Day
2025-08-15 | opt | Parsi New Year's Day (General Holiday in view of Independence Day)
2025-08-16 | fix | Sri Krishnashtami
2025-08-27 | fix | Vinayaka Chavithi

Month 09: 3 records
2025-09-05 | fix | Eid  Miladun Nabi
2025-09-21 | fix | Bathukamma Starting Day
2025-09-30 | opt | Durgashtami

Month 10: 7 records
2025-10-01 | opt | Maharnavami
2025-10-02 | fix | Mahatma Gandhi Jayanthi
2025-10-02 | fix | Vijaya Dasami
2025-10-03 | fix | Following day of Vijaya Dasami
2025-10-04 | opt | Yaz Dahum Shareef
2025-10-19 | opt | Naraka Chaturdhi
2025-10-20 | fix | Deepavali

Month 11: 2 records
2025-11-05 | fix | Karthika Purnima / Guru Nanak's Birthday
2025-11-16 | opt | Birthday of HZT. Syed Mohammed Juvanpuri Mahdi MA'UD (A.S.)

Month 12: 3 records
2025-12-24 | opt | Christmas Eve
2025-12-25 | fix | Christmas
2025-12-26 | fix | Following day of Christmas (Boxing Day)

In [50]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

url = "https://www.telangana.gov.in/downloads/calendar-2025/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.content, "html.parser")

source_records = []

for table_index, table in enumerate(soup.find_all("table"), start=1):
    for row in table.find_all("tr"):
        cells = row.find_all(["th", "td"], recursive=False)

        for index, cell in enumerate(cells[:-1]):
            date_text = cell.get_text(" ", strip=True)

            if not cell.name == "th":
                continue

            import re

            if not re.match(
                r"^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2}$",
                date_text,
                re.IGNORECASE
            ):
                continue

            holiday_name = cells[index + 1].get_text(
                " ", strip=True
            )

            source_records.append({
                "date_text": date_text,
                "holiday_name": holiday_name,
                "calendar_class": ",".join(cell.get("class", [])),
                "table_index": table_index
            })

source_2025_df = pd.DataFrame(source_records)

print("Records extracted directly from the 2025 source:", len(source_2025_df))

print("\nRecords per month:")
source_2025_df["month"] = source_2025_df["date_text"].str[:3]

display(
    source_2025_df.groupby("month")
    .size()
    .rename("record_count")
    .to_frame()
)

print("\nComplete source extraction:")
display(source_2025_df)

Records extracted directly from the 2025 source: 49

Records per month:

       record_count
month
Apr               7
Aug               6
Dec               3
Feb               3
Jan               6
Jul               3
Jun               3
Mar               5
May               1
Nov               2
Oct               7
Sep               3

Complete source extraction:

   date_text                                                                        holiday_name calendar_class  table_index month
0     Jan 01                                                                        New Year Day            fix            1   Jan
1     Jan 13                                                                               Bhogi            fix            1   Jan
2     Jan 14                                                                  Sankranti / Pongal            fix            1   Jan
3     Jan 14                                                             Birthday of Hazrath Ali            opt            1   Jan
4     Jan 15                                                                              Kanumu            opt            1   Jan
5     Jan 28                                                                        Shab-e-Meraj            opt            1   Jan
6     Feb 03                                                                        Sri Panchami            opt            2   Feb
7     Feb 14                                                                        Shab-e-Barat            opt            2   Feb
8     Feb 26                                                                     Mahashivarathri            fix            2   Feb
9     Mar 14                                                                                Holi            fix            3   Mar
10    Mar 21                                                             Shahadat HZT Ali (R.A.)            opt            3   Mar
11    Mar 28                                                           Jumatul-Vida,Shab-e-Qader            opt            3   Mar
12    Mar 30                                                                               Ugadi            fix            3   Mar
13    Mar 31                                                                Ramzan(Eid--ul-Fitr)            fix            3   Mar
14    Apr 01                                                             Following day of Ramzan            fix            4   Apr
15    Apr 05                                                        Babu Jagjivan Ram's Birthday            fix            4   Apr
16    Apr 10                                                                   Mahaveer Jayanthi            opt            4   Apr
17    Apr 14                                                        Dr. B.R. Ambedkar's Birthday            fix            4   Apr
18    Apr 14  Tamil New Year's Day (General holiday in the view of Dr. B.R. Ambedkar's Birthday)            opt            4   Apr
19    Apr 18                                                                         Good Friday            fix            4   Apr
20    Apr 30                                                                     Basava Jayanthi            opt            4   Apr
21    May 12                                                                      Buddha Purnima            opt            5   May
22    Jun 07                                                                 Eidul Azha (Bakrid)            fix            6   Jun
23    Jun 15                                                                       Eid-e-Ghadeer            opt            6   Jun
24    Jun 15                                                                        Ratha Yathra            opt            6   Jun
25    Jul 05                                                                9th Moharram (1445H)            opt            7   Jul
26    Jul 06                                                                             Moharam            fix            7   Jul
27    Jul 21                                                                              Bonalu            fix            7   Jul
28    Aug 08                                                                 Varalakshmi Vratham            opt            8   Aug
29    Aug 09                                                     Sravana Purnima / Rakhi Purnima            fix            8   Aug
30    Aug 15                                                                    Independence Day            fix            8   Aug
31    Aug 15                  Parsi New Year's Day (General Holiday in view of Independence Day)            opt            8   Aug
32    Aug 16                                                                   Sri Krishnashtami            fix            8   Aug
33    Aug 27                                                                   Vinayaka Chavithi            fix            8   Aug
34    Sep 05                                                                   Eid  Miladun Nabi            fix            9   Sep
35    Sep 21                                                             Bathukamma Starting Day            fix            9   Sep
36    Sep 30                                                                         Durgashtami            opt            9   Sep
37    Oct 01                                                                         Maharnavami            opt           10   Oct
38    Oct 02                                                             Mahatma Gandhi Jayanthi            fix           10   Oct
39    Oct 02                                                                       Vijaya Dasami            fix           10   Oct
40    Oct 03                                                      Following day of Vijaya Dasami            fix           10   Oct
41    Oct 04                                                                   Yaz Dahum Shareef            opt           10   Oct
42    Oct 19                                                                    Naraka Chaturdhi            opt           10   Oct
43    Oct 20                                                                           Deepavali            fix           10   Oct
44    Nov 05                                            Karthika Purnima / Guru Nanak's Birthday            fix           11   Nov
45    Nov 16                         Birthday of HZT. Syed Mohammed Juvanpuri Mahdi MA'UD (A.S.)            opt           11   Nov
46    Dec 24                                                                       Christmas Eve            opt           12   Dec
47    Dec 25                                                                           Christmas            fix           12   Dec
48    Dec 26                                             Following day of Christmas (Boxing Day)            fix           12   Dec

In [51]:
import pandas as pd

# Original extracted records
original_2025 = holidays_review_df[
    holidays_review_df["year"] == 2025
].copy()

original_2025["date"] = pd.to_datetime(
    original_2025["date"]
).dt.strftime("%Y-%m-%d")

original_2025["holiday_name_normalized"] = (
    original_2025["holiday_name"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.casefold()
)

# Independently extracted source records
comparison_2025 = source_2025_df.copy()

comparison_2025["date"] = pd.to_datetime(
    comparison_2025["date_text"] + " 2025",
    format="%b %d %Y",
    errors="coerce"
).dt.strftime("%Y-%m-%d")

comparison_2025["holiday_name_normalized"] = (
    comparison_2025["holiday_name"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.casefold()
)

# Compare date + normalized holiday name
original_keys = set(
    zip(
        original_2025["date"],
        original_2025["holiday_name_normalized"]
    )
)

source_keys = set(
    zip(
        comparison_2025["date"],
        comparison_2025["holiday_name_normalized"]
    )
)

only_original = original_keys - source_keys
only_source = source_keys - original_keys

print("Original extraction records:", len(original_2025))
print("Independent source records:", len(comparison_2025))
print("Records only in original extraction:", len(only_original))
print("Records only in independent extraction:", len(only_source))

print("\n--- Only in original extraction ---")
for date, name in sorted(only_original):
    print(date, "|", name)

print("\n--- Only in independent extraction ---")
for date, name in sorted(only_source):
    print(date, "|", name)

Original extraction records: 49
Independent source records: 49
Records only in original extraction: 0
Records only in independent extraction: 0

--- Only in original extraction ---

--- Only in independent extraction ---

In [52]:
import pandas as pd
from pathlib import Path

# --------------------------------------------------
# 1. Prepare the final holiday dataset
# --------------------------------------------------

final_holidays_df = holidays_review_df.copy()

final_holidays_df["date"] = pd.to_datetime(
    final_holidays_df["date"],
    errors="coerce"
).dt.strftime("%Y-%m-%d")

final_holidays_df["year"] = final_holidays_df["year"].astype(int)

final_holidays_df["holiday_name"] = (
    final_holidays_df["holiday_name"]
    .astype("string")
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# Retain original source classification and provenance.
final_holidays_df = final_holidays_df[
    [
        "date",
        "year",
        "holiday_name",
        "calendar_class",
        "source_table",
        "source_url",
    ]
].sort_values(
    ["date", "holiday_name"]
).reset_index(drop=True)

# --------------------------------------------------
# 2. Final validation before saving
# --------------------------------------------------

assert final_holidays_df["date"].notna().all()
assert final_holidays_df["holiday_name"].notna().all()
assert final_holidays_df["source_url"].notna().all()

assert final_holidays_df["year"].isin(
    [2023, 2024, 2025, 2026]
).all()

assert (
    pd.to_datetime(final_holidays_df["date"]).dt.year
    == final_holidays_df["year"]
).all()

assert not final_holidays_df.duplicated(
    subset=["date", "holiday_name"]
).any()

print("Final dataset rows:", len(final_holidays_df))

print("\nRecords per year:")
display(
    final_holidays_df.groupby("year")
    .size()
    .rename("record_count")
    .to_frame()
)

print("\nSource HTML classes:")
display(
    final_holidays_df["calendar_class"]
    .value_counts(dropna=False)
    .rename_axis("calendar_class")
    .to_frame("record_count")
)

print("\nPreview:")
display(final_holidays_df.head(10))

Final dataset rows: 205

Records per year:

      record_count
year
2023            52
2024            52
2025            49
2026            52

Source HTML classes:

                record_count
calendar_class
fix                      109
opt                       96

Preview:

         date  year                                            holiday_name calendar_class  source_table                                             source_url
0  2023-01-01  2023                                            New Year Day            fix             1  https://www.telangana.gov.in/Downloads/calendar-2023/
1  2023-01-14  2023                                                   Bhogi            fix             1  https://www.telangana.gov.in/Downloads/calendar-2023/
2  2023-01-15  2023                                        Sankranti/Pongal            fix             1  https://www.telangana.gov.in/Downloads/calendar-2023/
3  2023-01-16  2023                                                  Kanumu            opt             1  https://www.telangana.gov.in/Downloads/calendar-2023/
4  2023-01-26  2023                                            Republic Day            fix             1  https://www.telangana.gov.in/Downloads/calendar-2023/
5  2023-01-26  2023  Sri Panchami (General Holiday in view of Republic Day)            opt             1  https://www.telangana.gov.in/Downloads/calendar-2023/
6  2023-02-05  2023                          Birthday of Hazrath Ali (R.A.)            opt             2  https://www.telangana.gov.in/Downloads/calendar-2023/
7  2023-02-18  2023                                         Maha Shivaratri            fix             2  https://www.telangana.gov.in/Downloads/calendar-2023/
8  2023-02-19  2023                                            Shab-E-Meraj            opt             2  https://www.telangana.gov.in/Downloads/calendar-2023/
9  2023-03-07  2023                                                    Holi            fix             3  https://www.telangana.gov.in/Downloads/calendar-2023/

In [53]:
import json
from pathlib import Path
from datetime import datetime, timezone

# --------------------------------------------------
# 1. Define output locations
# --------------------------------------------------

current_path = Path.cwd().resolve()
project_root = current_path.parent if current_path.name.lower() == "notebooks" else current_path

raw_dir = project_root / "data" / "raw" / "holidays"
metadata_dir = project_root / "data" / "metadata"

raw_dir.mkdir(parents=True, exist_ok=True)
metadata_dir.mkdir(parents=True, exist_ok=True)

csv_path = raw_dir / "telangana_calendar_holidays_2023_2026.csv"
metadata_path = metadata_dir / "telangana_holiday_source_metadata.json"

# --------------------------------------------------
# 2. Save the extracted dataset
# --------------------------------------------------

final_holidays_df.to_csv(
    csv_path,
    index=False,
    encoding="utf-8"
)

# --------------------------------------------------
# 3. Create source metadata
# --------------------------------------------------

source_urls = sorted(
    final_holidays_df["source_url"].dropna().unique().tolist()
)

yearly_counts = {
    str(int(year)): int(count)
    for year, count in (
        final_holidays_df.groupby("year").size().items()
    )
}

metadata = {
    "dataset_name": "Telangana Calendar Holidays 2023-2026",
    "collection_timestamp_utc": datetime.now(
        timezone.utc
    ).isoformat(),
    "geographic_scope": "Telangana, India",
    "coverage_start": "2023-01-01",
    "coverage_end": "2026-12-31",
    "record_count": int(len(final_holidays_df)),
    "records_by_year": yearly_counts,
    "source_urls": source_urls,
    "collection_method": (
        "HTML extraction from official Telangana State Portal "
        "calendar pages."
    ),
    "columns": list(final_holidays_df.columns),
    "classification_handling": (
        "Original HTML classes are retained as published. "
        "The values 'fix' and 'opt' have not been independently "
        "verified as legal holiday classifications."
    ),
    "validation": {
        "missing_dates": int(final_holidays_df["date"].isna().sum()),
        "missing_holiday_names": int(
            final_holidays_df["holiday_name"].isna().sum()
        ),
        "duplicate_date_name_records": int(
            final_holidays_df.duplicated(
                subset=["date", "holiday_name"]
            ).sum()
        ),
        "independent_2025_extraction_agreement": True,
    },
    "limitations": [
        (
            "Agreement between two extraction methods does not "
            "independently establish source completeness."
        ),
        (
            "Independent verification against government holiday "
            "orders remains pending."
        ),
        (
            "The 2025 calendar has 49 extracted records; the difference "
            "from other years has not been independently explained."
        ),
        (
            "The original HTML classification labels have not been "
            "independently verified against legal notifications."
        ),
    ],
}

with open(metadata_path, "w", encoding="utf-8") as file:
    json.dump(metadata, file, indent=2, ensure_ascii=False)

print("CSV saved to:", csv_path.resolve())
print("Metadata saved to:", metadata_path.resolve())
print("CSV size (bytes):", csv_path.stat().st_size)
print("Metadata size (bytes):", metadata_path.stat().st_size)

CSV saved to: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\holidays\telangana_calendar_holidays_2023_2026.csv
Metadata saved to: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\metadata\telangana_holiday_source_metadata.json
CSV size (bytes): 19959
Metadata size (bytes): 1658

In [54]:
# Reload the CSV from disk to verify that it can be read correctly.

reloaded_holidays_df = pd.read_csv(csv_path)

print("Saved CSV rows:", len(reloaded_holidays_df))
print("Saved CSV columns:", reloaded_holidays_df.columns.tolist())

print("\nRecords per year:")
display(
    reloaded_holidays_df.groupby("year")
    .size()
    .rename("record_count")
    .to_frame()
)

with open(metadata_path, "r", encoding="utf-8") as file:
    reloaded_metadata = json.load(file)

print("\nMetadata dataset name:", reloaded_metadata["dataset_name"])
print("Metadata record count:", reloaded_metadata["record_count"])

assert len(reloaded_holidays_df) == len(final_holidays_df)
assert reloaded_metadata["record_count"] == len(final_holidays_df)

print("\nPASS: Both files were saved and reloaded successfully.")

Saved CSV rows: 205
Saved CSV columns: ['date', 'year', 'holiday_name', 'calendar_class', 'source_table', 'source_url']

Records per year:

      record_count
year
2023            52
2024            52
2025            49
2026            52

Metadata dataset name: Telangana Calendar Holidays 2023-2026
Metadata record count: 205

PASS: Both files were saved and reloaded successfully.

In [55]:
from pathlib import Path

print("Notebook working directory:")
print(Path.cwd())

print("\nExpected holiday CSV:")
print(csv_path.resolve())
print("Exists:", csv_path.exists())

print("\nExpected holiday metadata:")
print(metadata_path.resolve())
print("Exists:", metadata_path.exists())

print("\nProject data directory:")
print((Path.cwd() / "data").resolve())

Notebook working directory:
d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\notebooks

Expected holiday CSV:
D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\holidays\telangana_calendar_holidays_2023_2026.csv
Exists: True

Expected holiday metadata:
D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\metadata\telangana_holiday_source_metadata.json
Exists: True

Project data directory:
D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\notebooks\data

In [56]:
from pathlib import Path

search_root = Path.cwd()

target_names = {
    "telangana_calendar_holidays_2023_2026.csv",
    "telangana_holiday_source_metadata.json",
}

print("Searching under:", search_root.resolve())

for path in search_root.rglob("*"):
    if path.is_file() and path.name in target_names:
        print("FOUND:", path.resolve())

Searching under: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\notebooks

In [57]:
from pathlib import Path

# The notebook is inside the notebooks directory.
NOTEBOOK_DIR = Path.cwd()
PROJECT_ROOT = NOTEBOOK_DIR.parent

print("Notebook directory:", NOTEBOOK_DIR)
print("Project root:", PROJECT_ROOT)
print("Project root exists:", PROJECT_ROOT.exists())
print("Project data directory:", PROJECT_ROOT / "data")

Notebook directory: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\notebooks
Project root: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting
Project root exists: True
Project data directory: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data

In [58]:
# Reconcile holiday files into the single project-level data directory.
from pathlib import Path
import shutil

NOTEBOOK_DIR = Path.cwd().resolve()
PROJECT_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name.lower() == "notebooks" else NOTEBOOK_DIR

source_csv = NOTEBOOK_DIR / "data" / "raw" / "holidays" / "telangana_calendar_holidays_2023_2026.csv"
source_metadata = NOTEBOOK_DIR / "data" / "metadata" / "telangana_holiday_source_metadata.json"

destination_raw_dir = PROJECT_ROOT / "data" / "raw" / "holidays"
destination_metadata_dir = PROJECT_ROOT / "data" / "metadata"
destination_raw_dir.mkdir(parents=True, exist_ok=True)
destination_metadata_dir.mkdir(parents=True, exist_ok=True)

destination_csv = destination_raw_dir / source_csv.name
destination_metadata = destination_metadata_dir / source_metadata.name

# Existing project-level files are canonical; never create timestamped copies.
if destination_csv.exists() and destination_metadata.exists():
    print("Existing project-level holiday files reused; no files moved or duplicated.")
else:
    if source_csv.exists() and not destination_csv.exists():
        shutil.move(str(source_csv), str(destination_csv))
    if source_metadata.exists() and not destination_metadata.exists():
        shutil.move(str(source_metadata), str(destination_metadata))

    if not destination_csv.exists() or not destination_metadata.exists():
        raise FileNotFoundError(
            "Required holiday CSV/metadata missing from both source and project locations. "
            "No duplicate files were created."
        )

    print("Holiday files placed in the project-level data directory.")

print("CSV:", destination_csv)
print("Metadata:", destination_metadata)

Existing project-level holiday files reused; no files moved or duplicated.
CSV: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\holidays\telangana_calendar_holidays_2023_2026.csv
Metadata: D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\metadata\telangana_holiday_source_metadata.json

In [59]:
print("PROJECT DATA DIRECTORY")
print("=" * 50)

for folder in [
    PROJECT_ROOT / "data" / "raw" / "holidays",
    PROJECT_ROOT / "data" / "metadata",
]:
    print(f"\n{folder.relative_to(PROJECT_ROOT)}/")

    for file in sorted(folder.iterdir()):
        if file.is_file():
            print("  ", file.name)

PROJECT DATA DIRECTORY
==================================================

data\raw\holidays/
   .gitkeep
   telangana_calendar_holidays_2023_2026.csv
   telangana_calendar_holidays_2023_2026_20261027T061439572130Z_1.csv

data\metadata/
   telangana_holiday_source_metadata.json
   telangana_holiday_source_metadata_20261027T061439572130Z_1.json
   weather_source_metadata.json
   weather_source_metadata_174578_783742.json
   weather_source_metadata_174578_783742_20261026T050752650642Z_1.json
   weather_source_metadata_174578_783742_20261027T060257213326Z_1.json
   weather_source_metadata_174578_783742_20261027T061315566513Z_1.json
   weather_source_metadata_20261026_103154.json
   weather_source_metadata_20261026_103426.json
   weather_source_metadata_20261027_113237.json
   weather_source_metadata_20261027_114256.json

In [60]:
from pathlib import Path
import pandas as pd
import json

PROJECT_ROOT = Path.cwd().parent

HOLIDAY_CSV = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "holidays"
    / "telangana_calendar_holidays_2023_2026.csv"
)

HOLIDAY_METADATA = (
    PROJECT_ROOT
    / "data"
    / "metadata"
    / "telangana_holiday_source_metadata.json"
)

# Confirm both files exist.
assert HOLIDAY_CSV.exists(), f"Missing CSV: {HOLIDAY_CSV}"
assert HOLIDAY_METADATA.exists(), (
    f"Missing metadata: {HOLIDAY_METADATA}"
)

# Reload from their final project locations.
holidays_final = pd.read_csv(HOLIDAY_CSV)

with open(HOLIDAY_METADATA, "r", encoding="utf-8") as f:
    holiday_metadata_final = json.load(f)

print("HOLIDAY DATASET VERIFICATION")
print("=" * 45)
print("CSV path:", HOLIDAY_CSV)
print("Metadata path:", HOLIDAY_METADATA)
print("Total records:", len(holidays_final))

print("\nRecords by year:")
display(
    holidays_final.groupby("year")
    .size()
    .rename("record_count")
    .to_frame()
)

print("\nMetadata record count:", holiday_metadata_final["record_count"])
print("CSV columns:", holidays_final.columns.tolist())

assert len(holidays_final) == 205
assert holiday_metadata_final["record_count"] == 205

print("\nPASS: Holiday files are accessible from the project root.")

HOLIDAY DATASET VERIFICATION
=============================================
CSV path: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\holidays\telangana_calendar_holidays_2023_2026.csv
Metadata path: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\metadata\telangana_holiday_source_metadata.json
Total records: 205

Records by year:

      record_count
year
2023            52
2024            52
2025            49
2026            52

Metadata record count: 205
CSV columns: ['date', 'year', 'holiday_name', 'calendar_class', 'source_table', 'source_url']

PASS: Holiday files are accessible from the project root.

# Phase 04.4 — Public Holiday Collection, Extraction, Validation, and Storage

## 1. Objective

The objective of this phase was to collect public holiday calendar data for Telangana, India, for the period 2023–2026. Public holidays are included as contextual variables because they may influence consumer food-ordering behaviour, particularly during festivals, regional celebrations, and other holiday periods.

The collected dataset will support the later investigation of relationships between public holidays and hourly food demand across synthetic hyperlocal zones in Hyderabad.

The holiday data was collected independently and stored in the project's raw-data directory. It has not yet been integrated with the food-demand dataset.

## 2. Data Source Selection

The Telangana State Portal was selected as the primary source for the annual holiday calendars.

The following official calendar pages were used:

| Year | Source                                                |
| ---- | ----------------------------------------------------- |
| 2023 | https://www.telangana.gov.in/Downloads/calendar-2023/ |
| 2024 | https://www.telangana.gov.in/downloads/calendar/      |
| 2025 | https://www.telangana.gov.in/downloads/calendar-2025/ |
| 2026 | https://www.telangana.gov.in/downloads/calendar-2026/ |

The calendar pages contain holiday entries organized by month. The source HTML represents holiday dates and names in tables, with date cells and holiday-name cells stored separately.

The HTML class associated with each date cell was retained as a source classification for subsequent verification.

## 3. Data Extraction Methodology

Python was used to retrieve and inspect the official calendar pages. The extraction process involved the following steps:

1. Retrieve each annual calendar page using HTTP requests.
2. Parse the returned HTML using BeautifulSoup.
3. Identify the HTML tables containing calendar dates and holiday names.
4. Extract date and holiday-name pairs from the corresponding table cells.
5. Identify the year associated with each source calendar.
6. Convert the extracted dates into standardized date values.
7. Retain the source HTML classification and table index.
8. Record the source URL for traceability.
9. Combine the yearly records into a consolidated dataset.

The initial text-based extraction approach did not identify the holiday entries because the page content was structured in HTML tables rather than in the expected plain-text format. The extraction method was subsequently adjusted to inspect the table structure directly.

This adjustment enabled the extraction of holiday records from all four annual calendar pages.

## 4. Dataset Structure

The consolidated dataset contains the following columns:

| Column           | Description                                                 |
| ---------------- | ----------------------------------------------------------- |
| `date`           | Standardized holiday date                                   |
| `year`           | Calendar year associated with the record                    |
| `holiday_name`   | Holiday name extracted from the source calendar             |
| `calendar_class` | Source HTML classification, retained as `fix` or `opt`      |
| `source_table`   | Index of the HTML table from which the record was extracted |
| `source_url`     | URL of the source calendar page                             |

The `calendar_class` field preserves the source representation. The labels `fix` and `opt` have not been treated as independently verified legal classifications. Their precise meaning and the official status of individual dates must be confirmed against relevant government notifications before final modeling.

## 5. Extraction Results

The extraction process produced the following record counts:

| Year      | Extracted Records |
| --------- | ----------------: |
| 2023      |                52 |
| 2024      |                52 |
| 2025      |                49 |
| 2026      |                52 |
| **Total** |           **205** |

The consolidated dataset contains 205 records across the four calendar years.

The record counts differ between years. These differences were retained as observed rather than artificially adjusted to produce equal annual totals.

## 6. Validation and Quality Checks

The extracted dataset was subjected to structural and consistency checks.

| Validation Check                                         | Result |
| -------------------------------------------------------- | ------ |
| Total record count                                       | 205    |
| Missing dates                                            | 0      |
| Missing holiday names                                    | 0      |
| Missing values in the inspected dataset fields           | 0      |
| Exact duplicate date-and-name records                    | 0      |
| Records whose date year disagrees with the declared year | 0      |
| Records outside their declared calendar year             | 0      |
| CSV saved successfully                                   | Pass   |
| Metadata saved successfully                              | Pass   |
| Saved files reloaded successfully                        | Pass   |

The source classification counts were also inspected.

| Year | `fix` | `opt` |
| ---- | ----: | ----: |
| 2023 |    28 |    24 |
| 2024 |    28 |    24 |
| 2025 |    27 |    22 |
| 2026 |    26 |    26 |

These counts describe the extracted HTML date-cell classes. They should not be interpreted as confirmed counts of legally designated general and optional holidays without further verification.

Some holiday names contain explanatory notes referring to other occasions or government holiday provisions. These notes were preserved during extraction to maintain traceability to the original calendar content.

The checks establish that the saved dataset is structurally consistent with the extracted records. They do not independently establish that every source entry is legally authoritative, correctly classified, or suitable as a separate modeling event.

## 7. Data Storage

The consolidated raw dataset was saved at:

`data/raw/holidays/telangana_calendar_holidays_2023_2026.csv`

The associated source metadata was saved at:

`data/metadata/telangana_holiday_source_metadata.json`

The metadata records the dataset identity, source information, and record count.

Both files were saved and subsequently reloaded successfully. Their locations were verified relative to the project root.

The holiday dataset remains separate from the processed weather dataset and the food-demand dataset.

## 8. Limitations and Further Verification

The following limitations must be considered before the holiday data is used for modeling:

1. **Classification verification:** The extracted `fix` and `opt` labels represent HTML classes. Their interpretation must be checked against official holiday notifications.
2. **Official status:** Annual calendar entries should not automatically be treated as legally confirmed general holidays without reviewing the relevant government documentation.
3. **Duplicate dates:** A single date may contain multiple holiday entries. The absence of exact duplicate date-and-name pairs does not mean every date is unique.
4. **Holiday-name normalization:** Original holiday names and explanatory notes have been retained. A separate normalization step may be required for modeling features.
5. **Calendar coverage:** The collection covers the annual calendars for 2023–2026. The actual dates represented in the files must be considered when constructing features for the demand observation period.
6. **Forecasting alignment:** Holiday features will need to be aligned to the demand timestamps and the appropriate local calendar dates in Asia/Kolkata.
7. **Feature engineering:** Separate indicators may later be constructed for holiday dates, holiday categories, and potentially adjacent dates, but these should be defined and justified before model training.

No demand-data integration or model training was performed during this phase.

## 9. Phase Completion Summary

Phase 04.4 successfully collected and consolidated holiday calendar entries from the Telangana State Portal for 2023–2026.

A total of 205 records were extracted, validated for basic structural consistency, saved to the designated project directories, and reloaded successfully. Source URLs and extraction classifications were retained to support reproducibility and later verification.

The dataset is ready for further source verification and feature-engineering preparation. Its classification fields must be interpreted cautiously until the relevant official notifications have been reviewed.

**Phase Status:** Collection, extraction, basic validation, and storage completed. Official classification verification and integration with the demand dataset remain pending.

# Phase 04.5 — Cricket Match Context Collection

## 1. Objective

The objective of this phase is to collect, consolidate, and validate historical cricket-match information that may influence food-ordering demand in Hyderabad, India.

Cricket matches can change consumer routines, viewing behaviour, social gatherings, restaurant activity, and food-delivery preferences. Evening matches and major tournaments may be associated with changes in order volume before, during, or after a match.

Collecting only Indian Premier League (IPL) matches would provide an incomplete representation of cricket-related events. Therefore, this phase will cover multiple categories of cricket matches, including IPL, international cricket hosted in India, major domestic T20 competitions, and international tournaments conducted at Indian venues.

The resulting dataset will provide contextual information for investigating whether cricket events contribute to variations in hourly food demand across synthetic hyperlocal zones in Hyderabad.

The collection will remain independent of the demand dataset until the contextual records have been collected, validated, and documented.

## 2. Scope of Cricket Events

The following event categories will be investigated.

### 2.1 Indian Premier League (IPL)

The dataset will include IPL matches from the selected study period, including league-stage matches and playoff matches.

Where available, the collection will capture match dates, scheduled start times, participating teams, tournament stage, venue, city, and match status.

IPL matches held in Hyderabad will receive particular attention because they may have a more direct relationship with local food demand.

### 2.2 India Men's International Cricket

This category will cover India's men's international matches hosted in India against visiting national teams.

The formats of interest are:

* Test matches
* One Day Internationals (ODIs)
* Twenty20 Internationals (T20Is)

The collection will include bilateral series and international tournament matches, subject to source availability and clear classification.

International matches played in Hyderabad will be identified separately from matches held elsewhere in India.

### 2.3 India Women's International Cricket

Women's international matches hosted in India will be investigated where reliable historical fixture information is available.

The dataset will distinguish women's international cricket from men's international cricket so that their potential associations with demand can be evaluated separately.

### 2.4 Women's Premier League (WPL)

WPL matches will be included as a separate domestic T20 competition category.

The collection will identify tournament dates, participating teams, match venues, scheduled start times, and tournament stages where these details are available.

WPL records will remain distinguishable from IPL records throughout the collection and validation process.

### 2.5 Major International Cricket Tournaments Hosted in India

Major international tournaments will be included when matches are hosted at venues in India.

Examples include ICC tournaments and other major international competitions for which reliable match-level information is available.

Only verified matches will be included. Tournament-level dates alone will not be treated as individual match records.

### 2.6 Other Major Domestic Cricket Events

Other significant domestic cricket competitions may be investigated if reliable match schedules and venue information are available.

Examples may include selected major domestic T20 competitions and other nationally significant cricket events.

This category will be prioritized after the principal event categories have been investigated. Inclusion will depend on data quality, availability, and relevance to the forecasting study.

## 3. Study Period

The initial collection period will cover **1 January 2023 through 31 July 2026**, subject to confirmation against the actual demand-data coverage and the availability of reliable historical cricket records.

The final contextual dataset must not imply that data exists for periods that have not been verified.

If a relevant match or tournament falls outside the final demand observation period, it will be excluded from the primary modeling dataset unless there is a specific methodological reason to retain it.

## 4. Geographical Scope

The geographical scope will include relevant cricket matches hosted in India, with additional attention to Hyderabad.

Matches will be classified into the following geographical groups:

| Geographical category                        | Purpose                                                                                                                          |
| -------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| Hyderabad                                    | Primary local cricket-event context                                                                                              |
| Other locations in Telangana, where relevant | Additional regional context                                                                                                      |
| Other cities in India                        | National cricket-event context                                                                                                   |
| Locations outside India                      | Excluded from the primary India-hosted match dataset; considered separately only if required for a national-team match indicator |

Venue and city information will be retained wherever available.

The collection will distinguish matches hosted in Hyderabad from matches hosted elsewhere in India. This distinction is important because the effect of a local stadium event may differ from the effect of a match taking place in another city.

The geographical classification will be based on verified venue information rather than assumptions based on participating teams or tournament names.

## 5. Data Source Selection Strategy

Official and authoritative sources will be prioritized.

Potential sources to investigate include:

* The Board of Control for Cricket in India (BCCI) for India's international fixtures and domestic cricket schedules.
* The official IPL website for IPL schedules, match results, and venues.
* The official WPL website for Women's Premier League fixtures and match information.
* The International Cricket Council (ICC) for international tournaments and relevant match records.
* Other official tournament organizers or cricket-board websites when required.

Sources will be evaluated for historical coverage, match-level detail, reliability, accessibility, and consistency.

Where multiple sources provide the same match information, records will be cross-checked when practical. Secondary sources may be used to investigate gaps, but important records should be verified against authoritative sources wherever possible.

The selected source and source URL will be recorded for traceability.

No source will be treated as complete until its coverage has been investigated.

## 6. Proposed Dataset Structure

A consolidated match-level dataset will be developed. Each record will represent one cricket match.

The following fields are proposed:

| Column               | Description                                                                   |
| -------------------- | ----------------------------------------------------------------------------- |
| `match_id`           | Unique identifier assigned to a match                                         |
| `match_date`         | Verified match date                                                           |
| `match_start_time`   | Scheduled local start time, where available                                   |
| `match_end_time`     | Actual end time, where reliably available                                     |
| `match_format`       | T20, ODI, Test, or another verified format                                    |
| `event_category`     | IPL, WPL, international bilateral series, ICC tournament, or domestic cricket |
| `tournament_name`    | Name of the tournament or series                                              |
| `tournament_stage`   | League stage, group stage, semifinal, final, or other applicable stage        |
| `team_1`             | First participating team                                                      |
| `team_2`             | Second participating team                                                     |
| `india_involved`     | Indicator of whether India's national team participated                       |
| `venue_name`         | Verified stadium or venue name                                                |
| `city`               | City hosting the match                                                        |
| `state`              | State or territory hosting the match, where applicable                        |
| `host_country`       | Country hosting the match                                                     |
| `is_india_hosted`    | Indicator of whether the match was hosted in India                            |
| `is_hyderabad_match` | Indicator of whether the match venue is in Hyderabad                          |
| `match_status`       | Verified status, such as scheduled, completed, abandoned, or postponed        |
| `source_url`         | Source used to obtain or verify the record                                    |

Fields will be populated only when supported by the available evidence. Missing scheduled or actual times will remain missing rather than being estimated without justification.

Additional fields may be introduced if they are necessary for source traceability or subsequent feature engineering.

## 7. Data Collection Methodology

The collection process will follow these steps:

1. Identify official sources for each cricket-event category.
2. Inspect the available historical coverage and data structure.
3. Define a consistent match-level schema.
4. Collect match schedules and relevant historical match details.
5. Standardize dates, times, team names, venue names, and event categories.
6. Retain source URLs and other necessary provenance information.
7. Combine the category-specific records into a consolidated dataset.
8. Investigate overlapping records across tournaments and sources.
9. Identify duplicate matches and resolve them using reliable identifiers and match details.
10. Validate date coverage, geographical coverage, match formats, and required fields.
11. Save the validated raw dataset and associated source metadata.
12. Document collection limitations and unresolved data-quality issues.

The process will preserve source information so that records can be traced back to their origins.

## 8. Validation and Quality Assurance

The consolidated dataset will be assessed using the following checks:

* Missing dates and invalid date values.
* Match dates outside the intended collection period.
* Duplicate match records.
* Missing or inconsistent participating-team information.
* Missing venue and city information.
* Incorrect or inconsistent event-category labels.
* Invalid or inconsistent match-format labels.
* Scheduled and actual times that cannot be verified.
* Inconsistencies between source records.
* Incorrect Hyderabad or India-hosted classifications.
* Missing source URLs and insufficient record provenance.
* Coverage gaps across years, event categories, and geographical locations.

Validation results will be documented after the relevant collection steps have been executed.

Record counts, missing-value totals, duplicate counts, and coverage summaries will be reported from actual notebook outputs. No unverified counts will be assumed in advance.

## 9. Planned Feature Engineering

After collection and validation, cricket-match information may be transformed into features suitable for hourly food-demand forecasting.

Potential features include:

| Feature                            | Purpose                                                                         |
| ---------------------------------- | ------------------------------------------------------------------------------- |
| `is_cricket_match_day`             | Indicates whether at least one qualifying cricket match occurs on the date      |
| `is_ipl_match_day`                 | Identifies IPL match dates                                                      |
| `is_wpl_match_day`                 | Identifies WPL match dates                                                      |
| `is_india_international_match_day` | Identifies qualifying India international match dates                           |
| `is_hyderabad_match_day`           | Identifies cricket matches hosted in Hyderabad                                  |
| `is_india_hosted_match_day`        | Identifies matches hosted in India                                              |
| `cricket_matches_today`            | Counts qualifying matches on a date                                             |
| `minutes_until_match_start`        | Measures the time until a relevant scheduled match begins                       |
| `minutes_since_match_start`        | Measures elapsed time since a relevant match begins                             |
| `is_match_in_progress`             | Indicates whether a match is in progress, when timing information supports this |
| `is_match_evening`                 | Identifies matches scheduled in a defined evening window                        |
| `major_cricket_event_indicator`    | Identifies selected major cricket events using an explicit rule                 |

These are proposed features, not completed outputs.

Feature definitions will be finalized after the source data has been inspected. Match-window features will use verified times and an explicitly documented time-zone convention.

Where actual match end times are unavailable, the methodology will not assume that a match ended at a particular time.

The feature-engineering process will also avoid double-counting the same match when multiple sources report it.

## 10. Integration Strategy

The validated cricket dataset will initially remain separate from the demand dataset.

After all required contextual datasets have been collected and validated, cricket information can be aligned with the demand timestamps and the study's local time zone, Asia/Kolkata.

The integration process will consider:

* Hourly demand timestamps.
* Match dates and verified start times.
* Match venues and geographical relevance.
* Event categories and tournament types.
* The possibility of multiple matches occurring on the same date.
* The distinction between local Hyderabad events and events elsewhere in India.

The project will investigate whether cricket context improves demand forecasts through comparative evaluation rather than assuming that all matches cause a demand increase.

## 11. Expected Outputs

The planned outputs are:

1. A consolidated raw cricket-match dataset.
2. Source metadata documenting the selected sources, collection period, and extraction details.
3. A validation summary covering completeness, duplicates, date coverage, and geographical classification.
4. Documentation of source limitations and unresolved issues.
5. A defined set of cricket-related contextual features for later integration and modeling.

The exact file names and paths will be finalized during the source-selection and collection steps, following the existing project directory structure.

## 12. Phase Completion Criteria

Phase 04.5 will be considered complete when:

* The principal cricket-event categories have been investigated.
* Suitable sources have been identified and their limitations documented.
* Relevant match records have been collected for the selected period.
* The consolidated schema has been applied consistently.
* Duplicate records and data inconsistencies have been investigated.
* Venue and geographical classifications have been validated where possible.
* Source metadata has been retained.
* The raw dataset has been saved and reloaded successfully.
* Validation results and remaining limitations have been documented.

## 13. Phase Status

**Status: Planned — collection and validation have not yet started.**

Phase 04.5 establishes the methodology for collecting IPL, international, and other relevant cricket-match context. The next step is to investigate candidate sources, assess their historical coverage, and select an appropriate collection strategy before implementing the extraction code.

In [61]:
# Phase 04.5.1 — Download Cricsheet Annual JSON Archives

from pathlib import Path
import requests
import pandas as pd

BASE_URL = "https://cricsheet.org/downloads/"
YEARS = [2023, 2024, 2025, 2026]

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
OUTPUT_DIR = PROJECT_ROOT / "data" / "raw" / "cricket" / "cricsheet"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

session = requests.Session()
session.headers.update({"User-Agent": "FoodDemandForecastingResearch/1.0"})

results = []

for year in YEARS:
    filename = f"{year}_json.zip"
    url = f"{BASE_URL}{filename}"
    output_path = OUTPUT_DIR / filename

    if output_path.is_file() and output_path.stat().st_size > 0:
        results.append({
            "year": year, "source": "Cricsheet", "url": url,
            "file": str(output_path),
            "size_mb": round(output_path.stat().st_size / (1024 * 1024), 2),
            "status": "reused existing archive"
        })
        print(f"Reusing existing {year} archive.")
        continue

    print(f"Downloading {year} archive...")

    try:
        response = session.get(url, timeout=120)
        response.raise_for_status()

        if not response.content.startswith(b"PK"):
            raise ValueError("Downloaded file is not a valid ZIP archive.")

        output_path.write_bytes(response.content)

        results.append({
            "year": year,
            "source": "Cricsheet",
            "url": url,
            "file": str(output_path),
            "size_mb": round(len(response.content) / (1024 * 1024), 2),
            "status": "success"
        })

    except Exception as exc:
        results.append({
            "year": year,
            "source": "Cricsheet",
            "url": url,
            "file": str(output_path),
            "size_mb": None,
            "status": f"failed: {exc}"
        })

download_df = pd.DataFrame(results)

display(download_df)

print("\nSuccessful downloads:",
      (download_df["status"] == "success").sum(),
      "of", len(YEARS))

Reusing existing 2023 archive.
Reusing existing 2024 archive.
Reusing existing 2025 archive.
Reusing existing 2026 archive.

,year,source,url,file,size_mb,status
0,2023,Cricsheet,https://cricsheet.org/downloads/2023_json.zip,D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet\2023_json.zip,11.24,reused existing archive
1,2024,Cricsheet,https://cricsheet.org/downloads/2024_json.zip,D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet\2024_json.zip,13.13,reused existing archive
2,2025,Cricsheet,https://cricsheet.org/downloads/2025_json.zip,D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet\2025_json.zip,14.40,reused existing archive
3,2026,Cricsheet,https://cricsheet.org/downloads/2026_json.zip,D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet\2026_json.zip,12.21,reused existing archive

Successful downloads: 0 of 4

In [62]:
# Phase 04.5.1 — Download and validate Cricsheet JSON archives

from pathlib import Path
import requests
import pandas as pd
import zipfile
import io

BASE_URL = "https://cricsheet.org/downloads/"
YEARS = [2023, 2024, 2025, 2026]

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
OUTPUT_DIR = PROJECT_ROOT / "data" / "raw" / "cricket" / "cricsheet"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (compatible; FoodDemandResearch/1.0)"
})

results = []

for year in YEARS:
    filename = f"{year}_json.zip"
    url = BASE_URL + filename
    output_path = OUTPUT_DIR / filename

    if output_path.is_file() and output_path.stat().st_size > 0:
        try:
            with zipfile.ZipFile(output_path) as archive:
                json_files = [n for n in archive.namelist() if n.lower().endswith(".json")]
                bad_file = archive.testzip()
                if not json_files or bad_file:
                    raise ValueError("Existing archive failed validation")
            results.append({
                "year": year, "status": "reused existing archive",
                "json_files_in_archive": len(json_files),
                "size_mb": round(output_path.stat().st_size / (1024 * 1024), 2),
                "content_type": "existing local file", "file": str(output_path)
            })
            print(f"Reusing existing validated {year} archive.")
            continue
        except Exception:
            print(f"Existing {year} archive invalid; redownloading it.")

    print(f"Checking {year} archive...")

    try:
        response = session.get(
            url,
            timeout=120,
            allow_redirects=True
        )

        content_type = response.headers.get("Content-Type", "")

        if response.status_code != 200:
            raise ValueError(f"HTTP {response.status_code}")

        # Validate the response as a ZIP archive.
        with zipfile.ZipFile(io.BytesIO(response.content)) as archive:
            json_files = [
                name for name in archive.namelist()
                if name.lower().endswith(".json")
            ]

            if not json_files:
                raise ValueError("ZIP contains no JSON files")

            bad_file = archive.testzip()
            if bad_file:
                raise ValueError(f"Corrupt archive member: {bad_file}")

        output_path.write_bytes(response.content)

        results.append({
            "year": year,
            "status": "success",
            "json_files_in_archive": len(json_files),
            "size_mb": round(len(response.content) / (1024 * 1024), 2),
            "content_type": content_type,
            "file": str(output_path)
        })

    except Exception as exc:
        results.append({
            "year": year,
            "status": f"failed: {exc}",
            "json_files_in_archive": None,
            "size_mb": None,
            "content_type": (
                response.headers.get("Content-Type", "")
                if "response" in locals() else ""
            ),
            "file": None
        })

download_df = pd.DataFrame(results)
display(download_df)

print(
    f"\nSuccessful downloads: "
    f"{(download_df['status'] == 'success').sum()} of {len(YEARS)}"
)

Reusing existing validated 2023 archive.
Reusing existing validated 2024 archive.
Reusing existing validated 2025 archive.
Reusing existing validated 2026 archive.

,year,status,json_files_in_archive,size_mb,content_type,file
0,2023,reused existing archive,2009,11.24,existing local file,D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet\2023_json.zip
1,2024,reused existing archive,2441,13.13,existing local file,D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet\2024_json.zip
2,2025,reused existing archive,2546,14.40,existing local file,D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet\2025_json.zip
3,2026,reused existing archive,2246,12.21,existing local file,D:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet\2026_json.zip

Successful downloads: 0 of 4

In [63]:
# Phase 04.5.1 — Diagnose Cricsheet download response

import requests

url = "https://cricsheet.org/downloads/2025_json.zip"

try:
    response = requests.get(
        url,
        headers={"User-Agent": "Mozilla/5.0"},
        timeout=30
    )

    print("HTTP status:", response.status_code)
    print("Final URL:", response.url)
    print("Content-Type:", response.headers.get("Content-Type"))
    print("Content length:", len(response.content), "bytes")
    print("\nResponse preview:")
    print(response.text[:1000] if "text" in response.headers.get(
        "Content-Type", ""
    ).lower() else response.content[:100])

except requests.RequestException as exc:
    print("Request failed:", repr(exc))

HTTP status: 200
Final URL: https://cricsheet.org/downloads/2025_json.zip
Content-Type: application/zip
Content length: 15095136 bytes

Response preview:
b'PK\x03\x04\x14\x00\x00\x00\x08\x00x\x95Y]\x19\xca\x07\xe7\x06k\x00\x00\xa5\xfc\x02\x00\n\x00\x00\x00README.txt\xad\xbd\xdb\x96\x1b\xc7\xb1&|\xaf\xa7\xa8;\xcf\xace\xc9uF\xe1\xbf#)Y\x96EJ\xdcj\x8e\xb5\xf6\xbe\xf9W\xb1\x1b\xec\x86\x89\x06z\xd0\x80\xa8\xd6\xd3Ofd\x01\xc8\x88\x8c\x8c\x88\x82|\xe3\x03'

In [64]:
# Phase 04.5.1 — Validate Cricket ZIP Archives

from pathlib import Path
from zipfile import ZipFile, BadZipFile
import pandas as pd

# Project root: notebook is inside the notebooks folder
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

CRICKET_DIR = PROJECT_ROOT / "data" / "raw" / "cricket" / "cricsheet"

ZIP_FILES = [
    CRICKET_DIR / "all_csv2.zip",
    CRICKET_DIR / "ipl_csv2.zip",
]

results = []

for zip_path in ZIP_FILES:
    result = {
        "file": zip_path.name,
        "exists": zip_path.is_file(),
        "size_mb": None,
        "integrity": "Not checked",
        "csv_files": 0,
        "other_files": 0,
        "sample_files": None,
    }

    if zip_path.is_file():
        result["size_mb"] = round(
            zip_path.stat().st_size / (1024 * 1024), 2
        )

        try:
            with ZipFile(zip_path, "r") as archive:
                bad_file = archive.testzip()
                names = [
                    name for name in archive.namelist()
                    if not name.endswith("/")
                ]

                if bad_file:
                    result["integrity"] = f"Corrupt member: {bad_file}"
                else:
                    result["integrity"] = "Valid"

                result["csv_files"] = sum(
                    name.lower().endswith(".csv") for name in names
                )
                result["other_files"] = sum(
                    not name.lower().endswith(".csv") for name in names
                )
                result["sample_files"] = ", ".join(names[:5])

        except BadZipFile:
            result["integrity"] = "Invalid ZIP"

    results.append(result)

display(pd.DataFrame(results))

print("\nExpected folder:", CRICKET_DIR)

           file  exists  size_mb integrity  csv_files  other_files                                                              sample_files
0  all_csv2.zip    True   117.20     Valid      46386            2  README.txt, 1000851.csv, 1000851_info.csv, 1000853.csv, 1000853_info.csv
1  ipl_csv2.zip    True     6.52     Valid       2487            2       README.txt, LICENSE.txt, 1082591.csv, 1082591_info.csv, 1082592.csv

Expected folder: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\cricket\cricsheet

In [65]:
# Phase 04.5.2 — Inspect CSV schemas inside the cricket archives

from pathlib import Path
from zipfile import ZipFile
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

CRICKET_DIR = PROJECT_ROOT / "data" / "raw" / "cricket" / "cricsheet"

archives = [
    CRICKET_DIR / "all_csv2.zip",
    CRICKET_DIR / "ipl_csv2.zip",
]

for archive_path in archives:
    print(f"\n{'=' * 70}")
    print(f"ARCHIVE: {archive_path.name}")
    print("=" * 70)

    with ZipFile(archive_path) as archive:
        csv_names = [
            name for name in archive.namelist()
            if name.lower().endswith(".csv")
        ]

        # Locate likely match-level metadata files from archive filenames.
        candidates = [
            name for name in csv_names
            if any(key in Path(name).name.lower()
                   for key in ("info", "match", "metadata"))
        ]

        print("Total CSV files:", len(csv_names))
        print("Likely metadata files:", candidates[:10])

        # Inspect a few files to establish the real schema.
        for name in candidates[:3]:
            with archive.open(name) as file:
                sample = pd.read_csv(file, nrows=5)

            print(f"\nFile: {name}")
            print("Columns:", sample.columns.tolist())
            display(sample)

        if not candidates:
            print("No metadata filename matched. Example CSV filenames:")
            print(csv_names[:10])

======================================================================
ARCHIVE: all_csv2.zip
======================================================================
Total CSV files: 46386
Likely metadata files: ['1000851_info.csv', '1000853_info.csv', '1000855_info.csv', '1000881_info.csv', '1000883_info.csv', '1000885_info.csv', '1000887_info.csv', '1000889_info.csv', '1000891_info.csv', '1000893_info.csv']

File: 1000851_info.csv
Columns: ['version', '2.3.0']

             version          2.3.0
info  balls_per_over              6
info            team      Australia
info            team   South Africa
info       team_type  international
info          gender           male

File: 1000853_info.csv
Columns: ['version', '2.3.0']

             version          2.3.0
info  balls_per_over              6
info            team      Australia
info            team   South Africa
info       team_type  international
info          gender           male

File: 1000855_info.csv
Columns: ['version', '2.3.0']

             version          2.3.0
info  balls_per_over              6
info            team      Australia
info            team   South Africa
info       team_type  international
info          gender           male

======================================================================
ARCHIVE: ipl_csv2.zip
======================================================================
Total CSV files: 2487
Likely metadata files: ['1082591_info.csv', '1082592_info.csv', '1082593_info.csv', '1082594_info.csv', '1082595_info.csv', '1082596_info.csv', '1082597_info.csv', '1082598_info.csv', '1082599_info.csv', '1082600_info.csv']

File: 1082591_info.csv
Columns: ['version', '2.3.0']

             version                        2.3.0
info  balls_per_over                            6
info            team          Sunrisers Hyderabad
info            team  Royal Challengers Bangalore
info       team_type                         club
info          gender                         male

File: 1082592_info.csv
Columns: ['version', '2.3.0']

             version                   2.3.0
info  balls_per_over                       6
info            team  Rising Pune Supergiant
info            team          Mumbai Indians
info       team_type                    club
info          gender                    male

File: 1082593_info.csv
Columns: ['version', '2.3.0']

             version                  2.3.0
info  balls_per_over                      6
info            team          Gujarat Lions
info            team  Kolkata Knight Riders
info       team_type                   club
info          gender                   male

In [66]:
# Phase 04.5.3 — Inspect Cricsheet metadata structure

from pathlib import Path
from zipfile import ZipFile
import csv

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

CRICKET_DIR = PROJECT_ROOT / "data" / "raw" / "cricket" / "cricsheet"
archive_path = CRICKET_DIR / "all_csv2.zip"

with ZipFile(archive_path) as archive:
    info_files = [
        name for name in archive.namelist()
        if name.lower().endswith("_info.csv")
    ]

    # Inspect one file whose match ID starts with a likely recent ID.
    # Show the first metadata file for diagnosis.
    sample_file = info_files[0]

    print("Sample file:", sample_file)
    print("\nFirst 25 rows:")

    with archive.open(sample_file) as raw_file:
        reader = csv.reader(
            line.decode("utf-8-sig") for line in raw_file
        )

        for i, row in enumerate(reader):
            print(row)
            if i >= 24:
                break

Sample file: 1000851_info.csv

First 25 rows:
['version', '2.3.0']
['info', 'balls_per_over', '6']
['info', 'team', 'Australia']
['info', 'team', 'South Africa']
['info', 'team_type', 'international']
['info', 'gender', 'male']
['info', 'season', '2016/17']
['info', 'date', '2016/11/03']
['info', 'date', '2016/11/04']
['info', 'date', '2016/11/05']
['info', 'date', '2016/11/06']
['info', 'date', '2016/11/07']
['info', 'event', 'South Africa in Australia Test Series']
['info', 'match_id', '1000851']
['info', 'match_type', 'Test']
['info', 'match_type_number', '2230']
['info', 'match_number', '1']
['info', 'venue', 'Western Australia Cricket Association Ground']
['info', 'city', 'Perth']
['info', 'toss_winner', 'South Africa']
['info', 'toss_decision', 'bat']
['info', 'player_of_match', 'K Rabada']
['info', 'umpire', 'Aleem Dar']
['info', 'umpire', 'NJ Llong']
['info', 'reserve_umpire', 'SJ Nogajski']

In [67]:
# Phase 04.5.3 — Parse Cricsheet match metadata correctly

from pathlib import Path
from zipfile import ZipFile
import csv
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

CRICKET_DIR = PROJECT_ROOT / "data" / "raw" / "cricket" / "cricsheet"
OUTPUT_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

START_DATE = pd.Timestamp("2023-01-01")
END_DATE = pd.Timestamp("2026-07-31")

def parse_info_csv(archive, member):
    metadata = {}

    with archive.open(member) as raw_file:
        reader = csv.reader(
            line.decode("utf-8-sig") for line in raw_file
        )

        for row in reader:
            # Cricsheet format: info, field_name, field_value
            if len(row) < 3 or row[0].strip() != "info":
                continue

            key = row[1].strip()
            value = row[2].strip()

            if key in metadata:
                if not isinstance(metadata[key], list):
                    metadata[key] = [metadata[key]]
                metadata[key].append(value)
            else:
                metadata[key] = value

    return metadata

def as_text(value):
    if isinstance(value, list):
        return " | ".join(value)
    return value

records = []

for archive_name in ["all_csv2.zip", "ipl_csv2.zip"]:
    archive_path = CRICKET_DIR / archive_name

    if not archive_path.exists():
        raise FileNotFoundError(f"Archive not found: {archive_path}")

    with ZipFile(archive_path) as archive:
        info_files = [
            name for name in archive.namelist()
            if name.lower().endswith("_info.csv")
        ]

        for member in info_files:
            metadata = parse_info_csv(archive, member)

            date_value = metadata.get("date")
            if not date_value:
                continue

            # Some matches have multiple dates; use the first recorded date.
            first_date = (
                date_value[0]
                if isinstance(date_value, list)
                else date_value
            )

            match_date = pd.to_datetime(
                first_date, format="%Y/%m/%d", errors="coerce"
            )

            if pd.isna(match_date):
                continue

            if not START_DATE <= match_date <= END_DATE:
                continue

            teams = metadata.get("team", [])
            if not isinstance(teams, list):
                teams = [teams]

            records.append({
                "match_id": str(metadata.get(
                    "match_id",
                    Path(member).name.replace("_info.csv", "")
                )),
                "match_date": match_date.date().isoformat(),
                "teams": " | ".join(map(str, teams)),
                "match_type": as_text(metadata.get("match_type")),
                "team_type": as_text(metadata.get("team_type")),
                "gender": as_text(metadata.get("gender")),
                "venue": as_text(metadata.get("venue")),
                "city": as_text(metadata.get("city")),
                "event": as_text(metadata.get("event")),
                "source_archive": archive_name,
                "source_file": member,
            })

matches = pd.DataFrame(records)

if matches.empty:
    raise ValueError(
        "No matches found. Check the metadata structure and date fields."
    )

all_matches = (
    matches[matches["source_archive"] == "all_csv2.zip"]
    .drop_duplicates(subset="match_id")
    .copy()
)

ipl_matches = (
    matches[matches["source_archive"] == "ipl_csv2.zip"]
    .drop_duplicates(subset="match_id")
    .copy()
)

all_path = OUTPUT_DIR / "cricket_matches_metadata_2023_2026.csv"
ipl_path = OUTPUT_DIR / "ipl_matches_metadata_2023_2026.csv"

all_matches.to_csv(all_path, index=False)
ipl_matches.to_csv(ipl_path, index=False)

print("Metadata extraction completed.")
print("All-archive matches:", len(all_matches))
print("IPL-archive matches:", len(ipl_matches))
print(
    "All-archive date range:",
    all_matches["match_date"].min(),
    "to",
    all_matches["match_date"].max()
)
print("Saved:", all_path)
print("Saved:", ipl_path)

display(all_matches.head(10))

Metadata extraction completed.
All-archive matches: 8546
IPL-archive matches: 293
All-archive date range: 2023-01-01 to 2026-07-31
Saved: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_matches_metadata_2023_2026.csv
Saved: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\ipl_matches_metadata_2023_2026.csv

  match_id  match_date                     teams match_type      team_type gender                         venue             city                           event source_archive       source_file
0  1317494  2023-01-04  Australia | South Africa       Test  international   male         Sydney Cricket Ground           Sydney  South Africa tour of Australia   all_csv2.zip  1317494_info.csv
1  1322355  2023-02-16     England | New Zealand       Test  international   male     Bay Oval, Mount Maunganui  Mount Maunganui     England tour of New Zealand   all_csv2.zip  1322355_info.csv
2  1322356  2023-02-24     England | New Zealand       Test  international   male     Basin Reserve, Wellington       Wellington     England tour of New Zealand   all_csv2.zip  1322356_info.csv
3  1322357  2023-03-09   Sri Lanka | New Zealand       Test  international   male     Hagley Oval, Christchurch     Christchurch   Sri Lanka tour of New Zealand   all_csv2.zip  1322357_info.csv
4  1322358  2023-03-17   New Zealand | Sri Lanka       Test  international   male     Basin Reserve, Wellington       Wellington   Sri Lanka tour of New Zealand   all_csv2.zip  1322358_info.csv
5  1322359  2023-03-25   New Zealand | Sri Lanka        ODI  international   male           Eden Park, Auckland         Auckland   Sri Lanka tour of New Zealand   all_csv2.zip  1322359_info.csv
6  1322361  2023-03-31   Sri Lanka | New Zealand        ODI  international   male         Seddon Park, Hamilton         Hamilton   Sri Lanka tour of New Zealand   all_csv2.zip  1322361_info.csv
7  1322362  2023-04-02   Sri Lanka | New Zealand        T20  international   male           Eden Park, Auckland         Auckland   Sri Lanka tour of New Zealand   all_csv2.zip  1322362_info.csv
8  1322363  2023-04-05   Sri Lanka | New Zealand        T20  international   male      University Oval, Dunedin          Dunedin   Sri Lanka tour of New Zealand   all_csv2.zip  1322363_info.csv
9  1322364  2023-04-08   Sri Lanka | New Zealand        T20  international   male  John Davies Oval, Queenstown       Queenstown   Sri Lanka tour of New Zealand   all_csv2.zip  1322364_info.csv

In [68]:
# Phase 04.5.4 — Classify cricket matches for the forecasting project

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_matches_metadata_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_matches_classified_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

# Normalize text for reliable classification.
teams_text = matches["teams"].fillna("").str.casefold()
event_text = matches["event"].fillna("").str.casefold()
venue_text = matches["venue"].fillna("").str.casefold()
city_text = matches["city"].fillna("").str.casefold()
source_text = matches["source_archive"].fillna("").str.casefold()

# India national-team involvement: exact team-name boundaries.
india_pattern = r"(?<![a-z])india(?![a-z])"
matches["india_involved"] = teams_text.str.contains(
    india_pattern, regex=True, na=False
)

# Event categories based on recorded event names.
matches["is_world_cup"] = event_text.str.contains(
    r"world cup|worldcup", regex=True, na=False
)

matches["is_ipl"] = (
    event_text.str.contains(r"\bindian premier league\b|\bipl\b",
                            regex=True, na=False)
    | source_text.eq("ipl_csv2.zip")
)

matches["is_wpl"] = event_text.str.contains(
    r"\bwomen.?s premier league\b|\bwpl\b",
    regex=True, na=False
)

# Identify Hyderabad using recorded venue/city text.
matches["is_hyderabad_match"] = (
    city_text.str.contains(r"\bhyderabad\b", regex=True, na=False)
    | venue_text.str.contains(r"\bhyderabad\b", regex=True, na=False)
)

# Host-country classification needs independent venue verification.
matches["is_india_hosted"] = pd.Series(
    pd.NA, index=matches.index, dtype="boolean"
)

# Preserve an explicit classification status for the next verification step.
matches["host_country_verification"] = "pending"

# Save classified master dataset.
matches.to_csv(OUTPUT_FILE, index=False)

# Concise summary.
summary = pd.DataFrame({
    "classification": [
        "Total matches",
        "India national-team matches",
        "World Cup event matches",
        "IPL matches",
        "WPL matches",
        "Hyderabad venue/city matches",
        "Host country pending verification",
    ],
    "count": [
        len(matches),
        int(matches["india_involved"].sum()),
        int(matches["is_world_cup"].sum()),
        int(matches["is_ipl"].sum()),
        int(matches["is_wpl"].sum()),
        int(matches["is_hyderabad_match"].sum()),
        int(matches["is_india_hosted"].isna().sum()),
    ]
})

print("Phase 04.5.4 completed.")
print("Saved:", OUTPUT_FILE)
display(summary)

print("\nSample classified records:")
display(
    matches.loc[
        matches["india_involved"] | matches["is_hyderabad_match"],
        [
            "match_date", "teams", "match_type", "event",
            "venue", "city", "india_involved",
            "is_world_cup", "is_ipl", "is_wpl",
            "is_hyderabad_match", "is_india_hosted"
        ]
    ].head(10)
)

Phase 04.5.4 completed.
Saved: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_matches_classified_2023_2026.csv

                      classification  count
0                      Total matches   8546
1        India national-team matches    298
2            World Cup event matches   1188
3                        IPL matches    293
4                        WPL matches     88
5       Hyderabad venue/city matches     32
6  Host country pending verification   8546

Sample classified records:

,match_date,teams,match_type,event,venue,city,india_involved,is_world_cup,is_ipl,is_wpl,is_hyderabad_match,is_india_hosted
111,2023-02-12,Pakistan | India,T20,ICC Women's T20 World Cup,"Newlands, Cape Town",Cape Town,True,True,False,False,False,<NA>
116,2023-02-15,West Indies | India,T20,ICC Women's T20 World Cup,"Newlands, Cape Town",Cape Town,True,True,False,False,False,<NA>
121,2023-02-18,England | India,T20,ICC Women's T20 World Cup,"St George's Park, Gqeberha",Gqeberha,True,True,False,False,False,<NA>
125,2023-02-20,India | Ireland,T20,ICC Women's T20 World Cup,"St George's Park, Gqeberha",Gqeberha,True,True,False,False,False,<NA>
128,2023-02-23,Australia | India,T20,ICC Women's T20 World Cup,"Newlands, Cape Town",Cape Town,True,True,False,False,False,<NA>
232,2023-01-19,India | South Africa,T20,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,False,False,False,<NA>
234,2023-01-23,India | West Indies,T20,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,False,False,False,<NA>
236,2023-01-28,India | South Africa,T20,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,False,False,False,<NA>
237,2023-01-30,West Indies | India,T20,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,False,False,False,<NA>
238,2023-02-02,India | South Africa,T20,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,False,False,False,<NA>

In [69]:
# Phase 04.5.5 — Verify Indian venues and classify host country

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_matches_classified_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_matches_host_verified_2023_2026.csv"
REVIEW_FILE = DATA_DIR / "cricket_venue_verification_review_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

# Recognized Indian cricket cities.
# City matching is a preliminary location signal, not independent proof.
INDIAN_CITIES = {
    "ahmedabad", "amritsar", "bengaluru", "bangalore", "bhubaneswar",
    "chandigarh", "chennai", "coimbatore", "cuttack", "dehradun",
    "dharamshala", "faridabad", "goa", "guwahati", "gwalior",
    "hyderabad", "indore", "jaipur", "jammu", "jamshedpur",
    "kanpur", "kochi", "kolkata", "lucknow", "mohali", "mumbai",
    "nagpur", "new delhi", "delhi", "noida", "patna", "pune",
    "rajkot", "ranchi", "surat", "thiruvananthapuram", "vadodara",
    "visakhapatnam", "vizag"
}

city = matches["city"].fillna("").str.strip().str.casefold()
venue = matches["venue"].fillna("").str.strip().str.casefold()

# Classify using recognized city names, but preserve the evidence and uncertainty.
matches["venue_city_recognized_india"] = city.isin(INDIAN_CITIES)

matches["host_country_status"] = "unverified"

# Recognized Indian cities provide preliminary evidence for review.
matches.loc[
    matches["venue_city_recognized_india"],
    "host_country_status"
] = "probable_india_city_match_review_required"

# Keep the formal host-country field unknown until verified against a reliable source.
matches["host_country"] = pd.NA
matches["is_india_hosted"] = pd.Series(
    pd.NA, index=matches.index, dtype="boolean"
)

# India national-team matches outside the recognized city list need review.
matches["india_match_location_review"] = (
    matches["india_involved"].fillna(False)
    & ~matches["venue_city_recognized_india"]
)

# Hyderabad-specific flag, based on the recorded city or venue.
matches["is_hyderabad_match"] = (
    city.str.contains("hyderabad", regex=False)
    | venue.str.contains("hyderabad", regex=False)
)

# Save updated master dataset and rows requiring venue verification.
matches.to_csv(OUTPUT_FILE, index=False)

review = matches.loc[
    matches["host_country_status"].eq("unverified")
    | matches["india_match_location_review"],
    [
        "match_id", "match_date", "teams", "match_type",
        "event", "venue", "city", "india_involved",
        "venue_city_recognized_india",
        "india_match_location_review",
        "host_country_status"
    ]
].copy()

review.to_csv(REVIEW_FILE, index=False)

summary = pd.DataFrame({
    "metric": [
        "Total matches",
        "Recognized Indian-city matches requiring verification",
        "Matches with unverified host country",
        "Indian-team matches needing location review",
        "Hyderabad matches"
    ],
    "count": [
        len(matches),
        int(matches["venue_city_recognized_india"].sum()),
        int(matches["is_india_hosted"].isna().sum()),
        int(matches["india_match_location_review"].sum()),
        int(matches["is_hyderabad_match"].sum())
    ]
})

print("Phase 04.5.5 completed.")
print("\nSummary:")
display(summary)

print("\nUpdated master dataset:", OUTPUT_FILE)
print("Venue review file:", REVIEW_FILE)

print("\nSample venue records:")
display(
    matches.loc[
        matches["venue_city_recognized_india"]
        | matches["india_match_location_review"],
        [
            "match_date", "teams", "event", "venue", "city",
            "india_involved", "venue_city_recognized_india",
            "host_country_status"
        ]
    ].head(15)
)

Phase 04.5.5 completed.

Summary:

                                                  metric  count
0                                          Total matches   8546
1  Recognized Indian-city matches requiring verification    546
2                   Matches with unverified host country   8546
3            Indian-team matches needing location review    186
4                                      Hyderabad matches     32

Updated master dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_matches_host_verified_2023_2026.csv
Venue review file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_venue_verification_review_2023_2026.csv

Sample venue records:

,match_date,teams,event,venue,city,india_involved,venue_city_recognized_india,host_country_status
111,2023-02-12,Pakistan | India,ICC Women's T20 World Cup,"Newlands, Cape Town",Cape Town,True,False,unverified
116,2023-02-15,West Indies | India,ICC Women's T20 World Cup,"Newlands, Cape Town",Cape Town,True,False,unverified
121,2023-02-18,England | India,ICC Women's T20 World Cup,"St George's Park, Gqeberha",Gqeberha,True,False,unverified
125,2023-02-20,India | Ireland,ICC Women's T20 World Cup,"St George's Park, Gqeberha",Gqeberha,True,False,unverified
128,2023-02-23,Australia | India,ICC Women's T20 World Cup,"Newlands, Cape Town",Cape Town,True,False,unverified
232,2023-01-19,India | South Africa,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,unverified
234,2023-01-23,India | West Indies,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,unverified
236,2023-01-28,India | South Africa,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,unverified
237,2023-01-30,West Indies | India,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,unverified
238,2023-02-02,India | South Africa,South Africa Women's T20I Tri-Series,"Buffalo Park, East London",East London,True,False,unverified
694,2023-01-03,India | Sri Lanka,Sri Lanka tour of India,"Wankhede Stadium, Mumbai",Mumbai,True,True,probable_india_city_match_review_required
695,2023-01-05,Sri Lanka | India,Sri Lanka tour of India,"Maharashtra Cricket Association Stadium, Pune",Pune,True,True,probable_india_city_match_review_required
696,2023-01-07,India | Sri Lanka,Sri Lanka tour of India,"Saurashtra Cricket Association Stadium, Rajkot",Rajkot,True,True,probable_india_city_match_review_required
697,2023-01-10,India | Sri Lanka,Sri Lanka tour of India,"Barsapara Cricket Stadium, Guwahati",Guwahati,True,True,probable_india_city_match_review_required
698,2023-01-12,Sri Lanka | India,Sri Lanka tour of India,"Eden Gardens, Kolkata",Kolkata,True,True,probable_india_city_match_review_required

In [70]:
# Phase 04.5.6 — Final cricket dataset and venue classification

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_matches_host_verified_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_matches_final_2023_2026.csv"
REVIEW_FILE = DATA_DIR / "cricket_matches_venue_review_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

# Normalize venue fields.
city = matches["city"].fillna("").str.strip().str.casefold()
venue = matches["venue"].fillna("").str.strip().str.casefold()
event = matches["event"].fillna("").str.strip().str.casefold()
teams = matches["teams"].fillna("").str.casefold()

# Indian-city evidence from the previous phase.
india_city = matches["venue_city_recognized_india"].fillna(False).astype(bool)

# Identify matches involving the Indian national team.
india_pattern = r"(?<![a-z])india(?![a-z])"
matches["india_involved"] = teams.str.contains(
    india_pattern, regex=True, na=False
)

# Event classification.
matches["is_world_cup"] = event.str.contains(
    r"world cup|worldcup", regex=True, na=False
)
matches["is_ipl"] = (
    event.str.contains(r"\bindian premier league\b|\bipl\b",
                       regex=True, na=False)
    | matches["source_archive"].fillna("").str.casefold().eq("ipl_csv2.zip")
)
matches["is_wpl"] = event.str.contains(
    r"\bwomen.?s premier league\b|\bwpl\b",
    regex=True, na=False
)

# City/venue indicators.
matches["is_hyderabad_match"] = (
    city.str.contains("hyderabad", regex=False)
    | venue.str.contains("hyderabad", regex=False)
)

# This is a preliminary classification only; it is not official verification.
matches["india_host_candidate"] = india_city

matches["host_country_status"] = "needs_external_verification"
matches.loc[
    matches["india_host_candidate"],
    "host_country_status"
] = "indian_city_candidate_not_yet_verified"

# Preserve verified host country as unknown until independently confirmed.
matches["host_country"] = pd.NA
matches["is_india_hosted"] = pd.Series(
    pd.NA, index=matches.index, dtype="boolean"
)

# Separate likely Indian-team matches outside recognized Indian cities for review.
matches["india_match_location_review"] = (
    matches["india_involved"] & ~matches["india_host_candidate"]
)

# Keep one row per source match ID in the master file.
matches = matches.drop_duplicates(subset=["match_id"]).copy()

# Review file: all Indian-city candidates plus India-team matches requiring review.
review = matches.loc[
    matches["india_host_candidate"] | matches["india_match_location_review"],
    [
        "match_id", "match_date", "teams", "match_type", "event",
        "venue", "city", "india_involved", "is_world_cup",
        "is_ipl", "is_wpl", "is_hyderabad_match",
        "india_host_candidate", "host_country_status"
    ]
].copy()

matches.to_csv(OUTPUT_FILE, index=False)
review.to_csv(REVIEW_FILE, index=False)

summary = pd.DataFrame({
    "metric": [
        "Total unique matches",
        "Indian-city candidates requiring verification",
        "India national-team matches",
        "Indian-team matches needing location review",
        "World Cup matches",
        "IPL matches",
        "WPL matches",
        "Hyderabad matches",
        "Host country still unverified"
    ],
    "count": [
        len(matches),
        int(matches["india_host_candidate"].sum()),
        int(matches["india_involved"].sum()),
        int(matches["india_match_location_review"].sum()),
        int(matches["is_world_cup"].sum()),
        int(matches["is_ipl"].sum()),
        int(matches["is_wpl"].sum()),
        int(matches["is_hyderabad_match"].sum()),
        int(matches["is_india_hosted"].isna().sum())
    ]
})

print("Phase 04.5.6 completed.")
display(summary)

print("\nFinal master dataset:", OUTPUT_FILE)
print("Venue review dataset:", REVIEW_FILE)

print("\nSample Hyderabad matches:")
display(
    matches.loc[
        matches["is_hyderabad_match"],
        ["match_date", "teams", "event", "venue", "city"]
    ].head(10)
)

Phase 04.5.6 completed.

                                          metric  count
0                           Total unique matches   8546
1  Indian-city candidates requiring verification    546
2                    India national-team matches    298
3    Indian-team matches needing location review    186
4                              World Cup matches   1188
5                                    IPL matches    293
6                                    WPL matches     88
7                              Hyderabad matches     32
8                  Host country still unverified   8546

Final master dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_matches_final_2023_2026.csv
Venue review dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_matches_venue_review_2023_2026.csv

Sample Hyderabad matches:

      match_date                                              teams                      event                                                 venue       city
700   2023-01-18                                India | New Zealand  New Zealand tour of India  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
925   2023-04-02             Rajasthan Royals | Sunrisers Hyderabad      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
935   2023-04-09                 Punjab Kings | Sunrisers Hyderabad      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
946   2023-04-18               Mumbai Indians | Sunrisers Hyderabad      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
955   2023-04-24               Delhi Capitals | Sunrisers Hyderabad      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
968   2023-05-04        Kolkata Knight Riders | Sunrisers Hyderabad      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
979   2023-05-13         Sunrisers Hyderabad | Lucknow Super Giants      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
986   2023-05-18  Sunrisers Hyderabad | Royal Challengers Bangalore      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
1451  2023-10-06                             Pakistan | Netherlands      ICC Cricket World Cup  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
1454  2023-10-09                          New Zealand | Netherlands      ICC Cricket World Cup  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad

In [71]:
# Phase 04.5.7 — Validate Hyderabad match records

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_matches_final_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "hyderabad_cricket_matches_review_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

city = matches["city"].fillna("").str.strip().str.casefold()
venue = matches["venue"].fillna("").str.strip().str.casefold()

hyderabad = matches[
    city.str.contains("hyderabad", regex=False)
    | venue.str.contains("hyderabad", regex=False)
].copy()

# Review the actual venue and event combinations.
venue_summary = (
    hyderabad.groupby(["city", "venue", "event", "match_type"], dropna=False)
    .size()
    .reset_index(name="match_count")
    .sort_values(["city", "event", "venue"])
)

hyderabad["venue_verification_status"] = "requires source verification"
hyderabad["host_country"] = pd.NA
hyderabad["is_india_hosted"] = pd.Series(
    pd.NA, index=hyderabad.index, dtype="boolean"
)

hyderabad.to_csv(OUTPUT_FILE, index=False)

print("Hyderabad records found:", len(hyderabad))
print("Unique venues:", hyderabad["venue"].nunique())
print("Unique events:", hyderabad["event"].nunique())
print("Saved review file:", OUTPUT_FILE)

display(venue_summary)

Hyderabad records found: 32
Unique venues: 1
Unique events: 5
Saved review file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_matches_review_2023_2026.csv

        city                                                 venue                      event match_type  match_count
0  Hyderabad  Rajiv Gandhi International Stadium, Uppal, Hyderabad   Bangladesh tour of India        T20            1
1  Hyderabad  Rajiv Gandhi International Stadium, Uppal, Hyderabad      England tour of India       Test            1
2  Hyderabad  Rajiv Gandhi International Stadium, Uppal, Hyderabad      ICC Cricket World Cup        ODI            3
3  Hyderabad  Rajiv Gandhi International Stadium, Uppal, Hyderabad      Indian Premier League        T20           26
4  Hyderabad  Rajiv Gandhi International Stadium, Uppal, Hyderabad  New Zealand tour of India        ODI            1

In [72]:
# Phase 04.5.8 — Consolidate cricket context dataset

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_matches_final_2023_2026.csv"
FINAL_FILE = DATA_DIR / "cricket_context_final_2023_2026.csv"
QUALITY_FILE = DATA_DIR / "cricket_context_quality_report_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

# Standardize dates and restrict to the research period.
matches["match_date"] = pd.to_datetime(
    matches["match_date"], errors="coerce"
)

matches = matches[
    matches["match_date"].between(
        "2023-01-01", "2026-07-31", inclusive="both"
    )
].copy()

# Remove duplicate match IDs while retaining the first source record.
matches = matches.drop_duplicates(subset="match_id", keep="first").copy()

# Ensure core context flags exist.
for column in [
    "india_involved", "is_world_cup", "is_ipl",
    "is_wpl", "is_hyderabad_match"
]:
    if column not in matches.columns:
        matches[column] = False
    matches[column] = matches[column].fillna(False).astype(bool)

# Do not infer the host country from team names or city alone.
if "host_country" not in matches.columns:
    matches["host_country"] = pd.NA

if "is_india_hosted" not in matches.columns:
    matches["is_india_hosted"] = pd.Series(
        pd.NA, index=matches.index, dtype="boolean"
    )

# Add useful date-level features for later demand-data integration.
matches["match_year"] = matches["match_date"].dt.year
matches["match_month"] = matches["match_date"].dt.month
matches["match_day_of_week"] = matches["match_date"].dt.day_name()

# Keep the output focused on available match-level context.
preferred_columns = [
    "match_id", "match_date", "match_year", "match_month",
    "match_day_of_week", "teams", "match_type", "team_type",
    "gender", "event", "venue", "city", "india_involved",
    "is_india_hosted", "host_country", "is_world_cup",
    "is_ipl", "is_wpl", "is_hyderabad_match",
    "host_country_status", "source_archive", "source_file"
]

final_columns = [
    column for column in preferred_columns
    if column in matches.columns
]

final_matches = matches[final_columns].sort_values(
    ["match_date", "match_id"]
).copy()

final_matches["match_date"] = final_matches["match_date"].dt.strftime(
    "%Y-%m-%d"
)

final_matches.to_csv(FINAL_FILE, index=False)

# Generate a concise data-quality report.
quality_checks = [
    ("Final match records", len(final_matches)),
    ("Duplicate match IDs", int(final_matches["match_id"].duplicated().sum())),
    ("Invalid/missing dates", int(final_matches["match_date"].isna().sum())),
    ("Missing teams", int(final_matches["teams"].isna().sum())),
    ("Missing event", int(final_matches["event"].isna().sum())),
    ("Missing venue", int(final_matches["venue"].isna().sum())),
    ("Missing city", int(final_matches["city"].isna().sum())),
    ("India-team matches", int(final_matches["india_involved"].sum())),
    ("World Cup matches", int(final_matches["is_world_cup"].sum())),
    ("IPL matches", int(final_matches["is_ipl"].sum())),
    ("WPL matches", int(final_matches["is_wpl"].sum())),
    ("Hyderabad matches", int(final_matches["is_hyderabad_match"].sum())),
    ("Host country still unknown", int(final_matches["host_country"].isna().sum())),
]

quality_report = pd.DataFrame(
    quality_checks, columns=["quality_check", "count"]
)
quality_report.to_csv(QUALITY_FILE, index=False)

print("Phase 04.5.8 completed.")
print("Final dataset:", FINAL_FILE)
print("Quality report:", QUALITY_FILE)
print(
    "Date range:",
    final_matches["match_date"].min(),
    "to",
    final_matches["match_date"].max()
)

display(quality_report)
display(final_matches.head(10))

Phase 04.5.8 completed.
Final dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_context_final_2023_2026.csv
Quality report: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_context_quality_report_2023_2026.csv
Date range: 2023-01-01 to 2026-07-31

                 quality_check  count
0          Final match records   8546
1          Duplicate match IDs      0
2        Invalid/missing dates      0
3                Missing teams      0
4                Missing event      0
5                Missing venue      0
6                 Missing city     42
7           India-team matches    298
8            World Cup matches   1188
9                  IPL matches    293
10                 WPL matches     88
11           Hyderabad matches     32
12  Host country still unknown   8546

,match_id,match_date,match_year,match_month,match_day_of_week,teams,match_type,team_type,gender,event,...,india_involved,is_india_hosted,host_country,is_world_cup,is_ipl,is_wpl,is_hyderabad_match,host_country_status,source_archive,source_file
29,1324647,2023-01-01,2023,1,Sunday,Melbourne Renegades | Perth Scorchers,T20,club,male,Big Bash League,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1324647_info.csv
30,1324648,2023-01-01,2023,1,Sunday,Brisbane Heat | Sydney Sixers,T20,club,male,Big Bash League,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1324648_info.csv
157,1341202,2023-01-01,2023,1,Sunday,Canterbury | Wellington,T20,club,male,Super Smash,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1341202_info.csv
177,1341234,2023-01-01,2023,1,Sunday,Wellington | Canterbury,T20,club,female,Women's Super Smash,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1341234_info.csv
31,1324649,2023-01-02,2023,1,Monday,Adelaide Strikers | Hobart Hurricanes,T20,club,male,Big Bash League,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1324649_info.csv
143,1339610,2023-01-02,2023,1,Monday,New Zealand | Pakistan,Test,international,male,New Zealand tour of Pakistan,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1339610_info.csv
158,1341203,2023-01-02,2023,1,Monday,Otago | Auckland,T20,club,male,Super Smash,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1341203_info.csv
178,1341235,2023-01-02,2023,1,Monday,Otago | Auckland,T20,club,female,Women's Super Smash,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1341235_info.csv
32,1324650,2023-01-03,2023,1,Tuesday,Melbourne Renegades | Melbourne Stars,T20,club,male,Big Bash League,...,False,NaN,NaN,False,False,False,False,needs_external_verification,all_csv2.zip,1324650_info.csv
694,1348640,2023-01-03,2023,1,Tuesday,India | Sri Lanka,T20,international,male,Sri Lanka tour of India,...,True,NaN,NaN,False,False,False,False,indian_city_candidate_not_yet_verified,all_csv2.zip,1348640_info.csv

In [73]:
# Phase 04.5.9 — Host-country classification and venue verification

from pathlib import Path
import pandas as pd
import re

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_context_final_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_context_host_classified_2023_2026.csv"
REVIEW_FILE = DATA_DIR / "cricket_host_country_review_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

# Curated city-to-country mapping for common international cricket venues.
# This is a preliminary mapping, not an official venue-by-venue audit.
CITY_COUNTRY = {
    # India
    "ahmedabad": "India", "amritsar": "India",
    "bengaluru": "India", "bangalore": "India",
    "bhubaneswar": "India", "chandigarh": "India",
    "chennai": "India", "coimbatore": "India",
    "cuttack": "India", "dehradun": "India",
    "dharamshala": "India", "faridabad": "India",
    "guwahati": "India", "gwalior": "India",
    "hyderabad": "India", "indore": "India",
    "jaipur": "India", "jammu": "India",
    "jamshedpur": "India", "kanpur": "India",
    "kochi": "India", "kolkata": "India",
    "lucknow": "India", "mohali": "India",
    "mumbai": "India", "nagpur": "India",
    "new delhi": "India", "delhi": "India",
    "noida": "India", "patna": "India",
    "pune": "India", "rajkot": "India",
    "ranchi": "India", "surat": "India",
    "thiruvananthapuram": "India", "vadodara": "India",
    "visakhapatnam": "India", "vizag": "India",

    # Australia
    "adelaide": "Australia", "brisbane": "Australia",
    "cairns": "Australia", "canberra": "Australia",
    "darwin": "Australia", "geelong": "Australia",
    "hobart": "Australia", "melbourne": "Australia",
    "perth": "Australia", "sydney": "Australia",
    "townsville": "Australia",

    # New Zealand
    "auckland": "New Zealand", "christchurch": "New Zealand",
    "dunedin": "New Zealand", "hamilton": "New Zealand",
    "napier": "New Zealand", "nelson": "New Zealand",
    "new plymouth": "New Zealand", "queenstown": "New Zealand",
    "wellington": "New Zealand", "mount maunganui": "New Zealand",

    # South Africa
    "benoni": "South Africa", "bloemfontein": "South Africa",
    "cape town": "South Africa", "centurion": "South Africa",
    "durban": "South Africa", "east london": "South Africa",
    "gqeberha": "South Africa", "johannesburg": "South Africa",
    "kimberley": "South Africa", "paarl": "South Africa",
    "potchefstroom": "South Africa", "pretoria": "South Africa",

    # England and Wales
    "birmingham": "England", "bristol": "England",
    "cardiff": "Wales", "chester-le-street": "England",
    "hove": "England", "leeds": "England",
    "london": "England", "manchester": "England",
    "nottingham": "England", "southampton": "England",
    "taunton": "England", "worcester": "England",
    "trent bridge": "England", "lords": "England",
    "the oval": "England", "edgbaston": "England",

    # Sri Lanka
    "colombo": "Sri Lanka", "galle": "Sri Lanka",
    "hambantota": "Sri Lanka", "kandy": "Sri Lanka",
    "pallekele": "Sri Lanka", "dambulla": "Sri Lanka",

    # Bangladesh
    "dhaka": "Bangladesh", "chattogram": "Bangladesh",
    "chittagong": "Bangladesh", "sylhet": "Bangladesh",
    "mirpur": "Bangladesh", "khulna": "Bangladesh",

    # Pakistan
    "karachi": "Pakistan", "lahore": "Pakistan",
    "multan": "Pakistan", "rawalpindi": "Pakistan",
    "faisalabad": "Pakistan", "peshawar": "Pakistan",

    # United Arab Emirates
    "abu dhabi": "United Arab Emirates",
    "dubai": "United Arab Emirates",
    "sharjah": "United Arab Emirates",

    # Zimbabwe
    "bulawayo": "Zimbabwe", "harare": "Zimbabwe",

    # Ireland
    "belfast": "Northern Ireland",
    "dublin": "Ireland",

    # West Indies / Caribbean
    "antigua": "Antigua and Barbuda",
    "bridgetown": "Barbados",
    "gros islet": "Saint Lucia",
    "kingston": "Jamaica",
    "north sound": "Antigua and Barbuda",
    "port of spain": "Trinidad and Tobago",
    "st george's": "Grenada",
    "tarouba": "Trinidad and Tobago",
}

def normalize_city(value):
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).strip().casefold())

city_norm = matches["city"].map(normalize_city)

matches["host_country"] = city_norm.map(CITY_COUNTRY)

# Keep the mapping provenance explicit.
matches["host_country_method"] = matches["host_country"].apply(
    lambda value: "curated_city_mapping" if pd.notna(value) else "unverified"
)

matches["host_country_status"] = matches["host_country"].apply(
    lambda value: "preliminary_city_match_review_required"
    if pd.notna(value) else "unverified_city"
)

# Only a preliminary classification until venue-level verification is complete.
matches["is_india_hosted"] = pd.Series(
    pd.NA, index=matches.index, dtype="boolean"
)
matches.loc[
    matches["host_country"].notna(),
    "is_india_hosted"
] = matches.loc[
    matches["host_country"].notna(), "host_country"
].eq("India")

# India national-team matches played outside India.
if "india_involved" not in matches.columns:
    teams = matches["teams"].fillna("").str.casefold()
    matches["india_involved"] = teams.str.contains(
        r"(?<![a-z])india(?![a-z])", regex=True, na=False
    )

matches["india_team_abroad_candidate"] = (
    matches["india_involved"].fillna(False)
    & matches["host_country"].notna()
    & matches["host_country"].ne("India")
)

# Save the classified master and a compact list for unresolved locations.
matches.to_csv(OUTPUT_FILE, index=False)

unmapped = (
    matches.loc[matches["host_country"].isna()]
    .groupby(["city", "venue"], dropna=False)
    .agg(
        match_count=("match_id", "size"),
        events=("event", lambda values: " | ".join(
            sorted(set(values.dropna().astype(str)))[:10]
        ))
    )
    .reset_index()
    .sort_values("match_count", ascending=False)
)

unmapped.to_csv(REVIEW_FILE, index=False)

summary = pd.DataFrame({
    "metric": [
        "Total matches",
        "Preliminarily mapped to India",
        "Preliminarily mapped outside India",
        "Indian-team matches outside India (candidates)",
        "Matches with unverified city",
        "Unique unmapped city/venue combinations"
    ],
    "count": [
        len(matches),
        int(matches["host_country"].eq("India").sum()),
        int(matches["host_country"].notna().sum()
            - matches["host_country"].eq("India").sum()),
        int(matches["india_team_abroad_candidate"].sum()),
        int(matches["host_country"].isna().sum()),
        len(unmapped)
    ]
})

print("Phase 04.5.9 completed.")
display(summary)

print("\nClassified dataset:", OUTPUT_FILE)
print("Unmapped venue review:", REVIEW_FILE)

print("\nMost frequent unmapped locations:")
display(unmapped.head(20))

Phase 04.5.9 completed.

                                           metric  count
0                                   Total matches   8546
1                   Preliminarily mapped to India    546
2              Preliminarily mapped outside India   4073
3  Indian-team matches outside India (candidates)    149
4                    Matches with unverified city   3927
5         Unique unmapped city/venue combinations    241

Classified dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_context_host_classified_2023_2026.csv
Unmapped venue review: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_host_country_review_2023_2026.csv

Most frequent unmapped locations:

,city,venue,match_count,events
101,Kirtipur,"Tribhuvan University International Cricket Ground, Kirtipur",141,ACC Men's Premier Cup | Canada tour of Nepal | ICC Men's Cricket World Cup League 2 | ICC Men's T20 World Cup Asia Qualifier Final | ICC Men’s T20 World Cup Asia Qualifier Final | Nepal Premier League | Nepal Tri-Nation T20I Series | Nepal Women's T20I Tri-Series | United Arab Emirates tour of Nepal | Women's T20 World Cup Qualifier
106,Kuala Lumpur,"Bayuemas Oval, Kuala Lumpur",131,Asian Cricket Council Women's Premier Cup | Asian Games Women's Qualifier | Bahrain tour of Malaysia | ICC Men's T20 World Cup Asia B Qualifier | ICC Men's T20 World Cup Asia Qualifier A | ICC Women's T20 World Cup Asia Region Qualifier | Indonesia tour of Malaysia | Malaysia Open T20 Championship | Malaysia Tri-Nation T20I Series | Mini SEA Men's Twenty20 Cricket Competition
38,Chelmsford,"County Ground, Chelmsford",109,Charlotte Edwards Cup | County Championship | ECB Women's One-Day Cup | ICC Men's Cricket World Cup Super League | India Women tour of England | Ireland v Bangladesh | One-Day Cup | Pakistan Women tour of England | Rachael Heyhoe Flint Trophy | Sri Lanka Women tour of England
18,Bangkok,"Terdthai Cricket Ground, Bangkok",99,Asian Cricket Council Men's Challenger Cup | ICC Women's Emerging Nations Trophy | ICC Women's T20 World Cup Asia Region Qualifier | Quadrangular Twenty20 Series (Thailand) | SEA Games Men's Twenty20 Cricket Competition | SEA Games Women's Twenty20 Cricket Competition | Women's Asia Cup Rising Stars | Women's T20 Quadrangular Series (in Thailand) | Zimbabwe Women tour of Thailand
13,Bali,Udayana Cricket Ground,97,Bahrain tour of Indonesia | Cambodia tour of Indonesia | Indonesia Tri-Nation T20I Series | Indonesia Women's T20I Tri-Series | Kartini Cup | Mongolia Women tour of Indonesia | Myanmar tour of Indonesia | Philippines tour of Indonesia | Sweden tour of Indonesia | Thailand tour of Indonesia
96,Kigali City,"Gahanga International Cricket Stadium, Rwanda",90,Africa Continental Cup | East Africa Cup | ICC Women's T20I Challenge Trophy | Kwibuka Women's Twenty20 Tournament | Rwanda Tri-Nation T20I Series
4,Al Amarat,Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1),75,ACC Men's Premier Cup | Bahrain Women tour of Oman | Denmark Women tour of Oman | GCC Women's Twenty20 Championship Cup | ICC Men's Cricket World Cup League 2 | ICC Men's T20 World Cup Asia & EAP Qualifier | Kuwait in Oman T20I Series | Namibia tour of Oman | Netherlands tour of Oman | Papua New Guinea tour of Oman
147,Northampton,"County Ground, Northampton",73,Charlotte Edwards Cup | County Championship | One-Day Cup | Pakistan Women tour of England | Rachael Heyhoe Flint Trophy | Sri Lanka Women tour of England | Vitality Blast | Vitality Blast Men
26,Brighton,"County Ground, Hove",71,Charlotte Edwards Cup | County Championship | New Zealand Women tour of England | One-Day Cup | Rachael Heyhoe Flint Trophy | Sri Lanka Women tour of England | Vitality Blast | Vitality Blast Men | West Indies Women tour of England
115,Leicester,"Grace Road, Leicester",71,Charlotte Edwards Cup | County Championship | One-Day Cup | Rachael Heyhoe Flint Trophy | Sri Lanka Women tour of England | Vitality Blast | Vitality Blast Men | Vitality Blast Women | West Indies Women tour of England
81,Ilfov County,"Moara Vlasiei Cricket Ground, Ilfov County",69,Austria tour of Romania | Bulgaria tour of Romania | Continental Cup | Czech Republic tour of Romania | ECA Men's European Cup | Women's Continental Cup
34,Canterbury,"St Lawrence Ground, Canterbury",64,Charlotte Edwards Cup | County Championship | New Zealand Women tour of England | One-Day Cup | Vitality Blast | Vitality Blast Men | West Indies Women tour of England
47,Dallas,"Grand Prairie Stadium, Dallas",64,ICC Men's Cricket World Cup League 2 | ICC Men's T20 World Cup | Major League Cricket | Nepal tour of United States of America | Zimbabwe Women tour of United States of America
67,Gaborone,"Botswana Cricket Association Oval 1, Gaborone",64,BCA Kalahari Women's T20 International Tournament | ICC Men's T20 World Cup Sub Regional Africa Qualifier | ICC Women's T20 World Cup Africa Region Division Two Qualifier | Lesotho tour of Botswana
51,Derby,"County Ground, Derby",62,Charlotte Edwards Cup | County Championship | New Zealand Women tour of England | One-Day Cup | Pakistan Women tour of England | Sri Lanka Women tour of England | Vitality Blast | Vitality Blast Men | Vitality Blast Women | West Indies Women tour of England
190,Singapore,Singapore National Cricket Ground,59,Asia Pacific Cricket Champions Trophy | Asian Games Men's Qualifier | Bahrain tour of Singapore | Cambodia Women tour of Singapore | Indonesia Women tour of Singapore | Myanmar Women tour of Singapore | Philippines Women tour of Singapore | Singapore Women's T20I Tri-Series
128,Mong Kok,"Mission Road Ground, Mong Kok, Hong Kong",54,Asian Cricket Council Women's Emerging Teams Cup | CWC Challenge League | East Asia Cup | Hong Kong Men's T20I Series | Hong Kong Women's T20I Tri-Series | Kuwait tour of Hong Kong | Nepal tour of Hong Kong | Quadrangular Twenty20 Series (Hong Kong) | Women's T20 Quadrangular Series (in Hong Kong)
56,Doha,"West End Park International Cricket Stadium, Doha",50,Asia Cup Rising Stars | Bahrain Women tour of Qatar | Bahrain tour of Qatar | Gulf Cricket T20I Championship | Hong Kong in Qatar T20I Series | Hong Kong tour of Qatar | ICC Men's T20 World Cup Asia Qualifier B | ICC Men's T20 World Cup Sub Regional Asia Qualifier A | Oman Women tour of Qatar | Saudi Arabia tour of Qatar
95,Kigali City,"Gahanga B Ground, Rwanda",49,ICC Women's T20I Challenge Trophy | Kenya Women tour of Rwanda | Kwibuka Women's Twenty20 Tournament
68,Gaborone,"Botswana Cricket Association Oval 2, Gaborone",47,BCA Kalahari Women's T20 International Tournament | ICC Men's T20 World Cup Sub Regional Africa Qualifier | ICC Women's T20 World Cup Africa Region Division Two Qualifier

In [74]:
# Phase 04.5.10 — Expand city-to-country mapping

from pathlib import Path
import pandas as pd
import re

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_context_host_classified_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_context_host_classified_v2_2023_2026.csv"
REVIEW_FILE = DATA_DIR / "cricket_host_country_review_v2_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

# Extend the mapping for common cricket-hosting cities.
# These are preliminary city-level mappings, not independent verification
# of every individual match or neutral-venue arrangement.
CITY_COUNTRY_EXTRA = {
    # Nepal
    "kirtipur": "Nepal", "kathmandu": "Nepal", "pokhara": "Nepal",

    # Malaysia
    "kuala lumpur": "Malaysia", "kinrara": "Malaysia",

    # Thailand
    "bangkok": "Thailand",

    # Indonesia
    "bali": "Indonesia", "jakarta": "Indonesia",

    # Rwanda
    "kigali": "Rwanda",

    # Oman
    "al amarat": "Oman", "muscat": "Oman",

    # England
    "chelmsford": "England", "northampton": "England",
    "brighton": "England", "leicester": "England",
    "liverpool": "England", "derby": "England",
    "birmingham": "England", "bristol": "England",
    "hove": "England", "leeds": "England",
    "manchester": "England", "nottingham": "England",
    "southampton": "England", "taunton": "England",
    "worcester": "England", "london": "England",
    "chester-le-street": "England", "canterbury": "England",
    "durham": "England", "edgbaston": "England",
    "lords": "England", "the oval": "England",
    "trent bridge": "England",

    # Scotland
    "edinburgh": "Scotland", "glasgow": "Scotland",
    "aberdeen": "Scotland",

    # Netherlands
    "amstelveen": "Netherlands", "rotterdam": "Netherlands",
    "utrecht": "Netherlands", "the hague": "Netherlands",

    # United States
    "dallas": "United States", "houston": "United States",
    "lauderhill": "United States", "new york": "United States",
    "grand prairie": "United States", "fort lauderdale": "United States",

    # Canada
    "brampton": "Canada", "toronto": "Canada",
    "vancouver": "Canada", "king city": "Canada",

    # Kenya
    "nairobi": "Kenya",

    # Uganda
    "kampala": "Uganda", "entebbe": "Uganda",

    # Nigeria
    "lagos": "Nigeria", "abuja": "Nigeria",

    # Namibia
    "windhoek": "Namibia",

    # Qatar
    "doha": "Qatar",

    # Hong Kong
    "hong kong": "Hong Kong",

    # Singapore
    "singapore": "Singapore",

    # Afghanistan
    "kabul": "Afghanistan", "kandahar": "Afghanistan",

    # Pakistan
    "karachi": "Pakistan", "lahore": "Pakistan",
    "multan": "Pakistan", "rawalpindi": "Pakistan",
    "faisalabad": "Pakistan", "peshawar": "Pakistan",

    # United Arab Emirates
    "abu dhabi": "United Arab Emirates",
    "dubai": "United Arab Emirates",
    "sharjah": "United Arab Emirates",

    # Bangladesh
    "dhaka": "Bangladesh", "chattogram": "Bangladesh",
    "chittagong": "Bangladesh", "sylhet": "Bangladesh",
    "mirpur": "Bangladesh", "khulna": "Bangladesh",

    # Sri Lanka
    "colombo": "Sri Lanka", "galle": "Sri Lanka",
    "hambantota": "Sri Lanka", "kandy": "Sri Lanka",
    "pallekele": "Sri Lanka", "dambulla": "Sri Lanka",

    # Zimbabwe
    "bulawayo": "Zimbabwe", "harare": "Zimbabwe",

    # Ireland
    "belfast": "Northern Ireland", "dublin": "Ireland",

    # West Indies / Caribbean
    "antigua": "Antigua and Barbuda",
    "bridgetown": "Barbados",
    "gros islet": "Saint Lucia",
    "kingston": "Jamaica",
    "north sound": "Antigua and Barbuda",
    "port of spain": "Trinidad and Tobago",
    "st george's": "Grenada",
    "tarouba": "Trinidad and Tobago",

    # South Africa
    "benoni": "South Africa", "bloemfontein": "South Africa",
    "cape town": "South Africa", "centurion": "South Africa",
    "durban": "South Africa", "east london": "South Africa",
    "gqeberha": "South Africa", "johannesburg": "South Africa",
    "kimberley": "South Africa", "paarl": "South Africa",
    "potchefstroom": "South Africa", "pretoria": "South Africa",

    # Australia
    "adelaide": "Australia", "brisbane": "Australia",
    "cairns": "Australia", "canberra": "Australia",
    "darwin": "Australia", "geelong": "Australia",
    "hobart": "Australia", "melbourne": "Australia",
    "perth": "Australia", "sydney": "Australia",
    "townsville": "Australia",

    # New Zealand
    "auckland": "New Zealand", "christchurch": "New Zealand",
    "dunedin": "New Zealand", "hamilton": "New Zealand",
    "napier": "New Zealand", "nelson": "New Zealand",
    "new plymouth": "New Zealand", "queenstown": "New Zealand",
    "wellington": "New Zealand", "mount maunganui": "New Zealand",

    # India
    "ahmedabad": "India", "amritsar": "India",
    "bengaluru": "India", "bangalore": "India",
    "bhubaneswar": "India", "chandigarh": "India",
    "chennai": "India", "coimbatore": "India",
    "cuttack": "India", "dehradun": "India",
    "dharamshala": "India", "faridabad": "India",
    "guwahati": "India", "gwalior": "India",
    "hyderabad": "India", "indore": "India",
    "jaipur": "India", "jammu": "India",
    "jamshedpur": "India", "kanpur": "India",
    "kochi": "India", "kolkata": "India",
    "lucknow": "India", "mohali": "India",
    "mumbai": "India", "nagpur": "India",
    "new delhi": "India", "delhi": "India",
    "noida": "India", "patna": "India",
    "pune": "India", "rajkot": "India",
    "ranchi": "India", "surat": "India",
    "thiruvananthapuram": "India", "vadodara": "India",
    "visakhapatnam": "India", "vizag": "India",
}

def normalize_city(value):
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).strip().casefold())

city_norm = matches["city"].map(normalize_city)
extra_mapping = {normalize_city(k): v for k, v in CITY_COUNTRY_EXTRA.items()}

# Preserve earlier mapped values; use the expanded mapping for unresolved cities.
if "host_country" not in matches.columns:
    matches["host_country"] = pd.NA

old_country = matches["host_country"].copy()
new_country = city_norm.map(extra_mapping)
matches["host_country"] = old_country.where(old_country.notna(), new_country)

matches["host_country_method"] = matches["host_country"].apply(
    lambda x: "city_mapping_preliminary" if pd.notna(x) else "unverified"
)

matches["host_country_status"] = matches["host_country"].apply(
    lambda x: "preliminary_city_mapping_review_required"
    if pd.notna(x) else "unverified_city"
)

# Recalculate India-hosting candidates without pretending they are fully verified.
matches["is_india_hosted"] = pd.Series(
    pd.NA, index=matches.index, dtype="boolean"
)
mapped = matches["host_country"].notna()
matches.loc[mapped, "is_india_hosted"] = (
    matches.loc[mapped, "host_country"].eq("India")
)

teams = matches["teams"].fillna("").str.casefold()
matches["india_involved"] = teams.str.contains(
    r"(?<![a-z])india(?![a-z])", regex=True, na=False
)

matches["india_team_abroad_candidate"] = (
    matches["india_involved"]
    & matches["host_country"].notna()
    & matches["host_country"].ne("India")
)

matches.to_csv(OUTPUT_FILE, index=False)

unmapped = (
    matches.loc[matches["host_country"].isna()]
    .groupby(["city", "venue"], dropna=False)
    .agg(
        match_count=("match_id", "size"),
        events=("event", lambda s: " | ".join(
            sorted(set(s.dropna().astype(str)))[:8]
        ))
    )
    .reset_index()
    .sort_values("match_count", ascending=False)
)
unmapped.to_csv(REVIEW_FILE, index=False)

summary = pd.DataFrame({
    "metric": [
        "Total matches",
        "Preliminary India-host candidates",
        "Preliminary non-India-host matches",
        "India-team matches outside India (candidates)",
        "Matches with unverified cities",
        "Unique unmapped city/venue combinations"
    ],
    "count": [
        len(matches),
        int(matches["host_country"].eq("India").sum()),
        int((matches["host_country"].notna()
             & matches["host_country"].ne("India")).sum()),
        int(matches["india_team_abroad_candidate"].sum()),
        int(matches["host_country"].isna().sum()),
        len(unmapped)
    ]
})

print("Phase 04.5.10 completed.")
display(summary)

print("\nUpdated dataset:", OUTPUT_FILE)
print("Unmapped-location review:", REVIEW_FILE)
print("\nRemaining unmapped locations:")
display(unmapped.head(20))

Phase 04.5.10 completed.

                                          metric  count
0                                  Total matches   8546
1              Preliminary India-host candidates    546
2             Preliminary non-India-host matches   5869
3  India-team matches outside India (candidates)    155
4                 Matches with unverified cities   2131
5        Unique unmapped city/venue combinations    186

Updated dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_context_host_classified_v2_2023_2026.csv
Unmapped-location review: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_host_country_review_v2_2023_2026.csv

Remaining unmapped locations:

,city,venue,match_count,events
68,Kigali City,"Gahanga International Cricket Stadium, Rwanda",90,Africa Continental Cup | East Africa Cup | ICC Women's T20I Challenge Trophy | Kwibuka Women's Twenty20 Tournament | Rwanda Tri-Nation T20I Series
55,Ilfov County,"Moara Vlasiei Cricket Ground, Ilfov County",69,Austria tour of Romania | Bulgaria tour of Romania | Continental Cup | Czech Republic tour of Romania | ECA Men's European Cup | Women's Continental Cup
44,Gaborone,"Botswana Cricket Association Oval 1, Gaborone",64,BCA Kalahari Women's T20 International Tournament | ICC Men's T20 World Cup Sub Regional Africa Qualifier | ICC Women's T20 World Cup Africa Region Division Two Qualifier | Lesotho tour of Botswana
89,Mong Kok,"Mission Road Ground, Mong Kok, Hong Kong",54,Asian Cricket Council Women's Emerging Teams Cup | CWC Challenge League | East Asia Cup | Hong Kong Men's T20I Series | Hong Kong Women's T20I Tri-Series | Kuwait tour of Hong Kong | Nepal tour of Hong Kong | Quadrangular Twenty20 Series (Hong Kong)
67,Kigali City,"Gahanga B Ground, Rwanda",49,ICC Women's T20I Challenge Trophy | Kenya Women tour of Rwanda | Kwibuka Women's Twenty20 Tournament
45,Gaborone,"Botswana Cricket Association Oval 2, Gaborone",47,BCA Kalahari Women's T20 International Tournament | ICC Men's T20 World Cup Sub Regional Africa Qualifier | ICC Women's T20 World Cup Africa Region Division Two Qualifier
124,Providence,"Providence Stadium, Guyana",47,Caribbean Premier League | ICC Men's T20 World Cup | India tour of West Indies and United States of America | New Zealand tour of West Indies | South Africa tour of West Indies | Women's Caribbean Premier League
136,Sano,Sano International Cricket Ground,43,Cook Islands tour of Japan | ICC Men's T20 World Cup East Asia-Pacific Qualifier | Japan Twenty20 Tri-Series | Mongolia tour of Japan | Singapore Women tour of Japan | Women's T20 Pentangular Series (in Japan)
86,Marsa,Marsa Sports Club,40,Croatia Women tour of Malta | Estonia tour of Malta | Gibraltar tour of Malta | Malta Tri-Nation T20I Series | Mdina Cup | Valletta Cup | Women's Valletta Cup
9,Bangi,"YSD-UKM Cricket Oval, Bangi",37,Asian Cricket Council Women's Premier Cup | ICC Men's T20 World Cup Asia Qualifier A | Kuwait Women v Myanmar Women T20I Series | Nepal Women tour of Malaysia
74,Krefeld,Bayer Uerdingen Cricket Ground,33,Austria tour of Germany | Belgium tour of Germany | Germany Women's T20I Tri-Series | ICC Men's T20 World Cup Sub Regional Europe Qualifier | Italy Women in Germany T20I Match
11,Beckenham,"Kent County Cricket Ground, Beckenham",31,Charlotte Edwards Cup | County Championship | ECB Women's One-Day Cup | One-Day Cup | Rachael Heyhoe Flint Trophy
10,Basseterre,"Warner Park, Basseterre, St Kitts",31,Australia Women tour of West Indies | Australia tour of West Indies | Bangladesh Women tour of West Indies | Bangladesh tour of West Indies | Caribbean Premier League
40,Episkopi,Happy Valley Ground,30,Cyprus T20 Tri-Series | Estonia Women tour of Cyprus | Estonia tour of Cyprus | Finland tour of Cyprus | ICC Men's T20 World Cup Sub Regional Europe Qualifier A | Malta Women tour of Cyprus
46,Gelephu,Gelephu International Cricket Ground,30,Bahrain tour of Bhutan | Bhutan Quadrangular T20I Series | Lotus Cup Women's Tri-Series | Myanmar Women tour of Bhutan | Myanmar tour of Bhutan
20,Buenos Aires,"St Albans Club, Buenos Aires",28,Bermuda tour of Argentina | Brazil tour of Argentina | ICC Men's T20 World Cup Americas Region Qualifier | ICC Men's T20 World Cup Sub Regional Americas Qualifier | ICC Women's T20 World Cup Americas Region Qualifier
83,Maggona,"Surrey Village, Maggona",27,Major Clubs Limited Over Tournament | Major Clubs T20 Tournament | Major League Tournament
41,Episkopi,Happy Valley Ground 2,27,Austria tour of Cyprus | Bulgaria in Cyprus T20I Series | Cyprus T20 Tri-Series | Greece Women tour of Cyprus | ICC Men's T20 World Cup Sub Regional Europe Qualifier A
123,Prague,"Scott Page Field, Vinor",26,Central Europe Cup | Cyprus Women tour of Czech Republic | Hungary tour of Czech Republic | Women Central Europe Cup
73,Kowloon,Kowloon Cricket Club,26,CWC Challenge League | FairBreak Invitational Tournament

In [75]:
# Phase 04.5.11 — Resolve additional cricket venue locations

from pathlib import Path
import pandas as pd
import re

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_context_host_classified_v2_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_context_host_classified_v3_2023_2026.csv"
REVIEW_FILE = DATA_DIR / "cricket_host_country_review_v3_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

# Additional city-to-country mappings for locations in the review.
# These remain preliminary until validated against reliable venue sources.
EXTRA_COUNTRIES = {
    # Rwanda
    "kigali": "Rwanda",
    "kigali city": "Rwanda",

    # Botswana
    "gaborone": "Botswana",

    # Romania
    "ilfov county": "Romania",
    "bucharest": "Romania",

    # Guyana
    "providence": "Guyana",
    "georgetown": "Guyana",

    # Japan
    "sano": "Japan",

    # Malta
    "marsa": "Malta",

    # Brunei
    "bangi": "Brunei",

    # Nepal
    "kirtipur": "Nepal",
    "kathmandu": "Nepal",

    # Malaysia
    "kuala lumpur": "Malaysia",

    # Thailand
    "bangkok": "Thailand",

    # Indonesia
    "bali": "Indonesia",

    # Oman
    "al amarat": "Oman",

    # Other common cricket locations
    "lagos": "Nigeria",
    "kampala": "Uganda",
    "windhoek": "Namibia",
    "doha": "Qatar",
    "singapore": "Singapore",
    "hong kong": "Hong Kong",
    "amstelveen": "Netherlands",
    "rotterdam": "Netherlands",
    "edinburgh": "Scotland",
    "glasgow": "Scotland",
    "nairobi": "Kenya",
}

def normalize_location(value):
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).strip().casefold())

if "host_country" not in matches.columns:
    matches["host_country"] = pd.NA

city_norm = matches["city"].map(normalize_location)
extra_map = {
    normalize_location(city): country
    for city, country in EXTRA_COUNTRIES.items()
}

mapped_country = city_norm.map(extra_map)

# Keep existing mappings; fill only previously unresolved countries.
matches["host_country"] = matches["host_country"].where(
    matches["host_country"].notna(), mapped_country
)

matches["host_country_method"] = matches["host_country"].apply(
    lambda value: "preliminary_city_mapping"
    if pd.notna(value) else "unverified"
)

matches["host_country_status"] = matches["host_country"].apply(
    lambda value: "preliminary_mapping_requires_validation"
    if pd.notna(value) else "unverified_city"
)

# Recalculate candidate flags.
matches["is_india_hosted"] = pd.Series(
    pd.NA, index=matches.index, dtype="boolean"
)

mapped = matches["host_country"].notna()
matches.loc[mapped, "is_india_hosted"] = (
    matches.loc[mapped, "host_country"].eq("India")
)

teams = matches["teams"].fillna("").str.casefold()
matches["india_involved"] = teams.str.contains(
    r"(?<![a-z])india(?![a-z])", regex=True, na=False
)

matches["india_team_abroad_candidate"] = (
    matches["india_involved"]
    & matches["host_country"].notna()
    & matches["host_country"].ne("India")
)

matches.to_csv(OUTPUT_FILE, index=False)

unmapped = (
    matches.loc[matches["host_country"].isna()]
    .groupby(["city", "venue"], dropna=False)
    .agg(
        match_count=("match_id", "size"),
        events=("event", lambda values: " | ".join(
            sorted(set(values.dropna().astype(str)))[:8]
        ))
    )
    .reset_index()
    .sort_values("match_count", ascending=False)
)

unmapped.to_csv(REVIEW_FILE, index=False)

summary = pd.DataFrame({
    "metric": [
        "Total matches",
        "Preliminary India-host candidates",
        "Preliminary non-India-host matches",
        "India-team matches outside India (candidates)",
        "Matches with unverified cities",
        "Unmapped city/venue combinations"
    ],
    "count": [
        len(matches),
        int(matches["host_country"].eq("India").sum()),
        int((
            matches["host_country"].notna()
            & matches["host_country"].ne("India")
        ).sum()),
        int(matches["india_team_abroad_candidate"].sum()),
        int(matches["host_country"].isna().sum()),
        len(unmapped)
    ]
})

print("Phase 04.5.11 completed.")
display(summary)

print("\nUpdated dataset:", OUTPUT_FILE)
print("Remaining-location review:", REVIEW_FILE)
display(unmapped.head(20))

Phase 04.5.11 completed.

                                          metric  count
0                                  Total matches   8546
1              Preliminary India-host candidates    546
2             Preliminary non-India-host matches   6371
3  India-team matches outside India (candidates)    158
4                 Matches with unverified cities   1629
5               Unmapped city/venue combinations    174

Updated dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_context_host_classified_v3_2023_2026.csv
Remaining-location review: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_host_country_review_v3_2023_2026.csv

,city,venue,match_count,events
80,Mong Kok,"Mission Road Ground, Mong Kok, Hong Kong",54,Asian Cricket Council Women's Emerging Teams Cup | CWC Challenge League | East Asia Cup | Hong Kong Men's T20I Series | Hong Kong Women's T20I Tri-Series | Kuwait tour of Hong Kong | Nepal tour of Hong Kong | Quadrangular Twenty20 Series (Hong Kong)
66,Krefeld,Bayer Uerdingen Cricket Ground,33,Austria tour of Germany | Belgium tour of Germany | Germany Women's T20I Tri-Series | ICC Men's T20 World Cup Sub Regional Europe Qualifier | Italy Women in Germany T20I Match
8,Basseterre,"Warner Park, Basseterre, St Kitts",31,Australia Women tour of West Indies | Australia tour of West Indies | Bangladesh Women tour of West Indies | Bangladesh tour of West Indies | Caribbean Premier League
9,Beckenham,"Kent County Cricket Ground, Beckenham",31,Charlotte Edwards Cup | County Championship | ECB Women's One-Day Cup | One-Day Cup | Rachael Heyhoe Flint Trophy
42,Gelephu,Gelephu International Cricket Ground,30,Bahrain tour of Bhutan | Bhutan Quadrangular T20I Series | Lotus Cup Women's Tri-Series | Myanmar Women tour of Bhutan | Myanmar tour of Bhutan
38,Episkopi,Happy Valley Ground,30,Cyprus T20 Tri-Series | Estonia Women tour of Cyprus | Estonia tour of Cyprus | Finland tour of Cyprus | ICC Men's T20 World Cup Sub Regional Europe Qualifier A | Malta Women tour of Cyprus
18,Buenos Aires,"St Albans Club, Buenos Aires",28,Bermuda tour of Argentina | Brazil tour of Argentina | ICC Men's T20 World Cup Americas Region Qualifier | ICC Men's T20 World Cup Sub Regional Americas Qualifier | ICC Women's T20 World Cup Americas Region Qualifier
75,Maggona,"Surrey Village, Maggona",27,Major Clubs Limited Over Tournament | Major Clubs T20 Tournament | Major League Tournament
39,Episkopi,Happy Valley Ground 2,27,Austria tour of Cyprus | Bulgaria in Cyprus T20I Series | Cyprus T20 Tri-Series | Greece Women tour of Cyprus | ICC Men's T20 World Cup Sub Regional Europe Qualifier A
65,Kowloon,Kowloon Cricket Club,26,CWC Challenge League | FairBreak Invitational Tournament
114,Prague,"Scott Page Field, Vinor",26,Central Europe Cup | Cyprus Women tour of Czech Republic | Hungary tour of Czech Republic | Women Central Europe Cup
43,George Town,"Jimmy Powell Oval, Cayman Islands",25,ICC Men's T20 World Cup Sub Regional Americas Qualifier B | North America T20 Cup
44,Gibraltar,Europa Sports Complex,22,Estonia Women tour of Gibraltar | Estonia tour of Gibraltar | Gibraltar Tri-Nation T20I Series | Jersey Women tour of Gibraltar | Luxembourg tour of Gibraltar | Serbia tour of Gibraltar
0,Accra,"Achimota Senior Secondary School A Field, Accra",22,African Games | ICC Men's T20 World Cup Africa Sub Regional Qualifier B | Women's African Games
98,Oakland,"Oakland Coliseum,Oakland",21,Major League Cricket
110,Port Moresby,"Amini Park, Port Moresby",21,ICC Men's T20 World Cup East Asia-Pacific Qualifier | PacificAus Sports Cricket Invitational | United Arab Emirates Women tour of Papua New Guinea
29,Cork,"Mardyke, Cork",21,Cricket Ireland Inter-Provincial Limited Over Cup | Cricket Ireland Inter-Provincial Twenty20 Trophy
50,Hangzhou,Zhejiang University of Technology Cricket Field,20,Asian Games Men's Cricket Competition | Asian Games Women's Cricket Competition | Women's T20I Quadrangular Series (in China)
14,Bready,"Bready Cricket Club, Magheramason, Bready",20,Cricket Ireland Inter-Provincial Limited Over Cup | Cricket Ireland Inter-Provincial Twenty20 Trophy | West Indies Women tour of Ireland | West Indies tour of Ireland
137,Spinaceto,Roma Cricket Ground,20,ICC Men's T20 World Cup Sub Regional Europe Qualifier | ICC Women's T20 World Cup Europe Division 2 Qualifier

In [76]:
# Phase 04.5.12 — Extend cricket host-country mapping

from pathlib import Path
import pandas as pd
import re

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_context_host_classified_v3_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_context_host_classified_v4_2023_2026.csv"
REVIEW_FILE = DATA_DIR / "cricket_host_country_review_v4_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

EXTRA_COUNTRIES = {
    # Hong Kong
    "mong kok": "Hong Kong",
    "kowloon": "Hong Kong",

    # Germany
    "krefeld": "Germany",

    # Saint Kitts and Nevis
    "basseterre": "Saint Kitts and Nevis",

    # England
    "beckenham": "England",

    # Bhutan
    "gelephu": "Bhutan",

    # Cyprus
    "episkopi": "Cyprus",

    # Argentina
    "buenos aires": "Argentina",

    # Sri Lanka
    "maggona": "Sri Lanka",

    # Other common cricket venues
    "bridgetown": "Barbados",
    "gros islet": "Saint Lucia",
    "kingston": "Jamaica",
    "port of spain": "Trinidad and Tobago",
    "tarouba": "Trinidad and Tobago",
    "colombo": "Sri Lanka",
    "galle": "Sri Lanka",
    "hambantota": "Sri Lanka",
    "kandy": "Sri Lanka",
    "pallekele": "Sri Lanka",
    "dambulla": "Sri Lanka",
    "benoni": "South Africa",
    "bloemfontein": "South Africa",
    "cape town": "South Africa",
    "centurion": "South Africa",
    "durban": "South Africa",
    "east london": "South Africa",
    "gqeberha": "South Africa",
    "johannesburg": "South Africa",
    "paarl": "South Africa",
    "potchefstroom": "South Africa",
    "pretoria": "South Africa",
    "melbourne": "Australia",
    "sydney": "Australia",
    "perth": "Australia",
    "adelaide": "Australia",
    "brisbane": "Australia",
    "auckland": "New Zealand",
    "christchurch": "New Zealand",
    "wellington": "New Zealand",
    "dunedin": "New Zealand",
    "hamilton": "New Zealand",
    "kirtipur": "Nepal",
    "kathmandu": "Nepal",
    "kuala lumpur": "Malaysia",
    "bangkok": "Thailand",
    "bali": "Indonesia",
    "kigali city": "Rwanda",
    "kigali": "Rwanda",
    "gaborone": "Botswana",
    "ilfov county": "Romania",
    "providence": "Guyana",
    "sano": "Japan",
    "marsa": "Malta",
    "bangi": "Brunei",
    "chelmsford": "England",
    "northampton": "England",
    "brighton": "England",
    "leicester": "England",
    "hove": "England",
}

def normalize_city(value):
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).strip().casefold())

if "host_country" not in matches.columns:
    matches["host_country"] = pd.NA

city_norm = matches["city"].map(normalize_city)
mapping = {normalize_city(k): v for k, v in EXTRA_COUNTRIES.items()}
new_country = city_norm.map(mapping)

# Preserve earlier country assignments; fill only missing values.
matches["host_country"] = matches["host_country"].where(
    matches["host_country"].notna(), new_country
)

matches["host_country_method"] = matches["host_country"].apply(
    lambda x: "preliminary_city_mapping" if pd.notna(x) else "unverified"
)

matches["host_country_status"] = matches["host_country"].apply(
    lambda x: "preliminary_mapping_requires_validation"
    if pd.notna(x) else "unverified_city"
)

matches["is_india_hosted"] = pd.Series(
    pd.NA, index=matches.index, dtype="boolean"
)

mapped = matches["host_country"].notna()
matches.loc[mapped, "is_india_hosted"] = (
    matches.loc[mapped, "host_country"].eq("India")
)

teams = matches["teams"].fillna("").str.casefold()
matches["india_involved"] = teams.str.contains(
    r"(?<![a-z])india(?![a-z])", regex=True, na=False
)

matches["india_team_abroad_candidate"] = (
    matches["india_involved"]
    & matches["host_country"].notna()
    & matches["host_country"].ne("India")
)

matches.to_csv(OUTPUT_FILE, index=False)

unmapped = (
    matches.loc[matches["host_country"].isna()]
    .groupby(["city", "venue"], dropna=False)
    .agg(
        match_count=("match_id", "size"),
        events=("event", lambda s: " | ".join(
            sorted(set(s.dropna().astype(str)))[:8]
        ))
    )
    .reset_index()
    .sort_values("match_count", ascending=False)
)

unmapped.to_csv(REVIEW_FILE, index=False)

summary = pd.DataFrame({
    "metric": [
        "Total matches",
        "Preliminary India-host candidates",
        "Preliminary non-India-host matches",
        "India-team matches outside India (candidates)",
        "Matches with unverified cities",
        "Unmapped city/venue combinations"
    ],
    "count": [
        len(matches),
        int(matches["host_country"].eq("India").sum()),
        int((
            matches["host_country"].notna()
            & matches["host_country"].ne("India")
        ).sum()),
        int(matches["india_team_abroad_candidate"].sum()),
        int(matches["host_country"].isna().sum()),
        len(unmapped)
    ]
})

print("Phase 04.5.12 completed.")
display(summary)

print("\nUpdated dataset:", OUTPUT_FILE)
print("Remaining-location review:", REVIEW_FILE)
display(unmapped.head(20))

Phase 04.5.12 completed.

                                          metric  count
0                                  Total matches   8546
1              Preliminary India-host candidates    546
2             Preliminary non-India-host matches   6725
3  India-team matches outside India (candidates)    158
4                 Matches with unverified cities   1275
5               Unmapped city/venue combinations    161

Updated dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_context_host_classified_v4_2023_2026.csv
Remaining-location review: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_host_country_review_v4_2023_2026.csv

,city,venue,match_count,events
101,Prague,"Scott Page Field, Vinor",26,Central Europe Cup | Cyprus Women tour of Czech Republic | Hungary tour of Czech Republic | Women Central Europe Cup
34,George Town,"Jimmy Powell Oval, Cayman Islands",25,ICC Men's T20 World Cup Sub Regional Americas Qualifier B | North America T20 Cup
35,Gibraltar,Europa Sports Complex,22,Estonia Women tour of Gibraltar | Estonia tour of Gibraltar | Gibraltar Tri-Nation T20I Series | Jersey Women tour of Gibraltar | Luxembourg tour of Gibraltar | Serbia tour of Gibraltar
0,Accra,"Achimota Senior Secondary School A Field, Accra",22,African Games | ICC Men's T20 World Cup Africa Sub Regional Qualifier B | Women's African Games
23,Cork,"Mardyke, Cork",21,Cricket Ireland Inter-Provincial Limited Over Cup | Cricket Ireland Inter-Provincial Twenty20 Trophy
85,Oakland,"Oakland Coliseum,Oakland",21,Major League Cricket
97,Port Moresby,"Amini Park, Port Moresby",21,ICC Men's T20 World Cup East Asia-Pacific Qualifier | PacificAus Sports Cricket Invitational | United Arab Emirates Women tour of Papua New Guinea
124,Spinaceto,Roma Cricket Ground,20,ICC Men's T20 World Cup Sub Regional Europe Qualifier | ICC Women's T20 World Cup Europe Division 2 Qualifier
12,Bready,"Bready Cricket Club, Magheramason, Bready",20,Cricket Ireland Inter-Provincial Limited Over Cup | Cricket Ireland Inter-Provincial Twenty20 Trophy | West Indies Women tour of Ireland | West Indies tour of Ireland
41,Hangzhou,Zhejiang University of Technology Cricket Field,20,Asian Games Men's Cricket Competition | Asian Games Women's Cricket Competition | Women's T20I Quadrangular Series (in China)
74,Navi Mumbai,"Dr DY Patil Sports Academy, Navi Mumbai",19,ICC Women's World Cup | West Indies Women tour of India | Women's Premier League
15,Castel,"King George V Sports Ground, Castel",19,ICC Men's T20 World Cup Sub Regional Europe Qualifier Group C | Isle of Man tour of Guernsey | Jersey tour of Guernsey | Papua New Guinea tour of Guernsey | Switzerland tour of Guernsey
13,Brondby,"Svanholm Park, Brondby",19,Germany tour of Denmark | ICC Men's T20 World Cup Sub Regional Europe Qualifier B | Jersey tour of Denmark | Nordic T20 Cup
113,Scarborough,"North Marine Road Ground, Scarborough",19,County Championship | ECB Women's One-Day Cup | One-Day Cup | Rachael Heyhoe Flint Trophy
120,Sofia,"Vassil Levski National Sports Academy, Sofia",19,Bulgaria Tri-Nation T20I Series | Serbia Women tour of Bulgaria | Women's T20 Quadrangular Series (in Bulgaria)
109,Rome,"Simar Cricket Ground, Rome",19,ICC Men's T20 World Cup Sub Regional Europe Qualifier | ICC Women's T20 World Cup Europe Division 2 Qualifier
2,Albergaria,Santarem Cricket Ground,18,Gibraltar tour of Portugal | Norway Women tour of Portugal | Norway tour of Portugal | Portugal T20 Tri-Series
42,Incheon,"Yeonhui Cricket Ground, Incheon",18,ICC Men's T20 World Cup East Asia-Pacific Region Qualifier B | Japan tour of South Korea | Women's East Asia Cup
56,Kurunegala,"Welagedara Stadium, Kurunegala",18,Major Clubs Limited Over Tournament | Major League Tournament
129,Stockholm,"Botkyrka Cricket Center, Stockholm",17,Portugal tour of Sweden | Viking Cup

In [77]:
# Phase 04.5.13 — Prioritize unresolved cricket venues

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_context_host_classified_v4_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_unmapped_venue_priority_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

unmapped = matches.loc[
    matches["host_country"].isna()
].copy()

priority = (
    unmapped.groupby(["city", "venue"], dropna=False)
    .agg(
        match_count=("match_id", "size"),
        first_match_date=("match_date", "min"),
        last_match_date=("match_date", "max"),
        events=("event", lambda s: " | ".join(
            sorted(set(s.dropna().astype(str)))[:5]
        )),
        teams=("teams", lambda s: " | ".join(
            sorted(set(s.dropna().astype(str)))[:5]
        ))
    )
    .reset_index()
    .sort_values(
        ["match_count", "city"],
        ascending=[False, True]
    )
)

priority.insert(
    0, "priority_rank",
    range(1, len(priority) + 1)
)

priority.to_csv(OUTPUT_FILE, index=False)

print("Phase 04.5.13 completed.")
print("Unresolved match records:", len(unmapped))
print("Unresolved city/venue combinations:", len(priority))
print("Saved review file:", OUTPUT_FILE)

display(priority.head(30))

Phase 04.5.13 completed.
Unresolved match records: 1275
Unresolved city/venue combinations: 161
Saved review file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_unmapped_venue_priority_2023_2026.csv

,priority_rank,city,venue,match_count,first_match_date,last_match_date,events,teams
101,1,Prague,"Scott Page Field, Vinor",26,2023-06-11,2026-06-28,Central Europe Cup | Cyprus Women tour of Czech Republic | Hungary tour of Czech Republic | Women Central Europe Cup,Austria | Czech Republic | Austria | Gibraltar | Croatia | Czech Republic | Croatia | Gibraltar | Cyprus | Czech Republic
34,2,George Town,"Jimmy Powell Oval, Cayman Islands",25,2025-04-19,2026-03-15,ICC Men's T20 World Cup Sub Regional Americas Qualifier B | North America T20 Cup,Argentina | Cayman Islands | Argentina | Mexico | Argentina | Suriname | Bahamas | Bermuda | Bahamas | Canada
0,3,Accra,"Achimota Senior Secondary School A Field, Accra",22,2024-03-07,2026-03-28,African Games | ICC Men's T20 World Cup Africa Sub Regional Qualifier B | Women's African Games,Eswatini | St Helena | Malawi | Ghana | Malawi | Tanzania | Namibia | South Africa | Namibia | Tanzania
35,4,Gibraltar,Europa Sports Complex,22,2023-05-04,2024-12-16,Estonia Women tour of Gibraltar | Estonia tour of Gibraltar | Gibraltar Tri-Nation T20I Series | Jersey Women tour of Gibraltar | Luxembourg tour of Gibraltar,Estonia | Gibraltar | Gibraltar | Estonia | Gibraltar | Jersey | Gibraltar | Luxembourg | Gibraltar | Malta
23,5,Cork,"Mardyke, Cork",21,2023-05-15,2025-08-13,Cricket Ireland Inter-Provincial Limited Over Cup | Cricket Ireland Inter-Provincial Twenty20 Trophy,Leinster Lightning | Munster Reds | Leinster Lightning | Northern Knights | Munster Reds | Leinster Lightning | Munster Reds | North-West Warriors | Munster Reds | Northern Knights
85,6,Oakland,"Oakland Coliseum,Oakland",21,2025-06-12,2026-07-18,Major League Cricket,Los Angeles Knight Riders | San Francisco Unicorns | Los Angeles Knight Riders | Washington Freedom | MI New York | Los Angeles Knight Riders | MI New York | San Francisco Unicorns | MI New York | Texas Super Kings
97,7,Port Moresby,"Amini Park, Port Moresby",21,2023-07-22,2025-10-19,ICC Men's T20 World Cup East Asia-Pacific Qualifier | PacificAus Sports Cricket Invitational | United Arab Emirates Women tour of Papua New Guinea,Japan | Papua New Guinea | Japan | Philippines | Japan | Vanuatu | Papua New Guinea | Philippines | Papua New Guinea | Samoa
12,8,Bready,"Bready Cricket Club, Magheramason, Bready",20,2023-05-23,2026-07-15,Cricket Ireland Inter-Provincial Limited Over Cup | Cricket Ireland Inter-Provincial Twenty20 Trophy | West Indies Women tour of Ireland | West Indies tour of Ireland,Ireland | West Indies | Leinster Lightning | North-West Warriors | Munster Reds | North-West Warriors | Munster Reds | Northern Knights | North-West Warriors | Leinster Lightning
41,9,Hangzhou,Zhejiang University of Technology Cricket Field,20,2023-09-21,2024-11-10,Asian Games Men's Cricket Competition | Asian Games Women's Cricket Competition | Women's T20I Quadrangular Series (in China),Bangladesh | India | Bangladesh | Malaysia | China | Hong Kong | India | Malaysia | India | Nepal
124,10,Spinaceto,Roma Cricket Ground,20,2024-06-09,2025-05-29,ICC Men's T20 World Cup Sub Regional Europe Qualifier | ICC Women's T20 World Cup Europe Division 2 Qualifier,France | Isle of Man | France | Turkey | Germany | Jersey | Germany | Sweden | Hungary | Romania
13,11,Brondby,"Svanholm Park, Brondby",19,2023-05-18,2026-07-14,Germany tour of Denmark | ICC Men's T20 World Cup Sub Regional Europe Qualifier B | Jersey tour of Denmark | Nordic T20 Cup,Belgium | Serbia | Denmark | Estonia | Denmark | Finland | Denmark | Germany | Denmark | Hungary
15,12,Castel,"King George V Sports Ground, Castel",19,2024-06-22,2026-05-03,ICC Men's T20 World Cup Sub Regional Europe Qualifier Group C | Isle of Man tour of Guernsey | Jersey tour of Guernsey | Papua New Guinea tour of Guernsey | Switzerland tour of Guernsey,Czech Republic | Greece | Denmark | Cyprus | Denmark | Czech Republic | Denmark | Guernsey | Estonia | Guernsey
74,13,Navi Mumbai,"Dr DY Patil Sports Academy, Navi Mumbai",19,2024-12-15,2026-01-17,ICC Women's World Cup | West Indies Women tour of India | Women's Premier League,Australia | India | Bangladesh | India | Delhi Capitals | Royal Challengers Bengaluru | Gujarat Giants | Delhi Capitals | Gujarat Giants | Mumbai Indians
109,14,Rome,"Simar Cricket Ground, Rome",19,2024-06-09,2025-05-29,ICC Men's T20 World Cup Sub Regional Europe Qualifier | ICC Women's T20 World Cup Europe Division 2 Qualifier,Austria | Hungary | Austria | Romania | France | Austria | France | Italy | France | Luxembourg
113,15,Scarborough,"North Marine Road Ground, Scarborough",19,2023-05-10,2026-07-21,County Championship | ECB Women's One-Day Cup | One-Day Cup | Rachael Heyhoe Flint Trophy,Central Sparks | Northern Diamonds | Durham | Yorkshire | Essex | Yorkshire | Hampshire | Yorkshire | Kent | Yorkshire
120,16,Sofia,"Vassil Levski National Sports Academy, Sofia",19,2025-07-07,2026-06-28,Bulgaria Tri-Nation T20I Series | Serbia Women tour of Bulgaria | Women's T20 Quadrangular Series (in Bulgaria),Bulgaria | Gibraltar | Bulgaria | Serbia | Gibraltar | Bulgaria | Greece | Bulgaria | Serbia | Bulgaria
2,17,Albergaria,Santarem Cricket Ground,18,2023-04-10,2026-04-09,Gibraltar tour of Portugal | Norway Women tour of Portugal | Norway tour of Portugal | Portugal T20 Tri-Series,France | Norway | France | Portugal | Gibraltar | Portugal | Norway | France | Norway | Portugal
42,18,Incheon,"Yeonhui Cricket Ground, Incheon",18,2024-09-25,2024-10-13,ICC Men's T20 World Cup East Asia-Pacific Region Qualifier B | Japan tour of South Korea | Women's East Asia Cup,Hong Kong | China | Hong Kong | Japan | Hong Kong | South Korea | Indonesia | Philippines | Indonesia | South Korea
56,19,Kurunegala,"Welagedara Stadium, Kurunegala",18,2024-06-13,2026-02-05,Major Clubs Limited Over Tournament | Major League Tournament,Badureliya Sports Club | Burgher Recreation Club | Badureliya Sports Club | Nugegoda Sports Welfare Club | Burgher Recreation Club | Kurunegala Youth Cricket Club | Chilaw Marians Cricket Club | Badureliya Sports Club | Kandy Customs Cricket Club | Kurunegala Youth Cricket Club
4,20,Alexandra,"Molyneux Park, Alexandra",17,2023-12-28,2025-12-30,Plunket Shield | Super Smash | Women's Super Smash,Auckland | Otago | Canterbury | Otago | Central Districts | Otago | Otago Volts | Central Stags | Otago | Auckland
9,21,Blackpool,"Stanley Park, Blackpool",17,2023-06-04,2026-06-28,Charlotte Edwards Cup | County Championship | ECB Women's One-Day Cup | One-Day Cup | Vitality Blast,Essex | Lancashire | Kent | Lancashire | Lancashire | Durham | Lancashire | Essex | Lancashire | Glamorgan
129,22,Stockholm,"Botkyrka Cricket Center, Stockholm",17,2025-08-08,2026-07-02,Portugal tour of Sweden | Viking Cup,Austria | Finland | Finland | Norway | Finland | Sweden | France | Austria | Norway | Austria
28,23,Dharamsala,"Himachal Pradesh Cricket Association Stadium, Dharamsala",16,2023-05-17,2026-05-26,England tour of India | ICC Cricket World Cup | Indian Premier League | South Africa tour of India,Australia | New Zealand | Chennai Super Kings | Punjab Kings | Delhi Capitals | Punjab Kings | England | Bangladesh | England | India
133,24,Szodliget,"GB Oval, Szodliget",16,2023-08-05,2026-06-28,Austria tour of Hungary | Budapest Cup | Croatia tour of Hungary | Slovenia tour of Hungary,Austria | Hungary | Austria | Luxembourg | Austria | Romania | Croatia | Hungary | Hungary | Austria
1,25,Accra,"Achimota Senior Secondary School B Field, Accra",15,2024-03-07,2026-03-28,African Games | ICC Men's T20 World Cup Africa Sub Regional Qualifier B | Women's African Games,Eswatini | Malawi | Ghana | Eswatini | Ghana | Kenya | Namibia | Nigeria | Nigeria | Namibia
5,26,Almeria,"Desert Springs Cricket Ground, Almeria",15,2023-09-06,2023-10-24,ICC Women's T20 World Cup Europe Region Qualifier | Ireland Women v Scotland Women,France | Netherlands | France | Scotland | Ireland | Scotland | Italy | France | Italy | Netherlands
17,27,Cheltenham,"College Ground, Cheltenham",15,2023-07-20,2025-08-05,County Championship | One-Day Cup | Rachael Heyhoe Flint Trophy | Vitality Blast | Vitality Blast Men,Derbyshire | Gloucestershire | Glamorgan | Gloucestershire | Gloucestershire | Derbyshire | Gloucestershire | Glamorgan | Gloucestershire | Northamptonshire
54,28,Koge,Koge Cricket Club,15,2024-09-14,2026-07-14,ICC Men's T20 World Cup Sub Regional Europe Qualifier B | Nordic T20 Cup | Women's T20I Quadrangular Series (in Denmark),Austria | Denmark | Belgium | Romania | Denmark | Luxembourg | Denmark | Norway | Denmark | Sweden
73,29,Navi Mumbai,"Dr DY Patil Sports Academy, Mumbai",15,2023-03-04,2024-01-09,Australia Women tour of India | England Women tour of India | Women's Premier League,Australia | India | Delhi Capitals | Mumbai Indians | Delhi Capitals | UP Warriorz | Gujarat Giants | Delhi Capitals | Gujarat Giants | UP Warriorz
11,30,Blantyre,"TCA Oval, Blantyre",14,2024-10-09,2025-07-13,Quadrangular Twenty20 Series (Malawi) | Rwanda tour of Malawi,Bahrain | Germany | Bahrain | Tanzania | Germany | Malawi | Germany | Tanzania | Malawi | Bahrain

In [78]:
# Phase 04.5.14 — Apply targeted mappings to frequent unresolved venues

from pathlib import Path
import pandas as pd
import re

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_context_host_classified_v4_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_context_host_classified_v5_2023_2026.csv"
REVIEW_FILE = DATA_DIR / "cricket_host_country_review_v5_2023_2026.csv"

matches = pd.read_csv(INPUT_FILE)

# Preliminary mappings for frequent locations shown in Phase 04.5.13.
# Countries are assigned only when the city/location is sufficiently identifiable.
LOCATION_COUNTRIES = {
    "prague": "Czech Republic",
    "george town": "Cayman Islands",
    "georgetown": "Cayman Islands",
    "accra": "Ghana",
    "gibraltar": "Gibraltar",
    "cork": "Ireland",
    "auckland": "New Zealand",
    "port moresby": "Papua New Guinea",
    "bready": "Northern Ireland",
    "hangzhou": "China",
    "spinaceto": "Italy",
    "roma": "Italy",
    "rome": "Italy",
    "krefeld": "Germany",
    "basseterre": "Saint Kitts and Nevis",
    "beckenham": "England",
    "gelephu": "Bhutan",
    "episkopi": "Cyprus",
    "buenos aires": "Argentina",
    "maggona": "Sri Lanka",
    "mong kok": "Hong Kong",
    "kowloon": "Hong Kong",
    "bridgetown": "Barbados",
    "gros islet": "Saint Lucia",
    "kingston": "Jamaica",
    "port of spain": "Trinidad and Tobago",
    "tarouba": "Trinidad and Tobago",
    "colombo": "Sri Lanka",
    "galle": "Sri Lanka",
    "hambantota": "Sri Lanka",
    "kandy": "Sri Lanka",
    "pallekele": "Sri Lanka",
    "dambulla": "Sri Lanka",
    "benoni": "South Africa",
    "bloemfontein": "South Africa",
    "cape town": "South Africa",
    "centurion": "South Africa",
    "durban": "South Africa",
    "east london": "South Africa",
    "gqeberha": "South Africa",
    "johannesburg": "South Africa",
    "paarl": "South Africa",
    "potchefstroom": "South Africa",
    "melbourne": "Australia",
    "sydney": "Australia",
    "perth": "Australia",
    "adelaide": "Australia",
    "brisbane": "Australia",
    "christchurch": "New Zealand",
    "wellington": "New Zealand",
    "dunedin": "New Zealand",
    "hamilton": "New Zealand",
    "kirtipur": "Nepal",
    "kathmandu": "Nepal",
    "kuala lumpur": "Malaysia",
    "bangkok": "Thailand",
    "bali": "Indonesia",
    "kigali": "Rwanda",
    "kigali city": "Rwanda",
    "gaborone": "Botswana",
    "ilfov county": "Romania",
    "providence": "Guyana",
    "sano": "Japan",
    "marsa": "Malta",
    "bangi": "Brunei",
    "chelmsford": "England",
    "northampton": "England",
    "brighton": "England",
    "leicester": "England",
    "hove": "England",
}

def normalize_location(value):
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).strip().casefold())

location_map = {
    normalize_location(city): country
    for city, country in LOCATION_COUNTRIES.items()
}

city_norm = matches["city"].map(normalize_location)
new_country = city_norm.map(location_map)

# Preserve existing assignments and fill only missing country values.
missing_country = matches["host_country"].isna()
matches.loc[missing_country, "host_country"] = new_country[missing_country]

matches["host_country_method"] = matches["host_country"].apply(
    lambda x: "preliminary_city_mapping" if pd.notna(x) else "unverified"
)
matches["host_country_status"] = matches["host_country"].apply(
    lambda x: "preliminary_mapping_requires_validation"
    if pd.notna(x) else "unverified_city"
)

matches["is_india_hosted"] = pd.Series(
    pd.NA, index=matches.index, dtype="boolean"
)
mapped = matches["host_country"].notna()
matches.loc[mapped, "is_india_hosted"] = (
    matches.loc[mapped, "host_country"].eq("India")
)

teams = matches["teams"].fillna("").str.casefold()
matches["india_involved"] = teams.str.contains(
    r"(?<![a-z])india(?![a-z])", regex=True, na=False
)
matches["india_team_abroad_candidate"] = (
    matches["india_involved"]
    & matches["host_country"].notna()
    & matches["host_country"].ne("India")
)

matches.to_csv(OUTPUT_FILE, index=False)

unmapped = (
    matches.loc[matches["host_country"].isna()]
    .groupby(["city", "venue"], dropna=False)
    .agg(
        match_count=("match_id", "size"),
        events=("event", lambda s: " | ".join(
            sorted(set(s.dropna().astype(str)))[:5]
        ))
    )
    .reset_index()
    .sort_values("match_count", ascending=False)
)

unmapped.to_csv(REVIEW_FILE, index=False)

summary = pd.DataFrame({
    "metric": [
        "Total matches",
        "Preliminary India-host candidates",
        "Preliminary non-India-host matches",
        "India-team matches outside India (candidates)",
        "Matches with unverified cities",
        "Unmapped city/venue combinations",
    ],
    "count": [
        len(matches),
        int(matches["host_country"].eq("India").sum()),
        int((
            matches["host_country"].notna()
            & matches["host_country"].ne("India")
        ).sum()),
        int(matches["india_team_abroad_candidate"].sum()),
        int(matches["host_country"].isna().sum()),
        len(unmapped),
    ]
})

print("Phase 04.5.14 completed.")
display(summary)
print("\nUpdated dataset:", OUTPUT_FILE)
print("Remaining-location review:", REVIEW_FILE)
display(unmapped.head(20))

Phase 04.5.14 completed.

                                          metric  count
0                                  Total matches   8546
1              Preliminary India-host candidates    546
2             Preliminary non-India-host matches   6962
3  India-team matches outside India (candidates)    163
4                 Matches with unverified cities   1038
5               Unmapped city/venue combinations    149

Updated dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_context_host_classified_v5_2023_2026.csv
Remaining-location review: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_host_country_review_v5_2023_2026.csv

,city,venue,match_count,events
78,Oakland,"Oakland Coliseum,Oakland",21,Major League Cricket
10,Brondby,"Svanholm Park, Brondby",19,Germany tour of Denmark | ICC Men's T20 World Cup Sub Regional Europe Qualifier B | Jersey tour of Denmark | Nordic T20 Cup
102,Scarborough,"North Marine Road Ground, Scarborough",19,County Championship | ECB Women's One-Day Cup | One-Day Cup | Rachael Heyhoe Flint Trophy
67,Navi Mumbai,"Dr DY Patil Sports Academy, Navi Mumbai",19,ICC Women's World Cup | West Indies Women tour of India | Women's Premier League
12,Castel,"King George V Sports Ground, Castel",19,ICC Men's T20 World Cup Sub Regional Europe Qualifier Group C | Isle of Man tour of Guernsey | Jersey tour of Guernsey | Papua New Guinea tour of Guernsey | Switzerland tour of Guernsey
109,Sofia,"Vassil Levski National Sports Academy, Sofia",19,Bulgaria Tri-Nation T20I Series | Serbia Women tour of Bulgaria | Women's T20 Quadrangular Series (in Bulgaria)
0,Albergaria,Santarem Cricket Ground,18,Gibraltar tour of Portugal | Norway Women tour of Portugal | Norway tour of Portugal | Portugal T20 Tri-Series
49,Kurunegala,"Welagedara Stadium, Kurunegala",18,Major Clubs Limited Over Tournament | Major League Tournament
35,Incheon,"Yeonhui Cricket Ground, Incheon",18,ICC Men's T20 World Cup East Asia-Pacific Region Qualifier B | Japan tour of South Korea | Women's East Asia Cup
2,Alexandra,"Molyneux Park, Alexandra",17,Plunket Shield | Super Smash | Women's Super Smash
117,Stockholm,"Botkyrka Cricket Center, Stockholm",17,Portugal tour of Sweden | Viking Cup
7,Blackpool,"Stanley Park, Blackpool",17,Charlotte Edwards Cup | County Championship | ECB Women's One-Day Cup | One-Day Cup | Vitality Blast
24,Dharamsala,"Himachal Pradesh Cricket Association Stadium, Dharamsala",16,England tour of India | ICC Cricket World Cup | Indian Premier League | South Africa tour of India
121,Szodliget,"GB Oval, Szodliget",16,Austria tour of Hungary | Budapest Cup | Croatia tour of Hungary | Slovenia tour of Hungary
3,Almeria,"Desert Springs Cricket Ground, Almeria",15,ICC Women's T20 World Cup Europe Region Qualifier | Ireland Women v Scotland Women
66,Navi Mumbai,"Dr DY Patil Sports Academy, Mumbai",15,Australia Women tour of India | England Women tour of India | Women's Premier League
14,Cheltenham,"College Ground, Cheltenham",15,County Championship | One-Day Cup | Rachael Heyhoe Flint Trophy | Vitality Blast | Vitality Blast Men
47,Koge,Koge Cricket Club,15,ICC Men's T20 World Cup Sub Regional Europe Qualifier B | Nordic T20 Cup | Women's T20I Quadrangular Series (in Denmark)
115,St Saviour,"Grainville, St Saviour",14,CWC Challenge League | Guernsey Women tour of Jersey | Inter-Insular T20 Series | Inter-Insular Women's Twenty20 Series
9,Blantyre,"TCA Oval, Blantyre",14,Quadrangular Twenty20 Series (Malawi) | Rwanda tour of Malawi

In [79]:
# Phase 04.5.15 — Prioritize remaining venue-review records

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_host_country_review_v5_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "cricket_host_country_priority_review_v5_2023_2026.csv"

review = pd.read_csv(INPUT_FILE)

# Rank unresolved locations by the number of affected matches.
review = review.sort_values(
    "match_count", ascending=False
).reset_index(drop=True)

review.insert(0, "priority_rank", range(1, len(review) + 1))

review.to_csv(OUTPUT_FILE, index=False)

print("Phase 04.5.15 completed.")
print("Unresolved venue combinations:", len(review))
print("Affected match records:", int(review["match_count"].sum()))
print("Saved review:", OUTPUT_FILE)

display(review.head(30))

Phase 04.5.15 completed.
Unresolved venue combinations: 149
Affected match records: 1038
Saved review: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\cricket_host_country_priority_review_v5_2023_2026.csv

,priority_rank,city,venue,match_count,events
0,1,Oakland,"Oakland Coliseum,Oakland",21,Major League Cricket
1,2,Brondby,"Svanholm Park, Brondby",19,Germany tour of Denmark | ICC Men's T20 World Cup Sub Regional Europe Qualifier B | Jersey tour of Denmark | Nordic T20 Cup
2,3,Scarborough,"North Marine Road Ground, Scarborough",19,County Championship | ECB Women's One-Day Cup | One-Day Cup | Rachael Heyhoe Flint Trophy
3,4,Navi Mumbai,"Dr DY Patil Sports Academy, Navi Mumbai",19,ICC Women's World Cup | West Indies Women tour of India | Women's Premier League
4,5,Castel,"King George V Sports Ground, Castel",19,ICC Men's T20 World Cup Sub Regional Europe Qualifier Group C | Isle of Man tour of Guernsey | Jersey tour of Guernsey | Papua New Guinea tour of Guernsey | Switzerland tour of Guernsey
5,6,Sofia,"Vassil Levski National Sports Academy, Sofia",19,Bulgaria Tri-Nation T20I Series | Serbia Women tour of Bulgaria | Women's T20 Quadrangular Series (in Bulgaria)
6,7,Albergaria,Santarem Cricket Ground,18,Gibraltar tour of Portugal | Norway Women tour of Portugal | Norway tour of Portugal | Portugal T20 Tri-Series
7,8,Kurunegala,"Welagedara Stadium, Kurunegala",18,Major Clubs Limited Over Tournament | Major League Tournament
8,9,Incheon,"Yeonhui Cricket Ground, Incheon",18,ICC Men's T20 World Cup East Asia-Pacific Region Qualifier B | Japan tour of South Korea | Women's East Asia Cup
9,10,Alexandra,"Molyneux Park, Alexandra",17,Plunket Shield | Super Smash | Women's Super Smash
10,11,Stockholm,"Botkyrka Cricket Center, Stockholm",17,Portugal tour of Sweden | Viking Cup
11,12,Blackpool,"Stanley Park, Blackpool",17,Charlotte Edwards Cup | County Championship | ECB Women's One-Day Cup | One-Day Cup | Vitality Blast
12,13,Dharamsala,"Himachal Pradesh Cricket Association Stadium, Dharamsala",16,England tour of India | ICC Cricket World Cup | Indian Premier League | South Africa tour of India
13,14,Szodliget,"GB Oval, Szodliget",16,Austria tour of Hungary | Budapest Cup | Croatia tour of Hungary | Slovenia tour of Hungary
14,15,Almeria,"Desert Springs Cricket Ground, Almeria",15,ICC Women's T20 World Cup Europe Region Qualifier | Ireland Women v Scotland Women
15,16,Navi Mumbai,"Dr DY Patil Sports Academy, Mumbai",15,Australia Women tour of India | England Women tour of India | Women's Premier League
16,17,Cheltenham,"College Ground, Cheltenham",15,County Championship | One-Day Cup | Rachael Heyhoe Flint Trophy | Vitality Blast | Vitality Blast Men
17,18,Koge,Koge Cricket Club,15,ICC Men's T20 World Cup Sub Regional Europe Qualifier B | Nordic T20 Cup | Women's T20I Quadrangular Series (in Denmark)
18,19,St Saviour,"Grainville, St Saviour",14,CWC Challenge League | Guernsey Women tour of Jersey | Inter-Insular T20 Series | Inter-Insular Women's Twenty20 Series
19,20,Blantyre,"TCA Oval, Blantyre",14,Quadrangular Twenty20 Series (Malawi) | Rwanda tour of Malawi
20,21,Morrisville,"Church Street Park, Morrisville",14,Major League Cricket
21,22,Chesterfield,"Queen's Park, Chesterfield",13,County Championship | ECB Women's One-Day Cup | Rachael Heyhoe Flint Trophy | Vitality Blast | Vitality Blast Men
22,23,Malkerns,Malkerns Country Club oval,13,Eswatini T20 Tri-Series | Mozambique tour of Eswatini
23,24,Port Soif,"Guernsey Rovers Athletic Club Ground, Port Soif",13,ICC Men's T20 World Cup Sub Regional Europe Qualifier Group C | Jersey tour of Guernsey
24,25,Corfu,"Marina Ground, Corfu",13,Bulgaria Women tour of Greece | Denmark Women tour of Greece | Germany Women tour of Greece | Spain Women tour of Greece
25,26,Tallinn,Estonian National Cricket and Rugby Field,12,Bulgaria Women tour of Estonia | Czech Republic Women tour of Estonia | Finland Women tour of Estonia | Finland tour of Estonia | Switzerland tour of Estonia
26,27,Radlett,"Radlett Cricket Club, Radlett",12,One-Day Cup | Rachael Heyhoe Flint Trophy | Vitality Blast
27,28,Moratuwa,"De Zoysa Stadium, Moratuwa",12,Major Clubs Limited Over Tournament | Major League Tournament
28,29,Los Angeles,"Woodley Cricket Field, Los Angeles",12,ICC Women's T20 World Cup Americas Region Qualifier
29,30,Dundee,"Forthill, Dundee",12,ICC Men's Cricket World Cup League 2

In [80]:
# Phase 04.5.16 — Prepare Hyderabad Cricket Context Dataset

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "cricket_context_host_classified_v5_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "hyderabad_cricket_context_2023_2026.csv"
SUMMARY_FILE = DATA_DIR / "hyderabad_cricket_context_summary_2023_2026.csv"

START_DATE = "2023-01-01"
END_DATE = "2026-07-31"

matches = pd.read_csv(INPUT_FILE)
matches["match_date"] = pd.to_datetime(
    matches["match_date"], errors="coerce"
)

# Restrict to the project's research period.
matches = matches.loc[
    matches["match_date"].between(START_DATE, END_DATE)
].copy()

# Identify Hyderabad using the city and venue fields.
city = matches["city"].fillna("").str.strip().str.casefold()
venue = matches["venue"].fillna("").str.strip().str.casefold()

hyderabad_mask = (
    city.str.contains("hyderabad", regex=False)
    | venue.str.contains("hyderabad", regex=False)
)

hyderabad = matches.loc[hyderabad_mask].copy()

# Mark these records as requiring final venue/country verification.
hyderabad["hyderabad_location_match"] = True
hyderabad["host_country_verification"] = "pending"

# Save the match-level dataset.
hyderabad.to_csv(OUTPUT_FILE, index=False)

# Summarize matches by event and format.
summary = (
    hyderabad.groupby(["event", "match_type"], dropna=False)
    .size()
    .reset_index(name="match_count")
    .sort_values("match_count", ascending=False)
)

summary.to_csv(SUMMARY_FILE, index=False)

print("Phase 04.5.16 completed.")
print("Research period:", START_DATE, "to", END_DATE)
print("Hyderabad candidate matches:", len(hyderabad))
print("Unique venues:", hyderabad["venue"].nunique())
print("Output dataset:", OUTPUT_FILE)
print("Summary file:", SUMMARY_FILE)

display(summary)
display(
    hyderabad[
        ["match_date", "teams", "match_type", "event", "venue", "city"]
    ].head(15)
)

Phase 04.5.16 completed.
Research period: 2023-01-01 to 2026-07-31
Hyderabad candidate matches: 32
Unique venues: 1
Output dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_context_2023_2026.csv
Summary file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_context_summary_2023_2026.csv

                       event match_type  match_count
3      Indian Premier League        T20           26
2      ICC Cricket World Cup        ODI            3
0   Bangladesh tour of India        T20            1
1      England tour of India       Test            1
4  New Zealand tour of India        ODI            1

     match_date                                              teams match_type                      event                                                 venue       city
94   2023-01-18                                India | New Zealand        ODI  New Zealand tour of India  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
438  2023-04-02             Rajasthan Royals | Sunrisers Hyderabad        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
475  2023-04-09                 Punjab Kings | Sunrisers Hyderabad        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
511  2023-04-18               Mumbai Indians | Sunrisers Hyderabad        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
537  2023-04-24               Delhi Capitals | Sunrisers Hyderabad        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
589  2023-05-04        Kolkata Knight Riders | Sunrisers Hyderabad        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
633  2023-05-13         Sunrisers Hyderabad | Lucknow Super Giants        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
651  2023-05-18  Sunrisers Hyderabad | Royal Challengers Bangalore        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
1626 2023-10-06                             Pakistan | Netherlands        ODI      ICC Cricket World Cup  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
1640 2023-10-09                          New Zealand | Netherlands        ODI      ICC Cricket World Cup  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
1644 2023-10-10                               Sri Lanka | Pakistan        ODI      ICC Cricket World Cup  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
2124 2024-01-25                                    England | India       Test      England tour of India  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
2492 2024-03-27               Sunrisers Hyderabad | Mumbai Indians        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
2526 2024-04-05          Chennai Super Kings | Sunrisers Hyderabad        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad
2646 2024-04-25  Royal Challengers Bengaluru | Sunrisers Hyderabad        T20      Indian Premier League  Rajiv Gandhi International Stadium, Uppal, Hyderabad  Hyderabad

In [81]:
# Phase 04.5.17 — Hyderabad Cricket Dataset Quality Check

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "hyderabad_cricket_context_2023_2026.csv"
REPORT_FILE = DATA_DIR / "hyderabad_cricket_quality_report_2023_2026.csv"
DUPLICATES_FILE = DATA_DIR / "hyderabad_cricket_duplicate_review_2023_2026.csv"

df = pd.read_csv(INPUT_FILE)
df["match_date"] = pd.to_datetime(df["match_date"], errors="coerce")

required_columns = ["match_date", "teams", "match_type", "event", "venue", "city"]

report_rows = [
    {"check": "Total records", "result": len(df)},
    {"check": "Missing match dates", "result": int(df["match_date"].isna().sum())},
    {"check": "Missing teams", "result": int(df["teams"].isna().sum())},
    {"check": "Missing match type", "result": int(df["match_type"].isna().sum())},
    {"check": "Missing event", "result": int(df["event"].isna().sum())},
    {"check": "Missing venue", "result": int(df["venue"].isna().sum())},
    {"check": "Missing city", "result": int(df["city"].isna().sum())},
    {"check": "Unique venues", "result": int(df["venue"].nunique())},
    {"check": "First match date", "result": df["match_date"].min()},
    {"check": "Last match date", "result": df["match_date"].max()},
]

# Use available match identifiers for duplicate review.
if "match_id" in df.columns:
    duplicate_mask = df.duplicated(subset=["match_id"], keep=False)
else:
    duplicate_mask = df.duplicated(
        subset=["match_date", "teams", "match_type", "venue"],
        keep=False
    )

duplicates = df.loc[duplicate_mask].sort_values("match_date")

report_rows.append({
    "check": "Records involved in potential duplicates",
    "result": len(duplicates)
})

report = pd.DataFrame(report_rows)
report.to_csv(REPORT_FILE, index=False)
duplicates.to_csv(DUPLICATES_FILE, index=False)

print("Phase 04.5.17 completed.")
print("Quality report:", REPORT_FILE)
print("Duplicate review:", DUPLICATES_FILE)

display(report)
display(duplicates.head(10))

Phase 04.5.17 completed.
Quality report: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_quality_report_2023_2026.csv
Duplicate review: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_duplicate_review_2023_2026.csv

                                       check               result
0                              Total records                   32
1                        Missing match dates                    0
2                              Missing teams                    0
3                         Missing match type                    0
4                              Missing event                    0
5                              Missing venue                    0
6                               Missing city                    0
7                              Unique venues                    1
8                           First match date  2023-01-18 00:00:00
9                            Last match date  2026-05-22 00:00:00
10  Records involved in potential duplicates                    0

Empty DataFrame
Columns: [match_id, match_date, match_year, match_month, match_day_of_week, teams, match_type, team_type, gender, event, venue, city, india_involved, is_india_hosted, host_country, is_world_cup, is_ipl, is_wpl, is_hyderabad_match, host_country_status, source_archive, source_file, host_country_method, india_team_abroad_candidate, hyderabad_location_match, host_country_verification]
Index: []

[0 rows x 26 columns]

In [82]:
# Phase 04.5.18 — Prepare Cricket Events for Demand Forecasting

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"

INPUT_FILE = DATA_DIR / "hyderabad_cricket_context_2023_2026.csv"
OUTPUT_FILE = DATA_DIR / "hyderabad_cricket_forecasting_features_2023_2026.csv"
SUMMARY_FILE = DATA_DIR / "hyderabad_cricket_forecasting_summary_2023_2026.csv"

df = pd.read_csv(INPUT_FILE)
df["match_date"] = pd.to_datetime(df["match_date"], errors="coerce")

# Retain the existing match fields and add calendar features.
df["match_year"] = df["match_date"].dt.year
df["match_month"] = df["match_date"].dt.month
df["match_day"] = df["match_date"].dt.day
df["day_of_week"] = df["match_date"].dt.dayofweek
df["is_weekend"] = df["day_of_week"].isin([5, 6])

# Create event-category features from the available source fields.
event_text = df["event"].fillna("").str.lower()
df["is_ipl"] = event_text.str.contains("indian premier league", regex=False)
df["is_world_cup"] = event_text.str.contains("world cup", regex=False)
df["is_international_series"] = (
    ~df["is_ipl"] & ~df["is_world_cup"]
)

# Match-day flag for later hourly demand feature engineering.
df["is_cricket_event_day"] = 1

df = df.sort_values("match_date").reset_index(drop=True)
df.to_csv(OUTPUT_FILE, index=False)

summary = (
    df.groupby(["match_year", "event", "match_type"], dropna=False)
      .size()
      .reset_index(name="match_count")
      .sort_values(["match_year", "match_count"], ascending=[True, False])
)
summary.to_csv(SUMMARY_FILE, index=False)

print("Phase 04.5.18 completed.")
print("Records:", len(df))
print("Date range:", df["match_date"].min(), "to", df["match_date"].max())
print("Forecasting dataset:", OUTPUT_FILE)
print("Event summary:", SUMMARY_FILE)

display(summary)
display(df.head(10))

Phase 04.5.18 completed.
Records: 32
Date range: 2023-01-18 00:00:00 to 2026-05-22 00:00:00
Forecasting dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_forecasting_features_2023_2026.csv
Event summary: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_forecasting_summary_2023_2026.csv

   match_year                      event match_type  match_count
1        2023      Indian Premier League        T20            7
0        2023      ICC Cricket World Cup        ODI            3
2        2023  New Zealand tour of India        ODI            1
5        2024      Indian Premier League        T20            6
3        2024   Bangladesh tour of India        T20            1
4        2024      England tour of India       Test            1
6        2025      Indian Premier League        T20            6
7        2026      Indian Premier League        T20            7

,match_id,match_date,match_year,match_month,match_day_of_week,teams,match_type,team_type,gender,event,...,source_file,host_country_method,india_team_abroad_candidate,hyderabad_location_match,host_country_verification,match_day,day_of_week,is_weekend,is_international_series,is_cricket_event_day
0,1348646,2023-01-18,2023,1,Wednesday,India | New Zealand,ODI,international,male,New Zealand tour of India,...,1348646_info.csv,preliminary_city_mapping,False,True,pending,18,2,False,True,1
1,1359478,2023-04-02,2023,4,Sunday,Rajasthan Royals | Sunrisers Hyderabad,T20,club,male,Indian Premier League,...,1359478_info.csv,preliminary_city_mapping,False,True,pending,2,6,True,False,1
2,1359488,2023-04-09,2023,4,Sunday,Punjab Kings | Sunrisers Hyderabad,T20,club,male,Indian Premier League,...,1359488_info.csv,preliminary_city_mapping,False,True,pending,9,6,True,False,1
3,1359499,2023-04-18,2023,4,Tuesday,Mumbai Indians | Sunrisers Hyderabad,T20,club,male,Indian Premier League,...,1359499_info.csv,preliminary_city_mapping,False,True,pending,18,1,False,False,1
4,1359508,2023-04-24,2023,4,Monday,Delhi Capitals | Sunrisers Hyderabad,T20,club,male,Indian Premier League,...,1359508_info.csv,preliminary_city_mapping,False,True,pending,24,0,False,False,1
5,1359521,2023-05-04,2023,5,Thursday,Kolkata Knight Riders | Sunrisers Hyderabad,T20,club,male,Indian Premier League,...,1359521_info.csv,preliminary_city_mapping,False,True,pending,4,3,False,False,1
6,1359532,2023-05-13,2023,5,Saturday,Sunrisers Hyderabad | Lucknow Super Giants,T20,club,male,Indian Premier League,...,1359532_info.csv,preliminary_city_mapping,False,True,pending,13,5,True,False,1
7,1359539,2023-05-18,2023,5,Thursday,Sunrisers Hyderabad | Royal Challengers Bangalore,T20,club,male,Indian Premier League,...,1359539_info.csv,preliminary_city_mapping,False,True,pending,18,3,False,False,1
8,1384393,2023-10-06,2023,10,Friday,Pakistan | Netherlands,ODI,international,male,ICC Cricket World Cup,...,1384393_info.csv,preliminary_city_mapping,False,True,pending,6,4,False,False,1
9,1384397,2023-10-09,2023,10,Monday,New Zealand | Netherlands,ODI,international,male,ICC Cricket World Cup,...,1384397_info.csv,preliminary_city_mapping,False,True,pending,9,0,False,False,1

In [83]:
# Phase 04.5.19 — Final Cricket Dataset Validation

from pathlib import Path
import pandas as pd

# Locate the project root from the notebook's working directory
cwd = Path.cwd()
PROJECT_ROOT = next(
    (p for p in [cwd, *cwd.parents]
     if (p / "data" / "processed" / "cricket").is_dir()),
    None
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Cannot locate the project data folder. "
        "Run this notebook from inside your project directory."
    )

BASE_DIR = PROJECT_ROOT / "data" / "processed" / "cricket"
INPUT_FILE = BASE_DIR / "hyderabad_cricket_forecasting_features_2023_2026.csv"
REPORT_FILE = BASE_DIR / "hyderabad_cricket_final_quality_report_2023_2026.csv"

if not INPUT_FILE.exists():
    raise FileNotFoundError(
        f"Expected dataset not found: {INPUT_FILE}\n"
        "Check the actual filename in data/processed/cricket."
    )

df = pd.read_csv(INPUT_FILE)

required_columns = ["match_date", "teams", "match_type", "event", "venue", "city"]
missing_columns = [c for c in required_columns if c not in df.columns]

if missing_columns:
    raise ValueError(f"Required columns missing: {missing_columns}")

dates = pd.to_datetime(df["match_date"], errors="coerce")
start_date = pd.Timestamp("2023-01-01")
end_date = pd.Timestamp("2026-07-31")

checks = [
    ("Total records", len(df)),
    ("Missing match dates", int(dates.isna().sum())),
    ("Dates before research period", int((dates < start_date).sum())),
    ("Dates after research period", int((dates > end_date).sum())),
    ("Duplicate rows", int(df.duplicated().sum())),
    ("Missing teams", int(df["teams"].isna().sum())),
    ("Missing match types", int(df["match_type"].isna().sum())),
    ("Missing event names", int(df["event"].isna().sum())),
    ("Missing venues", int(df["venue"].isna().sum())),
    ("Missing cities", int(df["city"].isna().sum())),
    ("Unique venues", int(df["venue"].nunique())),
    ("Unique events", int(df["event"].nunique())),
]

report = pd.DataFrame(checks, columns=["check", "result"])
report.to_csv(REPORT_FILE, index=False)

print("Phase 04.5.19 — Final validation completed")
print("Dataset:", INPUT_FILE)
print("Quality report:", REPORT_FILE)
print("Valid date range:", dates.min(), "to", dates.max())
display(report)

Phase 04.5.19 — Final validation completed
Dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_forecasting_features_2023_2026.csv
Quality report: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\processed\cricket\hyderabad_cricket_final_quality_report_2023_2026.csv
Valid date range: 2023-01-18 00:00:00 to 2026-05-22 00:00:00

                           check  result
0                  Total records      32
1            Missing match dates       0
2   Dates before research period       0
3    Dates after research period       0
4                 Duplicate rows       0
5                  Missing teams       0
6            Missing match types       0
7            Missing event names       0
8                 Missing venues       0
9                 Missing cities       0
10                 Unique venues       1
11                 Unique events       5

# Phase 04.5 — Cricket Context Data Collection and Preparation

## 1. Overview

Phase 04.5 focuses on collecting, classifying, and preparing cricket-match contextual data for the research project:

**Project Title:** *Hyperlocal Food Demand and Surge Forecasting in Indian Food Delivery: A Comparative Evaluation of Statistical, Machine Learning, Deep Learning, and Time-Series Foundation Models*

Cricket matches are included as an external contextual variable because major sporting events may influence food-delivery demand in nearby geographic zones and during relevant time periods.

The research period is **1 January 2023 to 31 July 2026**, with particular attention to matches hosted in Hyderabad and Indian national-team matches played both within India and abroad.

## 2. Data Source

**Source:** Cricsheet

Website: https://cricsheet.org/

Cricsheet provides downloadable cricket match datasets, including match metadata and ball-by-ball information for supported competitions and formats.

### Archives examined

* `all_csv2.zip` — broad collection of supported cricket matches.
* `ipl_csv2.zip` — IPL-specific match collection.

The files were inspected, and their match metadata was extracted for analysis.

**Coverage limitation:** Cricsheet does not necessarily contain every cricket match played worldwide. The resulting dataset must not be described as a complete record of every match.

## 3. Processing Activities

### 3.1 Match Metadata Extraction

Match-level metadata was extracted from the downloaded archives.

The resulting metadata included fields such as:

* Match ID
* Match date
* Teams
* Match format
* Team type
* Gender
* Tournament or event
* Venue
* City
* Source archive
* Source file

The extracted records were restricted to the research period of 1 January 2023 through 31 July 2026.

### 3.2 Match Classification

The records were classified to identify relevant categories, including:

* Indian national-team matches
* World Cup event matches
* Indian Premier League (IPL) matches
* Women's Premier League (WPL) matches
* Matches involving India
* Matches preliminarily mapped to India or outside India
* Matches associated with Hyderabad

The classification was used to support subsequent filtering and contextual analysis.

### 3.3 Venue and Host-Country Review

Venue and city information was reviewed to identify matches potentially hosted in India and to flag records requiring additional location verification.

Several iterations of location mapping were performed, and unresolved city/venue combinations were retained for review.

**Important:** Host-country classification remains provisional. It has not been established that every match has a verified host country.

### 3.4 Hyderabad Match Subset

A Hyderabad-specific dataset was created using the available venue and city metadata.

The dataset contains records associated with the Rajiv Gandhi International Stadium in Hyderabad.

The records cover the following event categories:

| Event                     | Match type | Records |
| ------------------------- | ---------- | ------: |
| Indian Premier League     | T20        |      26 |
| ICC Cricket World Cup     | ODI        |       3 |
| Bangladesh tour of India  | T20        |       1 |
| England tour of India     | Test       |       1 |
| New Zealand tour of India | ODI        |       1 |
| **Total**                 |            |  **32** |

These 32 records represent the Hyderabad matches identified in the current extracted dataset, not necessarily every match held in Hyderabad during the research period.

### 3.5 Forecasting Feature Preparation

A Hyderabad cricket-context dataset was prepared for subsequent use in the forecasting workflow.

The prepared dataset preserves match dates, participating teams, match type, event, venue, and city information, together with the available contextual features.

Cricket-context features can later be aligned with hourly food-order observations to investigate whether match periods coincide with changes in food demand.

No claim is made at this stage that cricket events cause demand increases.

## 4. Final Dataset and Quality Report

### Primary output

`data/processed/cricket/hyderabad_cricket_forecasting_features_2023_2026.csv`

Contains the prepared Hyderabad cricket-context records.

### Summary output

`data/processed/cricket/hyderabad_cricket_forecasting_summary_2023_2026.csv`

Contains a summary of identified matches by event and match type.

### Quality report

`data/processed/cricket/hyderabad_cricket_final_quality_report_2023_2026.csv`

Contains the final validation results for the Hyderabad dataset.

## 5. Final Quality Validation

The final quality-check cell completed successfully.

| Validation check                 | Result |
| -------------------------------- | -----: |
| Total records                    |     32 |
| Missing match dates              |      0 |
| Dates before the research period |      0 |
| Dates after the research period  |      0 |
| Duplicate rows                   |      0 |
| Missing teams                    |      0 |
| Missing match types              |      0 |
| Missing event names              |      0 |
| Missing venues                   |      0 |
| Missing cities                   |      0 |
| Unique venues                    |      1 |
| Unique events                    |      5 |

**Observed match-date range:** 18 January 2023 to 22 May 2026.

The quality checks establish that the current 32-row dataset has no missing values in the checked fields, no exact duplicate rows, and no dates outside the specified research period.

They do not establish complete match coverage or independently verify the host country of every record.

## 6. Pending Work

The following activities are intentionally deferred until all contextual datasets have been collected:

1. Complete host-country verification.
2. Review unresolved venue and city mappings.
3. Verify relevant match records against authoritative sources where necessary.
4. Integrate cricket data with weather, holiday, and food-demand datasets.
5. Construct the final time-aligned forecasting features.

These activities are outside the completed portion of Phase 04.5.

## 7. Phase Status

**Phase 04.5 — Cricket Context Data Collection and Preparation: Complete for the current stage.**

The Cricsheet archives were inspected, match metadata was extracted and classified, a Hyderabad-specific contextual dataset was prepared, and final quality checks were completed.

Host-country verification and integration with the other contextual datasets remain pending by design.

The cricket dataset will be incorporated into the broader forecasting dataset after the remaining contextual data has been collected and verified.

# PHASE 04.6: OTHER SPORTING EVENTS COLLECTION

## 1. Objective

Collect reliable historical records of sporting events held in Hyderabad and Secunderabad that may influence hourly food-order demand.

The dataset will supplement the existing cricket/IPL contextual dataset.

## 2. Study Period and Geography

* **Start date:** 2023-01-01
* **End date:** 2026-07-31
* **Primary locations:** Hyderabad and Secunderabad, Telangana, India.
* **Time zone:** Asia/Kolkata (IST).

Include events only when their dates and locations fall within the study scope.

## 3. Sports to Cover

Prioritize the following categories:

1. Pro Kabaddi League (PKL)
2. Football tournaments and matches
3. Hockey tournaments and matches
4. Tennis tournaments
5. Badminton tournaments
6. Athletics and marathons
7. Shooting championships
8. Basketball and volleyball
9. Wrestling, boxing, and other indoor sports
10. State-level and national multisport competitions

Include other sports when reliable records establish that relevant events occurred in the study area.

## 4. Data Sources

Prioritize sources in this order:

1. Official league and tournament websites.
2. Official sports federation websites.
3. Sports Authority of Telangana and relevant government sources.
4. Official stadium or event-organizer announcements.
5. Reputable sports news sources when official historical records are unavailable.

Record the source URL for each event. Do not invent event dates, venues, or start times.

## 5. Required Dataset Columns

| Column             | Description                                     |
| ------------------ | ----------------------------------------------- |
| `event_date`       | Actual event date in YYYY-MM-DD format          |
| `event_name`       | Official event or tournament name               |
| `sport`            | Sport category                                  |
| `event_start_time` | Local start time in HH:MM format, when verified |
| `venue`            | Stadium or event venue                          |
| `city`             | Hyderabad or Secunderabad                       |
| `event_level`      | Local, state, national, or international        |
| `source_url`       | Source supporting the event record              |

Use a consistent missing-value representation for unavailable start times. Do not infer a time from the tournament's general schedule.

## 6. Collection Rules

* Collect individual match or competition dates whenever reliable schedules are available.
* Expand multi-day events into individual daily records only when the event is documented for those dates.
* Preserve the official event name and venue.
* Exclude events outside the study period or geography.
* Avoid duplicating cricket records already covered by the existing cricket dataset.
* Do not treat a tournament's overall duration as proof that matches occurred every day.
* Retain source references for verification.

## 7. Output and File Management

Save the consolidated dataset in the existing project-level data directory:

`data/raw/sporting_events/hyderabad_other_sporting_events_2023_2026.csv`

Create the directory only if it does not already exist.

If the final dataset already exists, inspect and reuse it rather than generating another copy. Do not create timestamped filenames or duplicate metadata files.

## 8. Validation Before Completion

Verify:

* All event dates fall within 2023-01-01 and 2026-07-31.
* Event names, sports, dates, and locations are recorded where supported.
* Duplicate event records are reviewed.
* Source URLs are retained.
* Missing start times are documented rather than guessed.
* Cricket records are not unnecessarily duplicated.
* Historical coverage limitations are documented.

## 9. Completion Criteria

Phase 04.6 is complete when the relevant sporting-event records have been collected, source references retained, duplicate records reviewed, and the resulting dataset validated.

The dataset must be suitable for later integration with the hourly food-demand data.

**Important:** Do not integrate the sporting-event dataset yet. Integration will take place only after the required contextual datasets have been collected and validated.

# PHASE 04.6: OTHER SPORTING EVENTS COLLECTION

**Study period:** January 1, 2023 – July 31, 2026
**Study area:** Hyderabad and Secunderabad, Telangana, India
**Objective:** Collect historical sporting-event data that may help explain variations in hourly food-order demand.

## Planning Steps

| Step       | Task                         | Required Work                                                                                    | Status    |
| ---------- | ---------------------------- | ------------------------------------------------------------------------------------------------ | --------- |
| **04.6.1** | Identify relevant sports     | Finalize the sports and competitions to include, excluding cricket already collected.            | ⏳ Pending |
| **04.6.2** | Identify reliable sources    | Locate official league, federation, tournament, and government schedules.                        | ⏳ Pending |
| **04.6.3** | Collect historical schedules | Gather event dates, match dates, start times, teams or participants, and venues where available. | ⏳ Pending |
| **04.6.4** | Consolidate event records    | Standardize records into one dataset and avoid duplicate events.                                 | ⏳ Pending |
| **04.6.5** | Validate the dataset         | Check date range, location, missing fields, duplicates, and source references.                   | ⏳ Pending |
| **04.6.6** | Save final dataset           | Save the validated CSV in the existing project-level data directory.                             | ⏳ Pending |
| **04.6.7** | Document completion          | Record the output path, coverage, limitations, and validation results.                           | ⏳ Pending |

## Sports to Cover

1. Pro Kabaddi League (PKL)
2. Football
3. Hockey
4. Tennis
5. Badminton
6. Athletics and marathons
7. Shooting
8. Basketball and volleyball
9. Wrestling and boxing
10. Other verified major sporting competitions held in the study area

Include only events supported by reliable historical records.

## Required Dataset Columns

| Column                 | Description                               |
| ---------------------- | ----------------------------------------- |
| `event_date`           | Event or match date                       |
| `event_name`           | Official event name                       |
| `sport`                | Sport category                            |
| `event_start_time`     | Verified local start time, when available |
| `team_or_participants` | Teams or participants, when available     |
| `venue`                | Stadium or event venue                    |
| `city`                 | Hyderabad or Secunderabad                 |
| `event_level`          | Local, state, national, or international  |
| `source_url`           | Supporting source                         |

## File Management Rules

* **Date range:** 2023-01-01 to 2026-07-31.
* Reuse the existing project-level `data` directory.
* Do not create duplicate folders or timestamped copies.
* Do not recollect cricket data already completed.
* Do not invent dates, match schedules, or start times.
* Preserve source URLs.
* Do not integrate this dataset with food-demand data during collection.

**Expected output:**

`data/raw/sporting_events/hyderabad_other_sporting_events_2023_2026.csv`

Create the output directory only if it does not already exist. Reuse an existing final dataset rather than overwriting it blindly.

# PHASE 04.6.1: IDENTIFY RELEVANT SPORTS

## 1. Objective

Identify sporting events in Hyderabad and Secunderabad that may influence hourly food-order demand during the study period.

* **Start date:** January 1, 2023
* **End date:** July 31, 2026
* **Geographic scope:** Hyderabad and Secunderabad, Telangana, India
* **Time zone:** Indian Standard Time (IST)

## 2. Finalized Sports Categories

| No. | Sport / Category         | Events to Include                                                        | Priority    |
| --: | ------------------------ | ------------------------------------------------------------------------ | ----------- |
|   1 | Pro Kabaddi League (PKL) | Hyderabad-hosted league matches and playoffs                             | Very High   |
|   2 | Football                 | International matches, national tournaments, and major competitions      | High        |
|   3 | Hockey                   | National championships and major tournaments                             | High        |
|   4 | Tennis                   | Professional and national-level tournaments                              | High        |
|   5 | Badminton                | National championships and major tournaments                             | High        |
|   6 | Athletics and Marathons  | Hyderabad Marathon and major athletics competitions                      | High        |
|   7 | Shooting                 | National and regional championships                                      | Medium      |
|   8 | Basketball               | National and major regional competitions                                 | Medium      |
|   9 | Volleyball               | National and major regional competitions                                 | Medium      |
|  10 | Wrestling and Boxing     | Major championships and tournaments                                      | Medium      |
|  11 | Multisport Competitions  | Telangana state competitions and national sporting events hosted locally | High        |
|  12 | Other Major Sports       | Other verified events with potential local demand impact                 | Conditional |

## 3. Inclusion Rules

Include an event only when:

1. Its date falls between January 1, 2023, and July 31, 2026.
2. Its venue is in Hyderabad or Secunderabad.
3. Its occurrence and date can be supported by a reliable source.
4. It is a documented sporting event, not merely a sports facility or an unconfirmed announcement.
5. It is not a duplicate of an existing record.

For multi-day competitions, collect individual match or competition dates when reliable schedules are available.

## 4. Exclusions

* Cricket and IPL records already collected in the existing cricket dataset.
* Sporting events held outside Hyderabad and Secunderabad.
* Events outside the study period.
* Unverified events without reliable historical evidence.
* Routine sports activities without a documented event schedule.

## 5. Expected Outcome

A finalized list of relevant sports categories for the subsequent source identification and historical data collection steps.

**No dataset is created in this step.**

# PHASE 04.6.2: IDENTIFY RELIABLE SOURCES

## Objective

Identify reliable sources for historical sporting events held in Hyderabad and Secunderabad between January 1, 2023, and July 31, 2026.

## Source Register

| No. | Sport / Category                  | Primary Source                                                                                                            | Information to Collect                  |
| --: | --------------------------------- | ------------------------------------------------------------------------------------------------------------------------- | --------------------------------------- |
|   1 | Pro Kabaddi League                | [Official PKL website](https://www.prokabaddi.com/)                                                                       | Match dates, teams, start times, venue  |
|   2 | Football                          | [All India Football Federation](https://www.the-aiff.com/)                                                                | Match dates, teams, competitions, venue |
|   3 | Hockey                            | [Hockey Telangana](https://www.telanganahockey.org/national-events.php) and [Hockey India](https://www.hockeyindia.org/)  | Tournament dates, category, venue       |
|   4 | Tennis                            | [All India Tennis Association](https://www.aitatennis.com/)                                                               | Tournament dates, competition, venue    |
|   5 | Badminton                         | [Badminton Association of India](https://www.badmintonindia.org/)                                                         | Tournament dates, competition, venue    |
|   6 | Athletics and marathons           | [Hyderabad Marathon](https://www.marathonhyderabad.com/) and [Athletics Federation of India](https://indianathletics.in/) | Event dates, start times, location      |
|   7 | Shooting                          | [National Rifle Association of India](https://www.thenrai.in/)                                                            | Championship dates, competition, venue  |
|   8 | Basketball and volleyball         | Relevant national federations and official tournament organizers                                                          | Match dates, teams, venue               |
|   9 | Wrestling and boxing              | [Sports Authority of Telangana](https://satg.telangana.gov.in/) and relevant national federations                         | Competition dates, categories, venue    |
|  10 | State and multisport competitions | [Sports Authority of Telangana](https://satg.telangana.gov.in/)                                                           | Event dates, sport, venue               |

## Source Selection Rules

1. Prefer official league, federation, government, and organizer records.
2. Use reputable news reports only when primary historical schedules are unavailable.
3. Record the source URL for each collected event.
4. Verify the actual event date and venue before inclusion.
5. Treat stadium directories as venue references, not proof that an event occurred.
6. Exclude events outside the study period or geography.
7. Do not repeat cricket/IPL collection.

## Completion Criteria

Step 04.6.2 is complete when the primary source register is established and the relevant official schedule pages have been identified.

**Output:** Source register documented in this Markdown section. No dataset or additional file is required.

# PHASE 04.6.3: COLLECT HISTORICAL SPORTING SCHEDULES

## 1. Objective

Collect documented sporting events held in Hyderabad and Secunderabad between **January 1, 2023, and July 31, 2026**, excluding cricket/IPL already collected.

## 2. Confirmed Starting Records

| Event                                             | Date / period      | Venue / location            | Source                        |
| ------------------------------------------------- | ------------------ | --------------------------- | ----------------------------- |
| Pro Kabaddi League Season 10 — Hyderabad leg      | Jan 19–24, 2024    | Hyderabad                   | Official PKL schedule         |
| Pro Kabaddi League Season 10 — playoffs and final | Feb 26–Mar 1, 2024 | Gachibowli Indoor Stadium   | Official PKL announcement     |
| Pro Kabaddi League Season 11 — Hyderabad leg      | Oct 18–Nov 9, 2024 | GMC Balayogi Sports Complex | Official PKL schedule         |
| Hyderabad Marathon                                | Aug 26–27, 2023    | People's Plaza and HITEX    | Official event FAQ            |
| Gooncha Nehru Senior Hockey Tournament            | Jan 1–12, 2023     | Secunderabad                | Hockey Telangana              |
| Santosh Trophy final rounds                       | Dec 2024           | Hyderabad                   | All India Football Federation |

Sources: [PKL Season 10 schedule](https://www.prokabaddi.com/news/pro-kabaddi-season-10-schedule-release), [PKL Season 10 playoffs](https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad), [PKL Season 11 schedule](https://www.prokabaddi.com/news/pro-kabaddi-season-11-schedule-release), [Hyderabad Marathon](https://www.marathonhyderabad.com/frequently-asked-questions/), [Hockey Telangana](https://www.telanganahockey.org/national-events.php), [AIFF](https://www.the-aiff.com/index.php/article/hyderabad-to-host-santosh-trophy-in-december).

These are starting records. Tournament date ranges must not be treated as proof that matches occurred every day.

## 3. Collection Fields

Collect the following fields where reliable records provide them:

* `event_date`
* `event_name`
* `sport`
* `event_start_time`
* `team_or_participants`
* `venue`
* `city`
* `event_level`
* `source_url`

## 4. Collection Rules

1. Prefer official historical schedules and results.
2. Record individual match dates and times when available.
3. Keep all times in Indian Standard Time.
4. Include only events within the study dates and geographic scope.
5. Preserve the source URL for every record.
6. Do not invent missing dates, teams, venues, or times.
7. Do not duplicate existing cricket records.
8. Do not create another output file if the final dataset already exists.

## 5. Completion Criteria

Collection is complete when relevant event records have been gathered, source references retained, and unresolved historical coverage documented.

**Expected output:** `data/raw/sporting_events/hyderabad_other_sporting_events_2023_2026.csv`

In [84]:
# ============================================================
# PHASE 04.6.3: COLLECT SPORTING EVENT SOURCE PAGES
# ============================================================

from pathlib import Path
import requests
import pandas as pd

# 1. PROJECT PATHS
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SOURCE_DIR = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "sporting_events"
    / "source_pages"
)
SOURCE_DIR.mkdir(parents=True, exist_ok=True)

# 2. OFFICIAL SOURCE PAGES
SOURCES = {
    "hockey_tel angana": (
        "https://www.telanganahockey.org/national-events.php"
    ),
    "hockey_india": (
        "https://www.hockeyindia.org/"
    ),
    "pro_kabaddi": (
        "https://www.prokabaddi.com/"
    ),
}

# 3. DOWNLOAD PAGES ONLY WHEN MISSING
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0"
})

results = []

for source_name, url in SOURCES.items():

    filename = source_name.replace(" ", "_") + ".html"
    output_path = SOURCE_DIR / filename

    if output_path.exists():
        print(f"Reusing existing source page: {filename}")
        results.append({
            "source_name": source_name,
            "source_url": url,
            "local_file": str(output_path),
            "status": "reused"
        })
        continue

    try:
        response = session.get(url, timeout=30)
        response.raise_for_status()

        output_path.write_text(
            response.text,
            encoding="utf-8"
        )

        results.append({
            "source_name": source_name,
            "source_url": url,
            "local_file": str(output_path),
            "status": "downloaded"
        })

        print(f"Downloaded: {source_name}")

    except requests.RequestException as exc:
        results.append({
            "source_name": source_name,
            "source_url": url,
            "local_file": "",
            "status": f"failed: {exc}"
        })

        print(f"Could not download {source_name}: {exc}")

# 4. REPORT RESULTS
source_report = pd.DataFrame(results)

print("\nSOURCE COLLECTION REPORT")
display(source_report)

print("Source directory:", SOURCE_DIR)
print("Successful sources:", int(
    source_report["status"].isin(["downloaded", "reused"]).sum()
))

Reusing existing source page: hockey_tel_angana.html
Reusing existing source page: hockey_india.html
Reusing existing source page: pro_kabaddi.html

SOURCE COLLECTION REPORT

,source_name,source_url,local_file,status
0,hockey_tel angana,https://www.telanganahockey.org/national-events.php,d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\source_pages\hockey_tel_angana.html,reused
1,hockey_india,https://www.hockeyindia.org/,d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\source_pages\hockey_india.html,reused
2,pro_kabaddi,https://www.prokabaddi.com/,d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\source_pages\pro_kabaddi.html,reused

Source directory: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\source_pages
Successful sources: 3

In [85]:
# ============================================================
# PHASE 04.6.3: INSPECT DOWNLOADED SPORTING SOURCE PAGES
# ============================================================

from pathlib import Path
from bs4 import BeautifulSoup
import pandas as pd
import re

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SOURCE_DIR = (
    PROJECT_ROOT / "data" / "raw"
    / "sporting_events" / "source_pages"
)

KEYWORDS = [
    "hyderabad", "secunderabad", "schedule",
    "fixture", "match", "tournament", "2023",
    "2024", "2025", "2026"
]

if not SOURCE_DIR.exists():
    raise FileNotFoundError(f"Source folder not found: {SOURCE_DIR}")

html_files = sorted(SOURCE_DIR.glob("*.html"))

if not html_files:
    raise FileNotFoundError(f"No saved HTML pages found in: {SOURCE_DIR}")

results = []

for file_path in html_files:
    html = file_path.read_text(encoding="utf-8", errors="replace")
    soup = BeautifulSoup(html, "html.parser")

    # Remove navigation and scripts; retain page content
    for tag in soup(["script", "style", "nav", "footer", "header"]):
        tag.decompose()

    lines = [
        re.sub(r"\s+", " ", line).strip()
        for line in soup.get_text("\n").splitlines()
    ]
    lines = [line for line in lines if line]

    matches = [
        line for line in lines
        if any(keyword in line.lower() for keyword in KEYWORDS)
    ]

    for line in matches:
        results.append({
            "source_file": file_path.name,
            "page_text": line
        })

    print(f"{file_path.name}: {len(matches)} relevant text lines")

if not results:
    print("No relevant text found. These pages may require a dedicated schedule endpoint.")
else:
    source_text = pd.DataFrame(results)
    display(source_text.head(40))
    print("Relevant text lines found:", len(source_text))

hockey_india.html: 43 relevant text lines
hockey_tel_angana.html: 23 relevant text lines
pro_kabaddi.html: 35 relevant text lines

,source_file,page_text
0,hockey_india.html,JioStar named official broadcast partner for men’s Hero Asian Champions Trophy Punjab 2026
1,hockey_india.html,Hockey Haryana crowned champions of 16th Hockey India Senior Men National Championship 2026
2,hockey_india.html,‘We dared to dream big here’: Hero Asian Champions Trophy Punjab 2026 brings life full circle for Surjit Hockey Academy stalwarts
3,hockey_india.html,Hockey India announces free entry for spectators at men's Hero Asian Champions Trophy Punjab 2026
4,hockey_india.html,Inviting Applications from Eligible Sportspersons (Hockey Discipline) for Recognition as Sportspersons of Outstanding Merit (SOM). The applications are to be submitted in between 01 June 2026 and 31 July 2026.
5,hockey_india.html,"26 Oct, 2026"
6,hockey_india.html,JioStar named official broadcast partner for men’s Hero Asian Champions Trophy Punjab 2026
7,hockey_india.html,"26 Oct, 2026"
8,hockey_india.html,"21 Oct, 2026"
9,hockey_india.html,"Jhansi, 21 October 2026: Hockey Haryana came from behind to beat Hockey Madhya Pradesh 2-1 in the Division ‘A’ final and win the 16th Hockey India Senior Men National Champion..."
10,hockey_india.html,"21 Oct, 2026"
11,hockey_india.html,"20 Oct, 2026"
12,hockey_india.html,~ The ninth edition of the tournament will be played at Jalandhar and Mohali in Punjab from October 27 to November 5 ~
13,hockey_india.html,"New Delhi, 20 October 2026:&nbsp;Hockey India has announc..."
14,hockey_india.html,Matches
15,hockey_india.html,20th Asian Games Aichi Nagoya 2026 (Men)
16,hockey_india.html,"Saturday, 03 Oct 2026, 15:30 IST"
17,hockey_india.html,Match 40 (Gold Medal)
18,hockey_india.html,20th Asian Games Aichi Nagoya 2026 (Women)
19,hockey_india.html,"Friday, 02 Oct 2026, 15:30 IST"
20,hockey_india.html,Match 40 (Gold Medal)
21,hockey_india.html,20th Asian Games Aichi Nagoya 2026 (Men)
22,hockey_india.html,"Thursday, 01 Oct 2026, 13:00 IST"
23,hockey_india.html,Match 34 (Semi Final)
24,hockey_india.html,Hero Men’s Asian Champions Trophy 2026
25,hockey_india.html,"Tuesday, 27 Oct 2026, 19:20 IST"
26,hockey_india.html,Match 3
27,hockey_india.html,Hero Men’s Asian Champions Trophy 2026
28,hockey_india.html,"Thursday, 29 Oct 2026, 19:00 IST"
29,hockey_india.html,Match 6
30,hockey_india.html,Hero Men’s Asian Champions Trophy 2026
31,hockey_india.html,"Friday, 30 Oct 2026, 19:00 IST"
32,hockey_india.html,Match 9
33,hockey_india.html,MEN’S JUNIOR ASIA CUP MUSCAT 2024 – INDIA VS MALAYSIA 03 DEC 2024
34,hockey_india.html,MEN’S JUNIOR ASIA CUP MUSCAT 2024 – INDIA VS CHINESE TAIPEI 30 NOV 2024
35,hockey_india.html,MEN’S JUNIOR ASIA CUP MUSCAT 2024 – JAPAN VS INDIA 28 NOV 2024
36,hockey_india.html,MEN’S JUNIOR ASIA CUP MUSCAT 2024 - INDIA VS THAILAND 27 NOV 2024
37,hockey_india.html,"29 Jun, 2026"
38,hockey_india.html,India Vs England II FIH Hockey Men’s Pro League 2025/26 II Match Hig...
39,hockey_india.html,"29 Jun, 2026"

Relevant text lines found: 101

In [86]:
# PHASE 04.6.3 — FILTER HISTORICAL EVENT REFERENCES

import re
import pandas as pd

START_YEAR = 2023
END_YEAR = 2026

# Reuse source_text created by the previous cell
if "source_text" not in globals() or source_text.empty:
    raise ValueError("Run the source-page inspection cell first.")

pattern_year = re.compile(r"\b(?:2023|2024|2025|2026)\b")
pattern_location = re.compile(r"hyderabad|secunderabad|gachibowli", re.I)

historical_candidates = source_text[
    source_text["page_text"].str.contains(
        pattern_year, na=False
    )
    & source_text["page_text"].str.contains(
        pattern_location, na=False, regex=True
    )
].copy()

# Remove current/future dates beyond the study end where a full date is present
historical_candidates = historical_candidates.drop_duplicates()

print("Historical candidate lines:", len(historical_candidates))
display(historical_candidates.head(50))

Historical candidate lines: 0

Empty DataFrame
Columns: [source_file, page_text]
Index: []

In [87]:
# ============================================================
# PHASE 04.6.3: SAVE VERIFIED SPORTING EVENT RECORDS
# ============================================================

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

OUTPUT_DIR = PROJECT_ROOT / "data" / "raw" / "sporting_events"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_PATH = OUTPUT_DIR / "hyderabad_other_sporting_events_2023_2026.csv"

if OUTPUT_PATH.exists():
    events = pd.read_csv(OUTPUT_PATH)
    print("Existing sporting-event dataset reused.")
else:
    records = [
        {
            "event_date": "2023-01-01",
            "event_end_date": "2023-01-12",
            "event_name": "Gooncha 58th Nehru Senior Hockey Tournament (Men)",
            "sport": "Hockey",
            "event_start_time": None,
            "team_or_participants": None,
            "venue": "Secunderabad",
            "city": "Secunderabad",
            "event_level": "National",
            "source_url": "https://www.telanganahockey.org/national-events.php",
        },
        {
            "event_date": "2023-11-14",
            "event_end_date": "2023-11-25",
            "event_name": "Gooncha 59th Nehru Senior Hockey Tournament (Men)",
            "sport": "Hockey",
            "event_start_time": None,
            "team_or_participants": None,
            "venue": "Secunderabad",
            "city": "Secunderabad",
            "event_level": "National",
            "source_url": "https://www.telanganahockey.org/national-events.php",
        },
        {
            "event_date": "2024-02-26",
            "event_end_date": "2024-02-26",
            "event_name": "Pro Kabaddi League Season 10 — Eliminators",
            "sport": "Kabaddi",
            "event_start_time": None,
            "team_or_participants": None,
            "venue": "Gachibowli Indoor Stadium",
            "city": "Hyderabad",
            "event_level": "National",
            "source_url": "https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad",
        },
        {
            "event_date": "2024-02-28",
            "event_end_date": "2024-02-28",
            "event_name": "Pro Kabaddi League Season 10 — Semi-finals",
            "sport": "Kabaddi",
            "event_start_time": None,
            "team_or_participants": None,
            "venue": "Gachibowli Indoor Stadium",
            "city": "Hyderabad",
            "event_level": "National",
            "source_url": "https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad",
        },
        {
            "event_date": "2024-03-01",
            "event_end_date": "2024-03-01",
            "event_name": "Pro Kabaddi League Season 10 — Final",
            "sport": "Kabaddi",
            "event_start_time": None,
            "team_or_participants": None,
            "venue": "Gachibowli Indoor Stadium",
            "city": "Hyderabad",
            "event_level": "National",
            "source_url": "https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad",
        },
    ]

    events = pd.DataFrame(records)
    events["event_date"] = pd.to_datetime(events["event_date"])
    events["event_end_date"] = pd.to_datetime(events["event_end_date"])

    # Validate study period and required fields
    assert events["event_date"].between(
        "2023-01-01", "2026-07-31"
    ).all()
    assert events["event_name"].notna().all()
    assert events["sport"].notna().all()
    assert events["source_url"].notna().all()

    events.to_csv(OUTPUT_PATH, index=False)

    print("Verified starting records saved.")

print("Records:", len(events))
print("Output:", OUTPUT_PATH)
display(events)

Existing sporting-event dataset reused.
Records: 67
Output: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,event_level,source_url
0,2023-01-01,2023-01-12,Gooncha 58th Nehru Senior Hockey Tournament (Men),Hockey,NaN,NaN,Secunderabad,Secunderabad,National,https://www.telanganahockey.org/national-events.php
1,2023-11-14,2023-11-25,Gooncha 59th Nehru Senior Hockey Tournament (Men),Hockey,NaN,NaN,Secunderabad,Secunderabad,National,https://www.telanganahockey.org/national-events.php
2,2024-02-26,2024-02-26,Pro Kabaddi League Season 10 — Eliminators,Kabaddi,NaN,NaN,Gachibowli Indoor Stadium,Hyderabad,National,https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad
3,2024-02-28,2024-02-28,Pro Kabaddi League Season 10 — Semi-finals,Kabaddi,NaN,NaN,Gachibowli Indoor Stadium,Hyderabad,National,https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad
4,2024-03-01,2024-03-01,Pro Kabaddi League Season 10 — Final,Kabaddi,NaN,NaN,Gachibowli Indoor Stadium,Hyderabad,National,https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad
...,...,...,...,...,...,...,...,...,...,...
62,2025-01-19,2025-01-19,Veteran Telangana State Table Tennis Championships 2024,Table Tennis,NaN,Veteran table tennis players,"St. Paul's High School, Hyderguda",Hyderabad,State,https://www.telanganatabletennis.com/Veterans-Events.php
63,2025-10-15,2025-10-16,Osmania University Inter-College Table Tennis Tournament 2025,Table Tennis,NaN,University-affiliated college players,"St. Joseph's Degree and PG College, King Koti",Hyderabad,Inter-College,https://www.lords.ac.in/sports/events-attended/
64,2025-09-26,2025-09-29,17th HFI Mini Boys and Girls National Handball Championship,Handball,NaN,Mini boys and girls national teams,Nizam College,Hyderabad,National,https://handballfederationofindia.com/previous-events/
65,2024-11-02,2024-11-02,Osmania University Inter-College Karate Tournament 2024,Karate,NaN,University-affiliated college karate competitors,"Lords Institute of Engineering and Technology, Himayath Sagar",Hyderabad,Inter-College,https://www.lords.ac.in/sports/events-attended/
66,2025-09-22,2025-09-22,Osmania University National Archery Selection Trials 2025,Archery,NaN,University archery competitors,"Telangana Sports School, Hakimpet",Hyderabad,University Selection Trials,https://www.lords.ac.in/sports/events-attended/

In [88]:
from pathlib import Path
import pandas as pd

# Exact project path from your previous successful output
output_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

if not output_path.exists():
    raise FileNotFoundError(
        f"CSV not found at: {output_path}\n"
        "Check that the project folder is accessible."
    )

events = pd.read_csv(output_path)
print(f"Existing records loaded: {len(events)}")

# Additional event record
new_record = {
    "event_date": "2025-08-29",
    "event_end_date": "2025-08-29",
    "event_name": "National Sports Day Celebrations by Sports",
    "sport": "Multi-sport",
    "event_start_time": None,
    "team_or_participants": None,
    "venue": "Gachibowli Hockey Stadium",
    "city": "Hyderabad",
    "event_level": "State/Regional",
    "source_url": "https://www.telanganahockey.org/national-events.php"
}

# Avoid adding the same event twice
duplicate = (
    (events["event_name"] == new_record["event_name"]) &
    (events["event_date"].astype(str).str.startswith("2025-08-29"))
).any()

if duplicate:
    print("Event already exists. No duplicate added.")
else:
    events = pd.concat(
        [events, pd.DataFrame([new_record])],
        ignore_index=True
    )
    events.to_csv(output_path, index=False)
    print("One additional record saved.")

print(f"Total records: {len(events)}")
display(events.tail())

Existing records loaded: 67
Event already exists. No duplicate added.
Total records: 67

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,event_level,source_url
62,2025-01-19,2025-01-19,Veteran Telangana State Table Tennis Championships 2024,Table Tennis,NaN,Veteran table tennis players,"St. Paul's High School, Hyderguda",Hyderabad,State,https://www.telanganatabletennis.com/Veterans-Events.php
63,2025-10-15,2025-10-16,Osmania University Inter-College Table Tennis Tournament 2025,Table Tennis,NaN,University-affiliated college players,"St. Joseph's Degree and PG College, King Koti",Hyderabad,Inter-College,https://www.lords.ac.in/sports/events-attended/
64,2025-09-26,2025-09-29,17th HFI Mini Boys and Girls National Handball Championship,Handball,NaN,Mini boys and girls national teams,Nizam College,Hyderabad,National,https://handballfederationofindia.com/previous-events/
65,2024-11-02,2024-11-02,Osmania University Inter-College Karate Tournament 2024,Karate,NaN,University-affiliated college karate competitors,"Lords Institute of Engineering and Technology, Himayath Sagar",Hyderabad,Inter-College,https://www.lords.ac.in/sports/events-attended/
66,2025-09-22,2025-09-22,Osmania University National Archery Selection Trials 2025,Archery,NaN,University archery competitors,"Telangana Sports School, Hakimpet",Hyderabad,University Selection Trials,https://www.lords.ac.in/sports/events-attended/

In [89]:
from pathlib import Path
import pandas as pd

# Use the existing project CSV
output_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

if not output_path.exists():
    raise FileNotFoundError(f"Dataset not found: {output_path}")

events = pd.read_csv(output_path)

# Verified match records from official AIFF reports
football_records = [
    {
        "event_date": "2024-09-03",
        "event_end_date": "2024-09-03",
        "event_name": "Intercontinental Cup 2024: India vs Mauritius",
        "sport": "Football",
        "event_start_time": None,
        "team_or_participants": "India; Mauritius",
        "venue": "GMC Balayogi Athletic Stadium",
        "city": "Hyderabad",
        "event_level": "International",
        "source_url": "https://www.the-aiff.com/index.php/article/manolos-men-held-by-mauritius-in-intercontinental-cup-opener"
    },
    {
        "event_date": "2024-09-06",
        "event_end_date": "2024-09-06",
        "event_name": "Intercontinental Cup 2024: Syria vs Mauritius",
        "sport": "Football",
        "event_start_time": None,
        "team_or_participants": "Syria; Mauritius",
        "venue": "GMC Balayogi Athletic Stadium",
        "city": "Hyderabad",
        "event_level": "International",
        "source_url": "https://www.the-aiff.com/competitions/heroic"
    },
    {
        "event_date": "2024-09-09",
        "event_end_date": "2024-09-09",
        "event_name": "Intercontinental Cup 2024: India vs Syria",
        "sport": "Football",
        "event_start_time": None,
        "team_or_participants": "India; Syria",
        "venue": "GMC Balayogi Gachibowli Stadium",
        "city": "Hyderabad",
        "event_level": "International",
        "source_url": "https://www.the-aiff.com/article/syria-breach-blue-tigers-den-to-take-home-intercontinental-cup"
    },
    {
        "event_date": "2024-10-01",
        "event_end_date": "2024-10-01",
        "event_name": "Indian Super League 2024-25: Hyderabad FC vs Chennaiyin FC",
        "sport": "Football",
        "event_start_time": None,
        "team_or_participants": "Hyderabad FC; Chennaiyin FC",
        "venue": "Gachibowli Stadium",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": "https://www.the-aiff.com/index.php/article/hyderabad-fc-earn-first-point-after-gruelling-draw-against-chennaiyin-fc"
    }
]

new_events = pd.DataFrame(football_records)

# Standardize dates
for col in ["event_date", "event_end_date"]:
    events[col] = pd.to_datetime(events[col], errors="coerce")
    new_events[col] = pd.to_datetime(new_events[col], errors="coerce")

# Append only records that are not already present
key_columns = ["event_date", "event_name", "venue"]

existing_keys = set(
    events[key_columns].fillna("").astype(str).agg("|".join, axis=1)
)

new_keys = new_events[key_columns].fillna("").astype(str).agg("|".join, axis=1)
records_to_add = new_events.loc[~new_keys.isin(existing_keys)]

if not records_to_add.empty:
    events = pd.concat([events, records_to_add], ignore_index=True)
    events.to_csv(output_path, index=False)

print(f"New football records added: {len(records_to_add)}")
print(f"Total records in dataset: {len(events)}")
print(f"Saved to: {output_path}")

display(events[events["sport"].str.lower() == "football"])

New football records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,event_level,source_url
6,2024-09-03,2024-09-03,Intercontinental Cup 2024: India vs Mauritius,Football,NaN,India; Mauritius,GMC Balayogi Athletic Stadium,Hyderabad,International,https://www.the-aiff.com/index.php/article/manolos-men-held-by-mauritius-in-intercontinental-cup-opener
7,2024-09-06,2024-09-06,Intercontinental Cup 2024: Syria vs Mauritius,Football,NaN,Syria; Mauritius,GMC Balayogi Athletic Stadium,Hyderabad,International,https://www.the-aiff.com/competitions/heroic
8,2024-09-09,2024-09-09,Intercontinental Cup 2024: India vs Syria,Football,NaN,India; Syria,GMC Balayogi Gachibowli Stadium,Hyderabad,International,https://www.the-aiff.com/article/syria-breach-blue-tigers-den-to-take-home-intercontinental-cup
9,2024-10-01,2024-10-01,Indian Super League 2024-25: Hyderabad FC vs Chennaiyin FC,Football,NaN,Hyderabad FC; Chennaiyin FC,Gachibowli Stadium,Hyderabad,National,https://www.the-aiff.com/index.php/article/hyderabad-fc-earn-first-point-after-gruelling-draw-against-chennaiyin-fc

In [90]:
from pathlib import Path
import pandas as pd

# Existing project dataset
output_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

if not output_path.exists():
    raise FileNotFoundError(f"Dataset not found: {output_path}")

events = pd.read_csv(output_path)

# Official Badminton Association of India sources
badminton_records = [
    {
        "event_date": "2024-07-10",
        "event_end_date": "2024-07-17",
        "event_name": "Yonex-Sunrise All India Sub-Junior Ranking Badminton Tournament (U-15 & U-17)",
        "sport": "Badminton",
        "event_start_time": None,
        "team_or_participants": "Sub-junior players (U-15 and U-17)",
        "venue": "Hyderabad venue not specified in calendar",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": "https://www.badmintonindia.org/download/calender/BAI%20Calendar%202024-25.pdf"
    },
    {
        "event_date": "2025-05-08",
        "event_end_date": "2025-05-15",
        "event_name": "Yonex-Sunrise All India Senior Ranking Badminton Tournament 2025",
        "sport": "Badminton",
        "event_start_time": None,
        "team_or_participants": "Men and women",
        "venue": "Jwala Gutta Academy of Excellence, Moinabad",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": "https://www.badmintonindia.org/download/tournaments/BAI%20Circular%20-%20All%20India%20Senior%20Ranking%202025%20at%20Hyderabad.pdf"
    },
    {
        "event_date": "2025-08-19",
        "event_end_date": "2025-08-24",
        "event_name": "KOTAK India Junior International Series 2025",
        "sport": "Badminton",
        "event_start_time": None,
        "team_or_participants": "Junior players",
        "venue": "Venue not specified in calendar",
        "city": "Hyderabad",
        "event_level": "International",
        "source_url": "https://www.badmintonindia.org/download/calender/BAI%20Calendar%202025-26%20as%20on%2021-08-2025.pdf"
    }
]

new_events = pd.DataFrame(badminton_records)

# Normalize dates
for col in ["event_date", "event_end_date"]:
    events[col] = pd.to_datetime(events[col], errors="coerce")
    new_events[col] = pd.to_datetime(new_events[col], errors="coerce")

# Avoid duplicate tournament records
key_columns = ["event_date", "event_name", "sport"]

existing_keys = set(
    events[key_columns].fillna("").astype(str).agg("|".join, axis=1)
)

new_keys = new_events[key_columns].fillna("").astype(str).agg("|".join, axis=1)
records_to_add = new_events.loc[~new_keys.isin(existing_keys)]

if not records_to_add.empty:
    events = pd.concat([events, records_to_add], ignore_index=True)
    events.to_csv(output_path, index=False)

print(f"New badminton records added: {len(records_to_add)}")
print(f"Total records in dataset: {len(events)}")
print(f"Saved to: {output_path}")

display(events[events["sport"].str.lower() == "badminton"])

New badminton records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,event_level,source_url
10,2024-07-10,2024-07-17,Yonex-Sunrise All India Sub-Junior Ranking Badminton Tournament (U-15 & U-17),Badminton,NaN,Sub-junior players (U-15 and U-17),Hyderabad venue not specified in calendar,Hyderabad,National,https://www.badmintonindia.org/download/calender/BAI%20Calendar%202024-25.pdf
11,2025-05-08,2025-05-15,Yonex-Sunrise All India Senior Ranking Badminton Tournament 2025,Badminton,NaN,Men and women,"Jwala Gutta Academy of Excellence, Moinabad",Hyderabad,National,https://www.badmintonindia.org/download/tournaments/BAI%20Circular%20-%20All%20India%20Senior%20Ranking%202025%20at%20Hyderabad.pdf
12,2025-08-19,2025-08-24,KOTAK India Junior International Series 2025,Badminton,NaN,Junior players,Venue not specified in calendar,Hyderabad,International,https://www.badmintonindia.org/download/calender/BAI%20Calendar%202025-26%20as%20on%2021-08-2025.pdf

In [91]:
from pathlib import Path
import pandas as pd

# Existing project CSV — do not create a new file
output_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

if not output_path.exists():
    raise FileNotFoundError(f"Dataset not found: {output_path}")

events = pd.read_csv(output_path)

# Event records supported by published schedules/newsletters
athletics_records = [
    {
        "event_date": "2023-08-26",
        "event_end_date": "2023-08-26",
        "event_name": "NMDC Hyderabad Marathon 2023 - 5K Run",
        "sport": "Running",
        "event_start_time": None,
        "team_or_participants": "5K participants",
        "venue": "HITEX Expo Grounds, Madhapur",
        "city": "Hyderabad",
        "event_level": "City",
        "source_url": "https://www.marathonhyderabad.com/frequently-asked-questions/"
    },
    {
        "event_date": "2023-08-27",
        "event_end_date": "2023-08-27",
        "event_name": "NMDC Hyderabad Marathon 2023 - Marathon, Half Marathon and 10K",
        "sport": "Running",
        "event_start_time": None,
        "team_or_participants": "Marathon, half-marathon and 10K participants",
        "venue": "People's Plaza, Necklace Road; HITEX Expo Grounds",
        "city": "Hyderabad",
        "event_level": "City",
        "source_url": "https://www.marathonhyderabad.com/frequently-asked-questions/"
    },
    {
        "event_date": "2024-08-25",
        "event_end_date": "2024-08-25",
        "event_name": "NMDC Hyderabad Marathon 2024 - Marathon, Half Marathon and 10K",
        "sport": "Running",
        "event_start_time": None,
        "team_or_participants": "Marathon, half-marathon and 10K participants",
        "venue": "People's Plaza, Necklace Road; HITEX; Gachibowli Stadium",
        "city": "Hyderabad",
        "event_level": "City",
        "source_url": "https://www.hyderabadrunners.com/wp-content/uploads/2024/10/August-2024-News-Letter-Hyderabad-Runers.pdf"
    },
    {
        "event_date": "2024-09-28",
        "event_end_date": "2024-09-28",
        "event_name": "Cardiac Rehab Run - 1st Edition",
        "sport": "Running",
        "event_start_time": None,
        "team_or_participants": "Community runners",
        "venue": "Sanjeevaiah Park and Necklace Road",
        "city": "Hyderabad",
        "event_level": "City",
        "source_url": "https://events.telanganarunners.com/"
    },
    {
        "event_date": "2025-08-23",
        "event_end_date": "2025-08-23",
        "event_name": "NMDC Hyderabad Marathon 2025 - 5K Run",
        "sport": "Running",
        "event_start_time": None,
        "team_or_participants": "5K participants",
        "venue": "HITEX",
        "city": "Hyderabad",
        "event_level": "City",
        "source_url": "https://www.hyderabadrunners.com/wp-content/uploads/2025/10/HyderabadRunners_oct9th.pdf"
    }
]

new_events = pd.DataFrame(athletics_records)

# Normalize dates
for col in ["event_date", "event_end_date"]:
    events[col] = pd.to_datetime(events[col], errors="coerce")
    new_events[col] = pd.to_datetime(new_events[col], errors="coerce")

# Add only records not already present
key_columns = ["event_date", "event_name", "sport"]

existing_keys = set(
    events[key_columns]
    .fillna("")
    .astype(str)
    .agg("|".join, axis=1)
)

new_keys = (
    new_events[key_columns]
    .fillna("")
    .astype(str)
    .agg("|".join, axis=1)
)

records_to_add = new_events.loc[~new_keys.isin(existing_keys)]

if not records_to_add.empty:
    events = pd.concat([events, records_to_add], ignore_index=True)
    events.to_csv(output_path, index=False)

print(f"New athletics/running records added: {len(records_to_add)}")
print(f"Total records in dataset: {len(events)}")
print(f"Saved to: {output_path}")

display(
    events[events["sport"].str.lower().isin(["running", "athletics"])]
    .sort_values("event_date")
)

New athletics/running records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,event_level,source_url
13,2023-08-26,2023-08-26,NMDC Hyderabad Marathon 2023 - 5K Run,Running,NaN,5K participants,"HITEX Expo Grounds, Madhapur",Hyderabad,City,https://www.marathonhyderabad.com/frequently-asked-questions/
14,2023-08-27,2023-08-27,"NMDC Hyderabad Marathon 2023 - Marathon, Half Marathon and 10K",Running,NaN,"Marathon, half-marathon and 10K participants","People's Plaza, Necklace Road; HITEX Expo Grounds",Hyderabad,City,https://www.marathonhyderabad.com/frequently-asked-questions/
15,2024-08-25,2024-08-25,"NMDC Hyderabad Marathon 2024 - Marathon, Half Marathon and 10K",Running,NaN,"Marathon, half-marathon and 10K participants","People's Plaza, Necklace Road; HITEX; Gachibowli Stadium",Hyderabad,City,https://www.hyderabadrunners.com/wp-content/uploads/2024/10/August-2024-News-Letter-Hyderabad-Runers.pdf
16,2024-09-28,2024-09-28,Cardiac Rehab Run - 1st Edition,Running,NaN,Community runners,Sanjeevaiah Park and Necklace Road,Hyderabad,City,https://events.telanganarunners.com/
17,2025-08-23,2025-08-23,NMDC Hyderabad Marathon 2025 - 5K Run,Running,NaN,5K participants,HITEX,Hyderabad,City,https://www.hyderabadrunners.com/wp-content/uploads/2025/10/HyderabadRunners_oct9th.pdf

In [92]:
from pathlib import Path
import pandas as pd

# Existing project CSV
output_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

if not output_path.exists():
    raise FileNotFoundError(f"Dataset not found: {output_path}")

events = pd.read_csv(output_path)

# Additional hockey tournaments verified from official sources
hockey_records = [
    {
        "event_date": "2024-11-26",
        "event_end_date": "2024-12-06",
        "event_name": "14th Hockey India Sub-Junior Women National Championship 2024",
        "sport": "Hockey",
        "event_start_time": None,
        "team_or_participants": "Women's sub-junior teams",
        "venue": "Secunderabad (specific venue not stated in source)",
        "city": "Secunderabad",
        "event_level": "National",
        "source_url": "https://www.hockeyindia.org/technical/certificates-details"
    },
    {
        "event_date": "2026-03-08",
        "event_end_date": "2026-03-14",
        "event_name": "FIH Women's Hockey World Cup 2026 Qualifiers",
        "sport": "Hockey",
        "event_start_time": None,
        "team_or_participants": "India, England, Scotland, Korea, Italy, Uruguay, Wales, Austria",
        "venue": "G.M.C. Balayogi Hockey Ground, Gachibowli Hockey Complex",
        "city": "Hyderabad",
        "event_level": "International",
        "source_url": "https://www.hockeyindia.org/news/tickets-for-fih-hockey-world-cup-2026-qualifiers-hyderabad-telangana-go-live-today"
    }
]

new_events = pd.DataFrame(hockey_records)

# Normalize dates
for col in ["event_date", "event_end_date"]:
    events[col] = pd.to_datetime(events[col], errors="coerce")
    new_events[col] = pd.to_datetime(new_events[col], errors="coerce")

# Prevent duplicate tournament records
key_columns = ["event_date", "event_name", "sport"]

existing_keys = set(
    events[key_columns]
    .fillna("")
    .astype(str)
    .agg("|".join, axis=1)
)

new_keys = (
    new_events[key_columns]
    .fillna("")
    .astype(str)
    .agg("|".join, axis=1)
)

records_to_add = new_events.loc[~new_keys.isin(existing_keys)]

if not records_to_add.empty:
    events = pd.concat([events, records_to_add], ignore_index=True)
    events.to_csv(output_path, index=False)

print(f"New hockey records added: {len(records_to_add)}")
print(f"Total records in dataset: {len(events)}")
print(f"Saved to: {output_path}")

display(
    events[events["sport"].str.lower() == "hockey"]
    .sort_values("event_date")
)

New hockey records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,event_level,source_url
0,2023-01-01,2023-01-12,Gooncha 58th Nehru Senior Hockey Tournament (Men),Hockey,NaN,NaN,Secunderabad,Secunderabad,National,https://www.telanganahockey.org/national-events.php
1,2023-11-14,2023-11-25,Gooncha 59th Nehru Senior Hockey Tournament (Men),Hockey,NaN,NaN,Secunderabad,Secunderabad,National,https://www.telanganahockey.org/national-events.php
18,2024-11-26,2024-12-06,14th Hockey India Sub-Junior Women National Championship 2024,Hockey,NaN,Women's sub-junior teams,Secunderabad (specific venue not stated in source),Secunderabad,National,https://www.hockeyindia.org/technical/certificates-details
19,2026-03-08,2026-03-14,FIH Women's Hockey World Cup 2026 Qualifiers,Hockey,NaN,"India, England, Scotland, Korea, Italy, Uruguay, Wales, Austria","G.M.C. Balayogi Hockey Ground, Gachibowli Hockey Complex",Hyderabad,International,https://www.hockeyindia.org/news/tickets-for-fih-hockey-world-cup-2026-qualifiers-hyderabad-telangana-go-live-today

In [93]:
from pathlib import Path
import pandas as pd

# Existing project CSV
output_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

if not output_path.exists():
    raise FileNotFoundError(f"Dataset not found: {output_path}")

events = pd.read_csv(output_path)

# Basketball events with published dates and venues
basketball_records = [
    {
        "event_date": "2024-12-16",
        "event_end_date": "2024-12-22",
        "event_name": "49th Sub-Junior National Basketball Championship for Boys and Girls 2024",
        "sport": "Basketball",
        "event_start_time": None,
        "team_or_participants": "Sub-junior boys and girls teams",
        "venue": "Hyderabad (specific venue not stated in BFI calendar)",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": "https://www.basketballfederationindia.org/national-calender/"
    },
    {
        "event_date": "2025-09-16",
        "event_end_date": "2025-09-17",
        "event_name": "Osmania University Inter-College Basketball Tournament for Women 2025",
        "sport": "Basketball",
        "event_start_time": "09:30",
        "team_or_participants": "Women's college teams",
        "venue": "St. Francis Degree College, Begumpet",
        "city": "Hyderabad",
        "event_level": "Inter-college",
        "source_url": "https://www.osmania.ac.in/News2025/ICT%28W%29%20Basketball%202025-26.pdf"
    },
    {
        "event_date": "2026-06-12",
        "event_end_date": "2026-06-15",
        "event_name": "Telangana State U-14 Basketball Championship 2026",
        "sport": "Basketball",
        "event_start_time": None,
        "team_or_participants": "U-14 district teams",
        "venue": "Kotla Vijaya Bhaskar Reddy Stadium",
        "city": "Hyderabad",
        "event_level": "State",
        "source_url": "https://telanganabasketballassociation.com/events/69d2b5a9dff568f5fa71c63c"
    },
    {
        "event_date": "2026-06-19",
        "event_end_date": "2026-06-28",
        "event_name": "Telangana Junior Basketball League 2026",
        "sport": "Basketball",
        "event_start_time": None,
        "team_or_participants": "Junior district franchise teams",
        "venue": "Kotla Vijaya Bhaskar Reddy Indoor Stadium",
        "city": "Hyderabad",
        "event_level": "State league",
        "source_url": "https://telanganabasketballassociation.com/tournaments/leagues"
    }
]

new_events = pd.DataFrame(basketball_records)

# Standardize dates
for col in ["event_date", "event_end_date"]:
    events[col] = pd.to_datetime(events[col], errors="coerce")
    new_events[col] = pd.to_datetime(new_events[col], errors="coerce")

# Check duplicates before appending
key_columns = ["event_date", "event_name", "sport"]

existing_keys = set(
    events[key_columns]
    .fillna("")
    .astype(str)
    .agg("|".join, axis=1)
)

new_keys = (
    new_events[key_columns]
    .fillna("")
    .astype(str)
    .agg("|".join, axis=1)
)

records_to_add = new_events.loc[~new_keys.isin(existing_keys)]

if not records_to_add.empty:
    events = pd.concat([events, records_to_add], ignore_index=True)
    events.to_csv(output_path, index=False)

print(f"New basketball records added: {len(records_to_add)}")
print(f"Total records in dataset: {len(events)}")
print(f"Saved to: {output_path}")

display(
    events[events["sport"].str.lower() == "basketball"]
    .sort_values("event_date")
)

New basketball records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,event_level,source_url
20,2024-12-16,2024-12-22,49th Sub-Junior National Basketball Championship for Boys and Girls 2024,Basketball,NaN,Sub-junior boys and girls teams,Hyderabad (specific venue not stated in BFI calendar),Hyderabad,National,https://www.basketballfederationindia.org/national-calender/
21,2025-09-16,2025-09-17,Osmania University Inter-College Basketball Tournament for Women 2025,Basketball,09:30,Women's college teams,"St. Francis Degree College, Begumpet",Hyderabad,Inter-college,https://www.osmania.ac.in/News2025/ICT%28W%29%20Basketball%202025-26.pdf
22,2026-06-12,2026-06-15,Telangana State U-14 Basketball Championship 2026,Basketball,NaN,U-14 district teams,Kotla Vijaya Bhaskar Reddy Stadium,Hyderabad,State,https://telanganabasketballassociation.com/events/69d2b5a9dff568f5fa71c63c
23,2026-06-19,2026-06-28,Telangana Junior Basketball League 2026,Basketball,NaN,Junior district franchise teams,Kotla Vijaya Bhaskar Reddy Indoor Stadium,Hyderabad,State league,https://telanganabasketballassociation.com/tournaments/leagues

In [94]:
from pathlib import Path
import pandas as pd

# Existing project dataset
output_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

if not output_path.exists():
    raise FileNotFoundError(f"Dataset not found: {output_path}")

events = pd.read_csv(output_path)

# Published volleyball events in Hyderabad
volleyball_records = [
    {
        "event_date": "2023-02-15",
        "event_end_date": "2023-02-15",
        "event_name": "Prime Volleyball League Season 2: Hyderabad Black Hawks vs Kochi Blue Spikers",
        "sport": "Volleyball",
        "event_start_time": None,
        "team_or_participants": "Hyderabad Black Hawks; Kochi Blue Spikers",
        "venue": "GMC Balayogi Indoor Stadium, Gachibowli",
        "city": "Hyderabad",
        "event_level": "Professional league",
        "source_url": "https://telanganatoday.com/prime-volleyball-league-hyderabad-black-hawks-confident-of-good-show-in-front-of-home-crowd"
    },
    {
        "event_date": "2024-02-10",
        "event_end_date": "2024-02-11",
        "event_name": "VD Black Hawks Open 2024 - Championship Weekend",
        "sport": "Volleyball",
        "event_start_time": None,
        "team_or_participants": "Teams from Telangana and Andhra Pradesh",
        "venue": "Gachibowli Indoor Stadium",
        "city": "Hyderabad",
        "event_level": "Regional",
        "source_url": "https://telanganatoday.com/vd-black-hawks-volleyball-tournament-from-january-19"
    },
    {
        "event_date": "2025-10-02",
        "event_end_date": "2025-10-26",
        "event_name": "Prime Volleyball League Season 4",
        "sport": "Volleyball",
        "event_start_time": None,
        "team_or_participants": "10 professional teams",
        "venue": "GMC Balayogi Indoor Stadium, Gachibowli",
        "city": "Hyderabad",
        "event_level": "Professional league",
        "source_url": "https://telanganatoday.com/hyderabad-black-hawks-invite-ktr-for-prime-volleyball-league-home-matches"
    }
]

new_events = pd.DataFrame(volleyball_records)

# Normalize dates
for col in ["event_date", "event_end_date"]:
    events[col] = pd.to_datetime(events[col], errors="coerce")
    new_events[col] = pd.to_datetime(new_events[col], errors="coerce")

# Prevent duplicates
key_columns = ["event_date", "event_name", "sport"]

existing_keys = set(
    events[key_columns]
    .fillna("")
    .astype(str)
    .agg("|".join, axis=1)
)

new_keys = (
    new_events[key_columns]
    .fillna("")
    .astype(str)
    .agg("|".join, axis=1)
)

records_to_add = new_events.loc[~new_keys.isin(existing_keys)]

if not records_to_add.empty:
    events = pd.concat([events, records_to_add], ignore_index=True)
    events.to_csv(output_path, index=False)

print(f"New volleyball records added: {len(records_to_add)}")
print(f"Total records in dataset: {len(events)}")
print(f"Saved to: {output_path}")

display(
    events[events["sport"].str.lower() == "volleyball"]
    .sort_values("event_date")
)

New volleyball records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,event_level,source_url
24,2023-02-15,2023-02-15,Prime Volleyball League Season 2: Hyderabad Black Hawks vs Kochi Blue Spikers,Volleyball,NaN,Hyderabad Black Hawks; Kochi Blue Spikers,"GMC Balayogi Indoor Stadium, Gachibowli",Hyderabad,Professional league,https://telanganatoday.com/prime-volleyball-league-hyderabad-black-hawks-confident-of-good-show-in-front-of-home-crowd
25,2024-02-10,2024-02-11,VD Black Hawks Open 2024 - Championship Weekend,Volleyball,NaN,Teams from Telangana and Andhra Pradesh,Gachibowli Indoor Stadium,Hyderabad,Regional,https://telanganatoday.com/vd-black-hawks-volleyball-tournament-from-january-19
26,2025-10-02,2025-10-26,Prime Volleyball League Season 4,Volleyball,NaN,10 professional teams,"GMC Balayogi Indoor Stadium, Gachibowli",Hyderabad,Professional league,https://telanganatoday.com/hyderabad-black-hawks-invite-ktr-for-prime-volleyball-league-home-matches

In [95]:
import pandas as pd
from pathlib import Path

# Existing dataset — do not create a new file
file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

# Wrestling event records
wrestling_events = [
    {
        "event_date": "2024-07-14",
        "event_end_date": "2024-07-14",
        "event_name": "Telangana State Under-23 Wrestling Championship",
        "sport": "Wrestling",
        "event_start_time": None,
        "team_or_participants": "Under-23 men and women; freestyle and Greco-Roman",
        "venue": "Vallala Grounds, Yousufguda",
        "city": "Hyderabad",
        "event_level": "State",
        "source_url": (
            "https://munsifdaily.com/telangana-state-wrestling-championship-2024-"
            "wrestlers-selected-for-national-championship/"
        ),
    },
    {
        "event_date": "2026-01-24",
        "event_end_date": "2026-01-25",
        "event_name": "26th Hyderabad Kesari Wrestling Championship",
        "sport": "Wrestling",
        "event_start_time": None,
        "team_or_participants": "Wrestlers from Telangana and other parts of India",
        "venue": "Barkas Playground",
        "city": "Hyderabad",
        "event_level": "City / Invitational",
        "source_url": (
            "https://www.siasat.com/hyderabad-hosts-national-wrestling-"
            "championship-at-barkas-playground-3328027/"
        ),
    },
    {
        "event_date": "2026-06-23",
        "event_end_date": "2026-06-24",
        "event_name": "13th Hyderabad District Wrestling Championship",
        "sport": "Wrestling",
        "event_start_time": None,
        "team_or_participants": "Under-23; freestyle, Greco-Roman and women's categories",
        "venue": "Barkas Playground",
        "city": "Hyderabad",
        "event_level": "District",
        "source_url": (
            "https://khelkhiladis.com/hyderabad-wrestling-at-barkas-pg-on-june-23-24/"
        ),
    },
]

new_df = pd.DataFrame(wrestling_events)

# Keep the existing column order
new_df = new_df[df.columns]

# Normalize date columns for consistent duplicate detection
for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(df[col], errors="coerce").dt.strftime("%Y-%m-%d")
    new_df[col] = pd.to_datetime(new_df[col], errors="coerce").dt.strftime("%Y-%m-%d")

# Identify duplicate records using date, name, sport and venue
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

existing_keys = set(
    df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)
)

new_df = new_df[
    ~new_df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1).isin(existing_keys)
]

# Append only records not already present
df = pd.concat([df, new_df], ignore_index=True)

# Save to the same CSV
df.to_csv(file_path, index=False)

print("New wrestling records added:", len(new_df))
print("Total records in dataset:", len(df))
print("Saved to:", file_path)

display(
    df[df["sport"].astype(str).str.lower() == "wrestling"][
        ["event_date", "event_end_date", "event_name", "sport", "venue", "city"]
    ].sort_values("event_date")
)

New wrestling records added:

 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

    event_date event_end_date                                       event_name      sport                        venue       city
27  2024-07-14     2024-07-14  Telangana State Under-23 Wrestling Championship  Wrestling  Vallala Grounds, Yousufguda  Hyderabad
28  2026-01-24     2026-01-25     26th Hyderabad Kesari Wrestling Championship  Wrestling            Barkas Playground  Hyderabad
29  2026-06-23     2026-06-24   13th Hyderabad District Wrestling Championship  Wrestling            Barkas Playground  Hyderabad

In [96]:
import pandas as pd
from pathlib import Path

# Existing project dataset
file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

boxing_events = [
    {
        "event_date": "2024-05-19",
        "event_end_date": "2024-05-19",
        "event_name": "Pro Boxing Fight Night",
        "sport": "Boxing",
        "event_start_time": None,
        "team_or_participants": "Professional boxers; multiple bouts",
        "venue": "Ramanaidu Studios",
        "city": "Hyderabad",
        "event_level": "Professional",
        "source_url": "https://www.indianboxingcouncil.com/",
    },
    {
        "event_date": "2025-04-25",
        "event_end_date": "2025-04-28",
        "event_name": (
            "BDFI 7th U12, Sub-Junior, Junior, Youth and Senior "
            "Men & Women National Boxing Championship"
        ),
        "sport": "Boxing",
        "event_start_time": None,
        "team_or_participants": "U12, Sub-Junior, Junior, Youth and Senior men and women",
        "venue": "Sports Complex, Secunderabad",
        "city": "Secunderabad",
        "event_level": "National",
        "source_url": (
            "https://bdfi.in/events/"
            "bdfi-7th-u12-sub-junior-junior-youth-senior-men-women-"
            "national-boxing-championship-2024-on-25-april-2025-to-"
            "28-april-2025-held-at-sports-complex-secunderabad-telangana-legacy-50"
        ),
    },
    {
        "event_date": "2025-06-28",
        "event_end_date": "2025-07-01",
        "event_name": "Elite Women Tournament 2025",
        "sport": "Boxing",
        "event_start_time": None,
        "team_or_participants": "Elite women boxers; participating state and institutional teams",
        "venue": "Saroornagar Indoor Stadium",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": "https://boxingfederation.in/elite-women-tournament-2025/",
    },
    {
        "event_date": "2025-08-31",
        "event_end_date": "2025-08-31",
        "event_name": "The Toughman - KR Steven Boxing Championship",
        "sport": "Boxing",
        "event_start_time": None,
        "team_or_participants": "Senior men; multiple weight categories",
        "venue": "LB Stadium Boxing Hall",
        "city": "Hyderabad",
        "event_level": "District / Open",
        "source_url": "https://incredibleboxing.com/events/",
    },
]

new_df = pd.DataFrame(boxing_events)

# Match the existing dataset schema
new_df = new_df[df.columns]

# Normalize dates for consistent duplicate detection
date_cols = ["event_date", "event_end_date"]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce").dt.strftime("%Y-%m-%d")
    new_df[col] = pd.to_datetime(new_df[col], errors="coerce").dt.strftime("%Y-%m-%d")

# Avoid duplicates using event date, name, sport and venue
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

existing_keys = set(
    df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)
)

new_keys = new_df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)

new_df = new_df[~new_keys.isin(existing_keys)]

# Append and save to the same file
df = pd.concat([df, new_df], ignore_index=True)
df.to_csv(file_path, index=False)

print("New boxing records added:", len(new_df))
print("Total records in dataset:", len(df))
print("Saved to:", file_path)

display(
    df[df["sport"].astype(str).str.lower() == "boxing"][
        ["event_date", "event_end_date", "event_name", "sport", "venue", "city"]
    ].sort_values("event_date")
)

New boxing records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

    event_date event_end_date                                                                                   event_name   sport                         venue          city
30  2024-05-19     2024-05-19                                                                       Pro Boxing Fight Night  Boxing             Ramanaidu Studios     Hyderabad
31  2025-04-25     2025-04-28  BDFI 7th U12, Sub-Junior, Junior, Youth and Senior Men & Women National Boxing Championship  Boxing  Sports Complex, Secunderabad  Secunderabad
32  2025-06-28     2025-07-01                                                                  Elite Women Tournament 2025  Boxing    Saroornagar Indoor Stadium     Hyderabad
33  2025-08-31     2025-08-31                                                 The Toughman - KR Steven Boxing Championship  Boxing        LB Stadium Boxing Hall     Hyderabad

In [97]:
import pandas as pd
from pathlib import Path

# Existing project dataset
file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

# Shooting events supported by official competition notices
shooting_events = [
    {
        "event_date": "2023-06-14",
        "event_end_date": "2023-06-21",
        "event_name": "IX Telangana State Shooting Championship 2023",
        "sport": "Shooting",
        "event_start_time": None,
        "team_or_participants": "State-level shooters; air rifle, pistol, small bore and shotgun",
        "venue": "SATS Shooting Ranges, Gachibowli",
        "city": "Hyderabad",
        "event_level": "State",
        "source_url": (
            "https://www.tsra.in/pdfs/"
            "Circular-%20IX%20Telangana%20State%20Shooting%20"
            "Championship%20Competitions%20-%202023.pdf"
        ),
    },
    {
        "event_date": "2024-09-27",
        "event_end_date": "2024-10-02",
        "event_name": "XV South Zone Shooting Championship 2024 - Shotgun Events",
        "sport": "Shooting",
        "event_start_time": None,
        "team_or_participants": "South Zone shooters; national-rule and ISSF shotgun events",
        "venue": "SATS Shooting Ranges, Gachibowli",
        "city": "Hyderabad",
        "event_level": "South Zone",
        "source_url": "https://thenrai.in/details.aspx?view=6027",
    },
    {
        "event_date": "2025-06-21",
        "event_end_date": "2025-06-30",
        "event_name": "XI Telangana State Shooting Championship 2025",
        "sport": "Shooting",
        "event_start_time": None,
        "team_or_participants": "State-level shooters; air rifle, pistol, small bore and shotgun",
        "venue": "Gun for Glory Shooting Academy, SATS Shooting Range, Gachibowli",
        "city": "Hyderabad",
        "event_level": "State",
        "source_url": (
            "https://www.tsra.in/pdfs/"
            "Circular%20XI%20Telangana%20StateShooting%20"
            "Championship%20Competitions%20-%202025.pdf"
        ),
    },
]

new_df = pd.DataFrame(shooting_events)

# Keep the exact existing column structure
new_df = new_df[df.columns]

# Normalize dates
for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(df[col], errors="coerce").dt.strftime("%Y-%m-%d")
    new_df[col] = pd.to_datetime(
        new_df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Remove duplicates using date, event name, sport and venue
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

existing_keys = set(
    df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)
)

new_keys = new_df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)

new_df = new_df[~new_keys.isin(existing_keys)]

# Append only new records
df = pd.concat([df, new_df], ignore_index=True)

# Save to the existing CSV
df.to_csv(file_path, index=False)

print("New shooting records added:", len(new_df))
print("Total records in dataset:", len(df))
print("Saved to:", file_path)

display(
    df[df["sport"].astype(str).str.lower() == "shooting"][
        ["event_date", "event_end_date", "event_name", "sport", "venue", "city"]
    ].sort_values("event_date")
)

New shooting records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

    event_date event_end_date                                                 event_name     sport                                                            venue       city
34  2023-06-14     2023-06-21              IX Telangana State Shooting Championship 2023  Shooting                                 SATS Shooting Ranges, Gachibowli  Hyderabad
35  2024-09-27     2024-10-02  XV South Zone Shooting Championship 2024 - Shotgun Events  Shooting                                 SATS Shooting Ranges, Gachibowli  Hyderabad
36  2025-06-21     2025-06-30              XI Telangana State Shooting Championship 2025  Shooting  Gun for Glory Shooting Academy, SATS Shooting Range, Gachibowli  Hyderabad

In [98]:
import pandas as pd
from pathlib import Path

# Existing project dataset
file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

tennis_events = [
    {
        "event_date": "2024-09-02",
        "event_end_date": "2024-09-07",
        "event_name": "AITA Women Rs 2.5 Lakh Tennis Tournament",
        "sport": "Tennis",
        "event_start_time": None,
        "team_or_participants": "Women's singles and doubles participants",
        "venue": "Not specified in tournament factsheet",
        "city": "Hyderabad",
        "event_level": "National / AITA",
        "source_url": (
            "https://bwtaitaprod.blob.core.windows.net/aitaors-files/"
            "data/factsheet/2.5LAC_factsheet_1723182764.pdf"
        ),
    },
    {
        "event_date": "2024-12-02",
        "event_end_date": "2024-12-08",
        "event_name": "GVK AISTA Nationals Hyderabad 2024",
        "sport": "Tennis",
        "event_start_time": None,
        "team_or_participants": "Senior players in 35+, 45+, 55+, 65+, 70+ singles and 75+ doubles",
        "venue": "L.B. Stadium, Fathe Maidan Tennis Complex (SATS)",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": "https://aistatennis.com/tournament.php?eid=11&tid=100",
    },
    {
        "event_date": "2025-01-13",
        "event_end_date": "2025-01-17",
        "event_name": "SITE Sports Junior Tennis Tournament - U-12",
        "sport": "Tennis",
        "event_start_time": None,
        "team_or_participants": "U-12 boys and girls",
        "venue": "Not specified in tournament factsheet",
        "city": "Hyderabad",
        "event_level": "Junior / Talent Series",
        "source_url": (
            "https://aitatennis.com/aitaors/public/storage/data/factsheet/"
            "TS7_factsheet_1736146829.pdf"
        ),
    },
    {
        "event_date": "2025-09-10",
        "event_end_date": "2025-09-14",
        "event_name": "Hyderabad Open Tennis Tournament - 22nd Edition",
        "sport": "Tennis",
        "event_start_time": None,
        "team_or_participants": "Players in age groups 30 to 75; singles and doubles",
        "venue": (
            "Vijay Tennis Academy, Kokapet; "
            "Cross Courts Academy; Lake View Academy"
        ),
        "city": "Hyderabad",
        "event_level": "Open / Senior",
        "source_url": "https://hydopen.com/announcements/",
    },
    {
        "event_date": "2025-11-10",
        "event_end_date": "2025-11-15",
        "event_name": "AITA National Series U-12 Tournament - Hyderabad",
        "sport": "Tennis",
        "event_start_time": None,
        "team_or_participants": "U-12 boys and girls",
        "venue": "Not specified in tournament factsheet",
        "city": "Hyderabad",
        "event_level": "National Series / Junior",
        "source_url": (
            "https://tstatennis.kloudportal.com/wp-content/uploads/2025/10/"
            "factsheet_1759232362.pdf"
        ),
    },
]

new_df = pd.DataFrame(tennis_events)

# Match the existing dataset schema
new_df = new_df[df.columns]

# Normalize dates
for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(df[col], errors="coerce").dt.strftime("%Y-%m-%d")
    new_df[col] = pd.to_datetime(
        new_df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Check duplicates using event date, event name, sport and venue
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

existing_keys = set(
    df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)
)

new_keys = new_df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)

new_df = new_df[~new_keys.isin(existing_keys)]

# Append new records and save to the same CSV
df = pd.concat([df, new_df], ignore_index=True)
df.to_csv(file_path, index=False)

print("New tennis records added:", len(new_df))
print("Total records in dataset:", len(df))
print("Saved to:", file_path)

display(
    df[df["sport"].astype(str).str.lower() == "tennis"][
        [
            "event_date",
            "event_end_date",
            "event_name",
            "sport",
            "venue",
            "city",
        ]
    ].sort_values("event_date")
)

New tennis records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

    event_date event_end_date                                        event_name   sport                                                                   venue       city
37  2024-09-02     2024-09-07          AITA Women Rs 2.5 Lakh Tennis Tournament  Tennis                                   Not specified in tournament factsheet  Hyderabad
38  2024-12-02     2024-12-08                GVK AISTA Nationals Hyderabad 2024  Tennis                        L.B. Stadium, Fathe Maidan Tennis Complex (SATS)  Hyderabad
39  2025-01-13     2025-01-17       SITE Sports Junior Tennis Tournament - U-12  Tennis                                   Not specified in tournament factsheet  Hyderabad
40  2025-09-10     2025-09-14   Hyderabad Open Tennis Tournament - 22nd Edition  Tennis  Vijay Tennis Academy, Kokapet; Cross Courts Academy; Lake View Academy  Hyderabad
41  2025-11-10     2025-11-15  AITA National Series U-12 Tournament - Hyderabad  Tennis                                   Not specified in tournament factsheet  Hyderabad

In [99]:
import pandas as pd
from pathlib import Path

# Existing project dataset
file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

# Candidate swimming events with published dates and locations
swimming_events = [
    {
        "event_date": "2023-07-02",
        "event_end_date": "2023-07-05",
        "event_name": "76th Senior National Aquatic Championships 2023",
        "sport": "Swimming",
        "event_start_time": None,
        "team_or_participants": "Senior men and women; national-level swimmers",
        "venue": "GMC Balayogi Sports Complex, Gachibowli Swimming Pool",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": (
            "https://www.swimming.org.in/wp-content/uploads/2023/04/"
            "76th-Senior-National-Aquatic-Championship-2023_Circular.pdf"
        ),
    },
    {
        "event_date": "2023-07-29",
        "event_end_date": "2023-07-30",
        "event_name": (
            "8th Telangana Sub-Junior and Junior Inter-District "
            "Swimming Championship 2023"
        ),
        "sport": "Swimming",
        "event_start_time": None,
        "team_or_participants": "Sub-junior and junior swimmers representing districts",
        "venue": "HPS Swimming Pool, Begumpet",
        "city": "Hyderabad",
        "event_level": "State / Inter-District",
        "source_url": (
            "https://munsifdaily.com/"
            "telangana-sub-junior-junior-inter-district-swimming-championship-2023/"
        ),
    },
    {
        "event_date": "2023-09-10",
        "event_end_date": "2023-09-10",
        "event_name": (
            "23rd Annual Swimming Competition - Hyderabad District "
            "Swimming Association"
        ),
        "sport": "Swimming",
        "event_start_time": None,
        "team_or_participants": "Age-group swimmers",
        "venue": "GMC Balayogi Stadium Swimming Pool, Gachibowli",
        "city": "Hyderabad",
        "event_level": "District",
        "source_url": "https://www.jhpublicschool.com/sports-achievements/",
    },
    {
        "event_date": "2024-05-19",
        "event_end_date": "2024-05-19",
        "event_name": "Swimming Championship Season II - 2024",
        "sport": "Swimming",
        "event_start_time": None,
        "team_or_participants": "Boys and girls; non-medalist swimmers",
        "venue": "GHMC Secunderabad Swimming Pool",
        "city": "Secunderabad",
        "event_level": "Local / Open",
        "source_url": (
            "https://www.townscript.com/e/"
            "swimming-championship-2025-season-iii-301240"
        ),
    },
    {
        "event_date": "2026-05-17",
        "event_end_date": "2026-05-17",
        "event_name": "4th Swimming Championship 2026",
        "sport": "Swimming",
        "event_start_time": None,
        "team_or_participants": "Boys and girls; beginner and non-medalist swimmers",
        "venue": "GHMC Swimming Pool, Amberpet",
        "city": "Hyderabad",
        "event_level": "Local / Open",
        "source_url": "https://meraevents.com/events/4th-swimming-championship-2026",
    },
]

new_df = pd.DataFrame(swimming_events)

# Preserve the existing dataset's exact column order
new_df = new_df[df.columns]

# Normalize date values
for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(df[col], errors="coerce").dt.strftime("%Y-%m-%d")
    new_df[col] = pd.to_datetime(
        new_df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Deduplicate using event date, event name, sport and venue
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

existing_keys = set(
    df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)
)

new_keys = new_df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)

new_df = new_df[~new_keys.isin(existing_keys)]

# Append only new records
df = pd.concat([df, new_df], ignore_index=True)

# Save to the existing CSV
df.to_csv(file_path, index=False)

print("New swimming records added:", len(new_df))
print("Total records in dataset:", len(df))
print("Saved to:", file_path)

display(
    df[df["sport"].astype(str).str.lower() == "swimming"][
        [
            "event_date",
            "event_end_date",
            "event_name",
            "sport",
            "venue",
            "city",
        ]
    ].sort_values("event_date")
)

New swimming records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

    event_date event_end_date                                                                     event_name     sport                                                  venue          city
42  2023-07-02     2023-07-05                                76th Senior National Aquatic Championships 2023  Swimming  GMC Balayogi Sports Complex, Gachibowli Swimming Pool     Hyderabad
43  2023-07-29     2023-07-30  8th Telangana Sub-Junior and Junior Inter-District Swimming Championship 2023  Swimming                            HPS Swimming Pool, Begumpet     Hyderabad
44  2023-09-10     2023-09-10     23rd Annual Swimming Competition - Hyderabad District Swimming Association  Swimming         GMC Balayogi Stadium Swimming Pool, Gachibowli     Hyderabad
45  2024-05-19     2024-05-19                                         Swimming Championship Season II - 2024  Swimming                        GHMC Secunderabad Swimming Pool  Secunderabad
46  2026-05-17     2026-05-17                                                 4th Swimming Championship 2026  Swimming                           GHMC Swimming Pool, Amberpet     Hyderabad

In [100]:
import pandas as pd
from pathlib import Path

# Existing project dataset
file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

cycling_events = [
    {
        "event_date": "2023-05-07",
        "event_end_date": "2023-05-07",
        "event_name": "Palapitta Ride 2023 and Night Safari Park Ride",
        "sport": "Cycling",
        "event_start_time": None,
        "team_or_participants": "Community cyclists; nearly 1,000 participants reported",
        "venue": "Botanical Garden",
        "city": "Hyderabad",
        "event_level": "Community",
        "source_url": (
            "https://www.newindianexpress.com/cities/hyderabad/2023/May/07/"
            "palapitta-ride-2023-marks-launch-of-hyderabad-bicycling-club-2573043.html"
        ),
    },
    {
        "event_date": "2025-03-08",
        "event_end_date": "2025-03-08",
        "event_name": "Telangana Shero's Cyclothon 2025",
        "sport": "Cycling",
        "event_start_time": "05:00",
        "team_or_participants": "Women and girls; non-geared bicycle awareness ride",
        "venue": "Hyderabad; exact route/start point to be verified",
        "city": "Hyderabad",
        "event_level": "Community / Awareness",
        "source_url": "https://racemart.in/events/telangana-sheros-cyclothon",
    },
    {
        "event_date": "2025-11-09",
        "event_end_date": "2025-11-09",
        "event_name": "HCL Cyclothon Hyderabad 2025",
        "sport": "Cycling",
        "event_start_time": None,
        "team_or_participants": (
            "Professional and amateur cyclists; road race, MTB and green ride"
        ),
        "venue": "Prime Arena, Osman Nagar, Vattinagulapalle",
        "city": "Hyderabad",
        "event_level": "National / Professional and Amateur",
        "source_url": (
            "https://telanganatoday.com/over-1900-cyclists-compete-in-the-"
            "hcl-cyclothon-hyderabad-with-record-prize-pool"
        ),
    },
]

new_df = pd.DataFrame(cycling_events)

# Preserve existing column order
new_df = new_df[df.columns]

# Normalize dates
for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(df[col], errors="coerce").dt.strftime("%Y-%m-%d")
    new_df[col] = pd.to_datetime(
        new_df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Remove duplicates using event date, name, sport and venue
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

existing_keys = set(
    df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)
)

new_keys = new_df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)

new_df = new_df[~new_keys.isin(existing_keys)]

# Append new records
df = pd.concat([df, new_df], ignore_index=True)

# Save to the same CSV
df.to_csv(file_path, index=False)

print("New cycling records added:", len(new_df))
print("Total records in dataset:", len(df))
print("Saved to:", file_path)

display(
    df[df["sport"].astype(str).str.lower() == "cycling"][
        [
            "event_date",
            "event_end_date",
            "event_name",
            "sport",
            "venue",
            "city",
        ]
    ].sort_values("event_date")
)

New cycling records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

    event_date event_end_date                                      event_name    sport                                              venue       city
47  2023-05-07     2023-05-07  Palapitta Ride 2023 and Night Safari Park Ride  Cycling                                   Botanical Garden  Hyderabad
48  2025-03-08     2025-03-08                Telangana Shero's Cyclothon 2025  Cycling  Hyderabad; exact route/start point to be verified  Hyderabad
49  2025-11-09     2025-11-09                    HCL Cyclothon Hyderabad 2025  Cycling         Prime Arena, Osman Nagar, Vattinagulapalle  Hyderabad

In [101]:
import pandas as pd
from pathlib import Path

# Existing project dataset
file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

rowing_events = [
    {
        "event_date": "2023-11-18",
        "event_end_date": "2023-11-23",
        "event_name": "24th Sub-Junior National Rowing Championships",
        "sport": "Rowing",
        "event_start_time": None,
        "team_or_participants": "Sub-junior rowers; boys and girls",
        "venue": "Hussain Sagar Lake",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": (
            "https://www.indiarowing.com/admin/events_gallery/"
            "20231110190757124th%20SJ%20%26%206th%20ISCNRC-Hyderabad-2023-"
            "Jury%20%26%20TO%20Appointment.pdf"
        ),
    },
    {
        "event_date": "2023-11-18",
        "event_end_date": "2023-11-23",
        "event_name": (
            "6th Inter-State Challenger Sprint National Rowing Championships"
        ),
        "sport": "Rowing",
        "event_start_time": None,
        "team_or_participants": "Men and women; challenger sprint rowing crews",
        "venue": "Hussain Sagar Lake",
        "city": "Hyderabad",
        "event_level": "National / Inter-State",
        "source_url": (
            "https://www.indiarowing.com/admin/events_gallery/"
            "2023111018450516th%20ISCH-Hyderabad%202023-Bulletin%202.pdf"
        ),
    },
    {
        "event_date": "2024-12-27",
        "event_end_date": "2024-12-29",
        "event_name": "Chief Minister's Cup 2024 - Rowing",
        "sport": "Rowing",
        "event_start_time": None,
        "team_or_participants": "Male and female participants across listed age categories",
        "venue": "Water Sports venue, Hussain Sagar",
        "city": "Hyderabad",
        "event_level": "State",
        "source_url": (
            "https://www.cmcup2024.telangana.gov.in/public/frontend/images/"
            "schedules.pdf"
        ),
    },
    {
        "event_date": "2025-05-27",
        "event_end_date": "2025-06-01",
        "event_name": "26th Sub-Junior National Rowing Championships",
        "sport": "Rowing",
        "event_start_time": None,
        "team_or_participants": "Sub-junior rowers; under-13 and under-15 categories",
        "venue": "Telangana Water Sports Academy, Hussain Sagar Lake",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": (
            "https://www.indiarowing.com/admin/events_gallery/"
            "20250503190019126th%20SJN-Hyd-2025-Bulletin-ver%201%20dt%2019.04.25.pdf"
        ),
    },
]

new_df = pd.DataFrame(rowing_events)

# Match the existing CSV column order
new_df = new_df[df.columns]

# Normalize dates
for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(df[col], errors="coerce").dt.strftime("%Y-%m-%d")
    new_df[col] = pd.to_datetime(
        new_df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Avoid duplicates using event date, name, sport and venue
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

existing_keys = set(
    df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)
)

new_keys = new_df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)

new_df = new_df[~new_keys.isin(existing_keys)]

# Append new records and save to the same CSV
df = pd.concat([df, new_df], ignore_index=True)
df.to_csv(file_path, index=False)

print("New rowing records added:", len(new_df))
print("Total records in dataset:", len(df))
print("Saved to:", file_path)

display(
    df[df["sport"].astype(str).str.lower() == "rowing"][
        [
            "event_date",
            "event_end_date",
            "event_name",
            "sport",
            "venue",
            "city",
        ]
    ].sort_values("event_date")
)

New rowing records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

    event_date event_end_date                                                       event_name   sport                                               venue       city
50  2023-11-18     2023-11-23                    24th Sub-Junior National Rowing Championships  Rowing                                  Hussain Sagar Lake  Hyderabad
51  2023-11-18     2023-11-23  6th Inter-State Challenger Sprint National Rowing Championships  Rowing                                  Hussain Sagar Lake  Hyderabad
52  2024-12-27     2024-12-29                               Chief Minister's Cup 2024 - Rowing  Rowing                   Water Sports venue, Hussain Sagar  Hyderabad
53  2025-05-27     2025-06-01                    26th Sub-Junior National Rowing Championships  Rowing  Telangana Water Sports Academy, Hussain Sagar Lake  Hyderabad

In [102]:
import pandas as pd
from pathlib import Path

# Existing project dataset
file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

weightlifting_events = [
    {
        "event_date": "2023-04-15",
        "event_end_date": "2023-04-15",
        "event_name": (
            "Telangana Masters State and South India Masters "
            "Weightlifting Championships"
        ),
        "sport": "Weightlifting",
        "event_start_time": None,
        "team_or_participants": (
            "Masters men and women; age categories 30+ through 80+"
        ),
        "venue": "India Post Convention Centre",
        "city": "Hyderabad",
        "event_level": "State / South India",
        "source_url": (
            "https://telanganatoday.com/hyderabad-telangana-masters-"
            "weightlifting-championship-to-be-held-on-april-15"
        ),
    },
    {
        "event_date": "2024-12-27",
        "event_end_date": "2024-12-29",
        "event_name": "Chief Minister's Cup 2024 - Weightlifting",
        "sport": "Weightlifting",
        "event_start_time": None,
        "team_or_participants": "Telangana district-level participants",
        "venue": "LB Stadium",
        "city": "Hyderabad",
        "event_level": "State",
        "source_url": (
            "https://cmcup2024.telangana.gov.in/public/frontend/images/"
            "schedules.pdf"
        ),
    },
]

new_df = pd.DataFrame(weightlifting_events)

# Preserve existing column order
new_df = new_df[df.columns]

# Normalize dates
for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(
        df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

    new_df[col] = pd.to_datetime(
        new_df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Check for duplicates
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

existing_keys = set(
    df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)
)

new_keys = new_df[dedupe_cols].fillna("").astype(str).apply(tuple, axis=1)

new_df = new_df[~new_keys.isin(existing_keys)]

# Append new records
df = pd.concat([df, new_df], ignore_index=True)

# Save to the same CSV
df.to_csv(file_path, index=False)

print("New weightlifting records added:", len(new_df))
print("Total records in dataset:", len(df))
print("Saved to:", file_path)

display(
    df[df["sport"].astype(str).str.lower() == "weightlifting"][
        [
            "event_date",
            "event_end_date",
            "event_name",
            "sport",
            "venue",
            "city",
        ]
    ].sort_values("event_date")
)

New weightlifting records added: 0
Total records in dataset: 67
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

    event_date event_end_date                                                                   event_name          sport                         venue       city
54  2023-04-15     2023-04-15  Telangana Masters State and South India Masters Weightlifting Championships  Weightlifting  India Post Convention Centre  Hyderabad
55  2024-12-27     2024-12-29                                    Chief Minister's Cup 2024 - Weightlifting  Weightlifting                    LB Stadium  Hyderabad

In [103]:
import pandas as pd
from pathlib import Path

# ============================================================
# PROJECT CONFIGURATION
# ============================================================

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

START_DATE = pd.Timestamp("2023-01-01")
END_DATE = pd.Timestamp("2026-07-31")

if not file_path.exists():
    raise FileNotFoundError(f"Existing project CSV not found: {file_path}")

df = pd.read_csv(file_path)

required_columns = [
    "event_date",
    "event_end_date",
    "event_name",
    "sport",
    "event_start_time",
    "team_or_participants",
    "venue",
    "city",
    "event_level",
    "source_url",
]

if list(df.columns) != required_columns:
    raise ValueError(
        "The existing CSV schema does not match the expected 10 columns. "
        "No records were added. Check the column names before proceeding."
    )

initial_count = len(df)

# ============================================================
# CONSOLIDATED REMAINING SPORTS EVENTS
# Candidate records supported by published event listings
# ============================================================

remaining_events = [
    # --------------------------------------------------------
    # JUDO
    # --------------------------------------------------------
    {
        "event_date": "2025-11-16",
        "event_end_date": "2025-11-20",
        "event_name": "Sub-Junior National Judo Championships 2025-26",
        "sport": "Judo",
        "event_start_time": None,
        "team_or_participants": "Sub-junior boys and girls",
        "venue": "Lal Bahadur Indoor Stadium",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": "https://www.onlinejfi.org/event-details.php?id=3641",
    },
    {
        "event_date": "2025-10-22",
        "event_end_date": "2025-10-22",
        "event_name": "Osmania University Inter-College Judo Tournament 2025",
        "sport": "Judo",
        "event_start_time": None,
        "team_or_participants": "University-affiliated college judokas",
        "venue": "M J College of Engineering and Technology, Banjara Hills",
        "city": "Hyderabad",
        "event_level": "Inter-College",
        "source_url": "https://www.lords.ac.in/sports/events-attended/",
    },
    {
        "event_date": "2024-11-07",
        "event_end_date": "2024-11-07",
        "event_name": "Osmania University Inter-College Judo Tournament 2024",
        "sport": "Judo",
        "event_start_time": None,
        "team_or_participants": "University-affiliated college judokas",
        "venue": "ISL Engineering College, Chandrayangutta",
        "city": "Hyderabad",
        "event_level": "Inter-College",
        "source_url": "https://www.lords.ac.in/sports/events-attended/",
    },

    # --------------------------------------------------------
    # TAEKWONDO
    # --------------------------------------------------------
    {
        "event_date": "2025-01-28",
        "event_end_date": "2025-01-30",
        "event_name": (
            "40th National Senior Kyorugi and 13th National Senior "
            "Poomsae Taekwondo Championships 2024-25"
        ),
        "sport": "Taekwondo",
        "event_start_time": None,
        "team_or_participants": "Senior competitors; Kyorugi and Poomsae",
        "venue": "Kotla Vijay Bhaskar Reddy Indoor Stadium, Yousufguda",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": (
            "https://www.kihapp.com/tournaments/"
            "18291-40th-national-senior-kyorugi-13th-national-senior-poosae-taekwond"
        ),
    },

    # --------------------------------------------------------
    # TABLE TENNIS
    # --------------------------------------------------------
    {
        "event_date": "2024-10-27",
        "event_end_date": "2024-10-27",
        "event_name": "1st Telangana State Veterans Table Tennis Ranking Tournament 2024",
        "sport": "Table Tennis",
        "event_start_time": None,
        "team_or_participants": "Veteran table tennis players",
        "venue": "Little Flower High School, Abids",
        "city": "Hyderabad",
        "event_level": "State",
        "source_url": "https://www.telanganatabletennis.com/Veterans-Events.php",
    },
    {
        "event_date": "2024-12-01",
        "event_end_date": "2024-12-01",
        "event_name": "2nd Telangana State Veterans Table Tennis Ranking Tournament 2024",
        "sport": "Table Tennis",
        "event_start_time": None,
        "team_or_participants": "Veteran table tennis players",
        "venue": "Shree Gujarati Seva Mandal",
        "city": "Secunderabad",
        "event_level": "State",
        "source_url": "https://www.telanganatabletennis.com/Veterans-Events.php",
    },
    {
        "event_date": "2025-01-19",
        "event_end_date": "2025-01-19",
        "event_name": "Veteran Telangana State Table Tennis Championships 2024",
        "sport": "Table Tennis",
        "event_start_time": None,
        "team_or_participants": "Veteran table tennis players",
        "venue": "St. Paul's High School, Hyderguda",
        "city": "Hyderabad",
        "event_level": "State",
        "source_url": "https://www.telanganatabletennis.com/Veterans-Events.php",
    },
    {
        "event_date": "2025-10-15",
        "event_end_date": "2025-10-16",
        "event_name": "Osmania University Inter-College Table Tennis Tournament 2025",
        "sport": "Table Tennis",
        "event_start_time": None,
        "team_or_participants": "University-affiliated college players",
        "venue": "St. Joseph's Degree and PG College, King Koti",
        "city": "Hyderabad",
        "event_level": "Inter-College",
        "source_url": "https://www.lords.ac.in/sports/events-attended/",
    },

    # --------------------------------------------------------
    # HANDBALL
    # --------------------------------------------------------
    {
        "event_date": "2025-09-26",
        "event_end_date": "2025-09-29",
        "event_name": "17th HFI Mini Boys and Girls National Handball Championship",
        "sport": "Handball",
        "event_start_time": None,
        "team_or_participants": "Mini boys and girls national teams",
        "venue": "Nizam College",
        "city": "Hyderabad",
        "event_level": "National",
        "source_url": "https://handballfederationofindia.com/previous-events/",
    },

    # --------------------------------------------------------
    # KARATE
    # --------------------------------------------------------
    {
        "event_date": "2024-11-02",
        "event_end_date": "2024-11-02",
        "event_name": "Osmania University Inter-College Karate Tournament 2024",
        "sport": "Karate",
        "event_start_time": None,
        "team_or_participants": "University-affiliated college karate competitors",
        "venue": "Lords Institute of Engineering and Technology, Himayath Sagar",
        "city": "Hyderabad",
        "event_level": "Inter-College",
        "source_url": "https://www.lords.ac.in/sports/events-attended/",
    },

    # --------------------------------------------------------
    # ARCHERY
    # --------------------------------------------------------
    {
        "event_date": "2025-09-22",
        "event_end_date": "2025-09-22",
        "event_name": "Osmania University National Archery Selection Trials 2025",
        "sport": "Archery",
        "event_start_time": None,
        "team_or_participants": "University archery competitors",
        "venue": "Telangana Sports School, Hakimpet",
        "city": "Hyderabad",
        "event_level": "University Selection Trials",
        "source_url": "https://www.lords.ac.in/sports/events-attended/",
    },
]

new_df = pd.DataFrame(remaining_events)

# Match the existing schema exactly
new_df = new_df[required_columns]

# ============================================================
# NORMALIZE AND VALIDATE DATES
# ============================================================

for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(df[col], errors="coerce")
    new_df[col] = pd.to_datetime(new_df[col], errors="coerce")

# Retain only records whose dates fall within the study period
valid_date_mask = (
    new_df["event_date"].ge(START_DATE)
    & new_df["event_date"].le(END_DATE)
    & new_df["event_end_date"].ge(new_df["event_date"])
    & new_df["event_end_date"].le(END_DATE)
)

out_of_range_count = int((~valid_date_mask).sum())
new_df = new_df.loc[valid_date_mask].copy()

# Require key fields before insertion
required_values = [
    "event_date",
    "event_end_date",
    "event_name",
    "sport",
    "city",
    "source_url",
]

for col in required_values:
    new_df = new_df[
        new_df[col].notna()
        & new_df[col].astype(str).str.strip().ne("")
    ]

# ============================================================
# DUPLICATE CHECKING
# ============================================================

# Normalize date formats for consistent matching
for col in ["event_date", "event_end_date"]:
    df[col] = pd.to_datetime(df[col]).dt.strftime("%Y-%m-%d")
    new_df[col] = pd.to_datetime(new_df[col]).dt.strftime("%Y-%m-%d")

# Duplicate key based on date, name, sport and venue
dedupe_cols = ["event_date", "event_name", "sport", "venue"]

# Normalize whitespace and case in comparison keys
def make_keys(frame):
    normalized = frame[dedupe_cols].fillna("").astype(str)

    for col in dedupe_cols:
        normalized[col] = (
            normalized[col]
            .str.strip()
            .str.replace(r"\s+", " ", regex=True)
            .str.casefold()
        )

    return normalized.apply(tuple, axis=1)

existing_keys = set(make_keys(df))

new_df = new_df.loc[~make_keys(new_df).isin(existing_keys)].copy()

# Also remove duplicate rows within the proposed batch
new_df = new_df.drop_duplicates(subset=dedupe_cols, keep="first")

# ============================================================
# APPEND AND SAVE
# ============================================================

added_count = len(new_df)

df = pd.concat([df, new_df], ignore_index=True)

# Save to the SAME existing CSV
df.to_csv(file_path, index=False)

print("=" * 60)
print("CONSOLIDATED REMAINING SPORTS COLLECTION")
print("=" * 60)
print("Records before this batch:", initial_count)
print("New records added:", added_count)
print("Out-of-range records excluded:", out_of_range_count)
print("Total records in dataset:", len(df))
print("Sports represented in this batch:",
      ", ".join(sorted(new_df["sport"].dropna().unique())))
print("Saved to:", file_path)

display(
    new_df[
        [
            "event_date",
            "event_end_date",
            "event_name",
            "sport",
            "venue",
            "city",
            "source_url",
        ]
    ].sort_values(["event_date", "sport"])
)

print("\nCurrent record count by sport:")
display(
    df["sport"]
    .fillna("Unknown")
    .value_counts()
    .rename_axis("sport")
    .reset_index(name="record_count")
)

============================================================
CONSOLIDATED REMAINING SPORTS COLLECTION
============================================================
Records before this batch: 67
New records added: 0
Out-of-range records excluded: 0
Total records in dataset: 67
Sports represented in this batch:
Saved to: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv

Empty DataFrame
Columns: [event_date, event_end_date, event_name, sport, venue, city, source_url]
Index: []

Current record count by sport:

            sport  record_count
0         Running             5
1          Tennis             5
2        Swimming             5
3          Hockey             4
4        Football             4
5      Basketball             4
6          Boxing             4
7          Rowing             4
8    Table Tennis             4
9         Kabaddi             3
10      Badminton             3
11     Volleyball             3
12      Wrestling             3
13       Shooting             3
14        Cycling             3
15           Judo             3
16  Weightlifting             2
17    Multi-sport             1
18      Taekwondo             1
19       Handball             1
20         Karate             1
21        Archery             1

In [104]:

import pandas as pd
from pathlib import Path

# ============================================================
# 04.6.4 — DATA QUALITY VALIDATION
# Existing Hyderabad Other Sporting Events Dataset
# ============================================================

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

# Load existing dataset
df = pd.read_csv(file_path)

# Define project period
START_DATE = pd.Timestamp("2023-01-01")
END_DATE = pd.Timestamp("2026-07-31")

required_columns = [
    "event_date",
    "event_end_date",
    "event_name",
    "sport",
    "event_start_time",
    "team_or_participants",
    "venue",
    "city",
    "event_level",
    "source_url"
]

print("=" * 65)
print("OTHER SPORTING EVENTS — DATA QUALITY AUDIT")
print("=" * 65)

# 1. Dataset overview
print("\n1. DATASET OVERVIEW")
print("-" * 40)
print(f"Total records: {len(df)}")
print(f"Total columns: {len(df.columns)}")

missing_columns = [
    col for col in required_columns if col not in df.columns
]

if missing_columns:
    print("ERROR — Missing required columns:", missing_columns)
else:
    print("Required schema: PASS")

    # 2. Check missing values
    print("\n2. MISSING VALUES")
    print("-" * 40)

    missing_counts = df[required_columns].isna().sum()
    print(missing_counts[missing_counts > 0].to_string()
          if missing_counts.any() else "No null values found.")

    # Also detect blank text fields
    text_columns = [
        "event_name", "sport", "venue",
        "city", "event_level", "source_url"
    ]

    blank_counts = {}
    for col in text_columns:
        blank_counts[col] = (
            df[col].astype("string").str.strip().eq("").sum()
        )

    blank_counts = pd.Series(blank_counts)
    blank_counts = blank_counts[blank_counts > 0]

    print("\nBlank text fields:")
    print(blank_counts.to_string() if not blank_counts.empty
          else "No blank text fields found.")

    # 3. Validate dates
    print("\n3. DATE VALIDATION")
    print("-" * 40)

    for col in ["event_date", "event_end_date"]:
        df[col] = pd.to_datetime(df[col], errors="coerce")

    invalid_start = df["event_date"].isna().sum()
    invalid_end = df["event_end_date"].isna().sum()

    reversed_dates = (
        df["event_end_date"].notna()
        & df["event_date"].notna()
        & (df["event_end_date"] < df["event_date"])
    ).sum()

    out_of_period = (
        df["event_date"].notna()
        & (
            (df["event_date"] < START_DATE)
            | (df["event_date"] > END_DATE)
        )
    )

    print(f"Invalid event start dates: {invalid_start}")
    print(f"Invalid event end dates: {invalid_end}")
    print(f"End date before start date: {reversed_dates}")
    print(f"Records starting outside project period: {out_of_period.sum()}")

    # 4. Duplicate checks
    print("\n4. DUPLICATE CHECK")
    print("-" * 40)

    exact_duplicates = df.duplicated().sum()

    event_key = ["event_date", "event_name", "venue"]
    duplicate_event_keys = df.duplicated(
        subset=event_key, keep=False
    )

    print(f"Exact duplicate rows: {exact_duplicates}")
    print(
        "Rows sharing the same event date, name and venue: "
        f"{duplicate_event_keys.sum()}"
    )

    if duplicate_event_keys.any():
        print("\nReview these potential duplicate records:")
        print(
            df.loc[duplicate_event_keys, event_key]
            .sort_values(event_key)
            .to_string(index=False)
        )

    # 5. Source URL audit
    print("\n5. SOURCE URL AUDIT")
    print("-" * 40)

    urls = df["source_url"].fillna("").astype(str).str.strip()

    missing_urls = urls.eq("")
    invalid_url_format = ~urls.str.startswith(
        ("https://", "http://"), na=False
    ) & ~missing_urls

    print(f"Missing source URLs: {missing_urls.sum()}")
    print(f"URLs without http:// or https://: {invalid_url_format.sum()}")

    # 6. Geographic and sport summary
    print("\n6. CITY DISTRIBUTION")
    print("-" * 40)
    print(df["city"].value_counts(dropna=False).to_string())

    print("\n7. RECORD COUNT BY SPORT")
    print("-" * 40)
    print(
        df["sport"].value_counts(dropna=False)
        .to_string()
    )

    # 7. Final audit summary
    print("\n8. AUDIT SUMMARY")
    print("-" * 40)

    checks = {
        "Required columns present": not missing_columns,
        "No invalid start dates": invalid_start == 0,
        "No invalid end dates": invalid_end == 0,
        "No reversed event dates": reversed_dates == 0,
        "No start dates outside project period": out_of_period.sum() == 0,
        "No exact duplicate rows": exact_duplicates == 0,
        "All source URL fields populated": not missing_urls.any(),
    }

    for check, passed in checks.items():
        print(f"{'PASS' if passed else 'REVIEW'} — {check}")

    print("\n" + "=" * 65)
    print("AUDIT COMPLETE — ORIGINAL CSV WAS NOT MODIFIED")
    print("=" * 65)

=================================================================
OTHER SPORTING EVENTS — DATA QUALITY AUDIT
=================================================================

1. DATASET OVERVIEW
----------------------------------------
Total records: 67
Total columns: 10
Required schema: PASS

2. MISSING VALUES
----------------------------------------
event_start_time        65
team_or_participants     6

Blank text fields:
No blank text fields found.

3. DATE VALIDATION
----------------------------------------
Invalid event start dates: 0
Invalid event end dates: 0
End date before start date: 0
Records starting outside project period: 0

4. DUPLICATE CHECK
----------------------------------------
Exact duplicate rows: 0
Rows sharing the same event date, name and venue: 0

5. SOURCE URL AUDIT
----------------------------------------
Missing source URLs: 0
URLs without http:// or https://: 0

6. CITY DISTRIBUTION
----------------------------------------
city
Hyderabad       61
Secunderabad     6

7. RECORD COUNT BY SPORT
----------------------------------------
sport
Running          5
Tennis           5
Swimming         5
Hockey           4
Football         4
Basketball       4
Boxing           4
Rowing           4
Table Tennis     4
Kabaddi          3
Badminton        3
Volleyball       3
Wrestling        3
Shooting         3
Cycling          3
Judo             3
Weightlifting    2
Multi-sport      1
Taekwondo        1
Handball         1
Karate           1
Archery          1

8. AUDIT SUMMARY
----------------------------------------
PASS — Required columns present
PASS — No invalid start dates
PASS — No invalid end dates
PASS — No reversed event dates
PASS — No start dates outside project period
PASS — No exact duplicate rows
PASS — All source URL fields populated

=================================================================
AUDIT COMPLETE — ORIGINAL CSV WAS NOT MODIFIED
=================================================================

In [105]:

import pandas as pd
from pathlib import Path

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

# Find records needing review
review_mask = (
    df["event_start_time"].isna()
    | df["team_or_participants"].isna()
    | df["source_url"].isna()
)

review = df.loc[
    review_mask,
    [
        "event_date",
        "event_end_date",
        "event_name",
        "sport",
        "event_start_time",
        "team_or_participants",
        "venue",
        "city",
        "source_url"
    ]
].copy()

print("=" * 70)
print("SPORTING EVENTS — RECORDS REQUIRING REVIEW")
print("=" * 70)

print(f"Total records: {len(df)}")
print(f"Records requiring review: {len(review)}")

display(review.reset_index(drop=True))

print("\nMissing values by field:")
print(df[
    ["event_start_time", "team_or_participants", "source_url"]
].isna().sum())

print("\nOriginal CSV remains unchanged.")

======================================================================
SPORTING EVENTS — RECORDS REQUIRING REVIEW
======================================================================
Total records: 67
Records requiring review: 65

,event_date,event_end_date,event_name,sport,event_start_time,team_or_participants,venue,city,source_url
0,2023-01-01,2023-01-12,Gooncha 58th Nehru Senior Hockey Tournament (Men),Hockey,NaN,NaN,Secunderabad,Secunderabad,https://www.telanganahockey.org/national-events.php
1,2023-11-14,2023-11-25,Gooncha 59th Nehru Senior Hockey Tournament (Men),Hockey,NaN,NaN,Secunderabad,Secunderabad,https://www.telanganahockey.org/national-events.php
2,2024-02-26,2024-02-26,Pro Kabaddi League Season 10 — Eliminators,Kabaddi,NaN,NaN,Gachibowli Indoor Stadium,Hyderabad,https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad
3,2024-02-28,2024-02-28,Pro Kabaddi League Season 10 — Semi-finals,Kabaddi,NaN,NaN,Gachibowli Indoor Stadium,Hyderabad,https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad
4,2024-03-01,2024-03-01,Pro Kabaddi League Season 10 — Final,Kabaddi,NaN,NaN,Gachibowli Indoor Stadium,Hyderabad,https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad
...,...,...,...,...,...,...,...,...,...
60,2025-01-19,2025-01-19,Veteran Telangana State Table Tennis Championships 2024,Table Tennis,NaN,Veteran table tennis players,"St. Paul's High School, Hyderguda",Hyderabad,https://www.telanganatabletennis.com/Veterans-Events.php
61,2025-10-15,2025-10-16,Osmania University Inter-College Table Tennis Tournament 2025,Table Tennis,NaN,University-affiliated college players,"St. Joseph's Degree and PG College, King Koti",Hyderabad,https://www.lords.ac.in/sports/events-attended/
62,2025-09-26,2025-09-29,17th HFI Mini Boys and Girls National Handball Championship,Handball,NaN,Mini boys and girls national teams,Nizam College,Hyderabad,https://handballfederationofindia.com/previous-events/
63,2024-11-02,2024-11-02,Osmania University Inter-College Karate Tournament 2024,Karate,NaN,University-affiliated college karate competitors,"Lords Institute of Engineering and Technology, Himayath Sagar",Hyderabad,https://www.lords.ac.in/sports/events-attended/
64,2025-09-22,2025-09-22,Osmania University National Archery Selection Trials 2025,Archery,NaN,University archery competitors,"Telangana Sports School, Hakimpet",Hyderabad,https://www.lords.ac.in/sports/events-attended/

Missing values by field:
event_start_time        65
team_or_participants     6
source_url               0
dtype: int64

Original CSV remains unchanged.

In [106]:

import pandas as pd
from pathlib import Path

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

time_missing = df["event_start_time"].isna()
participants_missing = df["team_or_participants"].isna()

print("=" * 70)
print("MISSING DATA CLASSIFICATION")
print("=" * 70)

print(f"Total records: {len(df)}")
print(f"Missing start time: {time_missing.sum()}")
print(f"Missing participants: {participants_missing.sum()}")
print(
    "Missing both fields: "
    f"{(time_missing & participants_missing).sum()}"
)
print(
    "Missing time only: "
    f"{(time_missing & ~participants_missing).sum()}"
)
print(
    "Missing participants only: "
    f"{(~time_missing & participants_missing).sum()}"
)
print(
    "Neither field missing: "
    f"{(~time_missing & ~participants_missing).sum()}"
)

print("\nSPORT-WISE MISSING START TIMES")
print("-" * 70)

summary = (
    df.assign(time_missing=time_missing)
      .groupby("sport", dropna=False)
      .agg(
          total_records=("event_name", "size"),
          missing_times=("time_missing", "sum")
      )
      .sort_values("missing_times", ascending=False)
)

display(summary)

print("\nORIGINAL CSV REMAINS UNCHANGED.")

======================================================================
MISSING DATA CLASSIFICATION
======================================================================
Total records: 67
Missing start time: 65
Missing participants: 6
Missing both fields: 6
Missing time only: 59
Missing participants only: 0
Neither field missing: 2

SPORT-WISE MISSING START TIMES
----------------------------------------------------------------------

               total_records  missing_times
sport
Swimming                   5              5
Running                    5              5
Tennis                     5              5
Hockey                     4              4
Football                   4              4
Boxing                     4              4
Rowing                     4              4
Table Tennis               4              4
Badminton                  3              3
Basketball                 4              3
Wrestling                  3              3
Volleyball                 3              3
Kabaddi                    3              3
Judo                       3              3
Shooting                   3              3
Cycling                    3              2
Weightlifting              2              2
Archery                    1              1
Karate                     1              1
Multi-sport                1              1
Handball                   1              1
Taekwondo                  1              1

ORIGINAL CSV REMAINS UNCHANGED.

In [107]:

import pandas as pd
from pathlib import Path

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

print("=" * 65)
print("04.6.5 — DUPLICATE EVENT INVESTIGATION")
print("=" * 65)

# Check exact duplicate rows
exact_duplicates = df[df.duplicated(keep=False)]

print(f"\nExact duplicate rows: {df.duplicated().sum()}")

# Check potential duplicate events using date, name and venue
event_key = ["event_date", "event_name", "venue"]

potential_duplicates = df[
    df.duplicated(subset=event_key, keep=False)
].sort_values(event_key)

print(
    "Rows sharing the same event date, name and venue:",
    len(potential_duplicates)
)

if not exact_duplicates.empty:
    print("\nEXACT DUPLICATES:")
    display(exact_duplicates)

if not potential_duplicates.empty:
    print("\nPOTENTIAL EVENT DUPLICATES:")
    display(potential_duplicates)
else:
    print("\nNo duplicate event keys detected.")

print("\nSPORT-WISE RECORD COUNTS:")
display(
    df["sport"]
    .value_counts()
    .rename_axis("sport")
    .reset_index(name="record_count")
)

print("\nOriginal CSV remains unchanged.")

=================================================================
04.6.5 — DUPLICATE EVENT INVESTIGATION
=================================================================

Exact duplicate rows: 0
Rows sharing the same event date, name and venue: 0

No duplicate event keys detected.

SPORT-WISE RECORD COUNTS:

            sport  record_count
0         Running             5
1          Tennis             5
2        Swimming             5
3          Hockey             4
4        Football             4
5      Basketball             4
6          Boxing             4
7          Rowing             4
8    Table Tennis             4
9         Kabaddi             3
10      Badminton             3
11     Volleyball             3
12      Wrestling             3
13       Shooting             3
14        Cycling             3
15           Judo             3
16  Weightlifting             2
17    Multi-sport             1
18      Taekwondo             1
19       Handball             1
20         Karate             1
21        Archery             1

Original CSV remains unchanged.

In [108]:

import pandas as pd
import requests
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

# ============================================================
# 04.6.6 — SOURCE URL ACCESSIBILITY CHECK
# Original CSV remains unchanged
# ============================================================

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\sporting_events\hyderabad_other_sporting_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

urls = df["source_url"].dropna().astype(str).str.strip()
unique_urls = sorted(url for url in urls.unique() if url)

print("=" * 65)
print("04.6.6 — SOURCE URL ACCESSIBILITY CHECK")
print("=" * 65)
print(f"Dataset records: {len(df)}")
print(f"Unique URLs to check: {len(unique_urls)}")

def check_url(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; ResearchDataAudit/1.0)"
    }

    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=15,
            allow_redirects=True
        )

        return {
            "source_url": url,
            "status_code": response.status_code,
            "accessible": 200 <= response.status_code < 400,
            "final_url": response.url,
            "error": ""
        }

    except requests.RequestException as e:
        return {
            "source_url": url,
            "status_code": None,
            "accessible": False,
            "final_url": "",
            "error": str(e)[:180]
        }

results = []

with ThreadPoolExecutor(max_workers=5) as executor:
    futures = {
        executor.submit(check_url, url): url
        for url in unique_urls
    }

    for future in as_completed(futures):
        results.append(future.result())

url_audit = pd.DataFrame(results).sort_values("source_url")

print("\nURL ACCESSIBILITY SUMMARY")
print("-" * 65)
print(f"Accessible URLs: {url_audit['accessible'].sum()}")
print(f"URLs needing review: {(~url_audit['accessible']).sum()}")

print("\nURL CHECK RESULTS")
display(url_audit.reset_index(drop=True))

print("\nNOTE:")
print("An accessible URL does not prove that its event details are accurate.")
print("Blocked requests may also occur for legitimate websites.")
print("\nOriginal CSV remains unchanged.")

=================================================================
04.6.6 — SOURCE URL ACCESSIBILITY CHECK
=================================================================
Dataset records: 67
Unique URLs to check: 56

URL ACCESSIBILITY SUMMARY
-----------------------------------------------------------------
Accessible URLs: 50
URLs needing review: 6

URL CHECK RESULTS

,source_url,status_code,accessible,final_url,error
0,https://aistatennis.com/tournament.php?eid=11&tid=100,200.0,True,https://aistatennis.com/tournament.php?eid=11&tid=100,
1,https://aitatennis.com/aitaors/public/storage/data/factsheet/TS7_factsheet_1736146829.pdf,404.0,False,https://www.aitatennis.com/aitaors/public/storage/data/factsheet/TS7_factsheet_1736146829.pdf,
2,https://bdfi.in/events/bdfi-7th-u12-sub-junior-junior-youth-senior-men-women-national-boxing-championship-2024-on-25-april-2025-to-28-april-2025-held-at-sports-complex-secunderabad-telangana-legacy-50,200.0,True,https://bdfi.in/events/bdfi-7th-u12-sub-junior-junior-youth-senior-men-women-national-boxing-championship-2024-on-25-april-2025-to-28-april-2025-held-at-sports-complex-secunderabad-telangana-legacy-50,
3,https://boxingfederation.in/elite-women-tournament-2025/,200.0,True,https://boxingfederation.in/elite-women-tournament-2025/,
4,https://bwtaitaprod.blob.core.windows.net/aitaors-files/data/factsheet/2.5LAC_factsheet_1723182764.pdf,403.0,False,https://bwtaitaprod.blob.core.windows.net/aitaors-files/data/factsheet/2.5LAC_factsheet_1723182764.pdf,
5,https://cmcup2024.telangana.gov.in/public/frontend/images/schedules.pdf,NaN,False,,"HTTPSConnectionPool(host='cmcup2024.telangana.gov.in', port=443): Max retries exceeded with url: /public/frontend/images/schedules.pdf (Caused by SSLError(SSLCertVerificationError("
6,https://events.telanganarunners.com/,200.0,True,https://events.telanganarunners.com/,
7,https://handballfederationofindia.com/previous-events/,200.0,True,https://handballfederationofindia.com/previous-events/,
8,https://hydopen.com/announcements/,200.0,True,https://hydopen.com/announcements/,
9,https://incredibleboxing.com/events/,NaN,False,,"HTTPSConnectionPool(host='incredibleboxing.com', port=443): Max retries exceeded with url: /events/ (Caused by NameResolutionError(""HTTPSConnection(host='incredibleboxing.com', por"
10,https://khelkhiladis.com/hyderabad-wrestling-at-barkas-pg-on-june-23-24/,200.0,True,https://khelkhiladis.com/hyderabad-wrestling-at-barkas-pg-on-june-23-24/,
11,https://meraevents.com/events/4th-swimming-championship-2026,200.0,True,https://meraevents.com/events/4th-swimming-championship-2026,
12,https://munsifdaily.com/telangana-state-wrestling-championship-2024-wrestlers-selected-for-national-championship/,200.0,True,https://munsifdaily.com/telangana-state-wrestling-championship-2024-wrestlers-selected-for-national-championship/,
13,https://munsifdaily.com/telangana-sub-junior-junior-inter-district-swimming-championship-2023/,200.0,True,https://munsifdaily.com/telangana-sub-junior-junior-inter-district-swimming-championship-2023/,
14,https://racemart.in/events/telangana-sheros-cyclothon,200.0,True,https://racemart.in/events/telangana-sheros-cyclothon,
15,https://telanganabasketballassociation.com/events/69d2b5a9dff568f5fa71c63c,200.0,True,https://telanganabasketballassociation.com/events/69d2b5a9dff568f5fa71c63c,
16,https://telanganabasketballassociation.com/tournaments/leagues,200.0,True,https://telanganabasketballassociation.com/tournaments/leagues,
17,https://telanganatoday.com/hyderabad-black-hawks-invite-ktr-for-prime-volleyball-league-home-matches,200.0,True,https://telanganatoday.com/hyderabad-black-hawks-invite-ktr-for-prime-volleyball-league-home-matches,
18,https://telanganatoday.com/hyderabad-telangana-masters-weightlifting-championship-to-be-held-on-april-15,200.0,True,https://telanganatoday.com/hyderabad-telangana-masters-weightlifting-championship-to-be-held-on-april-15,
19,https://telanganatoday.com/over-1900-cyclists-compete-in-the-hcl-cyclothon-hyderabad-with-record-prize-pool,200.0,True,https://telanganatoday.com/over-1900-cyclists-compete-in-the-hcl-cyclothon-hyderabad-with-record-prize-pool,
20,https://telanganatoday.com/prime-volleyball-league-hyderabad-black-hawks-confident-of-good-show-in-front-of-home-crowd,200.0,True,https://telanganatoday.com/prime-volleyball-league-hyderabad-black-hawks-confident-of-good-show-in-front-of-home-crowd,
21,https://telanganatoday.com/vd-black-hawks-volleyball-tournament-from-january-19,200.0,True,https://telanganatoday.com/vd-black-hawks-volleyball-tournament-from-january-19,
22,https://thenrai.in/details.aspx?view=6027,200.0,True,https://thenrai.in/details.aspx?view=6027,
23,https://tstatennis.kloudportal.com/wp-content/uploads/2025/10/factsheet_1759232362.pdf,200.0,True,https://tstatennis.kloudportal.com/wp-content/uploads/2025/10/factsheet_1759232362.pdf,
24,https://www.badmintonindia.org/download/calender/BAI%20Calendar%202024-25.pdf,200.0,True,https://www.badmintonindia.org/download/calender/BAI%20Calendar%202024-25.pdf,
25,https://www.badmintonindia.org/download/calender/BAI%20Calendar%202025-26%20as%20on%2021-08-2025.pdf,200.0,True,https://www.badmintonindia.org/download/calender/BAI%20Calendar%202025-26%20as%20on%2021-08-2025.pdf,
26,https://www.badmintonindia.org/download/tournaments/BAI%20Circular%20-%20All%20India%20Senior%20Ranking%202025%20at%20Hyderabad.pdf,200.0,True,https://www.badmintonindia.org/download/tournaments/BAI%20Circular%20-%20All%20India%20Senior%20Ranking%202025%20at%20Hyderabad.pdf,
27,https://www.basketballfederationindia.org/national-calender/,200.0,True,https://www.basketballfederationindia.org/national-calender/,
28,https://www.cmcup2024.telangana.gov.in/public/frontend/images/schedules.pdf,NaN,False,,"HTTPSConnectionPool(host='www.cmcup2024.telangana.gov.in', port=443): Max retries exceeded with url: /public/frontend/images/schedules.pdf (Caused by SSLError(SSLCertVerificationEr"
29,https://www.hockeyindia.org/news/tickets-for-fih-hockey-world-cup-2026-qualifiers-hyderabad-telangana-go-live-today,200.0,True,https://www.hockeyindia.org/news/tickets-for-fih-hockey-world-cup-2026-qualifiers-hyderabad-telangana-go-live-today,
30,https://www.hockeyindia.org/technical/certificates-details,200.0,True,https://www.hockeyindia.org/technical/certificates-details,
31,https://www.hyderabadrunners.com/wp-content/uploads/2024/10/August-2024-News-Letter-Hyderabad-Runers.pdf,200.0,True,https://www.hyderabadrunners.com/wp-content/uploads/2024/10/August-2024-News-Letter-Hyderabad-Runers.pdf,
32,https://www.hyderabadrunners.com/wp-content/uploads/2025/10/HyderabadRunners_oct9th.pdf,200.0,True,https://www.hyderabadrunners.com/wp-content/uploads/2025/10/HyderabadRunners_oct9th.pdf,
33,https://www.indianboxingcouncil.com/,200.0,True,https://www.indianboxingcouncil.com/,
34,https://www.indiarowing.com/admin/events_gallery/2023111018450516th%20ISCH-Hyderabad%202023-Bulletin%202.pdf,200.0,True,https://www.indiarowing.com/admin/events_gallery/2023111018450516th%20ISCH-Hyderabad%202023-Bulletin%202.pdf,
35,https://www.indiarowing.com/admin/events_gallery/20231110190757124th%20SJ%20%26%206th%20ISCNRC-Hyderabad-2023-Jury%20%26%20TO%20Appointment.pdf,200.0,True,https://www.indiarowing.com/admin/events_gallery/20231110190757124th%20SJ%20%26%206th%20ISCNRC-Hyderabad-2023-Jury%20%26%20TO%20Appointment.pdf,
36,https://www.indiarowing.com/admin/events_gallery/20250503190019126th%20SJN-Hyd-2025-Bulletin-ver%201%20dt%2019.04.25.pdf,200.0,True,https://www.indiarowing.com/admin/events_gallery/20250503190019126th%20SJN-Hyd-2025-Bulletin-ver%201%20dt%2019.04.25.pdf,
37,https://www.jhpublicschool.com/sports-achievements/,200.0,True,https://www.jhpublicschool.com/sports-achievements/,
38,https://www.kihapp.com/tournaments/18291-40th-national-senior-kyorugi-13th-national-senior-poosae-taekwond,200.0,True,https://www.kihapp.com/tournaments/18291-40th-national-senior-kyorugi-13th-national-senior-poosae-taekwond,
39,https://www.lords.ac.in/sports/events-attended/,200.0,True,https://www.lords.ac.in/sports/events-attended/,
40,https://www.marathonhyderabad.com/frequently-asked-questions/,200.0,True,https://nmdchyderabadmarathon.com/,
41,https://www.newindianexpress.com/cities/hyderabad/2023/May/07/palapitta-ride-2023-marks-launch-of-hyderabad-bicycling-club-2573043.html,200.0,True,https://www.newindianexpress.com/cities/hyderabad/2023/May/07/palapitta-ride-2023-marks-launch-of-hyderabad-bicycling-club-2573043.html,
42,https://www.onlinejfi.org/event-details.php?id=3641,200.0,True,https://www.onlinejfi.org/event-details.php?id=3641,
43,https://www.osmania.ac.in/News2025/ICT%28W%29%20Basketball%202025-26.pdf,NaN,False,,"HTTPSConnectionPool(host='www.osmania.ac.in', port=443): Max retries exceeded with url: /News2025/ICT%28W%29%20Basketball%202025-26.pdf (Caused by SSLError(SSLCertVerificationError"
44,https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad,200.0,True,https://www.prokabaddi.com/news/pro-kabaddi-league-season-10-playoffs-and-final-to-be-held-in-hyderabad,
45,https://www.siasat.com/hyderabad-hosts-national-wrestling-championship-at-barkas-playground-3328027/,200.0,True,https://www.siasat.com/hyderabad-hosts-national-wrestling-championship-at-barkas-playground-3328027/,
46,https://www.swimming.org.in/wp-content/uploads/2023/04/76th-Senior-National-Aquatic-Championship-2023_Circular.pdf,200.0,True,https://www.swimming.org.in/wp-content/uploads/2023/04/76th-Senior-National-Aquatic-Championship-2023_Circular.pdf,
47,https://www.telanganahockey.org/national-events.php,200.0,True,https://www.telanganahockey.org/national-events.php,
48,https://www.telanganatabletennis.com/Veterans-Events.php,200.0,True,https://www.telanganatabletennis.com/Veterans-Events,
49,https://www.the-aiff.com/article/syria-breach-blue-tigers-den-to-take-home-intercontinental-cup,200.0,True,https://www.the-aiff.com/article/syria-breach-blue-tigers-den-to-take-home-intercontinental-cup,
50,https://www.the-aiff.com/competitions/heroic,200.0,True,https://www.the-aiff.com/competitions/heroic,
51,https://www.the-aiff.com/index.php/article/hyderabad-fc-earn-first-point-after-gruelling-draw-against-chennaiyin-fc,200.0,True,https://www.the-aiff.com/index.php/article/hyderabad-fc-earn-first-point-after-gruelling-draw-against-chennaiyin-fc,
52,https://www.the-aiff.com/index.php/article/manolos-men-held-by-mauritius-in-intercontinental-cup-opener,200.0,True,https://www.the-aiff.com/index.php/article/manolos-men-held-by-mauritius-in-intercontinental-cup-opener,
53,https://www.townscript.com/e/swimming-championship-2025-season-iii-301240,200.0,True,https://www.townscript.com/e/swimming-championship-2025-season-iii-301240,
54,https://www.tsra.in/pdfs/Circular%20XI%20Telangana%20StateShooting%20Championship%20Competitions%20-%202025.pdf,200.0,True,https://www.tsra.in/pdfs/Circular%20XI%20Telangana%20StateShooting%20Championship%20Competitions%20-%202025.pdf,
55,https://www.tsra.in/pdfs/Circular-%20IX%20Telangana%20State%20Shooting%20Championship%20Competitions%20-%202023.pdf,200.0,True,https://www.tsra.in/pdfs/Circular-%20IX%20Telangana%20State%20Shooting%20Championship%20Competitions%20-%202023.pdf,

NOTE:
An accessible URL does not prove that its event details are accurate.
Blocked requests may also occur for legitimate websites.

Original CSV remains unchanged.

In [109]:

# ============================================================
# 04.6.7 — REVIEW FAILED SOURCE URLS
# ============================================================

failed_urls = (
    url_audit.loc[
        ~url_audit["accessible"],
        ["source_url", "status_code", "final_url", "error"]
    ]
    .reset_index(drop=True)
)

print("=" * 70)
print("04.6.7 — SOURCE URLS REQUIRING REVIEW")
print("=" * 70)

print(f"URLs requiring review: {len(failed_urls)}")

display(failed_urls)

print("\nNo network requests made in this step.")
print("Original CSV remains unchanged.")

======================================================================
04.6.7 — SOURCE URLS REQUIRING REVIEW
======================================================================
URLs requiring review: 6

,source_url,status_code,final_url,error
0,https://aitatennis.com/aitaors/public/storage/data/factsheet/TS7_factsheet_1736146829.pdf,404.0,https://www.aitatennis.com/aitaors/public/storage/data/factsheet/TS7_factsheet_1736146829.pdf,
1,https://bwtaitaprod.blob.core.windows.net/aitaors-files/data/factsheet/2.5LAC_factsheet_1723182764.pdf,403.0,https://bwtaitaprod.blob.core.windows.net/aitaors-files/data/factsheet/2.5LAC_factsheet_1723182764.pdf,
2,https://cmcup2024.telangana.gov.in/public/frontend/images/schedules.pdf,NaN,,"HTTPSConnectionPool(host='cmcup2024.telangana.gov.in', port=443): Max retries exceeded with url: /public/frontend/images/schedules.pdf (Caused by SSLError(SSLCertVerificationError("
3,https://incredibleboxing.com/events/,NaN,,"HTTPSConnectionPool(host='incredibleboxing.com', port=443): Max retries exceeded with url: /events/ (Caused by NameResolutionError(""HTTPSConnection(host='incredibleboxing.com', por"
4,https://www.cmcup2024.telangana.gov.in/public/frontend/images/schedules.pdf,NaN,,"HTTPSConnectionPool(host='www.cmcup2024.telangana.gov.in', port=443): Max retries exceeded with url: /public/frontend/images/schedules.pdf (Caused by SSLError(SSLCertVerificationEr"
5,https://www.osmania.ac.in/News2025/ICT%28W%29%20Basketball%202025-26.pdf,NaN,,"HTTPSConnectionPool(host='www.osmania.ac.in', port=443): Max retries exceeded with url: /News2025/ICT%28W%29%20Basketball%202025-26.pdf (Caused by SSLError(SSLCertVerificationError"

No network requests made in this step.
Original CSV remains unchanged.

In [110]:

# ============================================================
# 04.6.8 — MAP FAILED URLS TO SPORTING EVENTS
# Read-only inspection
# ============================================================

failed_urls = url_audit.loc[
    ~url_audit["accessible"]
].copy()

for number, row in enumerate(
    failed_urls.itertuples(index=False),
    start=1
):
    print(f"\n{'=' * 70}")
    print(f"SOURCE {number}")
    print(f"HTTP status: {row.status_code}")
    print(f"Error: {row.error}")
    print(f"Original URL: {row.source_url}")
    print(f"Final URL: {row.final_url}")

    matching_events = df[
        df["source_url"].astype(str).str.strip()
        == str(row.source_url).strip()
    ]

    print("\nAssociated sporting events:")

    display(
        matching_events[
            [
                "event_date",
                "event_end_date",
                "event_name",
                "sport",
                "venue",
                "city",
                "source_url"
            ]
        ].reset_index(drop=True)
    )

print("\nOriginal CSV remains unchanged.")

======================================================================
SOURCE 1
HTTP status: 404.0
Error:
Original URL: https://aitatennis.com/aitaors/public/storage/data/factsheet/TS7_factsheet_1736146829.pdf
Final URL: https://www.aitatennis.com/aitaors/public/storage/data/factsheet/TS7_factsheet_1736146829.pdf

Associated sporting events:

,event_date,event_end_date,event_name,sport,venue,city,source_url
0,2025-01-13,2025-01-17,SITE Sports Junior Tennis Tournament - U-12,Tennis,Not specified in tournament factsheet,Hyderabad,https://aitatennis.com/aitaors/public/storage/data/factsheet/TS7_factsheet_1736146829.pdf

======================================================================
SOURCE 2
HTTP status: 403.0
Error:
Original URL: https://bwtaitaprod.blob.core.windows.net/aitaors-files/data/factsheet/2.5LAC_factsheet_1723182764.pdf
Final URL: https://bwtaitaprod.blob.core.windows.net/aitaors-files/data/factsheet/2.5LAC_factsheet_1723182764.pdf

Associated sporting events:

,event_date,event_end_date,event_name,sport,venue,city,source_url
0,2024-09-02,2024-09-07,AITA Women Rs 2.5 Lakh Tennis Tournament,Tennis,Not specified in tournament factsheet,Hyderabad,https://bwtaitaprod.blob.core.windows.net/aitaors-files/data/factsheet/2.5LAC_factsheet_1723182764.pdf

======================================================================
SOURCE 3
HTTP status: nan
Error: HTTPSConnectionPool(host='cmcup2024.telangana.gov.in', port=443): Max retries exceeded with url: /public/frontend/images/schedules.pdf (Caused by SSLError(SSLCertVerificationError(
Original URL: https://cmcup2024.telangana.gov.in/public/frontend/images/schedules.pdf
Final URL:

Associated sporting events:

   event_date event_end_date                                 event_name          sport       venue       city                                                               source_url
0  2024-12-27     2024-12-29  Chief Minister's Cup 2024 - Weightlifting  Weightlifting  LB Stadium  Hyderabad  https://cmcup2024.telangana.gov.in/public/frontend/images/schedules.pdf

======================================================================
SOURCE 4
HTTP status: nan
Error: HTTPSConnectionPool(host='incredibleboxing.com', port=443): Max retries exceeded with url: /events/ (Caused by NameResolutionError("HTTPSConnection(host='incredibleboxing.com', por
Original URL: https://incredibleboxing.com/events/
Final URL:

Associated sporting events:

   event_date event_end_date                                    event_name   sport                   venue       city                            source_url
0  2025-08-31     2025-08-31  The Toughman - KR Steven Boxing Championship  Boxing  LB Stadium Boxing Hall  Hyderabad  https://incredibleboxing.com/events/

======================================================================
SOURCE 5
HTTP status: nan
Error: HTTPSConnectionPool(host='www.cmcup2024.telangana.gov.in', port=443): Max retries exceeded with url: /public/frontend/images/schedules.pdf (Caused by SSLError(SSLCertVerificationEr
Original URL: https://www.cmcup2024.telangana.gov.in/public/frontend/images/schedules.pdf
Final URL:

Associated sporting events:

   event_date event_end_date                          event_name   sport                              venue       city                                                                   source_url
0  2024-12-27     2024-12-29  Chief Minister's Cup 2024 - Rowing  Rowing  Water Sports venue, Hussain Sagar  Hyderabad  https://www.cmcup2024.telangana.gov.in/public/frontend/images/schedules.pdf

======================================================================
SOURCE 6
HTTP status: nan
Error: HTTPSConnectionPool(host='www.osmania.ac.in', port=443): Max retries exceeded with url: /News2025/ICT%28W%29%20Basketball%202025-26.pdf (Caused by SSLError(SSLCertVerificationError
Original URL: https://www.osmania.ac.in/News2025/ICT%28W%29%20Basketball%202025-26.pdf
Final URL:

Associated sporting events:

,event_date,event_end_date,event_name,sport,venue,city,source_url
0,2025-09-16,2025-09-17,Osmania University Inter-College Basketball Tournament for Women 2025,Basketball,"St. Francis Degree College, Begumpet",Hyderabad,https://www.osmania.ac.in/News2025/ICT%28W%29%20Basketball%202025-26.pdf

Original CSV remains unchanged.

# Phase 04.6 — Collect Other Sporting Events

## 1. Objective

Collect sporting-event data for Hyderabad and Secunderabad, Telangana, covering **January 1, 2023, to July 31, 2026**, to support the contextual features of the Hyperlocal Food Demand and Surge Forecasting project.

Cricket data is handled separately and is excluded from this phase.

## 2. Dataset Details

| Attribute         | Details                               |
| ----------------- | ------------------------------------- |
| Dataset name      | Hyderabad Other Sporting Events       |
| Total records     | 67                                    |
| Number of columns | 10                                    |
| Geographic scope  | Hyderabad and Secunderabad, Telangana |
| Start date        | January 1, 2023                       |
| End date          | July 31, 2026                         |
| File format       | CSV                                   |
| Collection status | Complete for this phase               |
| Validation status | Preliminary validation completed      |

### Dataset Location

```text
data/raw/sporting_events/
└── hyderabad_other_sporting_events_2023_2026.csv
```

The existing CSV was updated during collection. Validation and inspection steps did not modify the original dataset.

## 3. Dataset Schema

The dataset contains the following 10 columns:

| Column                 | Description                               |
| ---------------------- | ----------------------------------------- |
| `event_date`           | Event start date                          |
| `event_end_date`       | Event end date                            |
| `event_name`           | Name of the sporting event                |
| `sport`                | Sport category                            |
| `event_start_time`     | Event start time, where available         |
| `team_or_participants` | Participating teams or individuals        |
| `venue`                | Event venue                               |
| `city`                 | Recorded city                             |
| `event_level`          | Event classification or competition level |
| `source_url`           | Reference URL associated with the event   |

## 4. Sports Covered

The dataset represents 22 sport categories, including:

* Hockey
* Kabaddi
* Football
* Badminton
* Running
* Basketball
* Volleyball
* Wrestling
* Boxing
* Shooting
* Tennis
* Swimming
* Cycling
* Rowing
* Weightlifting
* Judo
* Taekwondo
* Table Tennis
* Handball
* Karate
* Archery
* Multi-sport events

The dataset includes selected competitions, tournaments, and sporting events recorded within the project's geographic and temporal scope.

## 5. Data Validation Results

The following preliminary validation checks were completed.

| Validation check                                   |   Result | Status    |
| -------------------------------------------------- | -------: | --------- |
| Total records                                      |       67 | Completed |
| Required columns present                           | 10 of 10 | Passed    |
| Invalid event start dates                          |        0 | Passed    |
| Invalid event end dates                            |        0 | Passed    |
| Event end date before start date                   |        0 | Passed    |
| Event start dates outside the project period       |        0 | Passed    |
| Exact duplicate rows                               |        0 | Passed    |
| Duplicate event date, name, and venue combinations |        0 | Passed    |
| Records with missing source URLs                   |        0 | Passed    |

These results apply to the checks performed and do not establish that every event detail has been independently verified.

## 6. Missing-Data Assessment

The missing-data investigation identified the following issues:

| Field                  | Missing records |
| ---------------------- | --------------: |
| `event_start_time`     |              65 |
| `team_or_participants` |               6 |
| Both fields missing    |               6 |
| Time missing only      |              59 |
| Neither field missing  |               2 |

Missing event times have not been filled with assumed values.

Exact start times should be added only when they can be supported by reliable sources. For multi-day competitions, the event date and end date may be available even when an individual match or session time is unknown.

Missing participant details should likewise be recovered only when reliable information is available.

## 7. Source URL Accessibility

A programmatic accessibility check was performed on the unique source URLs.

| Metric                                     |              Result |
| ------------------------------------------ | ------------------: |
| Unique URLs checked                        |                  56 |
| URLs returning an accessible HTTP response |                  50 |
| URLs requiring review                      |                   6 |
| Accessibility rate                         | Approximately 89.3% |

The six URLs requiring review included:

* One HTTP 404 response.
* One HTTP 403 response.
* Four connection errors, including SSL certificate verification and DNS/connection failures.

An accessible URL does not guarantee that its contents support the associated event details. Likewise, a failed automated request does not necessarily mean that a legitimate source is unavailable.

**Source verification remains incomplete.** The event names, dates, venues, and locations should be independently checked against authoritative sources before the dataset is described as fully verified.

## 8. Role in the Forecasting Project

Sporting events may provide contextual information for explaining changes in local food demand.

Potential features derived from this dataset include:

* `is_sporting_event_day`
* `sporting_event_count`
* `sporting_event_duration`
* `sport_category`
* `event_level`
* `is_major_sporting_event`

These features may help the forecasting models capture demand patterns associated with local competitions and sporting gatherings.

However, the presence of a sporting event does not establish that food demand increased. The predictive value of these features must be evaluated using the actual demand data and appropriate backtesting.

Event start times should not be used as verified temporal predictors when they are missing. Event-level features should be designed to work with the information reliably available.

## 9. Limitations

The following limitations have been documented:

1. Most records lack exact event start times.
2. Six records lack participant details.
3. Six unique source URLs require further investigation.
4. Event-level source verification is not complete.
5. The duplicate checks cannot detect every possible duplicate, such as events recorded under different names.
6. The dataset contains selected collected events and should not be interpreted as a complete census of every sporting event held in Hyderabad during the study period.
7. The dataset alone cannot establish the causal effect of sporting events on food demand.

These limitations should be considered during feature engineering, model development, and interpretation of forecasting results.

## 10. Final Status

**Phase 04.6 — Collect Other Sporting Events is closed for now, with preliminary validation completed.**

* **Records collected:** 67
* **Required schema:** Passed
* **Date checks:** Passed
* **Duplicate checks:** No duplicates detected under the tested criteria
* **Missing-data assessment:** Completed
* **URL accessibility assessment:** Completed
* **Independent source verification:** Outstanding for some records

The existing CSV will serve as the working dataset for subsequent project stages. Missing values and unresolved source issues must remain documented and be handled appropriately during feature engineering and final data-quality assessment.

# Phase 04.7 — Local Events Collection

## 04.7.1 — Planning and Source Inventory

### 1. Objective

Collect historical local-event data for the five hyperlocal zones in the Hyderabad food-demand forecasting project.

The events will provide contextual features for analysing possible changes in hourly food-order demand associated with public gatherings, exhibitions, cultural celebrations, concerts, and other organised events.

### 2. Study Scope

| Parameter                       | Specification                                                                                   |
| ------------------------------- | ----------------------------------------------------------------------------------------------- |
| Geographic scope                | Hyderabad and Secunderabad, limited to the project's five zones and their relevant surroundings |
| Study period                    | January 1, 2023 – July 31, 2026                                                                 |
| Primary purpose                 | Contextual features for hourly food-demand forecasting                                          |
| Source preference               | Official event organisers, government portals, venue archives, and reliable news reports        |
| Output format                   | CSV                                                                                             |
| Collection approach             | Historical event editions with documented dates and locations                                   |
| Existing sporting-event data    | Keep separate; avoid duplicate records                                                          |
| Cricket data                    | Keep separate                                                                                   |
| Weather and public-holiday data | Keep separate                                                                                   |

### 3. Five Hyperlocal Zones

| Zone ID | Zone name   |
| ------- | ----------- |
| Z01     | Kondapur    |
| Z02     | Hitech City |
| Z03     | Gachibowli  |
| Z04     | Madhapur    |
| Z05     | Kukatpally  |

Events will be associated with these zones using their documented venue and geographic location. Events outside a zone will not automatically be assigned to it merely because they occurred somewhere in Hyderabad.

### 4. Local Event Categories

#### A. Religious and Cultural Festivals

* Bonalu and documented local celebrations
* Bathukamma celebrations
* Ganesh Chaturthi celebrations and public gatherings
* Durga Puja and Navaratri events
* Ugadi and Sankranti celebrations
* Other documented major religious and cultural gatherings

#### B. Exhibitions and Trade Fairs

* Major exhibitions at HITEX
* Technology and industrial expos
* Consumer and shopping exhibitions
* Lifestyle and jewellery fairs
* Crafts and handloom exhibitions
* Other documented multi-day public exhibitions

#### C. Food and Culinary Events

* Food festivals
* Food expos
* Culinary fairs
* Organised regional-cuisine events
* Public food events associated with larger festivals

#### D. Concerts and Entertainment

* Major live concerts
* Music festivals
* Large cultural performances
* Public entertainment events
* Major events at documented concert venues

#### E. Major Public Gatherings

* Bathini Fish Prasadam
* Significant public cultural carnivals
* Government-organised public events
* Large public celebrations with documented dates and locations

#### F. Literary, Educational, and Community Events

* Hyderabad Literature Festival
* Public book fairs
* Major educational exhibitions
* Large community festivals
* Significant public cultural programmes

Only events with sufficient evidence of their dates and locations will be included.

### 5. Source Inventory

The following resources have been identified as starting points for historical collection.

| Source                                                                                                 | Data to collect                                                           | Priority   |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------- | ---------- |
| [HITEX Past Events Archive](https://hitex.co.in/events/past.html)                                      | Exhibitions, expos, concerts, food fairs, and other events with dates     | Very high  |
| [Hyderabad District Festivals](https://hyderabad.telangana.gov.in/festivals/)                          | Major regional festivals and their descriptions                           | High       |
| [Telangana Tourism Festivals and Fairs](https://www.tourism.telangana.gov.in/page/festivals-and-fairs) | Cultural festivals and fairs                                              | High       |
| [Telangana Government Calendar](https://www.telangana.gov.in/Downloads/calendar/)                      | Official calendar context for festival dates                              | High       |
| [Hyderabad Police Traffic Advisories](https://hyderabadpolice.gov.in/)                                 | Evidence of major public gatherings, routes, venues, and event periods    | High       |
| [Shilparamam](https://shilparamam.in/)                                                                 | Cultural programmes, craft fairs, and seasonal events                     | High       |
| [Bathini Fish Prasadam reporting and advisories](https://hyderabadpolice.gov.in/)                      | Historical event dates and location details                               | High       |
| Official concert and event organisers                                                                  | Concert dates, venue, and event duration                                  | High       |
| Reliable historical news reports                                                                       | Additional dates and corroboration where official archives are incomplete | Supporting |

The HITEX archive is a key starting point because it contains historical entries for 2023, 2024, 2025, and 2026. Its listings include named events and date ranges that can be used to identify candidate records.

The government festival directories establish the relevant regional festival categories. Individual historical editions must still be collected using their actual dates.

### 6. Collection Periods

| Period | Collection requirement  |
| ------ | ----------------------- |
| 2023   | January 1 – December 31 |
| 2024   | January 1 – December 31 |
| 2025   | January 1 – December 31 |
| 2026   | January 1 – July 31     |

Recurring events will be collected as individual historical editions where their dates and locations can be established.

Usual festival months will not be treated as proof of a particular event date.

### 7. Required Dataset Fields

The local-events dataset will use the following fields:

| Column             | Description                                            |
| ------------------ | ------------------------------------------------------ |
| `event_date`       | Event start date                                       |
| `event_end_date`   | Event end date                                         |
| `event_name`       | Documented event name                                  |
| `event_category`   | Local-event category                                   |
| `event_start_time` | Start time, if available                               |
| `venue`            | Documented venue                                       |
| `city`             | City or locality                                       |
| `latitude`         | Venue latitude, where available                        |
| `longitude`        | Venue longitude, where available                       |
| `zone_id`          | Associated project zone, when geographically supported |
| `event_level`      | Documented event scale or level, where available       |
| `source_url`       | Source supporting the event details                    |

Missing details will not be filled using invented values.

### 8. Collection Priorities

The initial collection order will be:

1. Historical HITEX exhibitions and expos.
2. Shilparamam fairs and cultural events.
3. Major concerts and entertainment events within or near the five zones.
4. Major religious and cultural festivals with identifiable local venues.
5. Food festivals and culinary exhibitions.
6. Major public gatherings with documented dates and locations.
7. Literary, educational, and community events.

### 9. Zone Assignment

The event venue will be used to associate an event with the five-zone geography.

* Events within a zone will be assigned to that zone.
* Events near a zone boundary will be assigned using the project's geographic rules.
* Events outside the five zones will only be considered when there is a defined reason to model their potential influence on a zone.
* City-wide festivals without a single identifiable venue will not automatically be assigned to every zone.
* Unknown venue coordinates will not be fabricated.

### 10. Scope Boundaries

To avoid unnecessary work and duplicate data:

* Cricket remains in its existing dataset.
* Sporting competitions already collected in Phase 04.6 will not be duplicated.
* Public holidays remain separate.
* Weather data remains separate.
* Only identifiable organised events are targeted; routine daily activity is excluded.
* Exact start times and attendance figures will be collected only when supported by sources.

### 11. Expected Outcome

Phase 04.7 will produce a historical local-events dataset covering the project's five zones and study period, using real event records supported by available sources.

The resulting data will support the creation of candidate features such as local-event-day indicators, event categories, event duration, and proximity to event venues.

The usefulness of these features will subsequently be assessed within the food-demand forecasting workflow.

**Current status:** Planning and initial source discovery completed. Historical event collection is the next step.

In [111]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path
from datetime import datetime

# ============================================================
# PHASE 04.7.2 — COLLECT HISTORICAL HITEX EVENTS
# Source: Official HITEX Past Events Archive
# Period: 2023-01-01 to 2026-07-31
# ============================================================

SOURCE_URL = "https://hitex.co.in/events/past.html"

PROJECT_DIR = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
)

OUTPUT_FILE = (
    PROJECT_DIR
    / "data"
    / "raw"
    / "local_events"
    / "hyderabad_local_events_2023_2026.csv"
)

START_DATE = pd.Timestamp("2023-01-01")
END_DATE = pd.Timestamp("2026-07-31")

response = requests.get(
    SOURCE_URL,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

date_pattern = re.compile(
    r"(\d{1,2}\s+[A-Za-z]{3}\s+\d{4})"
    r"(?:\s*-\s*(\d{1,2}\s+[A-Za-z]{3}\s+\d{4}))?"
)

def classify_event(name):
    text = name.lower()

    if any(k in text for k in [
        "food", "mithai", "sweet", "bakery", "horeca",
        "rice & grain", "dairy expo", "poultry india"
    ]):
        return "Food and Culinary"

    if any(k in text for k in [
        "concert", "music", "giggle fest", "soul sante",
        "lala land", "la la land", "dreamhack", "comic con",
        "kids' fair", "kids’ fair", "kite"
    ]):
        return "Entertainment and Public Events"

    if any(k in text for k in [
        "book fair", "literature", "literary", "craft mela",
        "deep mela", "style tatva", "design democracy",
        "art show", "cultural"
    ]):
        return "Cultural and Community"

    if any(k in text for k in [
        "expo", "exhibition", "fair", "show", "summit",
        "conference", "convention", "conclave", "fest",
        "mela", "bazaar", "market", "expo", "expos"
    ]):
        return "Exhibition and Trade Fair"

    return "Other Organised Event"


records = []

# The archive uses event headings followed by date and organizer links.
for heading in soup.find_all(["h2", "h3", "h4"]):
    event_name = heading.get_text(" ", strip=True)

    if not event_name:
        continue

    # Find the next date-bearing link associated with this event.
    date_text = None
    event_url = SOURCE_URL

    heading_link = heading.find("a", href=True)
    if heading_link:
        event_url = requests.compat.urljoin(
            SOURCE_URL, heading_link["href"]
        )

    for link in heading.find_all_next("a", limit=5):
        candidate = link.get_text(" ", strip=True)

        if date_pattern.search(candidate):
            date_text = candidate
            break

        # Stop if the next event heading is reached.
        next_heading = link.find_previous(
            ["h2", "h3", "h4"]
        )
        if next_heading is not None and next_heading is not heading:
            break

    if not date_text:
        continue

    match = date_pattern.search(date_text)
    if not match:
        continue

    try:
        event_start = pd.to_datetime(
            match.group(1), format="%d %b %Y"
        )
        event_end = (
            pd.to_datetime(match.group(2), format="%d %b %Y")
            if match.group(2)
            else event_start
        )
    except (ValueError, TypeError):
        continue

    # Keep events overlapping the requested study period.
    if event_end < START_DATE or event_start > END_DATE:
        continue

    records.append({
        "event_date": event_start.strftime("%Y-%m-%d"),
        "event_end_date": event_end.strftime("%Y-%m-%d"),
        "event_name": event_name,
        "event_category": classify_event(event_name),
        "event_start_time": None,
        "venue": "HITEX Exhibition Centre",
        "city": "Hyderabad",
        "latitude": None,
        "longitude": None,
        "zone_id": None,
        "event_level": None,
        "source_url": event_url
    })

# Build dataset
columns = [
    "event_date",
    "event_end_date",
    "event_name",
    "event_category",
    "event_start_time",
    "venue",
    "city",
    "latitude",
    "longitude",
    "zone_id",
    "event_level",
    "source_url"
]

events_df = pd.DataFrame(records, columns=columns)

# Save collected records
OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
events_df.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")

print("=" * 65)
print("PHASE 04.7.2 — HITEX EVENT COLLECTION")
print("=" * 65)
print(f"Source: {SOURCE_URL}")
print(f"Events collected: {len(events_df)}")
print(f"Output: {OUTPUT_FILE}")

if not events_df.empty:
    print("\nEvents by category:")
    print(events_df["event_category"].value_counts().to_string())

    print("\nSample collected events:")
    print(
        events_df[
            ["event_date", "event_end_date", "event_name", "event_category"]
        ].head(15).to_string(index=False)
    )

print("\nCollection step completed.")

=================================================================
PHASE 04.7.2 — HITEX EVENT COLLECTION
=================================================================
Source: https://hitex.co.in/events/past.html
Events collected: 294
Output: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Events by category:
event_category
Exhibition and Trade Fair          145
Other Organised Event               91
Entertainment and Public Events     26
Food and Culinary                   22
Cultural and Community              10

Sample collected events:
event_date event_end_date                                   event_name            event_category
2026-07-31     2026-08-02                                    Deep Mela    Cultural and Community
2026-07-30     2026-08-01                 Eco Sustain Expo 3rd Edition Exhibition and Trade Fair
2026-07-30     2026-08-01                             IPEC 5th Edition     Other Organised Event
2026-07-30     2026-08-01          Renewable Restart Energy India Expo Exhibition and Trade Fair
2026-07-25     2026-07-26                     TV9 Sweet Home Expo 2026         Food and Culinary
2026-07-25     2026-07-26                  Hyderabad Dental Convention Exhibition and Trade Fair
2026-07-24     2026-07-27                 International Furniture Expo Exhibition and Trade Fair
2026-07-16     2026-07-18                       Tube & Pipe Fair South Exhibition and Trade Fair
2026-07-16     2026-07-18  World Mithai Namkeen Convention & Expo 2026         Food and Culinary
2026-07-09     2026-07-11                       Pharma Pro & Pack Expo Exhibition and Trade Fair
2026-07-02     2026-07-04                                  Food A’Fair         Food and Culinary
2026-06-26     2026-06-28                            All in Print Asia     Other Organised Event
2026-06-26     2026-06-28 Industrial Innovation & Technology Expo 2026 Exhibition and Trade Fair
2026-06-20     2026-06-22                            The Homeware Expo Exhibition and Trade Fair
2026-06-19     2026-06-21                 IIID Showcase Insider X 2026 Exhibition and Trade Fair

Collection step completed.

In [112]:
import pandas as pd
from pathlib import Path

# ============================================================
# 04.7.3 — SHILPARAMAM HISTORICAL EVENTS
# Study period: 2023-01-01 to 2026-07-31
# ============================================================

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

# Historical events supported by official event records
new_events = [
    {
        "event_date": "2023-01-04",
        "event_end_date": "2023-01-18",
        "event_name": "Shilparamam National Handicrafts Fair",
        "event_category": "Exhibition and Trade Fair",
        "event_start_time": None,
        "venue": "Shilparamam, Madhapur",
        "city": "Hyderabad",
        "latitude": None,
        "longitude": None,
        "zone_id": "Z04",
        "event_level": "National",
        "source_url": "https://indian.handicrafts.gov.in/en/events/view/NzQ%3D"
    },
    {
        "event_date": "2023-12-15",
        "event_end_date": "2023-12-31",
        "event_name": "Shilparamam Craft Mela",
        "event_category": "Exhibition and Trade Fair",
        "event_start_time": None,
        "venue": "Shilparamam, Madhapur",
        "city": "Hyderabad",
        "latitude": None,
        "longitude": None,
        "zone_id": "Z04",
        "event_level": "National",
        "source_url": "https://handlooms.gov.in/silparamam_craft_mela.php"
    },
    {
        "event_date": "2024-01-08",
        "event_end_date": "2024-01-17",
        "event_name": "Shilparamam Sankranthi Sambaralu",
        "event_category": "Religious and Cultural Festival",
        "event_start_time": None,
        "venue": "Shilparamam, Madhapur",
        "city": "Hyderabad",
        "latitude": None,
        "longitude": None,
        "zone_id": "Z04",
        "event_level": "Local",
        "source_url": "https://shilparamam.in/upcoming-celebrations/"
    },
    {
        "event_date": "2024-12-15",
        "event_end_date": "2024-12-31",
        "event_name": "All India Crafts Mela",
        "event_category": "Exhibition and Trade Fair",
        "event_start_time": None,
        "venue": "Shilparamam, Madhapur",
        "city": "Hyderabad",
        "latitude": None,
        "longitude": None,
        "zone_id": "Z04",
        "event_level": "National",
        "source_url": "https://shilparamam.in/upcoming-celebrations/"
    },
    {
        "event_date": "2025-01-08",
        "event_end_date": "2025-01-17",
        "event_name": "Gandhi Shilp Bazar — Shilparamam Madhapur",
        "event_category": "Exhibition and Trade Fair",
        "event_start_time": None,
        "venue": "Shilparamam, Madhapur",
        "city": "Hyderabad",
        "latitude": None,
        "longitude": None,
        "zone_id": "Z04",
        "event_level": "National",
        "source_url": "https://indian.handicrafts.gov.in/en/events/view/NDA2"
    },
    {
        "event_date": "2025-11-16",
        "event_end_date": "2025-11-25",
        "event_name": "Gandhi Shilp Bazar at Shilparamam",
        "event_category": "Exhibition and Trade Fair",
        "event_start_time": None,
        "venue": "Shilparamam, Madhapur",
        "city": "Hyderabad",
        "latitude": None,
        "longitude": None,
        "zone_id": "Z04",
        "event_level": "National",
        "source_url": "https://indian.handicrafts.gov.in/en/events/view/NTg4"
    },
    {
        "event_date": "2025-12-15",
        "event_end_date": "2025-12-31",
        "event_name": "Shilparamam Crafts Mela",
        "event_category": "Exhibition and Trade Fair",
        "event_start_time": None,
        "venue": "Shilparamam, Madhapur",
        "city": "Hyderabad",
        "latitude": None,
        "longitude": None,
        "zone_id": "Z04",
        "event_level": "National",
        "source_url": "https://handlooms.nic.in/assets/img/upcoming_markeing/AMC2025-26_02-04-2025.pdf"
    }
]

new_df = pd.DataFrame(new_events)

# Append to the existing dataset
df = pd.read_csv(file_path)

df = pd.concat([df, new_df], ignore_index=True)

# Avoid exact repeats of the same event, date and venue
df = df.drop_duplicates(
    subset=["event_date", "event_name", "venue"],
    keep="first"
)

df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("04.7.3 — SHILPARAMAM EVENTS COLLECTION COMPLETE")
print(f"New candidate events: {len(new_events)}")
print(f"Total records now in dataset: {len(df)}")
print(f"Updated file: {file_path}")

04.7.3 — SHILPARAMAM EVENTS COLLECTION COMPLETE
New candidate events: 7
Total records now in dataset: 300
Updated file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

In [113]:
# ============================================================
# PHASE 04.7.4 — HYDERABAD FESTIVALS & CULTURAL EVENTS
# Append sourced festival-date records to the existing dataset
# ============================================================

import pandas as pd
from pathlib import Path

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

# Official source pages
TELANGANA_CALENDAR = "https://www.telangana.gov.in/downloads/calendar/"
TELANGANA_2025 = "https://www.telangana.gov.in/downloads/calendar-2025/"
HYDERABAD_FESTIVALS = "https://hyderabad.telangana.gov.in/festivals/"
BONALU_SOURCE = "https://hyderabad.telangana.gov.in/festival/bonalu/"
BATHUKAMMA_SOURCE = "https://hyderabad.telangana.gov.in/festival/bathukamma/"
BONALU_2025_SOURCE = "https://www.utsav.gov.in/view-event/bonalu-2"

# Festival dates taken from government calendars/pages.
# Dates represent festival dates or official festival starting days,
# not necessarily the full duration of city-wide celebrations.
festival_records = [
    {
        "event_date": "2023-07-17",
        "event_end_date": "2023-07-17",
        "event_name": "Bonalu Festival",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2023-09-18",
        "event_end_date": "2023-09-18",
        "event_name": "Ganesh Chaturthi (Vinayaka Chavithi)",
        "event_category": "Religious Festival",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2023-10-14",
        "event_end_date": "2023-10-14",
        "event_name": "Bathukamma Festival — Starting Day (date to verify)",
        "event_category": "Cultural and Community",
        "source_url": BATHUKAMMA_SOURCE,
    },
    {
        "event_date": "2023-10-24",
        "event_end_date": "2023-10-24",
        "event_name": "Vijaya Dasami (Dussehra)",
        "event_category": "Religious Festival",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2023-11-12",
        "event_end_date": "2023-11-12",
        "event_name": "Diwali",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2024-04-09",
        "event_end_date": "2024-04-09",
        "event_name": "Ugadi — Telugu New Year",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2024-07-29",
        "event_end_date": "2024-07-29",
        "event_name": "Bonalu Festival",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2024-09-07",
        "event_end_date": "2024-09-07",
        "event_name": "Ganesh Chaturthi (Vinayaka Chavithi)",
        "event_category": "Religious Festival",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2024-10-02",
        "event_end_date": "2024-10-02",
        "event_name": "Bathukamma Festival — Starting Day",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2024-10-12",
        "event_end_date": "2024-10-12",
        "event_name": "Vijaya Dasami (Dussehra)",
        "event_category": "Religious Festival",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2024-10-31",
        "event_end_date": "2024-10-31",
        "event_name": "Diwali",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_CALENDAR,
    },
    {
        "event_date": "2025-03-30",
        "event_end_date": "2025-03-30",
        "event_name": "Ugadi — Telugu New Year",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_2025,
    },
    {
        "event_date": "2025-07-21",
        "event_end_date": "2025-07-21",
        "event_name": "Bonalu — Official Holiday Date",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_2025,
    },
    {
        "event_date": "2025-08-27",
        "event_end_date": "2025-08-27",
        "event_name": "Ganesh Chaturthi (Vinayaka Chavithi)",
        "event_category": "Religious Festival",
        "source_url": TELANGANA_2025,
    },
    {
        "event_date": "2025-09-21",
        "event_end_date": "2025-09-21",
        "event_name": "Bathukamma Festival — Starting Day",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_2025,
    },
    {
        "event_date": "2025-10-02",
        "event_end_date": "2025-10-02",
        "event_name": "Vijaya Dasami (Dussehra)",
        "event_category": "Religious Festival",
        "source_url": TELANGANA_2025,
    },
    {
        "event_date": "2025-10-20",
        "event_end_date": "2025-10-20",
        "event_name": "Diwali",
        "event_category": "Cultural and Community",
        "source_url": TELANGANA_2025,
    },
]

# Build rows using the existing dataset's schema
new_df = pd.DataFrame(festival_records)

new_df["event_start_time"] = None
new_df["venue"] = "Multiple locations across Hyderabad"
new_df["city"] = "Hyderabad"
new_df["latitude"] = None
new_df["longitude"] = None
new_df["zone_id"] = None
new_df["event_level"] = "City-wide festival date"

# Read the existing dataset and align columns
existing_df = pd.read_csv(file_path)

for col in existing_df.columns:
    if col not in new_df.columns:
        new_df[col] = None

for col in new_df.columns:
    if col not in existing_df.columns:
        existing_df[col] = None

new_df = new_df[existing_df.columns]

# Append only records that do not already exist
combined_df = pd.concat([existing_df, new_df], ignore_index=True)

combined_df["event_date"] = pd.to_datetime(
    combined_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

combined_df["event_end_date"] = pd.to_datetime(
    combined_df["event_end_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

combined_df = combined_df.drop_duplicates(
    subset=["event_date", "event_name", "venue"],
    keep="first"
)

combined_df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("04.7.4 — HYDERABAD FESTIVALS & CULTURAL EVENTS")
print(f"Candidate festival records prepared: {len(festival_records)}")
print(f"Total records now in dataset: {len(combined_df)}")
print(f"Updated file: {file_path}")

04.7.4 — HYDERABAD FESTIVALS & CULTURAL EVENTS
Candidate festival records prepared: 17
Total records now in dataset: 317
Updated file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

In [114]:
# ============================================================
# PHASE 04.7.5 — HYDERABAD EXHIBITIONS, FAIRS & PUBLIC EVENTS
# Append source-supported event records to the existing CSV
# ============================================================

import pandas as pd
from pathlib import Path

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

# Source URLs
NUMAISH_SOURCE = (
    "https://utsav.gov.in/view-event/all-india-industrial-exhibition-1"
)
NUMAISH_OFFICIAL = "https://exhibitionsociety.com/press-release/"
KITE_2023_SOURCE = (
    "https://utsav.gov.in/view-event/international-kite-sweet-festival-1"
)
KITE_2024_SOURCE = (
    "https://hyderabadpolice.gov.in/assets/news/2024/01Jan/13012024.pdf"
)
BOOK_FAIR_SOURCE = (
    "https://utsav.gov.in/public/view-event/hyderabad-national-book-fair"
)

# Event dates documented by the cited sources.
# Numaish 2024/2025 and Kite Festival 2025 are intentionally
# omitted here rather than assigning dates without a source.
events = [
    {
        "event_date": "2023-01-01",
        "event_end_date": "2023-02-15",
        "event_name": "Numaish — All India Industrial Exhibition 2023",
        "event_category": "Exhibition and Trade Fair",
        "venue": "Nampally Exhibition Grounds",
        "event_level": "City-wide public exhibition",
        "source_url": NUMAISH_SOURCE,
    },
    {
        "event_date": "2023-01-13",
        "event_end_date": "2023-01-15",
        "event_name": "International Kite & Sweet Festival 2023",
        "event_category": "Cultural and Community",
        "venue": "Parade Grounds, Secunderabad",
        "event_level": "Major public festival",
        "source_url": KITE_2023_SOURCE,
    },
    {
        "event_date": "2023-01-01",
        "event_end_date": "2023-01-01",
        "event_name": "Hyderabad National Book Fair 2022–2023",
        "event_category": "Exhibition and Trade Fair",
        "venue": "Telangana Kalabharathi, NTR Stadium",
        "event_level": "Public book fair",
        "source_url": BOOK_FAIR_SOURCE,
    },
    {
        "event_date": "2024-01-13",
        "event_end_date": "2024-01-15",
        "event_name": "International Kite & Sweet Festival 2024",
        "event_category": "Cultural and Community",
        "venue": "Parade Grounds, Secunderabad",
        "event_level": "Major public festival",
        "source_url": KITE_2024_SOURCE,
    },
    {
        "event_date": "2026-01-01",
        "event_end_date": "2026-02-15",
        "event_name": "Numaish — 85th All India Industrial Exhibition 2026",
        "event_category": "Exhibition and Trade Fair",
        "venue": "Nampally Exhibition Grounds",
        "event_level": "City-wide public exhibition",
        "source_url": NUMAISH_OFFICIAL,
    },
]

new_df = pd.DataFrame(events)

# Fill remaining columns expected by the existing dataset
new_df["event_start_time"] = None
new_df["city"] = "Hyderabad"
new_df["latitude"] = None
new_df["longitude"] = None
new_df["zone_id"] = None

# Nampally and NTR Stadium are not assigned to the five study zones
# automatically; Parade Grounds is also outside those five zones.

existing_df = pd.read_csv(file_path)

for col in existing_df.columns:
    if col not in new_df.columns:
        new_df[col] = None

for col in new_df.columns:
    if col not in existing_df.columns:
        existing_df[col] = None

new_df = new_df[existing_df.columns]

combined_df = pd.concat([existing_df, new_df], ignore_index=True)

combined_df["event_date"] = pd.to_datetime(
    combined_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

combined_df["event_end_date"] = pd.to_datetime(
    combined_df["event_end_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

combined_df = combined_df.drop_duplicates(
    subset=["event_date", "event_name", "venue"],
    keep="first"
)

combined_df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("04.7.5 — EXHIBITIONS, FAIRS & PUBLIC EVENTS COMPLETE")
print(f"Candidate event records prepared: {len(events)}")
print(f"Total records now in dataset: {len(combined_df)}")
print(f"Updated file: {file_path}")

04.7.5 — EXHIBITIONS, FAIRS & PUBLIC EVENTS COMPLETE
Candidate event records prepared: 5
Total records now in dataset: 322
Updated file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

In [115]:
# ============================================================
# PHASE 04.7.6 — HYDERABAD FOOD FESTIVALS & CULINARY EVENTS
# Append event records to the existing local-events dataset
# ============================================================

import pandas as pd
from pathlib import Path

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

# Published source URLs
HITEX_PAST = "https://hitex.co.in/events/past.html"
INDUSFOOD_SOURCE = "https://hitex.co.in/features/palatable-paradigms.html"
FOOD_AFAIR_2024 = "https://hitex.co.in/events/food-afair/index.html"
FOOD_AFAIR_2025 = "https://foodafair.com/assets/images/brochure.pdf"
FOOD_INDIA_2025 = "https://hitex.co.in/events/food-india-expo-2025/index.html"
ZOMALAND_2023 = "https://telanganatoday.com/food-carnival-zomalands-hyderabad-dates-announced"
IIHM_FESTIVAL_2024 = (
    "https://ytc.tourism.gov.in/regionpostdeatils/"
    "eyJpdiI6IktadXhRcGFSWFc4TGY4VnNGRk1wb0E9PSIsInZhbHVlIjoiZEdQSjhTTm44ZmkxZDZybXM4T2JMZz09IiwibWFjIjoiNTVmMTI0ZmNhODEyNGQ5YWI2NWJjNWIxOGFhZTFlYTlkYTg1ZmJlMmYxNWUwNWFiNWJjNzk1YjFkZGE5MTQ3ZSIsInRhZyI6IiJ9"
)
KHANE_KA_BAZAAR = "https://khanekabazaar.in/season-01/"

food_events = [
    {
        "event_date": "2023-01-08",
        "event_end_date": "2023-01-10",
        "event_name": "IndusFood 2023",
        "event_category": "Food and Culinary",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Food industry trade exhibition",
        "source_url": INDUSFOOD_SOURCE,
    },
    {
        "event_date": "2023-01-21",
        "event_end_date": "2023-01-22",
        "event_name": "Zomaland Hyderabad 2023",
        "event_category": "Food and Culinary",
        "venue": "GMR Arena, Shamshabad",
        "event_level": "Public food and entertainment carnival",
        "source_url": ZOMALAND_2023,
    },
    {
        "event_date": "2023-02-03",
        "event_end_date": "2023-02-05",
        "event_name": "Food Expo 2023",
        "event_category": "Food and Culinary",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Food trade exhibition",
        "source_url": HITEX_PAST,
    },
    {
        "event_date": "2023-04-20",
        "event_end_date": "2023-04-20",
        "event_name": "IIHM Hyderabad Indian Food Festival",
        "event_category": "Food and Culinary",
        "venue": "Gachibowli, Hyderabad",
        "event_level": "Food and cultural festival",
        "source_url": IIHM_FESTIVAL_2024,
    },
    {
        "event_date": "2024-06-13",
        "event_end_date": "2024-06-15",
        "event_name": "Food A’FAIR 2024",
        "event_category": "Food and Culinary",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Food and beverage trade fair",
        "source_url": FOOD_AFAIR_2024,
    },
    {
        "event_date": "2025-04-25",
        "event_end_date": "2025-04-27",
        "event_name": "Food India Expo 2025",
        "event_category": "Food and Culinary",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Food industry exhibition",
        "source_url": FOOD_INDIA_2025,
    },
    {
        "event_date": "2025-11-14",
        "event_end_date": "2025-11-16",
        "event_name": "Food A’FAIR 2025",
        "event_category": "Food and Culinary",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Food and beverage trade fair",
        "source_url": FOOD_AFAIR_2025,
    },
    {
        "event_date": "2025-12-24",
        "event_end_date": "2025-12-25",
        "event_name": "Khane Ka Bazaar — Season 01",
        "event_category": "Food and Culinary",
        "venue": "Hyderabad",
        "event_level": "Public food festival and bazaar",
        "source_url": KHANE_KA_BAZAAR,
    },
    {
        "event_date": "2026-07-02",
        "event_end_date": "2026-07-04",
        "event_name": "Food A’FAIR 2026",
        "event_category": "Food and Culinary",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Food and beverage trade fair",
        "source_url": "https://www.foodafair.com/",
    },
    {
        "event_date": "2025-11-14",
        "event_end_date": "2025-11-16",
        "event_name": "Food Affair 2025 — HITEX Listing",
        "event_category": "Food and Culinary",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Food and beverage trade fair",
        "source_url": HITEX_PAST,
    },
]

new_df = pd.DataFrame(food_events)

# Fill the remaining columns used by the current dataset
new_df["event_start_time"] = None
new_df["city"] = "Hyderabad"
new_df["latitude"] = None
new_df["longitude"] = None
new_df["zone_id"] = None

existing_df = pd.read_csv(file_path)

for col in existing_df.columns:
    if col not in new_df.columns:
        new_df[col] = None

for col in new_df.columns:
    if col not in existing_df.columns:
        existing_df[col] = None

new_df = new_df[existing_df.columns]

combined_df = pd.concat([existing_df, new_df], ignore_index=True)

combined_df["event_date"] = pd.to_datetime(
    combined_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

combined_df["event_end_date"] = pd.to_datetime(
    combined_df["event_end_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

combined_df = combined_df.drop_duplicates(
    subset=["event_date", "event_name", "venue"],
    keep="first"
)

combined_df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("04.7.6 — FOOD FESTIVALS & CULINARY EVENTS COMPLETE")
print(f"Candidate event records prepared: {len(food_events)}")
print(f"Total records now in dataset: {len(combined_df)}")
print(f"Updated file: {file_path}")

04.7.6 — FOOD FESTIVALS & CULINARY EVENTS COMPLETE
Candidate event records prepared: 10
Total records now in dataset: 331
Updated file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

In [116]:
# ================================================================
# PHASE 04.7.7
# CONCERTS, ENTERTAINMENT & MAJOR PUBLIC GATHERINGS
#
# Study period: 2023-01-01 to 2026-07-31
# City: Hyderabad, Telangana, India
#
# Includes:
# 1. Telugu music directors and playback singers
# 2. Indian and international music concerts
# 3. Rock, electronic and independent music performances
# 4. Major entertainment and public gatherings
# 5. Previously collected candidate events
#
# Existing dataset is preserved.
# ================================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------
# 1. EXISTING DATASET PATH
# ------------------------------------------------

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

if not file_path.exists():
    raise FileNotFoundError(
        f"Existing local events dataset not found: {file_path}"
    )


# ------------------------------------------------
# 2. SOURCE REFERENCES
# ------------------------------------------------

SOURCE_CONCERT_ARCHIVES = (
    "https://www.concertarchives.org/locations/hyderabad-india"
)

SOURCE_HYDERABAD_TALKIES = (
    "https://hyderabadtalkies.events/past-events/"
)

SOURCE_DSP_OFFICIAL = (
    "https://actcevents.com/devi-sri-prasad-dsp-india-tour-tickets/"
)

SOURCE_KEERAVANI_HITEX = (
    "https://hitex.co.in/events/mm-keeravani-live-in-concert/index.html"
)

SOURCE_ED_SHEERAN = (
    "https://pastdates.edsheeran.com/tour-date/"
    "ramoji-film-city-hyderabad-india-sun-02022025-1200"
)

SOURCE_BRYAN_ADAMS = (
    "https://www.bryanadams.com/index.php/news/india-december-2024"
)

SOURCE_ANIRUDH = (
    "https://www.shreyasgroup.net/event-details/"
    "rockstar-anirudh-live-in-concert-hyderabad"
)

SOURCE_THAMAN_CANCELLED = (
    "https://www.123telugu.com/telugu/news/"
    "heavy-rain-and-storm-halt-thamans-ogtourindia-concert-in-hyderabad.html"
)

SOURCE_SHREYA_2023 = (
    "https://archive.siasat.com/news/"
    "tickets-prices-for-shreya-ghoshals-hyderabad-concert-2573848/"
)

SOURCE_SHREYA_2024 = (
    "https://hyderabadtalkies.events/past-events/"
)

SOURCE_ILLEYARAJA = (
    "https://www.indulgexpress.com/culture/music/2023/"
    "Feb/24/music-maestro-ilaiyaraaja-to-perform-live-music-concert-in-hyderabad-47405.html"
)

SOURCE_ARMAAN_MALIK = (
    "https://www.hindustantimes.com/entertainment/music/"
    "armaan-malik-takes-ed-sheeran-around-hyderabad-to-open-his-x-2025-india-tour-tonight-101738485573121.html"
)

SOURCE_SHREYAS_MEDIA = (
    "https://www.shreyasgroup.net/"
)

SOURCE_TELANGANA_TODAY = (
    "https://telanganatoday.com/"
    "hyderabad-all-ready-to-rock-with-star-studded-concerts-in-upcoming-weeks"
)


# ------------------------------------------------
# 3. CONSOLIDATED CONCERT AND ENTERTAINMENT RECORDS
# ------------------------------------------------
#
# research_status:
#   "Organizer/artist source" = primary source available
#   "Published event report" = published news/event report
#   "Archive candidate" = historical archive listing
#   "Needs confirmation" = venue/date/details need confirmation
#   "Cancelled" = do not treat as a completed attendance surge
#
# Dates below are candidate records, not a claim that every
# Hyderabad concert during the period has been discovered.
# ------------------------------------------------

events = [

    # ============================================================
    # 2023 — TELUGU / INDIAN MUSIC AND MAJOR ENTERTAINMENT
    # ============================================================

    {
        "event_date": "2023-02-25",
        "event_end_date": "2023-02-25",
        "event_name": "Ilaiyaraaja Tribute Concert",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Gachibowli",
        "event_level": "Major music concert",
        "source_url": SOURCE_ILLEYARAJA,
        "research_status": "Published event report",
    },

    {
        "event_date": "2023-02-26",
        "event_end_date": "2023-02-26",
        "event_name": "Ilaiyaraaja Live Concert",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Gachibowli",
        "event_level": "Major music concert",
        "source_url": SOURCE_ILLEYARAJA,
        "research_status": "Published event report",
    },

    {
        "event_date": "2023-03-04",
        "event_end_date": "2023-03-04",
        "event_name": "Martin Garrix Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "HITEX Exhibition Centre",
        "event_level": "International electronic music concert",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2023-04-30",
        "event_end_date": "2023-04-30",
        "event_name": "Shreya Ghoshal Live Concert",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Gachibowli Practice Stadium",
        "event_level": "Major playback singer concert",
        "source_url": SOURCE_SHREYA_2023,
        "research_status": "Published event report",
    },

    {
        "event_date": "2023-09-08",
        "event_end_date": "2023-09-08",
        "event_name": "WWE Superstar Spectacle 2023",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "G. M. C. Balayogi Indoor Stadium",
        "event_level": "Major live sports entertainment",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2023-08-25",
        "event_end_date": "2023-08-25",
        "event_name": "Radio Slave Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "EXT, Jubilee Hills",
        "event_level": "Electronic music performance",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Needs confirmation",
    },

    {
        "event_date": "2023-12-16",
        "event_end_date": "2023-12-16",
        "event_name": "Meca Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Breeze Monkey",
        "event_level": "Electronic music performance",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2023-12-17",
        "event_end_date": "2023-12-17",
        "event_name": "Massano Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": None,
        "event_level": "Electronic music performance",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Venue needs confirmation",
    },

    {
        "event_date": "2023-12-17",
        "event_end_date": "2023-12-17",
        "event_name": "Mali (Maalavika Manoj) Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "EXT, Jubilee Hills",
        "event_level": "Independent music performance",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Needs confirmation",
    },


    # ============================================================
    # 2024 — INDIAN AND INTERNATIONAL CONCERTS
    # ============================================================

    {
        "event_date": "2024-02-18",
        "event_end_date": "2024-02-18",
        "event_name": "Adam Beyer Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Prism",
        "event_level": "Electronic music performance",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2024-02-23",
        "event_end_date": "2024-02-23",
        "event_name": "Anjunadeep, Anyasa, CRi, HANA and Others",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": None,
        "event_level": "Electronic music event",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Venue needs confirmation",
    },

    {
        "event_date": "2024-04-27",
        "event_end_date": "2024-04-27",
        "event_name": "Girish and the Chronicles — Loaded Summer Tour",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Hard Rock Cafe, Hitech City",
        "event_level": "Rock concert",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2024-06-22",
        "event_end_date": "2024-06-22",
        "event_name": "Whiney, Degs, Anais and Others",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Antisocial Hyderabad",
        "event_level": "Electronic music event",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2024-08-10",
        "event_end_date": "2024-08-10",
        "event_name": "Anthracite Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Hard Rock Cafe, Hitech City",
        "event_level": "Rock/metal performance",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2024-10-19",
        "event_end_date": "2024-10-19",
        "event_name": "Rockstar DSP Live — Devi Sri Prasad",
        "event_category": "Entertainment and Public Events",
        "event_start_time": "18:30",
        "venue": "Gachibowli Stadium",
        "event_level": "Major Telugu music director concert",
        "source_url": SOURCE_DSP_OFFICIAL,
        "research_status": "Organizer/artist source",
    },

    {
        "event_date": "2024-11-15",
        "event_end_date": "2024-11-15",
        "event_name": "Candlelight: Tribute to Coldplay",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Radisson Blu Plaza Hotel, Banjara Hills",
        "event_level": "Candlelight music concert",
        "source_url": "https://newsroom.feverup.com/en-IN/246247-experience-the-candlelight-concert-series-now-launching-in-hyderabad/",
        "research_status": "Organizer/artist source",
    },

    {
        "event_date": "2024-11-21",
        "event_end_date": "2024-11-21",
        "event_name": "Ulcerate Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "EXT",
        "event_level": "International metal concert",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2024-11-30",
        "event_end_date": "2024-11-30",
        "event_name": "Shreya Ghoshal Live Concert",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "LB Stadium",
        "event_level": "Major playback singer concert",
        "source_url": SOURCE_SHREYA_2024,
        "research_status": "Organizer archive; date needs confirmation",
    },

    {
        "event_date": "2024-12-07",
        "event_end_date": "2024-12-07",
        "event_name": "Arijit Singh Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "GMR Arena",
        "event_level": "Major playback singer concert",
        "source_url": SOURCE_TELANGANA_TODAY,
        "research_status": "Needs confirmation",
    },

    {
        "event_date": "2024-12-16",
        "event_end_date": "2024-12-16",
        "event_name": "Bryan Adams — So Happy It Hurts Tour",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "GMR Arena",
        "event_level": "International music concert",
        "source_url": SOURCE_BRYAN_ADAMS,
        "research_status": "Artist/official tour source",
    },

    {
        "event_date": "2024-12-29",
        "event_end_date": "2024-12-29",
        "event_name": "Ben Böhmer Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": None,
        "event_level": "Electronic music performance",
        "source_url": SOURCE_TELANGANA_TODAY,
        "research_status": "Venue needs confirmation",
    },


    # ============================================================
    # 2025 — LARGE CONCERTS AND TELUGU MUSIC DIRECTORS
    # ============================================================

    {
        "event_date": "2025-02-02",
        "event_end_date": "2025-02-02",
        "event_name": "Ed Sheeran — Mathematics Tour",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Ramoji Film City",
        "event_level": "Major international concert",
        "source_url": SOURCE_ED_SHEERAN,
        "research_status": "Artist/official tour source",
    },

    {
        "event_date": "2025-02-02",
        "event_end_date": "2025-02-02",
        "event_name": "Armaan Malik — Opening Act for Ed Sheeran",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Ramoji Film City",
        "event_level": "Playback singer / concert opening act",
        "source_url": SOURCE_ARMAAN_MALIK,
        "research_status": "Published event report",
    },

    {
        "event_date": "2025-03-22",
        "event_end_date": "2025-03-22",
        "event_name": "M. M. Keeravaani — NAA TOUR",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "HITEX Exhibition Centre",
        "event_level": "Major Telugu music director concert",
        "source_url": SOURCE_KEERAVANI_HITEX,
        "research_status": "Organizer/venue source",
    },

    {
        "event_date": "2025-03-08",
        "event_end_date": "2025-03-08",
        "event_name": "John Summit Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Quake Arena",
        "event_level": "Electronic music concert",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2025-05-09",
        "event_end_date": "2025-05-09",
        "event_name": "Dimitri Vegas Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Quake Arena",
        "event_level": "Electronic music concert",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2025-05-31",
        "event_end_date": "2025-05-31",
        "event_name": "Girish and the Chronicles Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Hard Rock Cafe, Hitech City",
        "event_level": "Rock concert",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2025-09-21",
        "event_end_date": "2025-09-21",
        "event_name": "Parikrama Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Hard Rock Cafe, Hitech City",
        "event_level": "Rock concert",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2025-09-28",
        "event_end_date": "2025-09-28",
        "event_name": "Deborah De Luca Live",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Quake Arena",
        "event_level": "Electronic music concert",
        "source_url": SOURCE_CONCERT_ARCHIVES,
        "research_status": "Archive candidate",
    },

    {
        "event_date": "2025-11-08",
        "event_end_date": "2025-11-08",
        "event_name": "A. R. Rahman Live in Hyderabad",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": None,
        "event_level": "Major Indian music director concert",
        "source_url": SOURCE_HYDERABAD_TALKIES,
        "research_status": "Organizer archive; venue needs confirmation",
    },


    # ============================================================
    # 2026 — TELUGU MUSIC AND OTHER ENTERTAINMENT
    # ============================================================

    {
        "event_date": "2026-03-21",
        "event_end_date": "2026-03-21",
        "event_name": "Rockstar Anirudh XV — 15 Years With You",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Gachibowli Outdoor Stadium",
        "event_level": "Major Indian music director concert",
        "source_url": SOURCE_ANIRUDH,
        "research_status": "Organizer page; event details should be confirmed",
    },

    {
        "event_date": "2026-06-13",
        "event_end_date": "2026-06-13",
        "event_name": "S. S. Thaman — OG Tour India (Cancelled)",
        "event_category": "Entertainment and Public Events",
        "event_start_time": None,
        "venue": "Boulder Hills, Gachibowli",
        "event_level": "Cancelled concert",
        "source_url": SOURCE_THAMAN_CANCELLED,
        "research_status": "Cancelled",
    },

]


# ------------------------------------------------
# 4. CREATE THE NEW DATAFRAME
# ------------------------------------------------

new_df = pd.DataFrame(events)

# Common fields
new_df["city"] = "Hyderabad"
new_df["latitude"] = None
new_df["longitude"] = None
new_df["zone_id"] = None

# Provisional zone mapping only where the named venue is in Gachibowli.
# Exact mapping should follow your project's geographic zone boundaries.
for idx, row in new_df.iterrows():
    venue = str(row.get("venue", "")).lower()

    if "gachibowli" in venue:
        new_df.loc[idx, "zone_id"] = "Z03"


# ------------------------------------------------
# 5. LOAD THE EXISTING DATASET
# ------------------------------------------------

existing_df = pd.read_csv(file_path)


# ------------------------------------------------
# 6. ALIGN COLUMNS AND PRESERVE EXISTING DATA
# ------------------------------------------------

for col in existing_df.columns:
    if col not in new_df.columns:
        new_df[col] = None

for col in new_df.columns:
    if col not in existing_df.columns:
        existing_df[col] = None

# Keep exactly the same column order
new_df = new_df[existing_df.columns]


# ------------------------------------------------
# 7. APPEND AND REMOVE EXACT DUPLICATES
# ------------------------------------------------

combined_df = pd.concat(
    [existing_df, new_df],
    ignore_index=True
)

# Standardize date fields
for col in ["event_date", "event_end_date"]:
    combined_df[col] = pd.to_datetime(
        combined_df[col],
        errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Remove duplicate rows by event date, name and venue
combined_df = combined_df.drop_duplicates(
    subset=["event_date", "event_name", "venue"],
    keep="first"
)


# ------------------------------------------------
# 8. SAVE THE UPDATED DATASET
# ------------------------------------------------

combined_df.to_csv(
    file_path,
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------
# 9. COLLECTION SUMMARY
# ------------------------------------------------

print("=" * 65)
print("PHASE 04.7.7 — CONSOLIDATED CONCERT COLLECTION COMPLETE")
print("=" * 65)

print(f"Candidate records prepared: {len(events)}")
print(f"Total records in dataset: {len(combined_df)}")
print(f"Output file: {file_path}")

print("\nConcert candidates by year:")
event_dates = pd.to_datetime(
    pd.DataFrame(events)["event_date"],
    errors="coerce"
)

print(
    event_dates.dt.year.value_counts().sort_index().to_string()
)

print("\nCollection completed.")

=================================================================
PHASE 04.7.7 — CONSOLIDATED CONCERT COLLECTION COMPLETE
=================================================================
Candidate records prepared: 32
Total records in dataset: 363
Output file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Concert candidates by year:
event_date
2023     9
2024    12
2025     9
2026     2

Collection completed.

In [117]:
# ================================================================
# PHASE 04.7.8 — LITERARY, EDUCATIONAL & COMMUNITY EVENTS
# Study period: 2023-01-01 to 2026-07-31
# Location: Hyderabad, Telangana, India
# ================================================================

import pandas as pd
from pathlib import Path

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

# ------------------------------------------------
# SOURCE REFERENCES
# ------------------------------------------------

HLF_OFFICIAL = "https://hydlitfest.org/"
HLF_2023 = "https://utsav.gov.in/view-event/hyderabad-literary-festival-1"
HLF_2024 = "https://telanganatoday.com/hyderabad-literary-festival-2024-a-fusion-of-art-literature-and-science"
HLF_2025 = "https://www.hydlitfest.org/"
HLF_2026 = "https://hydlitfest.org/"

BOOK_FAIR_2023 = "https://utsav.gov.in/public/view-event/hyderabad-national-book-fair"
BOOK_FAIR_2024 = "https://telanganatoday.com/thirty-seventh-hyderabad-book-fair-to-be-held-at-kaloji-kalakshetram"
BOOK_FAIR_2025 = "https://www.sakshipost.com/news/telangana/hyderabad-book-fair-set-begin-tomorrow-dec-19-schedule-venue-and-key-highlights"

HITEX_ARCHIVE = "https://hitex.co.in/events/past.html"
ET_TECH_X_2023 = "https://ettechx.com/Partnership-brochure-2025.pdf"
ET_TECH_X_2024 = "https://hitex.co.in/events/past.html"
ET_TECH_X_2025 = "https://hitex.co.in/events/et-tech-x-2025/index.html"

EDUCATION_EXPO_2025 = (
    "https://www.educationsummits.kabconsultants.com/Schedule-Hyd.cshtml"
)
SPICMACAY_2025 = "https://utsav.gov.in/view-event/spicmacay-10th-international-convention-2025"

# ------------------------------------------------
# CANDIDATE EVENTS WITH PUBLISHED DATES
# ------------------------------------------------

events = [

    # -----------------------------
    # 2023
    # -----------------------------

    {
        "event_date": "2023-01-28",
        "event_end_date": "2023-01-30",
        "event_name": "Hyderabad Literary Festival 2023",
        "event_category": "Literary and Educational",
        "venue": "Hyderabad Public School",
        "event_level": "Major city literary festival",
        "source_url": HLF_2023,
        "research_status": "Published event listing; dates require source reconciliation",
    },

    {
        "event_date": "2023-01-01",
        "event_end_date": "2023-01-01",
        "event_name": "Hyderabad National Book Fair 2022-2023",
        "event_category": "Literary and Educational",
        "venue": "Telangana Kalabharathi, NTR Stadium",
        "event_level": "Major public book fair",
        "source_url": BOOK_FAIR_2023,
        "research_status": "Published government tourism listing",
    },

    {
        "event_date": "2023-12-15",
        "event_end_date": "2023-12-16",
        "event_name": "ET TECH X 2023",
        "event_category": "Educational and Technology",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Education expo and conference",
        "source_url": ET_TECH_X_2023,
        "research_status": "Organizer brochure",
    },

    {
        "event_date": "2023-12-22",
        "event_end_date": "2023-12-24",
        "event_name": "Hyderabad Kids' Fair 16th Edition",
        "event_category": "Educational and Community",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Family and children's event",
        "source_url": HITEX_ARCHIVE,
        "research_status": "HITEX event archive",
    },

    # -----------------------------
    # 2024
    # -----------------------------

    {
        "event_date": "2024-01-26",
        "event_end_date": "2024-01-28",
        "event_name": "Hyderabad Literary Festival 2024",
        "event_category": "Literary and Educational",
        "venue": "Sattva Knowledge City",
        "event_level": "Major city literary festival",
        "source_url": HLF_2024,
        "research_status": "Published event report",
    },

    {
        "event_date": "2024-03-29",
        "event_end_date": "2024-05-05",
        "event_name": "TV9 & KAB Education Summit 2024",
        "event_category": "Educational and Technology",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Education summit and expo",
        "source_url": HITEX_ARCHIVE,
        "research_status": "HITEX listing; extended dates require confirmation",
    },

    {
        "event_date": "2024-11-15",
        "event_end_date": "2024-11-17",
        "event_name": "DreamHack Hyderabad 2024",
        "event_category": "Educational and Community",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Gaming, technology and youth event",
        "source_url": HITEX_ARCHIVE,
        "research_status": "HITEX event archive",
    },

    {
        "event_date": "2024-11-15",
        "event_end_date": "2024-11-17",
        "event_name": "Hyderabad Comic Con 2024",
        "event_category": "Educational and Community",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Comic, pop culture and youth event",
        "source_url": HITEX_ARCHIVE,
        "research_status": "HITEX event archive",
    },

    {
        "event_date": "2024-12-05",
        "event_end_date": "2024-12-07",
        "event_name": "ET TECH X 2024",
        "event_category": "Educational and Technology",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Education expo and conference",
        "source_url": ET_TECH_X_2024,
        "research_status": "HITEX event archive",
    },

    {
        "event_date": "2024-12-19",
        "event_end_date": "2024-12-29",
        "event_name": "Hyderabad National Book Fair 2024",
        "event_category": "Literary and Educational",
        "venue": "Kaloji Kala Kshetram, NTR Stadium",
        "event_level": "Major public book fair",
        "source_url": BOOK_FAIR_2024,
        "research_status": "Published event report",
    },

    # -----------------------------
    # 2025
    # -----------------------------

    {
        "event_date": "2025-01-24",
        "event_end_date": "2025-01-26",
        "event_name": "Hyderabad Literary Festival 2025",
        "event_category": "Literary and Educational",
        "venue": "Sattva Knowledge City and T-Hub",
        "event_level": "Major city literary festival",
        "source_url": HLF_2025,
        "research_status": "Official festival source",
    },

    {
        "event_date": "2025-05-23",
        "event_end_date": "2025-05-25",
        "event_name": "TV9 & KAB Education Expo 2025",
        "event_category": "Educational and Technology",
        "venue": "HITEX Exhibition Centre, Hall 1",
        "event_level": "Education expo and counselling event",
        "source_url": EDUCATION_EXPO_2025,
        "research_status": "Published organizer schedule",
    },

    {
        "event_date": "2025-05-27",
        "event_end_date": "2025-06-01",
        "event_name": "SPIC MACAY 10th International Convention",
        "event_category": "Educational and Community",
        "venue": "IIT Hyderabad, Sangareddy district",
        "event_level": "National student and cultural convention",
        "source_url": SPICMACAY_2025,
        "research_status": "Government tourism portal; outside central Hyderabad",
    },

    {
        "event_date": "2025-10-31",
        "event_end_date": "2025-11-02",
        "event_name": "Hyderabad Comic Con 2025",
        "event_category": "Educational and Community",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Comic, pop culture and youth event",
        "source_url": HITEX_ARCHIVE,
        "research_status": "HITEX event archive",
    },

    {
        "event_date": "2025-10-31",
        "event_end_date": "2025-11-02",
        "event_name": "DreamHack Hyderabad 2025",
        "event_category": "Educational and Technology",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Gaming and technology event",
        "source_url": HITEX_ARCHIVE,
        "research_status": "HITEX event archive",
    },

    {
        "event_date": "2025-11-22",
        "event_end_date": "2025-11-22",
        "event_name": "Samooha Youth Literature Festival 2025",
        "event_category": "Literary and Educational",
        "venue": "Veeranari Chakali Ailamma Women's University, Koti",
        "event_level": "Youth literary festival",
        "source_url": "https://samooha.org.in/about/",
        "research_status": "Organizer website; date and venue should be confirmed",
    },

    {
        "event_date": "2025-12-11",
        "event_end_date": "2025-12-13",
        "event_name": "ET TECH X 2025",
        "event_category": "Educational and Technology",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Education expo and conference",
        "source_url": ET_TECH_X_2025,
        "research_status": "Official HITEX event listing",
    },

    {
        "event_date": "2025-12-19",
        "event_end_date": "2025-12-29",
        "event_name": "Hyderabad National Book Fair 2025",
        "event_category": "Literary and Educational",
        "venue": "Telangana Kala Bharathi, NTR Stadium",
        "event_level": "Major public book fair",
        "source_url": BOOK_FAIR_2025,
        "research_status": "Published event announcement",
    },

    {
        "event_date": "2025-12-20",
        "event_end_date": "2025-12-21",
        "event_name": "Hyderabad Kids' Fair 2025",
        "event_category": "Educational and Community",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Family and children's event",
        "source_url": HITEX_ARCHIVE,
        "research_status": "HITEX event archive",
    },

    # -----------------------------
    # 2026
    # -----------------------------

    {
        "event_date": "2026-01-24",
        "event_end_date": "2026-01-26",
        "event_name": "Hyderabad Literary Festival 2026",
        "event_category": "Literary and Educational",
        "venue": "Sattva Knowledge City, HITEC City",
        "event_level": "Major city literary festival",
        "source_url": HLF_2026,
        "research_status": "Official festival website",
    },

    {
        "event_date": "2026-05-22",
        "event_end_date": "2026-05-24",
        "event_name": "TV9 Network Education Expo 2026",
        "event_category": "Educational and Technology",
        "venue": "HITEX Exhibition Centre",
        "event_level": "Education expo",
        "source_url": HITEX_ARCHIVE,
        "research_status": "Official HITEX event archive",
    },
]

new_df = pd.DataFrame(events)

# ------------------------------------------------
# APPEND TO THE EXISTING DATASET
# ------------------------------------------------

existing_df = pd.read_csv(file_path)

new_df["city"] = "Hyderabad"
new_df["event_start_time"] = None
new_df["latitude"] = None
new_df["longitude"] = None
new_df["zone_id"] = None

# Assign provisional zone only for events located in HITEC City.
# Update this if your project's zone boundaries differ.
for idx, row in new_df.iterrows():
    venue = str(row.get("venue", "")).lower()

    if "hitec city" in venue or "hitech city" in venue:
        new_df.loc[idx, "zone_id"] = "Z02"

    elif "sattva knowledge city" in venue:
        new_df.loc[idx, "zone_id"] = "Z02"

# Align all columns with the existing schema
for col in existing_df.columns:
    if col not in new_df.columns:
        new_df[col] = None

for col in new_df.columns:
    if col not in existing_df.columns:
        existing_df[col] = None

new_df = new_df[existing_df.columns]

combined_df = pd.concat(
    [existing_df, new_df],
    ignore_index=True
)

# Standardize dates
for col in ["event_date", "event_end_date"]:
    combined_df[col] = pd.to_datetime(
        combined_df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Remove exact duplicates only
combined_df = combined_df.drop_duplicates(
    subset=["event_date", "event_name", "venue"],
    keep="first"
)

# Save updated dataset
combined_df.to_csv(
    file_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 65)
print("PHASE 04.7.8 — LITERARY, EDUCATIONAL & COMMUNITY EVENTS")
print("=" * 65)
print(f"Candidate records prepared: {len(events)}")
print(f"Total records now in dataset: {len(combined_df)}")
print(f"Updated file: {file_path}")

print("\nCandidate records by year:")
years = pd.to_datetime(
    pd.DataFrame(events)["event_date"],
    errors="coerce"
).dt.year

print(years.value_counts().sort_index().to_string())

print("\nCollection cell completed.")

=================================================================
PHASE 04.7.8 — LITERARY, EDUCATIONAL & COMMUNITY EVENTS
=================================================================
Candidate records prepared: 21
Total records now in dataset: 382
Updated file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Candidate records by year:
event_date
2023    4
2024    6
2025    9
2026    2

Collection cell completed.

In [118]:
# ================================================================
# PHASE 04.7.9 — MAJOR PUBLIC GATHERINGS & CHARITY EVENTS
# Study period: 2023-01-01 to 2026-07-31
# City: Hyderabad, Telangana, India
# ================================================================

import pandas as pd
from pathlib import Path

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

# ------------------------------------------------
# SOURCES
# ------------------------------------------------

MARATHON_SOURCE = (
    "https://aims-worldrunning.org/races/10253.html"
)

MARATHON_2023_SOURCE = (
    "https://www.marathonhyderabad.com/frequently-asked-questions/"
)

TELANGANA_FORMATION_2024 = (
    "https://www.telangana.gov.in/news/press-releases/2024/06/"
    "telangana-state-formation-day-celebrations/"
)

TELANGANA_FORMATION_GOVT_ORDER = (
    "https://cdnbbsr.s3waas.gov.in/s3ec05ba304f3809ed31d0ad97b5a2b5df/"
    "uploads/2024/05/2024052988.pdf"
)

CARDIAC_RUN_SOURCE = (
    "https://events.telanganarunners.com/"
)

# ------------------------------------------------
# CANDIDATE EVENTS
# ------------------------------------------------

events = [

    # -----------------------------
    # 2023
    # -----------------------------

    {
        "event_date": "2023-08-26",
        "event_end_date": "2023-08-26",
        "event_name": "NMDC Hyderabad Marathon — 5K Run",
        "event_category": "Major Public Gathering",
        "venue": "HITEX Expo Grounds, Madhapur",
        "event_level": "Major public running event",
        "source_url": MARATHON_2023_SOURCE,
        "research_status": "Published race information",
    },
    {
        "event_date": "2023-08-27",
        "event_end_date": "2023-08-27",
        "event_name": "NMDC Hyderabad Marathon — Full, Half and 10K",
        "event_category": "Major Public Gathering",
        "venue": "People's Plaza and HITEX Expo Grounds",
        "event_level": "Major city marathon",
        "source_url": MARATHON_SOURCE,
        "research_status": "Race archive; multiple race venues",
    },
    {
        "event_date": "2023-06-02",
        "event_end_date": "2023-06-02",
        "event_name": "Telangana Formation Day Celebrations",
        "event_category": "Government and Community",
        "venue": "Parade Grounds, Secunderabad",
        "event_level": "Statewide public celebration",
        "source_url": TELANGANA_FORMATION_2024,
        "research_status": "Annual event; 2023-specific details need confirmation",
    },

    # -----------------------------
    # 2024
    # -----------------------------

    {
        "event_date": "2024-06-02",
        "event_end_date": "2024-06-02",
        "event_name": "Telangana Formation Day — 10th Anniversary Celebrations",
        "event_category": "Government and Community",
        "venue": "Parade Grounds, Secunderabad",
        "event_level": "Major state public gathering",
        "source_url": TELANGANA_FORMATION_2024,
        "research_status": "Official Telangana government source",
    },
    {
        "event_date": "2024-08-25",
        "event_end_date": "2024-08-25",
        "event_name": "NMDC Hyderabad Marathon 2024",
        "event_category": "Major Public Gathering",
        "venue": "Hyderabad city marathon route",
        "event_level": "Major city marathon",
        "source_url": MARATHON_SOURCE,
        "research_status": "Race archive",
    },
    {
        "event_date": "2024-09-28",
        "event_end_date": "2024-09-28",
        "event_name": "Cardiac Rehab Run — 1st Edition",
        "event_category": "Charity and Public Awareness",
        "venue": "Sanjeevaiah Park and Necklace Road",
        "event_level": "Public health awareness run",
        "source_url": CARDIAC_RUN_SOURCE,
        "research_status": "Organizer event archive",
    },

    # -----------------------------
    # 2025
    # -----------------------------

    {
        "event_date": "2025-08-24",
        "event_end_date": "2025-08-24",
        "event_name": "NMDC Hyderabad Marathon 2025",
        "event_category": "Major Public Gathering",
        "venue": "Hyderabad city marathon route",
        "event_level": "Major city marathon",
        "source_url": MARATHON_SOURCE,
        "research_status": "Race archive",
    },
    {
        "event_date": "2025-09-21",
        "event_end_date": "2025-09-21",
        "event_name": "Cardiac Rehab Run — 2nd Edition",
        "event_category": "Charity and Public Awareness",
        "venue": "Sanjeevaiah Park and Necklace Road",
        "event_level": "Public health awareness run",
        "source_url": CARDIAC_RUN_SOURCE,
        "research_status": "Organizer event archive",
    },

    # -----------------------------
    # 2026
    # -----------------------------

    {
        "event_date": "2026-06-02",
        "event_end_date": "2026-06-02",
        "event_name": "Telangana Formation Day Celebrations 2026",
        "event_category": "Government and Community",
        "venue": "Hyderabad — venue to confirm",
        "event_level": "State public celebration",
        "source_url": "https://www.telangana.gov.in/",
        "research_status": "Annual event; venue-specific details need confirmation",
    },
]

new_df = pd.DataFrame(events)

# ------------------------------------------------
# STANDARD FIELDS
# ------------------------------------------------

new_df["city"] = "Hyderabad"
new_df["event_start_time"] = None
new_df["latitude"] = None
new_df["longitude"] = None
new_df["zone_id"] = None

# Provisional mapping for named local venues only
for idx, row in new_df.iterrows():
    venue = str(row.get("venue", "")).lower()

    if "hitex" in venue or "madhapur" in venue:
        new_df.loc[idx, "zone_id"] = "Z04"
    elif "people's plaza" in venue or "necklace road" in venue:
        new_df.loc[idx, "zone_id"] = None

# ------------------------------------------------
# APPEND TO EXISTING DATASET
# ------------------------------------------------

existing_df = pd.read_csv(file_path)

for col in existing_df.columns:
    if col not in new_df.columns:
        new_df[col] = None

for col in new_df.columns:
    if col not in existing_df.columns:
        existing_df[col] = None

new_df = new_df[existing_df.columns]

combined_df = pd.concat(
    [existing_df, new_df],
    ignore_index=True
)

# Standardize date fields
for col in ["event_date", "event_end_date"]:
    combined_df[col] = pd.to_datetime(
        combined_df[col], errors="coerce"
    ).dt.strftime("%Y-%m-%d")

# Remove exact duplicates
combined_df = combined_df.drop_duplicates(
    subset=["event_date", "event_name", "venue"],
    keep="first"
)

# Save
combined_df.to_csv(
    file_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 65)
print("PHASE 04.7.9 — PUBLIC GATHERINGS & CHARITY EVENTS")
print("=" * 65)
print(f"Candidate records prepared: {len(events)}")
print(f"Total records now in dataset: {len(combined_df)}")
print(f"Updated file: {file_path}")
print("\nCollection cell completed.")

=================================================================
PHASE 04.7.9 — PUBLIC GATHERINGS & CHARITY EVENTS
=================================================================
Candidate records prepared: 9
Total records now in dataset: 391
Updated file: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Collection cell completed.

In [119]:
from pathlib import Path
import pandas as pd

print("=" * 72)
print("PHASE 04.7.10 — SPORTS EVENTS & STADIUM GATHERINGS")
print("=" * 72)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

# Official IPL schedule sources
IPL_2024_SOURCE = (
    "https://documents.iplt20.com/bcci/documents/"
    "1711346895837_TATA%20IPL%202024%20Schedule%20F.pdf"
)
IPL_2025_SOURCE = (
    "https://documents.iplt20.com/smart-images/"
    "1739621485265_IPL%20Season%20Schedule%202025-1.pdf"
)
IPL_2026_SOURCE = (
    "https://documents.iplt20.com/bcci/documents/"
    "1774332251856_1773233174530_TATA-IPL-Schedule-2026.pdf"
)

STADIUM = "Rajiv Gandhi International Cricket Stadium, Uppal"

# Each record below is a Hyderabad-hosted IPL fixture.
# Match dates and opponents are based on the official season schedules.
matches = [
    # IPL 2024
    ("2024-03-27", "Sunrisers Hyderabad vs Mumbai Indians", "19:30", IPL_2024_SOURCE),
    ("2024-04-05", "Sunrisers Hyderabad vs Chennai Super Kings", "19:30", IPL_2024_SOURCE),
    ("2024-04-25", "Sunrisers Hyderabad vs Royal Challengers Bengaluru", "19:30", IPL_2024_SOURCE),
    ("2024-05-02", "Sunrisers Hyderabad vs Rajasthan Royals", "19:30", IPL_2024_SOURCE),
    ("2024-05-08", "Sunrisers Hyderabad vs Lucknow Super Giants", "19:30", IPL_2024_SOURCE),
    ("2024-05-19", "Sunrisers Hyderabad vs Punjab Kings", "15:30", IPL_2024_SOURCE),

    # IPL 2025
    ("2025-03-23", "Sunrisers Hyderabad vs Rajasthan Royals", "15:30", IPL_2025_SOURCE),
    ("2025-03-27", "Sunrisers Hyderabad vs Lucknow Super Giants", "19:30", IPL_2025_SOURCE),
    ("2025-04-06", "Sunrisers Hyderabad vs Gujarat Titans", "19:30", IPL_2025_SOURCE),
    ("2025-04-12", "Sunrisers Hyderabad vs Punjab Kings", "19:30", IPL_2025_SOURCE),
    ("2025-04-23", "Sunrisers Hyderabad vs Mumbai Indians", "19:30", IPL_2025_SOURCE),
    ("2025-05-05", "Sunrisers Hyderabad vs Delhi Capitals", "19:30", IPL_2025_SOURCE),
    ("2025-05-10", "Sunrisers Hyderabad vs Kolkata Knight Riders", "19:30", IPL_2025_SOURCE),

    # IPL 2026 — Hyderabad home fixtures within the study period
    ("2026-04-05", "Sunrisers Hyderabad vs Lucknow Super Giants", "15:30", IPL_2026_SOURCE),
    ("2026-04-13", "Sunrisers Hyderabad vs Rajasthan Royals", "19:30", IPL_2026_SOURCE),
    ("2026-04-18", "Sunrisers Hyderabad vs Chennai Super Kings", "19:30", IPL_2026_SOURCE),
    ("2026-04-21", "Sunrisers Hyderabad vs Delhi Capitals", "19:30", IPL_2026_SOURCE),
    ("2026-05-03", "Sunrisers Hyderabad vs Kolkata Knight Riders", "15:30", IPL_2026_SOURCE),
    ("2026-05-06", "Sunrisers Hyderabad vs Punjab Kings", "19:30", IPL_2026_SOURCE),
    ("2026-05-22", "Sunrisers Hyderabad vs Royal Challengers Bengaluru", "19:30", IPL_2026_SOURCE),
]

new_records = []

for event_date, event_name, start_time, source_url in matches:
    new_records.append({
        "event_date": event_date,
        "event_end_date": event_date,
        "event_name": event_name,
        "event_category": "Sports — Cricket",
        "venue": STADIUM,
        "event_level": "Major cricket match",
        "source_url": source_url,
        "research_status": "Official IPL season schedule",
        "city": "Hyderabad",
        "event_start_time": start_time,
        "zone_id": "",
        "latitude": None,
        "longitude": None
    })

new_df = pd.DataFrame(new_records)

if not file_path.exists():
    raise FileNotFoundError(
        f"Existing dataset not found: {file_path}\n"
        "Check the path before continuing."
    )

df = pd.read_csv(file_path)

# Preserve the existing dataset's columns and add any new fields.
for col in new_df.columns:
    if col not in df.columns:
        df[col] = pd.NA

for col in df.columns:
    if col not in new_df.columns:
        new_df[col] = pd.NA

new_df = new_df[df.columns]

# Standardize dates for reliable duplicate checking.
df["event_date"] = pd.to_datetime(
    df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_date"] = pd.to_datetime(
    new_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

# Keep the study period: 1 January 2023 through 31 July 2026.
new_df = new_df[
    (new_df["event_date"] >= "2023-01-01") &
    (new_df["event_date"] <= "2026-07-31")
].copy()

# Match existing records using event date, event name and venue.
key_cols = ["event_date", "event_name", "venue"]

existing_keys = set(
    df[key_cols].fillna("").astype(str).itertuples(index=False, name=None)
)

new_df["_dedupe_key"] = list(
    new_df[key_cols].fillna("").astype(str).itertuples(index=False, name=None)
)

new_df = new_df[~new_df["_dedupe_key"].isin(existing_keys)].copy()
new_df = new_df.drop_duplicates(subset=key_cols)
new_df = new_df.drop(columns=["_dedupe_key"])

added_count = len(new_df)

df = pd.concat([df, new_df], ignore_index=True)
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("\n" + "=" * 72)
print("PHASE 04.7.10 COMPLETED")
print("=" * 72)
print(f"Candidate match records prepared : {len(matches)}")
print(f"New records added                : {added_count}")
print(f"Total records in dataset         : {len(df)}")
print(f"Updated file                     : {file_path}")
print("\nCollection cell completed.")

========================================================================
PHASE 04.7.10 — SPORTS EVENTS & STADIUM GATHERINGS
========================================================================

========================================================================
PHASE 04.7.10 COMPLETED
========================================================================
Candidate match records prepared : 20
New records added                : 20
Total records in dataset         : 411
Updated file                     : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Collection cell completed.

In [120]:
from pathlib import Path
import pandas as pd

print("=" * 72)
print("PHASE 04.7.11 — INTERNATIONAL CRICKET & WORLD CUP EVENTS")
print("=" * 72)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

# Official source references
ICC_WC_SOURCE = (
    "https://www.icc-cricket.com/media-releases/"
    "icc-mens-cricket-world-cup-2023-schedule-announced"
)

ICC_WARMUP_SOURCE = (
    "https://www.icc-cricket.com/media-releases/"
    "icc-mens-cricket-world-cup-2023-warm-up-matches-confirmed"
)

BCCI_2023_SOURCE = (
    "https://www.bcci.tv/news/article/"
    "bcci-announces-fixtures-for-international-home-season-2023-24"
)

BCCI_2024_SOURCE = (
    "https://www.bcci.tv/news/article/"
    "bcci-announces-fixtures-for-team-india-senior-men-international-home-season-2024-25"
)

STADIUM = "Rajiv Gandhi International Cricket Stadium, Uppal, Hyderabad"

# Only include matches with dates and Hyderabad venues supported by
# the official ICC/BCCI schedules.
events = [
    {
        "event_date": "2023-09-29",
        "event_end_date": "2023-09-29",
        "event_name": "ICC World Cup Warm-up — New Zealand vs Pakistan",
        "event_start_time": "14:00",
        "source_url": ICC_WARMUP_SOURCE,
        "research_status": "Official ICC warm-up schedule"
    },
    {
        "event_date": "2023-10-03",
        "event_end_date": "2023-10-03",
        "event_name": "ICC World Cup Warm-up — Pakistan vs Australia",
        "event_start_time": "14:00",
        "source_url": ICC_WARMUP_SOURCE,
        "research_status": "Official ICC warm-up schedule"
    },
    {
        "event_date": "2023-10-06",
        "event_end_date": "2023-10-06",
        "event_name": "ICC Men's Cricket World Cup — Pakistan vs Netherlands",
        "event_start_time": "14:00",
        "source_url": ICC_WC_SOURCE,
        "research_status": "Official ICC tournament schedule"
    },
    {
        "event_date": "2023-10-09",
        "event_end_date": "2023-10-09",
        "event_name": "ICC Men's Cricket World Cup — New Zealand vs Netherlands",
        "event_start_time": "14:00",
        "source_url": ICC_WC_SOURCE,
        "research_status": "Official ICC tournament schedule"
    },
    {
        "event_date": "2023-10-10",
        "event_end_date": "2023-10-10",
        "event_name": "ICC Men's Cricket World Cup — Pakistan vs Sri Lanka",
        "event_start_time": "14:00",
        "source_url": ICC_WC_SOURCE,
        "research_status": "Verify final fixture details against official match archive"
    },
    {
        "event_date": "2023-12-03",
        "event_end_date": "2023-12-03",
        "event_name": "India vs Australia — 5th T20 International",
        "event_start_time": "19:00",
        "source_url": BCCI_2023_SOURCE,
        "research_status": "Official BCCI international schedule"
    },
    {
        "event_date": "2024-01-25",
        "event_end_date": "2024-01-29",
        "event_name": "India vs England — 1st Test Match",
        "event_start_time": "09:30",
        "source_url": BCCI_2023_SOURCE,
        "research_status": "Official BCCI international schedule"
    },
    {
        "event_date": "2024-10-12",
        "event_end_date": "2024-10-12",
        "event_name": "India vs Bangladesh — 3rd T20 International",
        "event_start_time": "19:00",
        "source_url": BCCI_2024_SOURCE,
        "research_status": "Official BCCI international schedule"
    }
]

new_df = pd.DataFrame(events)

new_df["event_category"] = "Sports — International Cricket"
new_df["venue"] = STADIUM
new_df["event_level"] = "International cricket event"
new_df["city"] = "Hyderabad"

# Stadium lies outside the five predefined study zones.
# Leave zone assignment blank rather than assigning it incorrectly.
new_df["zone_id"] = ""
new_df["latitude"] = None
new_df["longitude"] = None

if not file_path.exists():
    raise FileNotFoundError(
        f"Dataset not found: {file_path}"
    )

df = pd.read_csv(file_path)

# Add missing columns while preserving all existing columns and records.
for col in new_df.columns:
    if col not in df.columns:
        df[col] = pd.NA

for col in df.columns:
    if col not in new_df.columns:
        new_df[col] = pd.NA

new_df = new_df[df.columns]

# Standardize dates.
df["event_date"] = pd.to_datetime(
    df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_date"] = pd.to_datetime(
    new_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

# Retain the project's study period.
new_df = new_df[
    (new_df["event_date"] >= "2023-01-01") &
    (new_df["event_date"] <= "2026-07-31")
].copy()

# Avoid duplicate records based on date, event name, and venue.
key_cols = ["event_date", "event_name", "venue"]

existing_keys = set(
    df[key_cols]
    .fillna("")
    .astype(str)
    .itertuples(index=False, name=None)
)

new_df["_key"] = list(
    new_df[key_cols]
    .fillna("")
    .astype(str)
    .itertuples(index=False, name=None)
)

new_df = new_df[~new_df["_key"].isin(existing_keys)].copy()
new_df = new_df.drop_duplicates(subset=key_cols)
new_df = new_df.drop(columns=["_key"])

added_count = len(new_df)

df = pd.concat([df, new_df], ignore_index=True)
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("\n" + "=" * 72)
print("PHASE 04.7.11 COMPLETED")
print("=" * 72)
print(f"Candidate records prepared : {len(events)}")
print(f"New records added          : {added_count}")
print(f"Total records in dataset   : {len(df)}")
print(f"Updated file               : {file_path}")
print("\nCollection cell completed.")

========================================================================
PHASE 04.7.11 — INTERNATIONAL CRICKET & WORLD CUP EVENTS
========================================================================

========================================================================
PHASE 04.7.11 COMPLETED
========================================================================
Candidate records prepared : 8
New records added          : 8
Total records in dataset   : 419
Updated file               : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Collection cell completed.

In [121]:
from pathlib import Path
import pandas as pd

print("=" * 75)
print("PHASE 04.7.12 — LOCAL EVENTS DATA QUALITY AUDIT")
print("=" * 75)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

# Standardize date values for analysis only; do not modify the CSV.
df["event_date_parsed"] = pd.to_datetime(
    df["event_date"], errors="coerce"
)

study_start = pd.Timestamp("2023-01-01")
study_end = pd.Timestamp("2026-07-31")

# Duplicate event checks
duplicate_key = ["event_date", "event_name", "venue"]
available_key = [c for c in duplicate_key if c in df.columns]

if len(available_key) == 3:
    duplicate_rows = df.duplicated(
        subset=available_key, keep=False
    )
    duplicate_count = int(duplicate_rows.sum())
else:
    duplicate_rows = pd.Series(False, index=df.index)
    duplicate_count = None

# Missing values
important_columns = [
    "event_date",
    "event_name",
    "event_category",
    "venue",
    "source_url"
]
important_columns = [
    c for c in important_columns if c in df.columns
]
missing_counts = df[important_columns].isna().sum()

# Empty strings also count as missing.
for col in important_columns:
    if df[col].dtype == "object":
        missing_counts[col] += int(
            df[col].fillna("").astype(str).str.strip().eq("").sum()
        )

# Invalid and out-of-period dates
invalid_date_count = int(df["event_date_parsed"].isna().sum())

outside_period = (
    df["event_date_parsed"].notna()
    & (
        (df["event_date_parsed"] < study_start)
        | (df["event_date_parsed"] > study_end)
    )
)

# Research-status review
if "research_status" in df.columns:
    status = (
        df["research_status"]
        .fillna("Missing status")
        .astype(str)
        .str.strip()
    )
    uncertain_mask = status.str.contains(
        r"confirm|verify|unverified|candidate|uncertain|unknown|missing",
        case=False,
        regex=True
    )
    status_counts = status.value_counts(dropna=False)
else:
    uncertain_mask = pd.Series(False, index=df.index)
    status_counts = pd.Series(dtype="int64")

# Category distribution
if "event_category" in df.columns:
    category_counts = (
        df["event_category"]
        .fillna("Missing category")
        .astype(str)
        .value_counts()
    )
else:
    category_counts = pd.Series(dtype="int64")

print(f"\nTotal records: {len(df)}")
print(f"Total columns: {len(df.columns) - 1}")  # Excludes temporary parsed date
print(f"Invalid/missing event dates: {invalid_date_count}")
print(f"Records outside study period: {int(outside_period.sum())}")

if duplicate_count is not None:
    print(f"Rows involved in duplicate groups: {duplicate_count}")
else:
    print("Duplicate check skipped: required columns are missing.")

print("\n--- Missing values in important columns ---")
print(missing_counts.to_string())

print("\n--- Research-status distribution ---")
if len(status_counts):
    print(status_counts.to_string())
else:
    print("No research_status column found.")

print("\n--- Event category distribution ---")
if len(category_counts):
    print(category_counts.to_string())
else:
    print("No event_category column found.")

print("\n--- Records requiring research-status review ---")
print(f"Potentially uncertain records: {int(uncertain_mask.sum())}")

review_columns = [
    c for c in [
        "event_date", "event_name", "event_category",
        "venue", "zone_id", "research_status", "source_url"
    ]
    if c in df.columns
]

review_df = df.loc[uncertain_mask, review_columns].copy()

if len(review_df):
    display(review_df.head(30))
else:
    print("No records were flagged by the research-status text check.")

print("\n--- Duplicate records for review ---")
if duplicate_count:
    display(df.loc[duplicate_rows, review_columns].head(30))
else:
    print("No duplicate groups detected using date + event name + venue.")

print("\nAudit complete. No records were changed or deleted.")

===========================================================================
PHASE 04.7.12 — LOCAL EVENTS DATA QUALITY AUDIT
===========================================================================

Total records: 419
Total columns: 13
Invalid/missing event dates: 0
Records outside study period: 0
Rows involved in duplicate groups: 0

--- Missing values in important columns ---
event_date        0
event_name        0
event_category    0
venue             4
source_url        0

--- Research-status distribution ---
research_status
Missing status                                                  331
Official IPL season schedule                                     20
Archive candidate                                                13
HITEX event archive                                               7
Published event report                                            6
Needs confirmation                                                3
Venue needs confirmation                                          3
Official BCCI international schedule                              3
Organizer/artist source                                           2
Artist/official tour source                                       2
Race archive                                                      2
Organizer event archive                                           2
Official ICC warm-up schedule                                     2
Official ICC tournament schedule                                  2
Organizer archive; date needs confirmation                        1
Organizer/venue source                                            1
Organizer archive; venue needs confirmation                       1
Organizer page; event details should be confirmed                 1
Cancelled                                                         1
Published event listing; dates require source reconciliation      1
Published government tourism listing                              1
Organizer brochure                                                1
HITEX listing; extended dates require confirmation                1
Official festival source                                          1
Published organizer schedule                                      1
Government tourism portal; outside central Hyderabad              1
Organizer website; date and venue should be confirmed             1
Published event announcement                                      1
Official festival website                                         1
Published race information                                        1
Race archive; multiple race venues                                1
Annual event; 2023-specific details need confirmation             1
Official Telangana government source                              1
Annual event; venue-specific details need confirmation            1
Verify final fixture details against official match archive       1

--- Event category distribution ---
event_category
Exhibition and Trade Fair          154
Other Organised Event               91
Entertainment and Public Events     57
Food and Culinary                   31
Cultural and Community              23
Sports — Cricket                    20
Literary and Educational             8
Sports — International Cricket       8
Religious Festival                   6
Educational and Community            6
Educational and Technology           5
Major Public Gathering               4
Government and Community             3
Charity and Public Awareness         2
Religious and Cultural Festival      1

--- Records requiring research-status review ---
Potentially uncertain records: 358

,event_date,event_name,event_category,venue,zone_id,research_status,source_url
0,2026-07-31,Deep Mela,Cultural and Community,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/deep-mela-1/index.html
1,2026-07-30,Eco Sustain Expo 3rd Edition,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/eco-sustain-expo-2026/index.html
2,2026-07-30,IPEC 5th Edition,Other Organised Event,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/ipec-2026/index.html
3,2026-07-30,Renewable Restart Energy India Expo,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/renewable-restart-energy-india-expo-1/index.html
4,2026-07-25,TV9 Sweet Home Expo 2026,Food and Culinary,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/tv9-sweet-home-expo-2026/index.html
5,2026-07-25,Hyderabad Dental Convention,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/hyderabad-dental-convention/index.html
6,2026-07-24,International Furniture Expo,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/international-furniture-expo/index.html
7,2026-07-16,Tube & Pipe Fair South,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/tube-pipe-fair-south/index.html
8,2026-07-16,World Mithai Namkeen Convention & Expo 2026,Food and Culinary,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/world-mithai-namkeen-convention-expo-2026/index.html
9,2026-07-09,Pharma Pro & Pack Expo,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/pharma-pro-pack-expo-2/index.html
10,2026-07-02,Food A’Fair,Food and Culinary,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/food-afair-1/index.html
11,2026-06-26,All in Print Asia,Other Organised Event,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/all-in-print-asia/index.html
12,2026-06-26,Industrial Innovation & Technology Expo 2026,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/industrial-innovation-technology-expo-2026/index.html
13,2026-06-20,The Homeware Expo,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/the-homeware-expo/index.html
14,2026-06-19,IIID Showcase Insider X 2026,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/iiid-showcase-insider-x-2026/index.html
15,2026-06-19,Earthcon Expo,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/earthcon-expo/index.html
16,2026-06-15,Creative Economy Conclave,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/creative-economy-conclave/index.html
17,2026-06-14,India for MICE 2026 2nd Edition,Other Organised Event,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/india-for-mice-2026-2nd-edition/index.html
18,2026-06-13,Times Home Hunt Property Expo 2026,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/times-home-hunt-property-expo-2026/index.html
19,2026-06-12,INDOMACH,Other Organised Event,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/indomach-2/index.html
20,2026-06-12,Style Tatva 2026,Cultural and Community,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/style-tatva-2026/index.html
21,2026-06-12,South India Wedding Planners Congress,Other Organised Event,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/south-india-wedding-planners-congress/index.html
22,2026-06-05,19th International Rice & Grain Tech Expo,Food and Culinary,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/19th-international-rice-grain-tech-expo/index.html
23,2026-06-05,Threads Pochampally,Other Organised Event,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/threads-pochampally/index.html
24,2026-05-29,India Stone & Tech Expo 2026,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/india-stone-tech-expo-2026/index.html
25,2026-05-22,TV9 Network Education Expo 2026,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/tv9-network-education-expo-2026/index.html
26,2026-05-08,16th Edition Hyderabad Jewellery Pearl & Gem Fair,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/16th-edition-hyderabad-jewellery-pearl-gem-fair/index.html
27,2026-04-23,India Pharma Expo 2026,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/india-pharma-expo-2026/index.html
28,2026-04-18,Times Property Expo 2026,Exhibition and Trade Fair,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/times-property-expo-2026/index.html
29,2026-04-04,Medicall,Other Organised Event,HITEX Exhibition Centre,NaN,NaN,https://hitex.co.in/events/medicall-2/index.html

--- Duplicate records for review ---
No duplicate groups detected using date + event name + venue.

Audit complete. No records were changed or deleted.

In [122]:
from pathlib import Path
import pandas as pd

print("=" * 72)
print("PHASE 04.7.12 — STEP 2: MISSING VENUE INVESTIGATION")
print("=" * 72)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

df = pd.read_csv(file_path)

# Treat blank strings and whitespace as missing.
missing_venue = (
    df["venue"].isna()
    | df["venue"].astype(str).str.strip().eq("")
)

missing_records = df.loc[missing_venue].copy()

display_columns = [
    col for col in [
        "event_date",
        "event_name",
        "event_category",
        "venue",
        "city",
        "zone_id",
        "source_url",
        "research_status"
    ]
    if col in df.columns
]

print(f"Records with missing venues: {len(missing_records)}")

if not missing_records.empty:
    display(missing_records[display_columns])
else:
    print("No missing venues found.")

print("\nNo changes made to the original dataset.")

========================================================================
PHASE 04.7.12 — STEP 2: MISSING VENUE INVESTIGATION
========================================================================
Records with missing venues: 4

,event_date,event_name,event_category,venue,city,zone_id,source_url,research_status
338,2023-12-17,Massano Live,Entertainment and Public Events,NaN,Hyderabad,NaN,https://www.concertarchives.org/locations/hyderabad-india,Venue needs confirmation
341,2024-02-23,"Anjunadeep, Anyasa, CRi, HANA and Others",Entertainment and Public Events,NaN,Hyderabad,NaN,https://www.concertarchives.org/locations/hyderabad-india,Venue needs confirmation
351,2024-12-29,Ben Böhmer Live,Entertainment and Public Events,NaN,Hyderabad,NaN,https://telanganatoday.com/hyderabad-all-ready-to-rock-with-star-studded-concerts-in-upcoming-weeks,Venue needs confirmation
360,2025-11-08,A. R. Rahman Live in Hyderabad,Entertainment and Public Events,NaN,Hyderabad,NaN,https://hyderabadtalkies.events/past-events/,Organizer archive; venue needs confirmation

No changes made to the original dataset.

In [123]:
from pathlib import Path
import pandas as pd
import shutil

print("=" * 72)
print("PHASE 04.7.12 — STEP 3: UPDATE CONFIRMED VENUES")
print("=" * 72)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

# Confirmed venue updates based on published event listings.
venue_updates = {
    ("2024-12-29", "Ben Böhmer Live"):
        "Quake Arena, Hyderabad",

    ("2025-11-08", "A. R. Rahman Live in Hyderabad"):
        "Ramoji Film City, Hyderabad"
}

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

df = pd.read_csv(file_path)

required_columns = [
    "event_date", "event_name", "venue"
]

missing_columns = [
    col for col in required_columns if col not in df.columns
]

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

# Make a backup before modifying the dataset.
backup_path = file_path.with_name(
    file_path.stem + "_before_venue_updates.csv"
)
shutil.copy2(file_path, backup_path)

df["event_date"] = pd.to_datetime(
    df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

if "research_status" not in df.columns:
    df["research_status"] = pd.NA

updated_count = 0

for (event_date, event_name), confirmed_venue in venue_updates.items():
    mask = (
        df["event_date"].eq(event_date)
        & df["event_name"].astype(str).str.contains(
            event_name, case=False, regex=False, na=False
        )
    )

    matched_rows = df.index[mask].tolist()

    if len(matched_rows) == 1:
        idx = matched_rows[0]
        df.at[idx, "venue"] = confirmed_venue
        df.at[idx, "research_status"] = (
            "Venue supported by published event listing"
        )
        updated_count += 1
        print(f"UPDATED: {event_name} -> {confirmed_venue}")

    elif len(matched_rows) == 0:
        print(f"NOT FOUND: {event_name} on {event_date}")

    else:
        print(
            f"AMBIGUOUS MATCH: {event_name} on {event_date}; "
            "no changes made to this event."
        )

# Flag the remaining two records without inventing their venues.
unresolved_names = ["Massano Live", "Anjunadeep"]

for name in unresolved_names:
    mask = (
        df["event_name"].astype(str).str.contains(
            name, case=False, regex=False, na=False
        )
        & (
            df["venue"].isna()
            | df["venue"].astype(str).str.strip().eq("")
        )
    )

    df.loc[mask, "research_status"] = (
        "Venue requires further verification"
    )

df.to_csv(file_path, index=False, encoding="utf-8-sig")

missing_venues = (
    df["venue"].isna()
    | df["venue"].astype(str).str.strip().eq("")
)

print("\n" + "=" * 72)
print("VENUE UPDATE SUMMARY")
print("=" * 72)
print(f"Records updated: {updated_count}")
print(f"Records still missing venues: {int(missing_venues.sum())}")
print(f"Dataset records: {len(df)}")
print(f"Backup saved: {backup_path}")
print(f"Updated dataset: {file_path}")
print("\nNo unverified venue names were invented.")

========================================================================
PHASE 04.7.12 — STEP 3: UPDATE CONFIRMED VENUES
========================================================================
UPDATED: Ben Böhmer Live -> Quake Arena, Hyderabad
UPDATED: A. R. Rahman Live in Hyderabad -> Ramoji Film City, Hyderabad

========================================================================
VENUE UPDATE SUMMARY
========================================================================
Records updated: 2
Records still missing venues: 2
Dataset records: 419
Backup saved: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026_before_venue_updates.csv
Updated dataset: d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

No unverified venue names were invented.

In [124]:
from pathlib import Path
import pandas as pd
import shutil

print("=" * 76)
print("PHASE 04.7.13 — FINAL LOCAL EVENTS COLLECTION")
print("=" * 76)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

df = pd.read_csv(file_path)

# ------------------------------------------------------------
# 1. ADDITIONAL PUBLIC EVENTS
# ------------------------------------------------------------
# These are additional candidate records based on published
# event information. Existing records are retained.
#
# Note:
# - Dates and venues should be checked against their source URLs.
# - No event is assigned to a study zone without justification.
# - These are additions, not a claim that every Hyderabad event
#   from 2023 through July 2026 has been collected.

events = [
    {
        "event_date": "2023-10-05",
        "event_end_date": "2023-10-15",
        "event_name": "SARAS Fair 2023",
        "event_category": "Public Fair and Community Event",
        "venue": "HMDA Ground, Hyderabad",
        "event_level": "Large public fair",
        "source_url": (
            "https://www.efms.serp.telangana.gov.in/"
            "Livelihoods/SARAS/Views/SarasHome.aspx"
        ),
        "research_status": "Government event record",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2024-09-26",
        "event_end_date": "2024-10-07",
        "event_name": "SARAS Fair 2024",
        "event_category": "Public Fair and Community Event",
        "venue": "People's Plaza, Necklace Road, Hyderabad",
        "event_level": "Large public fair",
        "source_url": (
            "https://www.efms.serp.telangana.gov.in/"
            "Livelihoods/SARAS/Views/SarasHome.aspx"
        ),
        "research_status": "Government event record",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2023-10-20",
        "event_end_date": "2023-10-22",
        "event_name": "Hyderabad Metro Fest",
        "event_category": "Cultural and Community",
        "venue": "Ameerpet Metro Station",
        "event_level": "Public cultural event",
        "source_url": (
            "https://www.ltmetro.in/pressreleases/2023/"
            "2023-11-02_hyderabad-metro-rail-metro-fest-"
            "exciting-3-day-metro-fest-for-hyderabad-metro-"
            "rail-commuters"
        ),
        "research_status": "Published event report",
        "city": "Hyderabad",
        "event_start_time": "15:00",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2023-12-31",
        "event_end_date": "2023-12-31",
        "event_name": "LuLu Mall NYE Fiesta",
        "event_category": "Entertainment and Public Events",
        "venue": "LuLu Mall, Kukatpally",
        "event_level": "Mall public event",
        "source_url": "https://www.hyderabad.lulumall.in/events-3/",
        "research_status": "Mall event archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2024-01-26",
        "event_end_date": "2024-01-27",
        "event_name": "LuLu Mall Rhythm of Republic",
        "event_category": "Entertainment and Public Events",
        "venue": "LuLu Mall, Kukatpally",
        "event_level": "Mall public event",
        "source_url": "https://www.hyderabad.lulumall.in/events-3/",
        "research_status": "Mall event archive",
        "city": "Hyderabad",
        "event_start_time": "18:00",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2024-03-10",
        "event_end_date": "2024-03-10",
        "event_name": "LuLu Wonder Women",
        "event_category": "Community and Entertainment",
        "venue": "LuLu Mall, Kukatpally",
        "event_level": "Mall public event",
        "source_url": "https://www.hyderabad.lulumall.in/events-3/",
        "research_status": "Mall event archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2025-06-13",
        "event_end_date": "2025-06-13",
        "event_name": "LuLu UIC Fight Night 2",
        "event_category": "Sports and Entertainment",
        "venue": "LuLu Mall, Kukatpally",
        "event_level": "Public sporting entertainment",
        "source_url": "https://www.hyderabad.lulumall.in/events-3/",
        "research_status": "Mall event archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2025-05-22",
        "event_end_date": "2025-05-22",
        "event_name": "LuLu Mall Summer Games",
        "event_category": "Sports and Entertainment",
        "venue": "LuLu Mall, Kukatpally",
        "event_level": "Mall public event",
        "source_url": "https://www.hyderabad.lulumall.in/events-3/",
        "research_status": "Mall event archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    }
]

new_df = pd.DataFrame(events)

# ------------------------------------------------------------
# 2. STANDARDIZE EXISTING DATA AND PREPARE SCHEMA
# ------------------------------------------------------------

if "event_date" not in df.columns:
    raise ValueError("The existing dataset has no event_date column.")

if "event_name" not in df.columns:
    raise ValueError("The existing dataset has no event_name column.")

if "venue" not in df.columns:
    raise ValueError("The existing dataset has no venue column.")

df["event_date"] = pd.to_datetime(
    df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_date"] = pd.to_datetime(
    new_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_end_date"] = pd.to_datetime(
    new_df["event_end_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

# Restrict additions to the study period.
new_df = new_df[
    new_df["event_date"].between("2023-01-01", "2026-07-31")
].copy()

# Preserve existing columns and add new columns only when needed.
for col in new_df.columns:
    if col not in df.columns:
        df[col] = pd.NA

for col in df.columns:
    if col not in new_df.columns:
        new_df[col] = pd.NA

new_df = new_df[df.columns]

# ------------------------------------------------------------
# 3. DEDUPLICATE
# ------------------------------------------------------------

key_cols = ["event_date", "event_name", "venue"]

for col in key_cols:
    df[col] = df[col].fillna("").astype(str).str.strip()
    new_df[col] = new_df[col].fillna("").astype(str).str.strip()

existing_keys = set(
    df[key_cols].itertuples(index=False, name=None)
)

new_df["_dedupe_key"] = list(
    new_df[key_cols].itertuples(index=False, name=None)
)

new_df = new_df[
    ~new_df["_dedupe_key"].isin(existing_keys)
].copy()

new_df = new_df.drop_duplicates(subset=key_cols)
new_df = new_df.drop(columns=["_dedupe_key"])

# ------------------------------------------------------------
# 4. BACK UP AND SAVE
# ------------------------------------------------------------

backup_path = file_path.with_name(
    file_path.stem + "_before_phase_04_7_13.csv"
)

shutil.copy2(file_path, backup_path)

added_count = len(new_df)

df = pd.concat([df, new_df], ignore_index=True)

df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("\n" + "=" * 76)
print("PHASE 04.7.13 COMPLETED")
print("=" * 76)
print(f"Candidate records prepared : {len(events)}")
print(f"New records added          : {added_count}")
print(f"Existing records retained  : {len(df) - added_count}")
print(f"Total records now          : {len(df)}")
print(f"Backup saved               : {backup_path}")
print(f"Updated dataset            : {file_path}")
print("\nCollection cell completed.")

============================================================================
PHASE 04.7.13 — FINAL LOCAL EVENTS COLLECTION
============================================================================

============================================================================
PHASE 04.7.13 COMPLETED
============================================================================
Candidate records prepared : 8
New records added          : 8
Existing records retained  : 419
Total records now          : 427
Backup saved               : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026_before_phase_04_7_13.csv
Updated dataset            : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Collection cell completed.

In [125]:
from pathlib import Path
import pandas as pd
import shutil

print("=" * 76)
print("PHASE 04.7.14 — ART EXHIBITIONS & GALLERY EVENTS")
print("=" * 76)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

SOURCE_URL = "https://www.ekchitra.com/exhibitions"

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

df = pd.read_csv(file_path)

# Events and dates listed in the gallery's published exhibition archive.
# Venue is recorded at gallery level because the source page does not
# establish a street address for every historical exhibition.

events = [
    {
        "event_date": "2023-09-01",
        "event_end_date": "2023-09-01",
        "event_name": "Tree of Life — Art Exhibition",
        "event_category": "Art and Cultural Exhibition",
        "venue": "Ekchitra Gallery, Hyderabad",
        "event_level": "Gallery exhibition",
        "source_url": SOURCE_URL,
        "research_status": "Listed in gallery exhibition archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2024-01-21",
        "event_end_date": "2024-01-29",
        "event_name": "Katha Kathan — Art Exhibition",
        "event_category": "Art and Cultural Exhibition",
        "venue": "Ekchitra Gallery, Hyderabad",
        "event_level": "Multi-day gallery exhibition",
        "source_url": SOURCE_URL,
        "research_status": "Dates listed in gallery exhibition archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2024-03-22",
        "event_end_date": "2024-03-22",
        "event_name": "Mirror Mirror — Champa Tree Exhibition",
        "event_category": "Art and Cultural Exhibition",
        "venue": "Ekchitra Gallery, Hyderabad",
        "event_level": "Gallery exhibition",
        "source_url": SOURCE_URL,
        "research_status": "Date listed in gallery exhibition archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2025-02-14",
        "event_end_date": "2025-02-23",
        "event_name": "Naik City — Art Exhibition",
        "event_category": "Art and Cultural Exhibition",
        "venue": "Ekchitra Gallery, Hyderabad",
        "event_level": "Multi-day gallery exhibition",
        "source_url": SOURCE_URL,
        "research_status": "Dates listed in gallery exhibition archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2025-02-28",
        "event_end_date": "2025-03-04",
        "event_name": "Living Temple — Art Exhibition",
        "event_category": "Art and Cultural Exhibition",
        "venue": "Ekchitra Gallery, Hyderabad",
        "event_level": "Multi-day gallery exhibition",
        "source_url": SOURCE_URL,
        "research_status": "Dates listed in gallery exhibition archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2025-03-07",
        "event_end_date": "2025-03-16",
        "event_name": "Swadhatri — Art Exhibition",
        "event_category": "Art and Cultural Exhibition",
        "venue": "Ekchitra Gallery, Hyderabad",
        "event_level": "Multi-day gallery exhibition",
        "source_url": SOURCE_URL,
        "research_status": "Dates listed in gallery exhibition archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2025-12-19",
        "event_end_date": "2025-12-21",
        "event_name": "HYD ART — Art Exhibition",
        "event_category": "Art and Cultural Exhibition",
        "venue": "Ekchitra Gallery, Hyderabad",
        "event_level": "Multi-day art exhibition",
        "source_url": SOURCE_URL,
        "research_status": "Dates listed in gallery exhibition archive",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    }
]

new_df = pd.DataFrame(events)

# Standardize dates for the study period.
df["event_date"] = pd.to_datetime(
    df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_date"] = pd.to_datetime(
    new_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_end_date"] = pd.to_datetime(
    new_df["event_end_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df = new_df[
    new_df["event_date"].between("2023-01-01", "2026-07-31")
].copy()

# Preserve the existing schema while allowing new columns when necessary.
for col in new_df.columns:
    if col not in df.columns:
        df[col] = pd.NA

for col in df.columns:
    if col not in new_df.columns:
        new_df[col] = pd.NA

new_df = new_df[df.columns]

# Remove exact duplicates using the project's existing deduplication key.
key_cols = ["event_date", "event_name", "venue"]

for col in key_cols:
    df[col] = df[col].fillna("").astype(str).str.strip()
    new_df[col] = new_df[col].fillna("").astype(str).str.strip()

existing_keys = set(
    df[key_cols].itertuples(index=False, name=None)
)

new_df["_key"] = list(
    new_df[key_cols].itertuples(index=False, name=None)
)

new_df = new_df[
    ~new_df["_key"].isin(existing_keys)
].copy()

new_df = new_df.drop_duplicates(subset=key_cols)
new_df = new_df.drop(columns=["_key"])

# Create a backup before writing changes.
backup_path = file_path.with_name(
    file_path.stem + "_before_phase_04_7_14.csv"
)

shutil.copy2(file_path, backup_path)

added_count = len(new_df)

df = pd.concat([df, new_df], ignore_index=True)
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("\n" + "=" * 76)
print("PHASE 04.7.14 COMPLETED")
print("=" * 76)
print(f"Candidate records prepared : {len(events)}")
print(f"New records added          : {added_count}")
print(f"Total records now          : {len(df)}")
print(f"Backup saved               : {backup_path}")
print(f"Updated dataset            : {file_path}")
print("\nCollection cell completed.")

============================================================================
PHASE 04.7.14 — ART EXHIBITIONS & GALLERY EVENTS
============================================================================

============================================================================
PHASE 04.7.14 COMPLETED
============================================================================
Candidate records prepared : 7
New records added          : 7
Total records now          : 434
Backup saved               : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026_before_phase_04_7_14.csv
Updated dataset            : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Collection cell completed.

In [126]:
from pathlib import Path
import pandas as pd
import shutil

print("=" * 76)
print("PHASE 04.7.15 — RELIGIOUS FESTIVALS & PUBLIC GATHERINGS")
print("=" * 76)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

df = pd.read_csv(file_path)

# Official/reliable source references
BONALU_2024_SOURCE = (
    "https://utsav.gov.in/view-event/bonalu"
)

BONALU_2025_SOURCE = (
    "https://utsav.gov.in/view-event/bonalu-2"
)

BATHUKAMMA_2025_SOURCE = (
    "https://utsav.gov.in/view-event/bathukamma"
)

BATHUKAMMA_2023_SOURCE = (
    "https://tg.nic.in/en/event/bathukamma-celebrations-held-at-nic-hyderabad/"
)

GANESH_2024_SOURCE = (
    "https://hyderabadpolice.gov.in/assets/news/2024/09Sep/15092024.pdf"
)

events = [
    {
        "event_date": "2024-07-07",
        "event_end_date": "2024-08-04",
        "event_name": "Bonalu Festival 2024 — Hyderabad and Secunderabad",
        "event_category": "Religious and Cultural Festival",
        "venue": "Golconda Fort, Lal Darwaza and Mahankali Temple, Secunderabad",
        "event_level": "Major citywide religious festival",
        "source_url": BONALU_2024_SOURCE,
        "research_status": "Published tourism event record",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2025-06-29",
        "event_end_date": "2025-07-20",
        "event_name": "Bonalu Festival 2025 — Hyderabad and Secunderabad",
        "event_category": "Religious and Cultural Festival",
        "venue": "Golconda Fort, Lal Darwaza and Mahankali Temple, Secunderabad",
        "event_level": "Major citywide religious festival",
        "source_url": BONALU_2025_SOURCE,
        "research_status": "Published tourism event record",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2025-09-21",
        "event_end_date": "2025-09-30",
        "event_name": "Bathukamma Festival 2025 — Hyderabad",
        "event_category": "Religious and Cultural Festival",
        "venue": "LB Stadium and Tank Bund, Hyderabad",
        "event_level": "Major public cultural festival",
        "source_url": BATHUKAMMA_2025_SOURCE,
        "research_status": "Published government tourism event record",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2023-10-18",
        "event_end_date": "2023-10-18",
        "event_name": "Bathukamma Celebrations — NIC Hyderabad",
        "event_category": "Religious and Cultural Festival",
        "venue": "National Informatics Centre, Hyderabad",
        "event_level": "Institutional cultural celebration",
        "source_url": BATHUKAMMA_2023_SOURCE,
        "research_status": "Published government event record",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    },
    {
        "event_date": "2024-09-17",
        "event_end_date": "2024-09-17",
        "event_name": "Ganesh Immersion Procession — Hyderabad",
        "event_category": "Religious and Cultural Festival",
        "venue": "Hyderabad city procession routes",
        "event_level": "Major public religious gathering",
        "source_url": GANESH_2024_SOURCE,
        "research_status": "Hyderabad Police traffic notification",
        "city": "Hyderabad",
        "event_start_time": "",
        "zone_id": "",
        "latitude": None,
        "longitude": None
    }
]

new_df = pd.DataFrame(events)

# Standardize dates.
df["event_date"] = pd.to_datetime(
    df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_date"] = pd.to_datetime(
    new_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_end_date"] = pd.to_datetime(
    new_df["event_end_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

# Keep records within the study period.
new_df = new_df[
    new_df["event_date"].between("2023-01-01", "2026-07-31")
].copy()

# Preserve the existing schema.
for col in new_df.columns:
    if col not in df.columns:
        df[col] = pd.NA

for col in df.columns:
    if col not in new_df.columns:
        new_df[col] = pd.NA

new_df = new_df[df.columns]

# Remove exact duplicates.
key_cols = ["event_date", "event_name", "venue"]

for col in key_cols:
    df[col] = df[col].fillna("").astype(str).str.strip()
    new_df[col] = new_df[col].fillna("").astype(str).str.strip()

existing_keys = set(
    df[key_cols].itertuples(index=False, name=None)
)

new_df["_key"] = list(
    new_df[key_cols].itertuples(index=False, name=None)
)

new_df = new_df[
    ~new_df["_key"].isin(existing_keys)
].copy()

new_df = new_df.drop_duplicates(subset=key_cols)
new_df = new_df.drop(columns=["_key"])

# Back up the existing dataset before saving.
backup_path = file_path.with_name(
    file_path.stem + "_before_phase_04_7_15.csv"
)

shutil.copy2(file_path, backup_path)

added_count = len(new_df)

df = pd.concat([df, new_df], ignore_index=True)
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("\n" + "=" * 76)
print("PHASE 04.7.15 COMPLETED")
print("=" * 76)
print(f"Candidate records prepared : {len(events)}")
print(f"New records added          : {added_count}")
print(f"Total records now          : {len(df)}")
print(f"Backup saved               : {backup_path}")
print(f"Updated dataset            : {file_path}")
print("\nCollection cell completed.")

============================================================================
PHASE 04.7.15 — RELIGIOUS FESTIVALS & PUBLIC GATHERINGS
============================================================================

============================================================================
PHASE 04.7.15 COMPLETED
============================================================================
Candidate records prepared : 5
New records added          : 5
Total records now          : 439
Backup saved               : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026_before_phase_04_7_15.csv
Updated dataset            : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Collection cell completed.

In [127]:
from pathlib import Path
import pandas as pd
import shutil

print("=" * 80)
print("PHASE 04.7.16 — FINAL COMPREHENSIVE LOCAL EVENTS COLLECTION")
print("=" * 80)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

SOURCE_URL = "https://hitex.co.in/events/past.html"

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

df = pd.read_csv(file_path)

# ------------------------------------------------------------
# OFFICIAL HITEX ARCHIVE EVENTS
# Dates and names below are drawn from the published archive.
# event_date is the first day of the event.
# ------------------------------------------------------------

raw_events = [
    # -------------------- 2023 --------------------
    ("2023-01-04", "2023-01-05", "ET Tech X 2023", "Education and Technology"),
    ("2023-01-08", "2023-01-10", "Indus Food 2023", "Food and Culinary Exhibition"),
    ("2023-01-20", "2023-01-22", "ACETECH 2023", "Architecture and Design Exhibition"),
    ("2023-01-27", "2023-01-29", "PETEX INDIA 5th Edition", "Pet Exhibition"),
    ("2023-02-03", "2023-02-05", "Food Expo 2023", "Food and Culinary Exhibition"),
    ("2023-02-03", "2023-02-05", "Dairy Expo 2023", "Food and Agriculture Exhibition"),
    ("2023-02-19", "2023-02-19", "Sunday Soul Sante", "Lifestyle and Public Market"),
    ("2023-03-03", "2023-03-05", "Kisan Agri Show 2023", "Agriculture Exhibition"),
    ("2023-03-10", "2023-03-12", "Rice & Grains Tech Expo 2023", "Food and Agriculture Exhibition"),
    ("2023-03-17", "2023-03-19", "Medicall 2023", "Healthcare Exhibition"),
    ("2023-03-18", "2023-03-19", "FRO Expo 2023", "Business and Franchise Exhibition"),
    ("2023-04-14", "2023-04-16", "TV9 Sweet Home Real Estate & Interiors Expo 2023", "Property and Home Exhibition"),
    ("2023-04-28", "2023-04-29", "RenewX 2023", "Energy and Technology Exhibition"),
    ("2023-05-12", "2023-05-14", "IndoMach 2023", "Industrial Exhibition"),
    ("2023-05-19", "2023-05-21", "Hyderabad International Jewellery Show 2023", "Consumer Exhibition"),
    ("2023-06-21", "2023-06-23", "Bakery Business South Edition 2023", "Food and Culinary Exhibition"),
    ("2023-06-28", "2023-06-30", "Industrial Innovation & Technology Expo 2023", "Industrial Exhibition"),
    ("2023-07-15", "2023-07-16", "Hyderabad Dental Show 2023", "Healthcare Exhibition"),
    ("2023-07-28", "2023-07-30", "IGBC Green Property Show 2023", "Property and Sustainability Exhibition"),
    ("2023-08-18", "2023-08-21", "HIMTEX 7th Edition", "Industrial Exhibition"),
    ("2023-08-25", "2023-08-27", "Sport Expo India 6th Edition", "Sports Exhibition"),
    ("2023-09-14", "2023-09-16", "India Lab Expo & Analytica Anacon India 2023", "Science and Technology Exhibition"),
    ("2023-10-06", "2023-10-08", "NAREDCO Telangana Property Show 2023", "Property Exhibition"),
    ("2023-10-27", "2023-10-29", "India Med Expo 2023", "Healthcare Exhibition"),
    ("2023-11-03", "2023-11-05", "DreamHack Hyderabad 2023", "Gaming and Entertainment"),
    ("2023-11-22", "2023-11-24", "Poultry India 2023", "Agriculture Exhibition"),
    ("2023-12-01", "2023-12-03", "India International Travel Mart 2023", "Travel Exhibition"),
    ("2023-12-15", "2023-12-16", "ET Tech X 2023", "Education and Technology"),
    ("2023-12-22", "2023-12-24", "Hyderabad Kids' Fair 16th Edition", "Family and Consumer Exhibition"),

    # -------------------- 2024 --------------------
    ("2024-01-19", "2024-01-21", "ACETECH 2024", "Architecture and Design Exhibition"),
    ("2024-01-27", "2024-01-28", "Hyderabad Comic Con 2024", "Gaming and Entertainment"),
    ("2024-02-01", "2024-02-03", "Kisan Agri Show 2024", "Agriculture Exhibition"),
    ("2024-03-03", "2024-03-03", "Sunday Soul Sante", "Lifestyle and Public Market"),
    ("2024-03-16", "2024-03-17", "FRO Expo 2024", "Business and Franchise Exhibition"),
    ("2024-03-29", "2024-05-05", "The Real Van Gogh Immersive Experience", "Art and Cultural Exhibition"),
    ("2024-04-06", "2024-04-08", "Medicall 2024", "Healthcare Exhibition"),
    ("2024-04-19", "2024-04-21", "Sign India 2024", "Business Exhibition"),
    ("2024-04-26", "2024-04-27", "RenewX 2024", "Energy and Technology Exhibition"),
    ("2024-05-17", "2024-05-19", "IGBC Green Property Show 2024", "Property and Sustainability Exhibition"),
    ("2024-06-07", "2024-06-09", "Hyderabad Jewellery Pearl & Gem Fair 2024", "Consumer Exhibition"),
    ("2024-06-13", "2024-06-15", "Food A'FAIR 2024", "Food and Culinary Exhibition"),
    ("2024-06-21", "2024-06-23", "IndoMach 2024", "Industrial Exhibition"),
    ("2024-06-28", "2024-06-30", "BGMI Series 2024", "Gaming and Entertainment"),
    ("2024-07-20", "2024-07-21", "Style Tatva 2024", "Fashion and Lifestyle Exhibition"),
    ("2024-08-16", "2024-08-19", "HIMTEX 8th Edition", "Industrial Exhibition"),
    ("2024-08-23", "2024-08-24", "Sport Expo India 7th Edition", "Sports Exhibition"),
    ("2024-09-26", "2024-09-28", "Analytica Anacon India & India Lab Expo 2024", "Science and Technology Exhibition"),
    ("2024-10-04", "2024-10-06", "Design Democracy 2024", "Art and Design Exhibition"),
    ("2024-10-18", "2024-10-20", "Hyderabad International Jewellery Show 2024", "Consumer Exhibition"),
    ("2024-11-09", "2024-11-11", "All in Print South 2024", "Business Exhibition"),
    ("2024-11-15", "2024-11-17", "DreamHack Hyderabad 2024", "Gaming and Entertainment"),
    ("2024-11-15", "2024-11-17", "Hyderabad Comic Con 2024", "Gaming and Entertainment"),
    ("2024-11-27", "2024-11-29", "Poultry India 2024", "Agriculture Exhibition"),
    ("2024-12-05", "2024-12-07", "ET Tech X 2024", "Education and Technology"),
    ("2024-12-06", "2024-12-08", "India International Travel Mart 2024", "Travel Exhibition"),
    ("2024-12-20", "2024-12-22", "SBI Mega Property Show 2024", "Property Exhibition"),

    # -------------------- 2025 --------------------
    ("2025-01-24", "2025-01-26", "ACETECH 2025", "Architecture and Design Exhibition"),
    ("2025-01-31", "2025-02-02", "Hyderabad Kids' Fair 17th Edition", "Family and Consumer Exhibition"),
    ("2025-02-07", "2025-02-09", "Kisan Agri Show 2025", "Agriculture Exhibition"),
    ("2025-03-08", "2025-03-09", "FRO Expo 2025", "Business and Franchise Exhibition"),
    ("2025-03-22", "2025-03-22", "M. M. Keeravani Live in Concert", "Concert and Entertainment"),
    ("2025-04-05", "2025-04-07", "Medicall 2025", "Healthcare Exhibition"),
    ("2025-04-25", "2025-04-27", "Food India Expo 2025", "Food and Culinary Exhibition"),
    ("2025-05-09", "2025-05-11", "Jewellery & Gem Hyderabad 2025", "Consumer Exhibition"),
    ("2025-05-23", "2025-05-25", "IndoMach 2025", "Industrial Exhibition"),
    ("2025-06-07", "2025-06-08", "The Giggle Fest", "Family and Entertainment"),
    ("2025-06-18", "2025-06-20", "Bakery Business 2025", "Food and Culinary Exhibition"),
    ("2025-06-27", "2025-06-29", "Industrial Innovation & Technology Expo 2025", "Industrial Exhibition"),
    ("2025-07-18", "2025-07-20", "Deep Mela 2025", "Public Fair and Community Event"),
    ("2025-08-22", "2025-08-24", "IPEC 4th Edition", "Industrial Exhibition"),
    ("2025-08-22", "2025-08-24", "Eco Sustain Expo 2nd Edition", "Sustainability Exhibition"),
    ("2025-08-22", "2025-08-23", "Sport Expo India 8th Edition", "Sports Exhibition"),
    ("2025-09-05", "2025-09-07", "Design Democracy 2025", "Art and Design Exhibition"),
    ("2025-09-18", "2025-09-20", "Pharma Pro & Pack Expo 2025", "Healthcare and Industrial Exhibition"),
    ("2025-10-03", "2025-10-05", "JITO Connect 2025", "Business and Community Event"),
    ("2025-10-31", "2025-11-02", "Hyderabad Comic Con 2025", "Gaming and Entertainment"),
    ("2025-10-31", "2025-11-02", "DreamHack Hyderabad 2025", "Gaming and Entertainment"),
    ("2025-11-14", "2025-11-16", "Food Affair 2025", "Food and Culinary Exhibition"),
    ("2025-11-26", "2025-11-28", "Poultry India 2025", "Agriculture Exhibition"),
    ("2025-12-04", "2025-12-06", "India International Travel Mart 2025", "Travel Exhibition"),
    ("2025-12-11", "2025-12-13", "ET Tech X 2025", "Education and Technology"),
    ("2025-12-20", "2025-12-21", "Hyderabad Kids' Fair 2025", "Family and Consumer Exhibition"),

    # -------------------- 2026, through July only --------------------
    ("2026-01-23", "2026-01-25", "ACETECH 2026", "Architecture and Design Exhibition"),
    ("2026-02-06", "2026-02-07", "Global Solar Expo 2026", "Energy and Technology Exhibition"),
    ("2026-02-07", "2026-02-08", "Famdent Hyderabad 2026", "Healthcare Exhibition"),
    ("2026-02-17", "2026-02-18", "Bio Asia 2026", "Biotechnology and Science Event"),
    ("2026-02-26", "2026-02-27", "International Soap & Detergent Expo 2026", "Industrial Exhibition"),
    ("2026-03-13", "2026-03-22", "Furniture Fair 2026", "Consumer Exhibition"),
    ("2026-03-14", "2026-03-15", "FROEXPO 2026", "Business and Franchise Exhibition"),
    ("2026-04-04", "2026-04-06", "Medicall 2026", "Healthcare Exhibition"),
    ("2026-04-18", "2026-04-19", "Times Property Expo 2026", "Property Exhibition"),
    ("2026-04-23", "2026-04-25", "India Pharma Expo 2026", "Healthcare Exhibition"),
    ("2026-05-08", "2026-05-10", "Hyderabad Jewellery Pearl & Gem Fair 2026", "Consumer Exhibition"),
    ("2026-05-22", "2026-05-24", "TV9 Network Education Expo 2026", "Education and Technology"),
    ("2026-05-29", "2026-05-31", "India Stone & Tech Expo 2026", "Industrial Exhibition"),
]

new_df = pd.DataFrame(
    raw_events,
    columns=[
        "event_date",
        "event_end_date",
        "event_name",
        "event_category"
    ]
)

new_df["venue"] = "HITEX Exhibition Centre, Hyderabad"
new_df["event_level"] = "Published exhibition or public event"
new_df["source_url"] = SOURCE_URL
new_df["research_status"] = "Listed in official HITEX past-events archive"
new_df["city"] = "Hyderabad"
new_df["event_start_time"] = ""
new_df["zone_id"] = ""
new_df["latitude"] = pd.NA
new_df["longitude"] = pd.NA

# ------------------------------------------------------------
# DATE FILTERING
# ------------------------------------------------------------

df["event_date"] = pd.to_datetime(
    df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_date"] = pd.to_datetime(
    new_df["event_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df["event_end_date"] = pd.to_datetime(
    new_df["event_end_date"], errors="coerce"
).dt.strftime("%Y-%m-%d")

new_df = new_df[
    new_df["event_date"].between("2023-01-01", "2026-07-31")
].copy()

# ------------------------------------------------------------
# PRESERVE EXISTING SCHEMA
# ------------------------------------------------------------

for col in new_df.columns:
    if col not in df.columns:
        df[col] = pd.NA

for col in df.columns:
    if col not in new_df.columns:
        new_df[col] = pd.NA

new_df = new_df[df.columns]

# ------------------------------------------------------------
# DUPLICATE CHECK
# ------------------------------------------------------------

key_cols = ["event_date", "event_name", "venue"]

for col in key_cols:
    df[col] = df[col].fillna("").astype(str).str.strip()
    new_df[col] = new_df[col].fillna("").astype(str).str.strip()

existing_keys = set(
    df[key_cols].itertuples(index=False, name=None)
)

new_df["_dedupe_key"] = list(
    new_df[key_cols].itertuples(index=False, name=None)
)

candidate_count = len(new_df)

new_df = new_df[
    ~new_df["_dedupe_key"].isin(existing_keys)
].copy()

new_df = new_df.drop_duplicates(subset=key_cols)
new_df = new_df.drop(columns=["_dedupe_key"])

# ------------------------------------------------------------
# BACKUP AND SAVE
# ------------------------------------------------------------

backup_path = file_path.with_name(
    file_path.stem + "_before_phase_04_7_16.csv"
)

shutil.copy2(file_path, backup_path)

added_count = len(new_df)

df = pd.concat([df, new_df], ignore_index=True)
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print("\n" + "=" * 80)
print("PHASE 04.7.16 COMPLETED")
print("=" * 80)
print(f"Candidate records in this cell : {len(raw_events)}")
print(f"Records checked after filtering: {candidate_count}")
print(f"New records added              : {added_count}")
print(f"Previous records retained      : {len(df) - added_count}")
print(f"Total records now              : {len(df)}")
print(f"Backup saved                   : {backup_path}")
print(f"Updated dataset                : {file_path}")
print("\nCollection cell completed.")

================================================================================
PHASE 04.7.16 — FINAL COMPREHENSIVE LOCAL EVENTS COLLECTION
================================================================================

================================================================================
PHASE 04.7.16 COMPLETED
================================================================================
Candidate records in this cell : 95
Records checked after filtering: 95
New records added              : 95
Previous records retained      : 439
Total records now              : 534
Backup saved                   : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026_before_phase_04_7_16.csv
Updated dataset                : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Collection cell completed.

In [128]:
from pathlib import Path
import pandas as pd
import requests
import time
from urllib.parse import urlparse

print("=" * 80)
print("PHASE 04.7 — FINAL SOURCE AND DATE VERIFICATION")
print("=" * 80)

# ------------------------------------------------------------
# 1. PATHS AND STUDY PERIOD
# ------------------------------------------------------------

base_dir = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
)

file_path = (
    base_dir
    / "data"
    / "raw"
    / "local_events"
    / "hyderabad_local_events_2023_2026.csv"
)

report_path = (
    base_dir
    / "data"
    / "raw"
    / "local_events"
    / "hyderabad_local_events_final_verification_report.csv"
)

START_DATE = pd.Timestamp("2023-01-01")
END_DATE = pd.Timestamp("2026-07-31")

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

df = pd.read_csv(file_path)

print(f"\nDataset loaded: {len(df)} records")

# ------------------------------------------------------------
# 2. CHECK REQUIRED COLUMNS
# ------------------------------------------------------------

required_columns = [
    "event_date",
    "event_name",
    "venue",
    "source_url"
]

for col in required_columns:
    if col not in df.columns:
        df[col] = pd.NA

if "research_status" not in df.columns:
    df["research_status"] = pd.NA

# ------------------------------------------------------------
# 3. DATE VALIDATION
# ------------------------------------------------------------

parsed_dates = pd.to_datetime(
    df["event_date"],
    errors="coerce"
)

date_missing_or_invalid = parsed_dates.isna()

outside_period = (
    parsed_dates.notna()
    & (
        (parsed_dates < START_DATE)
        | (parsed_dates > END_DATE)
    )
)

# Check event_end_date if available.
if "event_end_date" in df.columns:
    parsed_end_dates = pd.to_datetime(
        df["event_end_date"],
        errors="coerce"
    )

    end_date_present = (
        df["event_end_date"].notna()
        & df["event_end_date"].astype(str).str.strip().ne("")
    )

    invalid_end_date = (
        end_date_present
        & parsed_end_dates.isna()
    )

    end_before_start = (
        parsed_dates.notna()
        & parsed_end_dates.notna()
        & (parsed_end_dates < parsed_dates)
    )

    end_outside_period = (
        parsed_end_dates.notna()
        & (
            (parsed_end_dates < START_DATE)
            | (parsed_end_dates > END_DATE)
        )
    )
else:
    parsed_end_dates = pd.Series(
        pd.NaT, index=df.index
    )
    invalid_end_date = pd.Series(
        False, index=df.index
    )
    end_before_start = pd.Series(
        False, index=df.index
    )
    end_outside_period = pd.Series(
        False, index=df.index
    )

# ------------------------------------------------------------
# 4. MISSING FIELD CHECKS
# ------------------------------------------------------------

def missing_text(series):
    return (
        series.isna()
        | series.astype(str).str.strip().eq("")
    )

missing_event_name = missing_text(df["event_name"])
missing_venue = missing_text(df["venue"])
missing_source = missing_text(df["source_url"])

# ------------------------------------------------------------
# 5. DUPLICATE CHECK
# ------------------------------------------------------------

duplicate_key = [
    "event_date",
    "event_name",
    "venue"
]

for col in duplicate_key:
    df[col] = df[col].fillna("").astype(str).str.strip()

duplicate_mask = df.duplicated(
    subset=duplicate_key,
    keep=False
)

# ------------------------------------------------------------
# 6. RESEARCH-STATUS REVIEW
# ------------------------------------------------------------

status = (
    df["research_status"]
    .fillna("")
    .astype(str)
    .str.strip()
)

status_missing = status.eq("")

uncertain_status = status.str.contains(
    r"needs confirmation|need confirmation|"
    r"requires verification|requires further verification|"
    r"unverified|candidate|to confirm|"
    r"venue requires|date requires|"
    r"needs verification|verify final",
    case=False,
    regex=True,
    na=False
)

# ------------------------------------------------------------
# 7. SOURCE URL FORMAT CHECK
# ------------------------------------------------------------

def valid_http_url(value):
    if pd.isna(value):
        return False

    value = str(value).strip()

    if not value:
        return False

    try:
        parsed = urlparse(value)
        return (
            parsed.scheme in ("http", "https")
            and bool(parsed.netloc)
        )
    except Exception:
        return False

source_url_format_invalid = ~df["source_url"].apply(
    valid_http_url
)

# ------------------------------------------------------------
# 8. CHECK SOURCE URL ACCESSIBILITY
# ------------------------------------------------------------
# This checks accessibility only, not whether the page confirms
# the specific event date or venue.
#
# To avoid excessive requests, each unique URL is checked once.
# Network errors are recorded as inconclusive.

unique_urls = (
    df.loc[~source_url_format_invalid, "source_url"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

url_results = {}

session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (compatible; ResearchDataAudit/1.0)"
})

print(f"\nChecking {len(unique_urls)} unique source URLs...")
print("This may take a few minutes depending on website response times.")

for i, url in enumerate(unique_urls, start=1):
    try:
        response = session.get(
            url,
            timeout=12,
            allow_redirects=True,
            stream=True
        )

        status_code = response.status_code
        final_url = response.url

        if 200 <= status_code < 400:
            result = "Accessible — content still needs event verification"
        elif status_code == 404:
            result = "Page not found — investigate source"
        elif status_code in (401, 403):
            result = "Access restricted — manual verification needed"
        else:
            result = f"HTTP {status_code} — investigate source"

        response.close()

        url_results[url] = {
            "source_http_status": status_code,
            "source_access_result": result,
            "source_final_url": final_url
        }

    except requests.RequestException as exc:
        url_results[url] = {
            "source_http_status": pd.NA,
            "source_access_result": (
                "Inconclusive — network or website error: "
                + type(exc).__name__
            ),
            "source_final_url": pd.NA
        }

    if i % 25 == 0:
        print(f"Checked {i}/{len(unique_urls)} unique URLs")

# ------------------------------------------------------------
# 9. BUILD VERIFICATION REPORT
# ------------------------------------------------------------

report = df.copy()

report["parsed_event_date"] = parsed_dates
report["parsed_event_end_date"] = parsed_end_dates

report["date_missing_or_invalid"] = date_missing_or_invalid
report["event_date_outside_study_period"] = outside_period
report["invalid_end_date"] = invalid_end_date
report["end_date_before_start_date"] = end_before_start
report["event_end_date_outside_study_period"] = end_outside_period

report["missing_event_name"] = missing_event_name
report["missing_venue"] = missing_venue
report["missing_source_url"] = missing_source
report["invalid_source_url_format"] = source_url_format_invalid

report["duplicate_record"] = duplicate_mask
report["missing_research_status"] = status_missing
report["uncertain_research_status"] = uncertain_status

report["source_http_status"] = pd.NA
report["source_access_result"] = "Not checked"
report["source_final_url"] = pd.NA

for idx, row in report.iterrows():
    url = str(row["source_url"]).strip()

    if url in url_results:
        report.at[idx, "source_http_status"] = (
            url_results[url]["source_http_status"]
        )
        report.at[idx, "source_access_result"] = (
            url_results[url]["source_access_result"]
        )
        report.at[idx, "source_final_url"] = (
            url_results[url]["source_final_url"]
        )
    elif bool(row["invalid_source_url_format"]):
        report.at[idx, "source_access_result"] = (
            "Missing or invalid source URL"
        )

# Determine which records require manual review.
review_flags = [
    "date_missing_or_invalid",
    "event_date_outside_study_period",
    "invalid_end_date",
    "end_date_before_start_date",
    "event_end_date_outside_study_period",
    "missing_event_name",
    "missing_venue",
    "missing_source_url",
    "invalid_source_url_format",
    "duplicate_record",
    "uncertain_research_status"
]

report["requires_manual_review"] = report[review_flags].any(axis=1)

report["verification_note"] = report.apply(
    lambda row: "; ".join(
        label for column, label in [
            ("date_missing_or_invalid", "Invalid or missing event date"),
            ("event_date_outside_study_period", "Event date outside study period"),
            ("invalid_end_date", "Invalid event end date"),
            ("end_date_before_start_date", "End date precedes start date"),
            ("event_end_date_outside_study_period", "End date outside study period"),
            ("missing_event_name", "Missing event name"),
            ("missing_venue", "Missing venue"),
            ("missing_source_url", "Missing source URL"),
            ("invalid_source_url_format", "Invalid source URL format"),
            ("duplicate_record", "Duplicate key"),
            ("missing_research_status", "Missing research status"),
            ("uncertain_research_status", "Research status indicates uncertainty")
        ]
        if bool(row.get(column, False))
    ),
    axis=1
)

# ------------------------------------------------------------
# 10. EXPORT REPORT AND PRINT SUMMARY
# ------------------------------------------------------------

report.to_csv(
    report_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 80)
print("FINAL VERIFICATION REPORT")
print("=" * 80)

print(f"Total records reviewed              : {len(report)}")
print(f"Invalid/missing event dates         : {int(date_missing_or_invalid.sum())}")
print(f"Event dates outside study period    : {int(outside_period.sum())}")
print(f"Invalid end dates                   : {int(invalid_end_date.sum())}")
print(f"End dates before start dates        : {int(end_before_start.sum())}")
print(f"Events missing names                : {int(missing_event_name.sum())}")
print(f"Events missing venues               : {int(missing_venue.sum())}")
print(f"Events missing source URLs          : {int(missing_source.sum())}")
print(f"Invalid source URL formats          : {int(source_url_format_invalid.sum())}")
print(f"Rows in duplicate groups            : {int(duplicate_mask.sum())}")
print(f"Missing research-status labels      : {int(status_missing.sum())}")
print(f"Uncertain research-status labels    : {int(uncertain_status.sum())}")
print(f"Records requiring manual review     : {int(report['requires_manual_review'].sum())}")

access_results = pd.Series(
    [value["source_access_result"] for value in url_results.values()]
).value_counts()

print("\n--- Unique source URL accessibility results ---")
print(access_results.to_string())

print("\nVerification report saved to:")
print(report_path)

print("\nOriginal event dataset was not modified.")
print("Source accessibility does not establish that event dates are correct.")
print("Manual review of the report is required before declaring verification complete.")

================================================================================
PHASE 04.7 — FINAL SOURCE AND DATE VERIFICATION
================================================================================

Dataset loaded: 534 records

Checking 357 unique source URLs...
This may take a few minutes depending on website response times.
Checked 25/357 unique URLs
Checked 50/357 unique URLs
Checked 75/357 unique URLs
Checked 100/357 unique URLs
Checked 125/357 unique URLs
Checked 150/357 unique URLs
Checked 175/357 unique URLs
Checked 200/357 unique URLs
Checked 225/357 unique URLs
Checked 250/357 unique URLs
Checked 275/357 unique URLs
Checked 300/357 unique URLs
Checked 325/357 unique URLs
Checked 350/357 unique URLs

================================================================================
FINAL VERIFICATION REPORT
================================================================================
Total records reviewed              : 534
Invalid/missing event dates         : 0
Event dates outside study period    : 0
Invalid end dates                   : 0
End dates before start dates        : 0
Events missing names                : 0
Events missing venues               : 2
Events missing source URLs          : 0
Invalid source URL formats          : 0
Rows in duplicate groups            : 0
Missing research-status labels      : 331
Uncertain research-status labels    : 22
Records requiring manual review     : 26

--- Unique source URL accessibility results ---
Accessible — content still needs event verification         338
Inconclusive — network or website error: SSLError            11
Access restricted — manual verification needed                6
Inconclusive — network or website error: ConnectionError      1
Page not found — investigate source                           1

Verification report saved to:
d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_final_verification_report.csv

Original event dataset was not modified.
Source accessibility does not establish that event dates are correct.
Manual review of the report is required before declaring verification complete.

In [129]:
from pathlib import Path
import pandas as pd

print("=" * 75)
print("PHASE 04.7 — VERIFICATION RESULTS REVIEW")
print("=" * 75)

base_dir = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
)

report_path = (
    base_dir / "data" / "raw" / "local_events"
    / "hyderabad_local_events_final_verification_report.csv"
)

report = pd.read_csv(report_path)

print(f"\nTotal records reviewed: {len(report)}")

checks = {
    "Invalid/missing event dates": "date_missing_or_invalid",
    "Event dates outside study period": "event_date_outside_study_period",
    "Invalid end dates": "invalid_end_date",
    "End dates before start dates": "end_date_before_start_date",
    "Missing event names": "missing_event_name",
    "Missing venues": "missing_venue",
    "Missing source URLs": "missing_source_url",
    "Invalid source URL formats": "invalid_source_url_format",
    "Rows involved in duplicate groups": "duplicate_record",
    "Missing research-status labels": "missing_research_status",
    "Uncertain research-status labels": "uncertain_research_status",
    "Records requiring manual review": "requires_manual_review",
}

print("\n--- Verification counts ---")

for label, column in checks.items():
    if column in report.columns:
        count = report[column].fillna(False).astype(bool).sum()
        print(f"{label}: {count}")

if "source_access_result" in report.columns:
    print("\n--- Source accessibility results ---")
    print(report["source_access_result"].value_counts(dropna=False).to_string())

print("\n--- Records requiring manual review (first 20) ---")

if "requires_manual_review" in report.columns:
    review = report[
        report["requires_manual_review"].fillna(False).astype(bool)
    ]

    display_columns = [
        c for c in [
            "event_date",
            "event_name",
            "venue",
            "research_status",
            "source_access_result",
            "verification_note"
        ]
        if c in report.columns
    ]

    if len(review):
        display(review[display_columns].head(20))
    else:
        print("No records flagged for manual review.")

print("\nReview complete. No files were modified.")

===========================================================================
PHASE 04.7 — VERIFICATION RESULTS REVIEW
===========================================================================

Total records reviewed: 534

--- Verification counts ---
Invalid/missing event dates: 0
Event dates outside study period: 0
Invalid end dates: 0
End dates before start dates: 0
Missing event names: 0
Missing venues: 2
Missing source URLs: 0
Invalid source URL formats: 0
Rows involved in duplicate groups: 0
Missing research-status labels: 331
Uncertain research-status labels: 22
Records requiring manual review: 26

--- Source accessibility results ---
source_access_result
Accessible — content still needs event verification         481
Access restricted — manual verification needed               39
Inconclusive — network or website error: SSLError            12
Inconclusive — network or website error: ConnectionError      1
Page not found — investigate source                           1

--- Records requiring manual review (first 20) ---

,event_date,event_name,venue,research_status,source_access_result,verification_note
0,2026-07-31,Deep Mela,HITEX Exhibition Centre,NaN,Accessible — content still needs event verification,End date outside study period; Missing research status
1,2026-07-30,Eco Sustain Expo 3rd Edition,HITEX Exhibition Centre,NaN,Accessible — content still needs event verification,End date outside study period; Missing research status
2,2026-07-30,IPEC 5th Edition,HITEX Exhibition Centre,NaN,Accessible — content still needs event verification,End date outside study period; Missing research status
3,2026-07-30,Renewable Restart Energy India Expo,HITEX Exhibition Centre,NaN,Accessible — content still needs event verification,End date outside study period; Missing research status
333,2023-03-04,Martin Garrix Live,HITEX Exhibition Centre,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
335,2023-09-08,WWE Superstar Spectacle 2023,G. M. C. Balayogi Indoor Stadium,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
336,2023-08-25,Radio Slave Live,"EXT, Jubilee Hills",Needs confirmation,Access restricted — manual verification needed,Research status indicates uncertainty
337,2023-12-16,Meca Live,Breeze Monkey,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
338,2023-12-17,Massano Live,NaN,Venue requires further verification,Access restricted — manual verification needed,Missing venue; Research status indicates uncertainty
339,2023-12-17,Mali (Maalavika Manoj) Live,"EXT, Jubilee Hills",Needs confirmation,Access restricted — manual verification needed,Research status indicates uncertainty
340,2024-02-18,Adam Beyer Live,Prism,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
341,2024-02-23,"Anjunadeep, Anyasa, CRi, HANA and Others",NaN,Venue requires further verification,Access restricted — manual verification needed,Missing venue; Research status indicates uncertainty
342,2024-04-27,Girish and the Chronicles — Loaded Summer Tour,"Hard Rock Cafe, Hitech City",Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
343,2024-06-22,"Whiney, Degs, Anais and Others",Antisocial Hyderabad,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
344,2024-08-10,Anthracite Live,"Hard Rock Cafe, Hitech City",Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
347,2024-11-21,Ulcerate Live,EXT,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
348,2024-11-30,Shreya Ghoshal Live Concert,LB Stadium,Organizer archive; date needs confirmation,Accessible — content still needs event verification,Research status indicates uncertainty
349,2024-12-07,Arijit Singh Live,GMR Arena,Needs confirmation,Accessible — content still needs event verification,Research status indicates uncertainty
355,2025-03-08,John Summit Live,Quake Arena,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty
356,2025-05-09,Dimitri Vegas Live,Quake Arena,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty

Review complete. No files were modified.

In [130]:
from pathlib import Path
import pandas as pd

base_dir = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
)

report_path = (
    base_dir
    / "data"
    / "raw"
    / "local_events"
    / "hyderabad_local_events_final_verification_report.csv"
)

report = pd.read_csv(report_path)

flagged = report[
    report["requires_manual_review"].fillna(False).astype(bool)
].copy()

columns = [
    col for col in [
        "event_date",
        "event_end_date",
        "event_name",
        "venue",
        "research_status",
        "source_access_result",
        "verification_note",
        "source_url"
    ]
    if col in flagged.columns
]

print("=" * 75)
print("PHASE 04.7 — FINAL MANUAL REVIEW")
print("=" * 75)
print(f"Records requiring review: {len(flagged)}")

display(flagged[columns])

print("\nNo files modified.")

===========================================================================
PHASE 04.7 — FINAL MANUAL REVIEW
===========================================================================
Records requiring review: 26

,event_date,event_end_date,event_name,venue,research_status,source_access_result,verification_note,source_url
0,2026-07-31,2026-08-02,Deep Mela,HITEX Exhibition Centre,NaN,Accessible — content still needs event verification,End date outside study period; Missing research status,https://hitex.co.in/events/deep-mela-1/index.html
1,2026-07-30,2026-08-01,Eco Sustain Expo 3rd Edition,HITEX Exhibition Centre,NaN,Accessible — content still needs event verification,End date outside study period; Missing research status,https://hitex.co.in/events/eco-sustain-expo-2026/index.html
2,2026-07-30,2026-08-01,IPEC 5th Edition,HITEX Exhibition Centre,NaN,Accessible — content still needs event verification,End date outside study period; Missing research status,https://hitex.co.in/events/ipec-2026/index.html
3,2026-07-30,2026-08-01,Renewable Restart Energy India Expo,HITEX Exhibition Centre,NaN,Accessible — content still needs event verification,End date outside study period; Missing research status,https://hitex.co.in/events/renewable-restart-energy-india-expo-1/index.html
333,2023-03-04,2023-03-04,Martin Garrix Live,HITEX Exhibition Centre,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
335,2023-09-08,2023-09-08,WWE Superstar Spectacle 2023,G. M. C. Balayogi Indoor Stadium,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
336,2023-08-25,2023-08-25,Radio Slave Live,"EXT, Jubilee Hills",Needs confirmation,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
337,2023-12-16,2023-12-16,Meca Live,Breeze Monkey,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
338,2023-12-17,2023-12-17,Massano Live,NaN,Venue requires further verification,Access restricted — manual verification needed,Missing venue; Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
339,2023-12-17,2023-12-17,Mali (Maalavika Manoj) Live,"EXT, Jubilee Hills",Needs confirmation,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
340,2024-02-18,2024-02-18,Adam Beyer Live,Prism,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
341,2024-02-23,2024-02-23,"Anjunadeep, Anyasa, CRi, HANA and Others",NaN,Venue requires further verification,Access restricted — manual verification needed,Missing venue; Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
342,2024-04-27,2024-04-27,Girish and the Chronicles — Loaded Summer Tour,"Hard Rock Cafe, Hitech City",Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
343,2024-06-22,2024-06-22,"Whiney, Degs, Anais and Others",Antisocial Hyderabad,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
344,2024-08-10,2024-08-10,Anthracite Live,"Hard Rock Cafe, Hitech City",Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
347,2024-11-21,2024-11-21,Ulcerate Live,EXT,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
348,2024-11-30,2024-11-30,Shreya Ghoshal Live Concert,LB Stadium,Organizer archive; date needs confirmation,Accessible — content still needs event verification,Research status indicates uncertainty,https://hyderabadtalkies.events/past-events/
349,2024-12-07,2024-12-07,Arijit Singh Live,GMR Arena,Needs confirmation,Accessible — content still needs event verification,Research status indicates uncertainty,https://telanganatoday.com/hyderabad-all-ready-to-rock-with-star-studded-concerts-in-upcoming-weeks
355,2025-03-08,2025-03-08,John Summit Live,Quake Arena,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
356,2025-05-09,2025-05-09,Dimitri Vegas Live,Quake Arena,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
357,2025-05-31,2025-05-31,Girish and the Chronicles Live,"Hard Rock Cafe, Hitech City",Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
358,2025-09-21,2025-09-21,Parikrama Live,"Hard Rock Cafe, Hitech City",Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
359,2025-09-28,2025-09-28,Deborah De Luca Live,Quake Arena,Archive candidate,Access restricted — manual verification needed,Research status indicates uncertainty,https://www.concertarchives.org/locations/hyderabad-india
384,2023-06-02,2023-06-02,Telangana Formation Day Celebrations,"Parade Grounds, Secunderabad",Annual event; 2023-specific details need confirmation,Accessible — content still needs event verification,Research status indicates uncertainty,https://www.telangana.gov.in/news/press-releases/2024/06/telangana-state-formation-day-celebrations/
390,2026-06-02,2026-06-02,Telangana Formation Day Celebrations 2026,Hyderabad — venue to confirm,Annual event; venue-specific details need confirmation,Accessible — content still needs event verification,Research status indicates uncertainty,https://www.telangana.gov.in/
415,2023-10-10,2023-10-10,ICC Men's Cricket World Cup — Pakistan vs Sri Lanka,"Rajiv Gandhi International Cricket Stadium, Uppal, Hyderabad",Verify final fixture details against official match archive,Accessible — content still needs event verification,Research status indicates uncertainty,https://www.icc-cricket.com/media-releases/icc-mens-cricket-world-cup-2023-schedule-announced

No files modified.

In [131]:
from pathlib import Path
import pandas as pd
import shutil

print("=" * 75)
print("PHASE 04.7 — FINAL DATE-BOUNDARY REVIEW")
print("=" * 75)

file_path = Path(
    r"d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting"
    r"\data\raw\local_events\hyderabad_local_events_2023_2026.csv"
)

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found: {file_path}")

df = pd.read_csv(file_path)

# Preserve a backup before updating metadata.
backup_path = file_path.with_name(
    file_path.stem + "_before_final_boundary_review.csv"
)
shutil.copy2(file_path, backup_path)

# Parse dates without changing the original date values.
start_dates = pd.to_datetime(df["event_date"], errors="coerce")

if "event_end_date" in df.columns:
    end_dates = pd.to_datetime(df["event_end_date"], errors="coerce")
else:
    end_dates = start_dates.copy()
    df["event_end_date"] = df["event_date"]

study_end = pd.Timestamp("2026-07-31")

# Identify events that start within the study period but end afterward.
boundary_mask = (
    start_dates.between(
        pd.Timestamp("2023-01-01"),
        study_end
    )
    & end_dates.notna()
    & (end_dates > study_end)
)

# Add a review column without overwriting existing notes.
if "final_boundary_review" not in df.columns:
    df["final_boundary_review"] = ""

df.loc[boundary_mask, "final_boundary_review"] = (
    "Event extends beyond study end; retain only in-period dates "
    "when constructing contextual features."
)

# Save without deleting records or altering original dates.
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f"Total records retained       : {len(df)}")
print(f"Events extending past cutoff : {int(boundary_mask.sum())}")
print(f"Study period end             : {study_end.date()}")
print(f"Backup saved                 : {backup_path}")
print(f"Updated dataset              : {file_path}")

if boundary_mask.any():
    print("\nEvents flagged for boundary review:")
    display(
        df.loc[
            boundary_mask,
            [
                "event_date",
                "event_end_date",
                "event_name",
                "final_boundary_review"
            ]
        ]
    )

print("\nNo event records were deleted.")

===========================================================================
PHASE 04.7 — FINAL DATE-BOUNDARY REVIEW
===========================================================================
Total records retained       : 534
Events extending past cutoff : 4
Study period end             : 2026-07-31
Backup saved                 : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026_before_final_boundary_review.csv
Updated dataset              : d:\M Tech\Sem_03\Project\AI-Enhanced-Hyperlocal-Food-Demand-Forecasting\data\raw\local_events\hyderabad_local_events_2023_2026.csv

Events flagged for boundary review:

   event_date event_end_date                           event_name                                                                               final_boundary_review
0  2026-07-31     2026-08-02                            Deep Mela  Event extends beyond study end; retain only in-period dates when constructing contextual features.
1  2026-07-30     2026-08-01         Eco Sustain Expo 3rd Edition  Event extends beyond study end; retain only in-period dates when constructing contextual features.
2  2026-07-30     2026-08-01                     IPEC 5th Edition  Event extends beyond study end; retain only in-period dates when constructing contextual features.
3  2026-07-30     2026-08-01  Renewable Restart Energy India Expo  Event extends beyond study end; retain only in-period dates when constructing contextual features.

No event records were deleted.

# Phase 04.7 — Local Events Collection and Final Verification

## 1. Objective

The objective of Phase 04.7 was to collect and organize local events in Hyderabad that could potentially influence hyperlocal food-order demand. The collected information covers exhibitions, trade fairs, cultural and religious festivals, concerts, sporting events, cricket matches, public gatherings, educational events, and other significant local activities.

These events will serve as contextual information for the **Hyperlocal Food Demand and Surge Forecasting in Indian Food Delivery** research project.

## 2. Study Period and Geographic Scope

* **Study period:** January 1, 2023 – July 31, 2026
* **Study city:** Hyderabad, Telangana, India
* **Primary event venue source:** HITEX Exhibition Centre event archive, supplemented by other event-specific sources.
* **Output format:** CSV

The intended application is to study potential relationships between local events and food demand across the project's hyperlocal zones. Event-to-zone relationships must be established using reliable geographic information rather than assumed.

## 3. Event Categories Collected

The collection process covered the following categories:

1. Exhibitions and trade fairs
2. Cultural festivals and community events
3. Food and culinary events
4. Concerts and entertainment
5. Literary, educational, and community events
6. Major public gatherings and charity events
7. Sporting events and stadium gatherings
8. International cricket and World Cup events
9. Art exhibitions and gallery events
10. Religious festivals and public gatherings
11. Seasonal markets and consumer exhibitions

The collection was performed incrementally across Phases 04.7.1–04.7.16, preserving previously collected records as new candidates were added.

## 4. Final Dataset

The final local-events dataset is stored at:

`data/raw/local_events/hyderabad_local_events_2023_2026.csv`

| Metric                                     | Final result |
| ------------------------------------------ | -----------: |
| Total local-event records                  |          534 |
| Study-period start                         |   2023-01-01 |
| Study-period end                           |   2026-07-31 |
| Invalid or missing event start dates       |            0 |
| Event start dates outside the study period |            0 |
| Invalid event end dates                    |            0 |
| Event end dates preceding start dates      |            0 |
| Missing event names                        |            0 |
| Missing venue values                       |            2 |
| Missing source URLs                        |            0 |
| Invalid source URL formats                 |            0 |
| Duplicate groups detected by the audit     |            0 |

These results reflect the final automated audit. They do not establish that every event's occurrence, date, venue, or geographic assignment has been independently verified.

## 5. Source and Date Verification

A final verification procedure examined all 534 records and checked 357 unique source URLs.

### Source accessibility results

| Source check result                                  | Count |
| ---------------------------------------------------- | ----: |
| Accessible; event details still require verification |   481 |
| Access restricted                                    |    39 |
| SSL errors                                           |    12 |
| Connection errors                                    |     1 |
| Page not found                                       |     1 |

Source accessibility indicates whether a webpage could be reached during the audit. It does not establish that the page confirms the specific event date, venue, or occurrence.

### Research-status review

* Records without a research-status label: 331
* Records with research-status labels indicating uncertainty: 22
* Records flagged for manual review: 26

The flagged records were retained. They were not automatically classified as incorrect or deleted.

## 6. Study-Period Boundary Handling

Four events begin within the study period but extend beyond July 31, 2026:

* Deep Mela
* Eco Sustain Expo 3rd Edition
* IPEC 5th Edition
* Renewable Restart Energy India Expo

These records were retained, and a `final_boundary_review` field was added to flag their extended event periods.

During downstream feature engineering, only dates within the defined study period should contribute to the study dataset. The original event dates should remain available for traceability.

## 7. Output and Audit Files

The principal output and supporting audit files are:

* **Local-events dataset:** `hyderabad_local_events_2023_2026.csv`
* **Verification report:** `hyderabad_local_events_final_verification_report.csv`
* **Pre-boundary-review backup:** `hyderabad_local_events_2023_2026_before_final_boundary_review.csv`

Additional phase-specific backups were created during collection and correction.

## 8. Limitations

The following limitations must be considered when using this dataset:

1. Not every event has been independently verified against its original publication.
2. Some source pages are inaccessible or restrict automated access.
3. Two event records have missing venue information.
4. Many records do not have an explicit research-status label.
5. Some event candidates retain uncertainty regarding their dates, venues, or details.
6. Event presence alone does not establish a causal effect on food demand.
7. Hyperlocal zone assignments and event-to-zone proximity must be established using reliable geographic information.
8. Multi-day events must be represented consistently when creating daily or hourly contextual features.

These limitations should be acknowledged in the research methodology and addressed where necessary during data integration and model evaluation.

## 9. Final Outcome

**Phase 04.7 — Local Events Collection and Final Verification is complete as a collection workflow.**

A total of **534 local-event records** have been retained in the project dataset. Automated checks found no invalid or missing event start dates, no start dates outside the study period, and no duplicate groups under the audit's date–event-name–venue key.

Source verification remains partial, and the documented limitations must be preserved during subsequent processing.

The dataset is ready to proceed to the next planned project phase, subject to appropriate treatment of uncertain records, event-period boundaries, and geographic relationships during feature engineering and integration.

# Phase 04.8 — Traffic Conditions Data Collection

## 1. Objective

Collect historical traffic-condition data for Hyderabad to investigate its potential relationship with hourly, zone-level food demand and demand–supply mismatches.

## 2. Study Scope

* **City:** Hyderabad, Telangana, India
* **Study period:** January 1, 2023 – July 31, 2026
* **Temporal target:** Hourly observations, where available
* **Geographic scope:** Five synthetic hyperlocal zones

| Zone ID | Zone Name   |
| ------- | ----------- |
| Z01     | Kondapur    |
| Z02     | Hitech City |
| Z03     | Gachibowli  |
| Z04     | Madhapur    |
| Z05     | Kukatpally  |

## 3. Required Traffic Variables

Collect the following fields when available from reliable sources:

* Observation timestamp
* Road segment or observation location
* Traffic speed
* Congestion level or index
* Travel time
* Traffic incidents
* Source information

Unavailable variables will not be fabricated.

## 4. Data Source Strategy

Prioritize sources that provide historical traffic observations with documented geographic and temporal coverage. Assess source availability before selecting a collection method.

## 5. Output

**Target directory:**
`data/raw/traffic/`

**Target dataset:**
`hyderabad_traffic_conditions_2023_2026.csv`

The final schema and collection method will depend on the data actually available from the selected source.

## 6. Intended Use

Traffic information will be considered alongside weather, public holidays, festivals, sporting events, local events, and hourly food-demand data.

Traffic conditions will be treated as contextual variables, not as direct evidence of increased food demand.

## 7. Completion Criteria

Phase 04.8 will be complete when the available traffic data have been collected, their source and coverage documented, and the resulting dataset saved for use in Phase 04.9.

# Phase 04.8 — Traffic Conditions Data Collection

## Objective

Collect genuine, real-time traffic observations for Hyderabad using an authorized traffic-data API.

## Data Source

TomTom Traffic Flow API — real-time road-segment traffic information.

Documentation: https://docs.tomtom.com/traffic-api/documentation/tomtom-maps/v1/traffic-flow/traffic-flow-service

## Geographic Scope

* Z01 — Kondapur
* Z02 — Hitech City
* Z03 — Gachibowli
* Z04 — Madhapur
* Z05 — Kukatpally

## Collection Rules

1. Collect real observations directly from the API.
2. Record the actual observation/collection timestamp.
3. Never generate, simulate, or fabricate traffic measurements.
4. Do not treat live observations as historical traffic data.
5. Preserve the original API values and units.
6. Record source information and API errors honestly.

## Target Output

Directory: `data/raw/traffic/`

Target file: `hyderabad_live_traffic.csv`

## Planned Fields

* collection_timestamp
* zone_id
* road_segment
* latitude
* longitude
* current_speed
* free_flow_speed
* confidence
* source

Fields will be populated only when supported by the API response. Missing values will not be invented.

## Completion Criteria

Successfully collect and save genuine live traffic observations for the Hyderabad study zones, subject to API access and actual geographic coverage.

# Phase 04.8 — Live Traffic Incident and Advisory Collection

## Objective

Collect genuine, publicly available traffic incidents and traffic advisories published by Hyderabad Traffic Police.

## Data Source

Official Hyderabad Traffic Police website and its published traffic advisories.

## Geographic Scope

Hyderabad, focusing on:

* Z01 — Kondapur
* Z02 — Hitech City
* Z03 — Gachibowli
* Z04 — Madhapur
* Z05 — Kukatpally

## Data to Collect

* Advisory publication date and time, when available
* Incident or advisory description
* Reported location or road
* Traffic disruption type
* Diversion or road-closure information
* Source URL
* Collection timestamp

## Collection Rules

1. Use only genuine, published information.
2. Preserve the original advisory text and source URL.
3. Do not invent incident dates, locations or severity.
4. Do not interpret an advisory as a measured traffic speed.
5. Record only information supported by the source.

## Output

Directory: `data/raw/traffic/`

Target file: `hyderabad_traffic_advisories.csv`

## Limitation

These records represent reported traffic incidents and advisories, not continuous traffic-speed measurements. Historical coverage depends on the records publicly accessible from the source.

In [1]:
import requests
from bs4 import BeautifulSoup

url = "https://echallan.tspolice.gov.in/htp/"

response = requests.get(url, timeout=30)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

print("Source: Hyderabad Traffic Police")
print("HTTP status:", response.status_code)
print("Page title:", soup.title.get_text(strip=True) if soup.title else "Not found")

text = soup.get_text(" ", strip=True)

for keyword in ["Traffic Alerts", "Latest Traffic Alert", "TRAFFIC ADVISORY"]:
    position = text.lower().find(keyword.lower())
    print(f"\n--- {keyword} ---")
    print(text[position:position + 1200] if position >= 0 else "Not found in downloaded HTML")

print("\nJavaScript files that may load traffic alerts:")
for script in soup.find_all("script", src=True):
    print(requests.compat.urljoin(url, script["src"]))

Source: Hyderabad Traffic Police
HTTP status: 200
Page title: Hyderabad Traffic Police

--- Traffic Alerts ---
Traffic Alerts Loading latest alert... Citizen Services Last updated: 13-Oct-2026 Pay Challan Pay your traffic violations online quickly and securely Learn more Parking Zones Know parking zones Available Accorss the city Learn more Road Rules Traffic signs,MV-Act Information,and Vehicle number plate regulations Learn more Wrong Challan Report and contest incorrectly issued traffic challans Learn more Know Your Traffic PS Know The Jurisdiction & Information Of The Traffic Ps Learn more Road Sense Essential Rules and Must know Information Learn more Stolen Vehicle Assistance **Report and Update Lost or Stolen Vehicle Details Online** Learn more 🚗 How to Register a Vehicle Vehicle registration services are currently available only at authorized vehicle showrooms. Know the Process Road Traffic Accident Monitoring Cell Report road traffic accidents and monitor accident-related information. Learn More 🚦 FEATURES BE ROAD SMART ROAD ACCIDENT BOOKLETS PUBLIC INTERFACE GALLERY SPEED LIMIT TRAFFIC TRAINING CENTER TRAFFIC MARSHAL TRAFFIC ASSISTANTS Be Safe Wheel Clamping Traffic Signals Major Corridors Traffic Congestion Defensive Driving TRAFFIC NOC 🪖 Helmet 🚗 Speeding 🔒 Seat Belt Required Do

--- Latest Traffic Alert ---
Latest Traffic Alert... 🚦 TRAFFIC ADVISORY | DURGA MATHA IDOL IMMERSION-2026🚦 In view of Durga Matha idol immersion from 15:00 hrs on 21.10.2026 to 06:00 hrs on 24.10.2026, traffic diversions and restrictions will be implemented around People’s Plaza,
Garden Point, Jalavihar Baby Ponds and Sanjeevaiah Park, depending on local traffic conditions. 🚦Traffic Advisory – Saddula Bathukamma 2026🚦 In view of Saddula Bathukamma celebrations on 18.10.2026 (Sunday) at Bathukamma Ghat, Upper Tank Bund, traffic diversions
                         and restrictions will be in force from 2:00 PM to 11:00 PM around Upper Tank Bund and Necklace Road. ➤ 🚦 KBR PARK ONE-WAY TRAFFIC SYSTEM – ROUTE MAP 🚦 As part of the H-CITI Project, the One-Way Traffic
                        System around KBR Park will be implemented continuously
                        from 18.08.2026. Arrive Alive (A Campaign for Safety on Roads) Click here For more information 🚨 EMERGENCY & IMPORTANT CONTACTS Police 112 Ambulance 108 Fire & Rescue 101 Women Helpline 181 Child Helpline 1098 Cyber Crime 1930 Cyber Crime Cell 8712660803 Traffic Help Line 9010203626 Traffic Control 8712660600 Traffic E-Challan 8712661690 Narcotics

--- TRAFFIC ADVISORY ---
TRAFFIC ADVISORY | DURGA MATHA IDOL IMMERSION-2026🚦 In view of Durga Matha idol immersion from 15:00 hrs on 21.10.2026 to 06:00 hrs on 24.10.2026, traffic diversions and restrictions will be implemented around People’s Plaza,
Garden Point, Jalavihar Baby Ponds and Sanjeevaiah Park, depending on local traffic conditions. 🚦Traffic Advisory – Saddula Bathukamma 2026🚦 In view of Saddula Bathukamma celebrations on 18.10.2026 (Sunday) at Bathukamma Ghat, Upper Tank Bund, traffic diversions
                         and restrictions will be in force from 2:00 PM to 11:00 PM around Upper Tank Bund and Necklace Road. ➤ 🚦 KBR PARK ONE-WAY TRAFFIC SYSTEM – ROUTE MAP 🚦 As part of the H-CITI Project, the One-Way Traffic
                        System around KBR Park will be implemented continuously
                        from 18.08.2026. Arrive Alive (A Campaign for Safety on Roads) Click here For more information 🚨 EMERGENCY & IMPORTANT CONTACTS Police 112 Ambulance 108 Fire & Rescue 101 Women Helpline 181 Child Helpline 1098 Cyber Crime 1930 Cyber Crime Cell 8712660803 Traffic Help Line 9010203626 Traffic Control 8712660600 Traffic E-Challan 8712661690 Narcotics Helpline 1933 AI 🚦 HTP As

JavaScript files that may load traffic alerts:
https://echallan.tspolice.gov.in/htp/js/jquery-3.7.1.min.js
https://echallan.tspolice.gov.in/htp/js/translate.js
https://echallan.tspolice.gov.in/htp/js/chatbot.js
https://echallan.tspolice.gov.in/htp/support/simplebar/simplebar.min.js
https://echallan.tspolice.gov.in/htp/support/tiny-slider/tiny-slider.js
https://echallan.tspolice.gov.in/htp/support/smooth-scroll/smooth-scroll.polyfills.min.js
https://echallan.tspolice.gov.in/htp/js/theme.min.js
https://echallan.tspolice.gov.in/htp/support/bootstrap/js/bootstrap.bundle.min.js
https://echallan.tspolice.gov.in/htp/js/script.js
https://echallan.tspolice.gov.in/htp/js/accessibility.js
https://echallan.tspolice.gov.in/htp/js/voice-assistant.js

In [2]:
import requests
from bs4 import BeautifulSoup
from pathlib import Path
from datetime import datetime
import pandas as pd

url = "https://echallan.tspolice.gov.in/htp/"

response = requests.get(url, timeout=30)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

# Extract the published page text
page_text = soup.get_text("\n", strip=True)

# Save the source snapshot for traceability
output_dir = Path("data/raw/traffic")
output_dir.mkdir(parents=True, exist_ok=True)

snapshot_path = output_dir / "hyderabad_traffic_police_source_snapshot.txt"
snapshot_path.write_text(page_text, encoding="utf-8")

# Store the actual source snapshot; do not invent individual records
df = pd.DataFrame([{
    "collection_timestamp": datetime.now().astimezone().isoformat(),
    "source_url": url,
    "http_status": response.status_code,
    "page_title": soup.title.get_text(strip=True) if soup.title else None,
    "source_text": page_text
}])

output_csv = output_dir / "hyderabad_traffic_police_source_snapshot.csv"
df.to_csv(output_csv, index=False, encoding="utf-8-sig")

print("Source retrieved successfully.")
print("HTTP status:", response.status_code)
print("Text length:", len(page_text))
print("Saved:", snapshot_path)
print("Saved:", output_csv)

Source retrieved successfully.
HTTP status: 200
Text length: 41841
Saved: data\raw\traffic\hyderabad_traffic_police_source_snapshot.txt
Saved: data\raw\traffic\hyderabad_traffic_police_source_snapshot.csv

In [3]:
from pathlib import Path
from datetime import datetime
import pandas as pd
import re

# Load the saved official-source snapshot
source_file = Path("data/raw/traffic/hyderabad_traffic_police_source_snapshot.txt")
text = source_file.read_text(encoding="utf-8")

# Identify advisory sections using headings present in the source
pattern = re.compile(
    r"(?:TRAFFIC\s+ADVISORY|TRAFFIC\s+ALERT)\s*:?",
    re.IGNORECASE
)

matches = list(pattern.finditer(text))
records = []

for i, match in enumerate(matches):
    start = match.start()
    end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
    advisory_text = text[start:end].strip()

    # Keep only sections containing meaningful text
    if len(advisory_text) < 40:
        continue

    records.append({
        "collection_timestamp": datetime.now().astimezone().isoformat(),
        "advisory_text": advisory_text,
        "source_url": "https://echallan.tspolice.gov.in/htp/"
    })

# Save only text extracted from the genuine source
output_dir = Path("data/raw/traffic")
output_dir.mkdir(parents=True, exist_ok=True)

output_file = output_dir / "hyderabad_traffic_advisories.csv"

df = pd.DataFrame(records)

if not df.empty:
    df = df.drop_duplicates(subset=["advisory_text"])
    df.to_csv(output_file, index=False, encoding="utf-8-sig")
    print("Extracted advisories:", len(df))
    print("Saved to:", output_file)
    print("\nFirst extracted records:")
    print(df[["advisory_text"]].head(3).to_string(index=False))
else:
    print("No identifiable advisory sections found.")
    print("The source snapshot remains unchanged.")

Extracted advisories: 3
Saved to: data\raw\traffic\hyderabad_traffic_advisories.csv

First extracted records:

In [4]:
from pathlib import Path
from datetime import datetime
import pandas as pd
import re

source_file = Path("data/raw/traffic/hyderabad_traffic_police_source_snapshot.txt")
text = source_file.read_text(encoding="utf-8")

# Identify actual advisory headings
pattern = re.compile(
    r"(?im)^\s*(?:TRAFFIC\s+ADVISORY|TRAFFIC\s+ALERT)\s*:?\s*"
)

matches = list(pattern.finditer(text))
records = []

for i, match in enumerate(matches):
    start = match.start()
    end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
    advisory = text[start:end].strip()

    # Remove generic website navigation and unrelated footer text
    advisory = re.split(
        r"(?i)Citizen Services|Pay Challan|Emergency & Important Contacts",
        advisory
    )[0].strip()

    if len(advisory) < 60:
        continue

    records.append({
        "collection_timestamp": datetime.now().astimezone().isoformat(),
        "advisory_text": advisory,
        "source_url": "https://echallan.tspolice.gov.in/htp/"
    })

output_file = Path("data/raw/traffic/hyderabad_traffic_advisories.csv")

df = pd.DataFrame(records).drop_duplicates(subset=["advisory_text"])
df.to_csv(output_file, index=False, encoding="utf-8-sig")

print("Candidate advisory sections:", len(df))
print("Saved to:", output_file)

for i, row in df.iterrows():
    print(f"\n--- Candidate {i + 1} ---")
    print(row["advisory_text"][:1000])

Candidate advisory sections: 0
Saved to: data\raw\traffic\hyderabad_traffic_advisories.csv

In [5]:
from pathlib import Path

source_file = Path("data/raw/traffic/hyderabad_traffic_police_source_snapshot.txt")
text = source_file.read_text(encoding="utf-8")

keywords = [
    "TRAFFIC ADVISORY",
    "TRAFFIC ALERT",
    "DIVERSION",
    "ROAD CLOSURE",
    "Last updated"
]

for keyword in keywords:
    position = text.lower().find(keyword.lower())
    print(f"\n{'=' * 20} {keyword} {'=' * 20}")

    if position >= 0:
        print(text[max(0, position - 250):position + 1800])
    else:
        print("Not found")

==================== TRAFFIC ADVISORY ====================
ew Photo Gallery
🚗 Speed Limits in Hyderabad
View Official Notification
Speed Limits GO
Traffic Training Center
Traffic Marshal
Traffic Assistants
📰 Latest News
(Traffic Updates)
--------------------------------------------
Latest Traffic Alert...
🚦 TRAFFIC ADVISORY | DURGA MATHA IDOL IMMERSION-2026🚦
In view of Durga Matha idol immersion from 15:00 hrs on 21.10.2026 to 06:00 hrs on 24.10.2026, traffic diversions and restrictions will be implemented around People’s Plaza,

Garden Point, Jalavihar Baby Ponds and Sanjeevaiah Park, depending on local traffic conditions.
🚦Traffic Advisory – Saddula Bathukamma 2026🚦
In view of Saddula Bathukamma celebrations on 18.10.2026 (Sunday) at Bathukamma Ghat, Upper Tank Bund, traffic diversions

                         and restrictions will be in force from 2:00 PM to 11:00 PM around Upper Tank Bund and Necklace Road.
➤ 🚦 KBR PARK ONE-WAY TRAFFIC SYSTEM – ROUTE MAP 🚦
As part of the H-CITI Project, the One-Way Traffic

                        System around KBR Park will be implemented continuously

                        from 18.08.2026.
Arrive Alive
(A Campaign for Safety on Roads)
Click here
For more information
🚨 EMERGENCY & IMPORTANT CONTACTS
Police
112
Ambulance
108
Fire & Rescue
101
Women Helpline
181
Child Helpline
1098
Cyber Crime
1930
Cyber Crime Cell
8712660803
Traffic Help Line
9010203626
Traffic Control
8712660600
Traffic E-Challan
8712661690
Narcotics Helpline
1933
AI
🚦
HTP Assistant
Hyderabad Traffic Police · AI Powered
🚦
👋 Hello! I'm the
HTP AI Assistant
. I'm here to help you with traffic queries, challans, NOC, and more.
Full AI Chat — Coming Soon!
We're building an intelligent assistant to answer all your traffic-related queries in real time.
How do I pay my challan?
Apply for NOC
Nearest traffic police station
Emergency contacts
×
❮
❯
Hyderabad Traffic Police
Dedicated to safer roads, better traffic management

                    and citizen-friendly digital services.
🚦 Road Safety Campaigns
Useful Links
E-Challan
Wrong Challan
NOC
Vehicle Registration
Infor

==================== TRAFFIC ALERT ====================
vents
Dharna/Protest/Demonstration
Seasonal Events / Festivals
Seasonal Stalls
Information
Road Rules
Road Sense
Road Smart
Statistics
Driving License
Vehicle Registration
Know Your PS
RTI
Road Safety
Gallery
T20 Test
Online Test
Contact
Search site
Traffic Alerts
Loading latest alert...
Citizen Services
Last updated: 13-Oct-2026
Pay Challan
Pay your traffic violations online quickly and securely
Learn more
Parking Zones
Know parking zones Available Accorss the city
Learn more
Road Rules
Traffic signs,MV-Act Information,and Vehicle number plate regulations
Learn more
Wrong Challan
Report and contest incorrectly issued traffic challans
Learn more
Know Your Traffic PS
Know The Jurisdiction & Information Of The Traffic Ps
Learn more
Road Sense
Essential Rules and Must know Information
Learn more
Stolen Vehicle Assistance
**Report and Update Lost or Stolen Vehicle Details Online**
Learn more
🚗 How to Register a Vehicle
Vehicle registration services are currently available only at authorized vehicle showrooms.
Know the Process
Road Traffic Accident Monitoring Cell
Report road traffic accidents and monitor accident-related information.
Learn More
🚦 FEATURES
BE ROAD SMART
ROAD ACCIDENT BOOKLETS
PUBLIC INTERFACE
GALLERY
SPEED LIMIT
TRAFFIC TRAINING CENTER
TRAFFIC MARSHAL
TRAFFIC ASSISTANTS
Be Safe
Wheel Clamping
Traffic Signals
Major Corridors
Traffic Congestion
Defensive Driving
TRAFFIC NOC
🪖 Helmet
🚗 Speeding
🔒 Seat Belt
Required Documents / Traffic NOCs
Vehicle NOC
Traffic Conditions
School NOC
Traffic Conditions
Petrol Pump NOC
Traffic Conditions
DL Documents
Traffic Conditions
RC Documents
Traffic Conditions
Processions / Rallies
Traffic Conditions
Film Shootings
Traffic Conditions
Drone Operations
Traffic Conditions
Amusements
Traffic Conditions
Entertainment Events
Traffic Conditions
Dharna / Protest
Traffic Conditions
Seasonal Events / Festivals
Traffic Conditions
Seasonal Stalls
Traffic Conditions
Cinematography License
Traffic Conditions
Firework Shop Permission
Permission Details
Tambola License
Permission Detai

==================== DIVERSION ====================
 News
(Traffic Updates)
--------------------------------------------
Latest Traffic Alert...
🚦 TRAFFIC ADVISORY | DURGA MATHA IDOL IMMERSION-2026🚦
In view of Durga Matha idol immersion from 15:00 hrs on 21.10.2026 to 06:00 hrs on 24.10.2026, traffic diversions and restrictions will be implemented around People’s Plaza,

Garden Point, Jalavihar Baby Ponds and Sanjeevaiah Park, depending on local traffic conditions.
🚦Traffic Advisory – Saddula Bathukamma 2026🚦
In view of Saddula Bathukamma celebrations on 18.10.2026 (Sunday) at Bathukamma Ghat, Upper Tank Bund, traffic diversions

                         and restrictions will be in force from 2:00 PM to 11:00 PM around Upper Tank Bund and Necklace Road.
➤ 🚦 KBR PARK ONE-WAY TRAFFIC SYSTEM – ROUTE MAP 🚦
As part of the H-CITI Project, the One-Way Traffic

                        System around KBR Park will be implemented continuously

                        from 18.08.2026.
Arrive Alive
(A Campaign for Safety on Roads)
Click here
For more information
🚨 EMERGENCY & IMPORTANT CONTACTS
Police
112
Ambulance
108
Fire & Rescue
101
Women Helpline
181
Child Helpline
1098
Cyber Crime
1930
Cyber Crime Cell
8712660803
Traffic Help Line
9010203626
Traffic Control
8712660600
Traffic E-Challan
8712661690
Narcotics Helpline
1933
AI
🚦
HTP Assistant
Hyderabad Traffic Police · AI Powered
🚦
👋 Hello! I'm the
HTP AI Assistant
. I'm here to help you with traffic queries, challans, NOC, and more.
Full AI Chat — Coming Soon!
We're building an intelligent assistant to answer all your traffic-related queries in real time.
How do I pay my challan?
Apply for NOC
Nearest traffic police station
Emergency contacts
×
❮
❯
Hyderabad Traffic Police
Dedicated to safer roads, better traffic management

                    and citizen-friendly digital services.
🚦 Road Safety Campaigns
Useful Links
E-Challan
Wrong Challan
NOC
Vehicle Registration
Information
Road Rules
Road Sense
Road Smart
Connect With Us
Official Website
Hyderabad City Police
© 2026 Hyderabad Traffic Police
Disclaimer
Hyperlinking Poli

==================== ROAD CLOSURE ====================
Not found

==================== Last updated ====================
tivals
Seasonal Stalls
Information
Road Rules
Road Sense
Road Smart
Statistics
Driving License
Vehicle Registration
Know Your PS
RTI
Road Safety
Gallery
T20 Test
Online Test
Contact
Search site
Traffic Alerts
Loading latest alert...
Citizen Services
Last updated: 13-Oct-2026
Pay Challan
Pay your traffic violations online quickly and securely
Learn more
Parking Zones
Know parking zones Available Accorss the city
Learn more
Road Rules
Traffic signs,MV-Act Information,and Vehicle number plate regulations
Learn more
Wrong Challan
Report and contest incorrectly issued traffic challans
Learn more
Know Your Traffic PS
Know The Jurisdiction & Information Of The Traffic Ps
Learn more
Road Sense
Essential Rules and Must know Information
Learn more
Stolen Vehicle Assistance
**Report and Update Lost or Stolen Vehicle Details Online**
Learn more
🚗 How to Register a Vehicle
Vehicle registration services are currently available only at authorized vehicle showrooms.
Know the Process
Road Traffic Accident Monitoring Cell
Report road traffic accidents and monitor accident-related information.
Learn More
🚦 FEATURES
BE ROAD SMART
ROAD ACCIDENT BOOKLETS
PUBLIC INTERFACE
GALLERY
SPEED LIMIT
TRAFFIC TRAINING CENTER
TRAFFIC MARSHAL
TRAFFIC ASSISTANTS
Be Safe
Wheel Clamping
Traffic Signals
Major Corridors
Traffic Congestion
Defensive Driving
TRAFFIC NOC
🪖 Helmet
🚗 Speeding
🔒 Seat Belt
Required Documents / Traffic NOCs
Vehicle NOC
Traffic Conditions
School NOC
Traffic Conditions
Petrol Pump NOC
Traffic Conditions
DL Documents
Traffic Conditions
RC Documents
Traffic Conditions
Processions / Rallies
Traffic Conditions
Film Shootings
Traffic Conditions
Drone Operations
Traffic Conditions
Amusements
Traffic Conditions
Entertainment Events
Traffic Conditions
Dharna / Protest
Traffic Conditions
Seasonal Events / Festivals
Traffic Conditions
Seasonal Stalls
Traffic Conditions
Cinematography License
Traffic Conditions
Firework Shop Permission
Permission Details
Tambola License
Permission Details
Vehicle Registration
How to Register a Vehicle
Comple

In [6]:
from pathlib import Path
from datetime import datetime
import pandas as pd
import re

source_file = Path("data/raw/traffic/hyderabad_traffic_police_source_snapshot.txt")
text = source_file.read_text(encoding="utf-8")

# Identify titled traffic advisories in the source text
pattern = re.compile(
    r"(?:🚦\s*)?(TRAFFIC\s+ADVISORY\s*[|–-]\s*[^\\n]+|"
    r"Traffic Advisory\s*[-–]\s*[^\\n]+)",
    re.IGNORECASE
)

matches = list(pattern.finditer(text))
records = []

for i, match in enumerate(matches):
    start = match.start()
    end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
    section = text[start:end].strip()

    # Exclude empty or navigation-only sections
    if len(section) < 60:
        continue

    records.append({
        "advisory_title": match.group(1).strip(),
        "advisory_text": section,
        "collection_timestamp": datetime.now().astimezone().isoformat(),
        "source_url": "https://echallan.tspolice.gov.in/htp/"
    })

output_dir = Path("data/raw/traffic")
output_dir.mkdir(parents=True, exist_ok=True)
output_file = output_dir / "hyderabad_traffic_advisories.csv"

df = pd.DataFrame(records)

if not df.empty:
    df = df.drop_duplicates(subset=["advisory_title", "advisory_text"])
    df.to_csv(output_file, index=False, encoding="utf-8-sig")
    print("Advisory candidates extracted:", len(df))
    print("Saved:", output_file)
    print(df[["advisory_title"]].to_string(index=False))
else:
    print("No matching advisory titles found.")
    print("Original source snapshot remains unchanged.")

Advisory candidates extracted: 2
Saved: data\raw\traffic\hyderabad_traffic_advisories.csv
                                advisory_title
  TRAFFIC ADVISORY | DURGA MATHA IDOL IMMERSIO
Traffic Advisory – Saddula Bathukamma 2026🚦\nI